### ISSUE TITLE
error: omsagent:8 unknown option 'endscript' -- ignoring line

### ISSUE THREAD

**Issue by sjohner** [Microsoft/OMS-Agent-for-Linux#10]
Getting "error: omsagent:8 unknown option 'endscript' -- ignoring line" when logrotate is run on omsagent config. Configuration seems to contain a needless "endscript" since there is no postrotate for omsagent logrotate config.

![untitled](https://cloud.githubusercontent.com/assets/16019080/12402478/9b221ec4-be2d-11e5-859a-3cfab3aabca2.png)

**Comment by agup006** [comment]
Hi @sjohner this fix will be in the next release of the agent (after version -21). Thank you for letting us know about this problem.
