### ISSUE TITLE
omsagent for Linux is not collecting mysql data

### ISSUE THREAD

**Issue by danibaeyens** [Microsoft/OMS-Agent-for-Linux#100]
Hi,

I've created a new instance from the bitnami MySQL image, based on Ubuntu 14.04 LTS release.
I manually installed the oms agent for linux, as detailed in the instructions. The bitnami mysql configured is not located in the default directories (i.e. /var/lib/mysql), so I had to create two symlinks to allow the installation of the mysql-cimprov extension: One for /usr/lib/libmysqlclient.so and the other for /var/lib/mysql

Once created both, the package installs. and the agent runs without errors.

I've also upgraded the Azure VM extension LinuxDiagnostic to 2.2 version. I've also set up valid credentials with mycimprovauth to allow the agent to connect into the mysql and fetch the performance data. Also, I granted enough permissions on mysql to provide them.

Once done, I'm able to see the performance indicators on the OMS settings, but I'm not receiving any data from the MySQL server.

/var/opt/omi/log/omiserver.log is empty
/var/opt/omi/log/omiagent.root.root.log is empty
/var/opt/microsoft/mysql-cimprov/log/omsagent/ has no logs
/var/opt/microsoft/omsagent/log/omsagent.log has contents, but the configuration file shown in the log doesn't seem to have any source related to mysql
/opt/omi/bin/omicli ei root/mysql MySQL_Server returns nothing

How can I debug the problem? What can be the issue here?

Thanks

**Comment by agup006** [comment]
Hi @danibaeyens, When you say "/opt/omi/bin/omicli ei root/mysql MySQL_Server returns nothing" is there no output at all?

**Comment by jeffaco** [comment]
Hi Dani. I wonder if the agent was able to determine the MySQL instances that were running. Is your MySQL configuration file in the standard location? Oh, no, it's not. That's the problem.

Since your MySQL configuration file is not in the standard location, we're not able to determine what instances exist via the configuration files. Regardless, though, you'd need to set up a username and password for us to bind against.

I suggest you just run the MySQL authentication utility at `/opt/microsoft/mysql-cimprov/bin/mycimprovauth`. Turn off automatic updating, then add an entry (via update) for each instance that you have. Just use interactive mode, online help should be enough for you to get going.

Let me know if you have further questions,

/Jeff

**Comment by danibaeyens** [comment]
Due to timezones, I cannot test it today... Sorry

Wouldn't be nice to have a chance of giving a config file or some parameters to set all the needed info manually? It would also leverage you some "problems" of the autodetection of the mysql directories, I guess...

I'll tell you tomorrow my results

**Comment by jeffaco** [comment]
We do document the MySQL stuff, but I'm not sure that's been referenced in the OMS documentation. @agup006: Should we be giving links to MySQL agent setup in the OMS configuration instructions?

We work with standard MySQL installations from all major vendors, and we work with source installations as well **if you choose default installation directories**. Since you did not, we had no chance of finding the configuration files. Even if the MySQL configuration files were run, though, you'd still need to run `mycimprovauth` since we need a username and password to bind to the database with in order to collect our information.

If you run that and turn off auto-update, then we won't try to find the MySQL configuration files. Then set up the instances you want, and you should be all set.

I'm going to close this issue. Feel free to re-open it if you need further information.

/Jeff

**Comment by danibaeyens** [comment]
Thanks for your prompt reply @jeffaco 

But, please consider:
- People read the manuals. You told me twice that I had to use `mycimprovauth` to set the credentials, I've said I used it first 😉 
- People sometimes **do not have the chance to choose** the default installation directories. I would have preferred to use a default image, but this is the one that I received. And I had to configure these tools on top of that.
- People can be eager to give you suggestions and help, but not allowing patches on the repo, assuming that people don't read the docs, refer to undocumented features and closing the issue before giving even a chance of testing your suggestion, does not help to love Microsoft's software at all.

Btw, I got a moment to test it. It doesn't work:
```~$ /opt/omi/bin/omicli ei root/mysql MySQL_Server
instance of MySQL_Server
{
    [Key] ProductIdentifyingNumber=BitnamiMonitoredDbVM:127.0.0.1:3306
    [Key] ProductName=MySQL
    [Key] ProductVendor=Oracle
    [Key] ProductVersion=5.6.29
    [Key] SystemID=0
    [Key] CollectionID=linux-glibc2.5
    ErrorLogFile=/opt/bitnami/mysql/data/mysqld.log
    Hostname=MyArenaMonitoredDbVM2
    BindAddress=127.0.0.1
    Port=3306
    SocketFile=/opt/bitnami/mysql/tmp/mysql.sock
    DataDirectory=/opt/bitnami/mysql/data/
    OperatingStatus=OK
}
```

And I don't see any data on OMS. How much time do I need to wait for the data? Already waiting for more than 30 minutes and nothing...

Cheers!

**Comment by jeffaco** [comment]
Hi @danibaeyens My apologies, I scanned your original message very quickly, you did mention that you ran mycimprovauth. Realize that a lot of folks do NOT read manuals and don't realize that some software has to be configured before it works.

In your original message, you said: `/opt/omi/bin/omicli ei root/mysql MySQL_Server returns nothing`. This lead me to believe that mycimprovauth wasn't run.

From your latest message, I see that MySQL is now working properly (OperatingStatus=OK). That's great, and indicates that the MySQL provider is now properly configured.

What do you have in your OMS configuration files to monitor MySQL and send the data up to OMS? Please let us know, thanks.

**Comment by danibaeyens** [comment]
Hi @jeffaco,

I think OMS performance data counters configured in the OMS portal are not correctly pulled (pushed?) to the Linux Agent right now, because I was unable to see any changes on the omsagent log in `/var/opt/microsoft/omsagent/log/omsagent.log`.
Am I right?

Nevertheless, I disabled the automatic OMS performance data fetched and I manually configured all the MySQL Server counters to see if the data was being collected correctly.

I wrongly added an entry at `/etc/opt/microsoft/omsagent/conf/omsagent.d/` and thankfully it verbosely complained with an error: `Could not find ObjectName 'MySQL Server(*)' in /etc/opt/microsoft/omsagent/sysconf/omi_mapping.json` in the log when I restarted `omsagent`

After checking the json file, I fixed the config file with an entry like:
```
<source>
  type oms_omi
  object_name "MySQL Server"
  instance_regex ".*"
  counter_name_regex ".*"
  interval 5m
</source>
```

After some time (30 mins) I received the first entry:

```
6/9/2016 10:28:22.230 AM | Perf 
...Computer:BitnamiMonitoredDbVM
...ObjectName:MySQL Server
...CounterName:Disk Space Use in Bytes
...InstanceName:BitnamiMonitoredDbVM:127.0.0.1:3306
...TimeGenerated:6/9/2016 10:28:22.230 AM
...CounterPath:\\BitnamiMonitoredDbVM\MySQL Server(BitnamiMonitoredDbVM:127.0.0.1:3306)\Disk Space Use in Bytes
...StandardDeviation:0
...CounterValue:2784819
...Min:2784819
...Max:2784819
...SampleCount:6
...BucketStartTime:6/9/2016 10:02:55.287 AM
...BucketEndTime:6/9/2016 10:28:22.230 AM
...SourceSystem:OpsManager
```

I've added details to help anybody who could find this issue in the future.

Now, this issue can be closed.
Thanks for pointing to disable the autoupdate and launch the interactive mode.

**Comment by jeffaco** [comment]
@robbiezhang, @danibaeyens says the following:

> I think OMS performance data counters configured in the OMS portal are not correctly pulled (pushed?) to the Linux Agent right now, because I was unable to see any changes on the omsagent log in /var/opt/microsoft/omsagent/log/omsagent.log.
> Am I right?
>
>Nevertheless, I disabled the automatic OMS performance data fetched and I manually configured all the MySQL Server counters to see if the data was being collected correctly.

Can you check if the DSC stuff is set up properly from Portal settings to enable MySQL properly?

**Comment by robbiezhang** [comment]
Dani (@danibaeyens) can you send me a screenshot of your Linux Performance Counter setting in OMS portal and your workspace id?

**Comment by agup006** [comment]
Additionally @danibaeyens , can we double check that omsconfig package is also installed. `dpkg --list omsconfig`

**Comment by danibaeyens** [comment]
@agup006 
`ii  omsconfig              1.1.1.150        amd64            Operations Management Suite Agent Configuration`

@robbiezhang 
I have these counters:
<img width="649" alt="entries" src="https://cloud.githubusercontent.com/assets/3591851/15957093/184f0d1e-2eed-11e6-9794-e3447605c943.png">

on `8fbe0f0a-cc7a-4f90-b17a-1bbba35f13b3`

I was getting an error, until it stopped:
```
2016/06/08 11:22:42: ERROR: null(0): EventId=1 Priority=ERROR Job 91CA578E-4461-44A7-8CF4-340E5BF1DB6E : 
This event indicates that failure happens when LCM is trying to get the configuration from pull server using download manager null. ErrorId is 1. ErrorDetail is null
2016/06/08 11:27:44: ERROR: null(0): EventId=1 Priority=ERROR Job D5897760-68B7-49CE-95A9-92EDFD6EEF89 : 
DSC Engine Error : 
         Error Message Loading the instance document from the pending location did not succeed. 
        Error Code : 1 
2016/06/08 11:27:44: ERROR: null(0): EventId=1 Priority=ERROR Job D5897760-68B7-49CE-95A9-92EDFD6EEF89 : 
This event indicates that failure happens when LCM is trying to get the configuration from pull server using download manager null. ErrorId is 1. ErrorDetail is null
2016/06/08 11:32:45: WARNING: null(0): EventId=2 Priority=WARNING Job F6F23A96-0A4E-4B2F-8994-1D1284BEB15F : 
Displaying messages from built-in DSC resources:
         WMI channel 1 
         ResourceID:  
         Message : []:                            [] Starting consistency engine.
2016/06/08 11:32:45: WARNING: null(0): EventId=2 Priority=WARNING Job F6F23A96-0A4E-4B2F-8994-1D1284BEB15F : 
Displaying messages from built-in DSC resources:
         WMI channel 1 
         ResourceID:  
         Message : []:                            [] Consistency check completed.
2016/06/08 11:37:45: WARNING: null(0): EventId=2 Priority=WARNING Job AD9BADFB-8D9B-4E5B-8779-05AC2E841C59 : 
Displaying messages from built-in DSC resources:
         WMI channel 1 
         ResourceID:  
         Message : []:                            [] Starting consistency engine.
2016/06/08 11:37:45: WARNING: null(0): EventId=2 Priority=WARNING Job AD9BADFB-8D9B-4E5B-8779-05AC2E841C59 : 
Displaying messages from built-in DSC resources:
         WMI channel 1 
         ResourceID:  
         Message : []:                            [] Consistency check completed.
```

**Comment by robbiezhang** [comment]
@danibaeyens appreciate your information. Our configuration pulling agent (omsconfig) depends on curl.
can you check the curl version on you server?
You can get it by running: curl --version
The curl version on my Ubuntu 14.04 is 7.35.0, which can pull the configuration successfully.
If it's lower on your machine, you can run apt-get upgrade and apt-get update to upgrade it.

**Comment by danibaeyens** [comment]
@robbiezhang
Oh my...

This is the installed version on the image
$ dpkg -l |grep curl
ii  curl                                7.35.0-1ubuntu2.6                amd64        command line tool for transferring data with URL syntax
ii  libcurl3:amd64                      7.35.0-1ubuntu2.6                amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64               7.35.0-1ubuntu2.6                amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)

but:
$ which curl
/opt/bitnami/common/bin/curl
$ curl --version
curl 7.45.0 (x86_64-pc-linux-gnu) libcurl/7.45.0 OpenSSL/1.0.2f zlib/1.2.8

So, I'm not 100% sure which version might be using. If omsconfig uses libcurl, then it probably seems 7.35. If it's  plain curl, it seems 7.45

**Comment by agup006** [comment]
Hi @danibaeyens , would you be able to try reporting this issue for MySQL Data with the latest version of the Agent - v1.1.0-239: https://github.com/Microsoft/OMS-Agent-for-Linux/releases.

**Comment by agup006** [comment]
Hi @danibaeyens I am going to close this, feel free to re-open if issue is persisting with latest agent v1.1.0-239. Additionally, we are introducing other mechanism to get MySQL metrics that is Ruby based
