### ISSUE TITLE
Agent is way too verbose using default configuration

### ISSUE THREAD

**Issue by gpenin** [microsoft/OMS-Agent-for-Linux#1002]
We start having issues with file systems full, caused by the following log file : /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/watcher.log

The agent seems to be really verbose for an informational logging level. Please find an example log file attached. On this server, the log file grows by approximately 100 Mo per day.

(This log file does not seem to be rotated, so we also opened an issue on WALinuxAgent side : https://github.com/Azure/WALinuxAgent/issues/1562).

[watcher.log.gz](https://github.com/microsoft/OMS-Agent-for-Linux/files/3416434/watcher.log.gz)

**Comment by othmanaljundi-microsoft** [comment]
First ensure that WALinuxAgent and omsagent are up to date : 

	# yum update WALinuxAgent
	# yum update omsagent

Then; we will be adding a new entry to logrotation service for this log file :

	# touch /etc/logrotate.d/OmsAgentForLinux-watcher
	# vi /etc/logrotate.d/OmsAgentForLinux-watcher

		/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/watcher.log
		{
			rotate 10
			hourly
			missingok
			notifempty
			delaycompress
			compress
			size 100M
		}

Restart rsyslog service :

	# service rsyslog restart

Restart Agent service :

	# /opt/microsoft/omsagent/bin/service_control restart

**Comment by hestolz** [comment]
#1006

**Comment by A143730** [comment]
> First ensure that WALinuxAgent and omsagent are up to date :
> 
> ```
> # yum update WALinuxAgent
> # yum update omsagent
> ```
> 
> Then; we will be adding a new entry to logrotation service for this log file :
> 
> ```
> # touch /etc/logrotate.d/OmsAgentForLinux-watcher
> # vi /etc/logrotate.d/OmsAgentForLinux-watcher
> 
> 	/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/watcher.log
> 	{
> 		rotate 10
> 		hourly
> 		missingok
> 		notifempty
> 		delaycompress
> 		compress
> 		size 100M
> 	}
> ```
> 
> Restart rsyslog service :
> 
> ```
> # service rsyslog restart
> ```
> 
> Restart Agent service :
> 
> ```
> # /opt/microsoft/omsagent/bin/service_control restart 
> ```

hi @othmanaljundi-microsoft  - there are so many logrotate.conf , could you please send the relative path, also for me its the watcher.log inside /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux which has become a huge single file

**Comment by A143730** [comment]
hi @othmanaljundi-microsoft  where is this logrotate.conf, I have added the entry to all logrotate.conf on my ubuntu server but still it doen't seems to be working, it is still creating a single file.

**Comment by A143730** [comment]
in my case the file was 
/etc/opt/microsoft/scx/conf/logrotate.conf
and i added the below snippet

/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/watcher.log {
rotate 5
missingok
notifempty
compress
size 100M
copytruncate
}
