### ISSUE TITLE
omsagent : TTY=unknown 

### ISSUE THREAD

**Issue by maccas777** [microsoft/OMS-Agent-for-Linux#1004]
Hi all i am new in this azure 

Can i know if this is normal i see this all the time in the message of my centos server 
agent : TTY=unknown ; PWD=/opt/microsoft/omsconfig/Scripts/2.6x-2.7x ; USER=root ; COMMAND=/opt/microsoft/omsconfig/Scripts/OMSAuditdPlugin.sh get /var/opt/microsoft/omsagent/877af235-fbbc-424e-99ab-c755b8184a18/tmp
  pam_unix(sudo:session): session opened for user root by (uid=0)
  pam_unix(sudo:session): session closed for user root
 omsagent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/plugin/collectantimalwareinfo.rb

**Comment by z4r4k1** [comment]
Similar issue here and I am getting huge amount of emails as an alert is setup. Any fix or solution?

**Comment by War1810** [comment]
same issue here, please share how to fix it 
 Oct 15 10:04:56 ServerName sudo[13686]: PAM pam_parse: expecting '='; [...die]
Oct 15 10:04:56 ServerName sudo[13686]: omsagent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/plugin/collectantimalwareinfo.rb

**Comment by dsusca** [comment]
The same issue, 
 omsagent : TTY=unknown ; PWD=/ ;

**Comment by mshivanna** [comment]
` 
# Antimalware plugins
<source>
    type exec
    tag oms.antimalware
    command sleep 60 && sudo /opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/plugin/collectantimalwareinfo.rb
    format json
</source>

<source>
    type exec
    tag oms.antimalware
    command sleep 60 && sudo /opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/plugin/collectantimalwareinfo.rb
    format json
    run_interval 1h
</source>

<filter oms.antimalware>
    type filter_antimalware
    log_level info`

**Comment by NarineM** [comment]
omsagent user is setup in sudoers config to not require terminal for running command, however by default linux system logs  sudo command that was issued by a user. Because omsagent is a sudo user, it is expected to see tty alerts.  To disable these alert logging, you need to add this line somewhere in the  omsagent's sudoers file (/etc/sudoers.d/omsagent) at the top( after line #3 for example):

Defaults:omsagent !syslog
