### ISSUE TITLE
omazuremds error at connect(). errno=No such file or directory

### ISSUE THREAD

**Issue by hanschou** [microsoft/OMS-Agent-for-Linux#1008]
Hi

21500 time a day I get the this error message in /var/log/message

`Jul 25 23:59:59 srv7 rsyslogd-3000: omazuremds error at connect(). errno=No such file or directory`

I have tried to delete the file /etc/rsyslog.d/10-omazurelinuxmds.conf and restart rsyslog but the file is recreated each night 02 am and then the error message comes back.

I have some other servers which should have an identical setup but they don't have the config file and they don't get the error.

Can I just delete the package or is it needed for some monitoring?

The version is:
```

# uname -a 
Linux srv7 4.1.12-94.2.1.el7uek.x86_64 #2 SMP Wed Apr 26 15:32:38 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

# grep ^P /etc/os-release 
PRETTY_NAME="Oracle Linux Server 7.3"

# rpm -qa | grep oms
omsconfig-1.1.1-876.x86_64
omsagent-1.8.1-256.x86_64

```

best regards

**Comment by abenbachir** [comment]
the omazuremds is a rsyslog module that will be installed when mdsd is installed. Are you using LAD ? I'm asking you that because LAD will install both OMS and MDSD.

**Comment by abenbachir** [comment]
This is not related to OMS, this will be closed.
