### ISSUE TITLE
Custom port to bind ?

### ISSUE THREAD

**Issue by przemolb** [microsoft/OMS-Agent-for-Linux#1011]
Is there any way I can chose my custom port the OMS agent will bind to ? I'd like to keep it the same across all our servers.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
