### ISSUE TITLE
RHEL8 Selinux requires additional permission for systemctl to run omid

### ISSUE THREAD

**Issue by oniled** [microsoft/OMS-Agent-for-Linux#1012]
After installing a fresh copy of the latest OMS Agent, and attempting to start via systemctl, found these logs via journalctl -xe

> Aug 01 09:46:08 UCSMGMT02.id.sdsu.edu systemd[1]: Starting OMI CIM Server...
> Subject: Unit omid.service has begun start-up
> Defined-By: systemd
> Support: https://access.redhat.com/support
> Unit omid.service has begun starting up.
> Aug 01 09:46:09 UCSMGMT02.id.sdsu.edu systemd[1]: omid.service: Can't open PID file /var/opt/omi/run/omiserver.pid (yet?) after start: No such file or directory
> Aug 01 09:46:09 UCSMGMT02.id.sdsu.edu systemd[1]: omid.service: Can't convert PID files /var/opt/omi/run/omiserver.pid O_PATH file descriptor to proper file descriptor: Permission denied
> Aug 01 09:46:09 UCSMGMT02.id.sdsu.edu systemd[1]: omid.service: Can't convert PID files /var/opt/omi/run/omiserver.pid O_PATH file descriptor to proper file descriptor: Permission denied

Running audit2allow gave me this info:

> type=AVC msg=audit(1564675641.188:10145): avc:  denied  { read } for  pid=1 comm="systemd" name="omiserver.pid" dev="sda4" ino=68871427 scontext=system_u:system_r:init_t:s0 tcontext=unconfined_u:object_r:var_t:s0 tclass=file permissive=0
> Was caused by:
> Missing type enforcement (TE) allow rule.
> You can use audit2allow to generate a loadable module to allow this access.

Had to make a Selinux module for it to work.

> module init_t 1.0;
> 
> require {
>         type rpm_t;
>         type var_t;
>         type init_t;
>         class dbus send_msg;
>         class file { getattr open read };
>         class dir { read remove_name write };
> }
> 
> #============= init_t ==============
> 
> #!!!! This avc is allowed in the current policy
> allow init_t var_t:file { open read getattr };
> allow init_t var_t:dir { read remove_name write };

**Comment by hestolz** [comment]
Not an OMS Agent issue, please open an issue against the proper repo [here](https://github.com/microsoft/omi).
