### ISSUE TITLE
Collecting Large Custom Logs 

### ISSUE THREAD

**Issue by norberttech** [microsoft/OMS-Agent-for-Linux#1028]
Hey, 
since couple of weeks oms agent that is configured to collect logs from few hosts is randomly freezing and restarts does not help. 

Custom logs are collected from files generated by php app, there is no log rotation except the one that creates new log file every day.

*Example Log File:* `/var/log/app/app_log-2019-08-28.log`
*Path Configuraiton:* `/var/log/app/app_log*.log` 

Application is generating around 300-400mb logs every day (it will grow). 

Below visualization of log entries on a timeline:

![image](https://user-images.githubusercontent.com/1921950/63856928-0c04bc80-c9a3-11e9-8dc9-1fe26c88b318.png)

Around 5:00 UTC oms agent stoped to forward logs into log analytics workspace. 
You can find omsagent logs here: https://gist.github.com/norzechowicz/4b76f9d72a76c2aaa174d284c95ad81d 

When I looked into the application log around 5:00 I found one huge entry, **275k** characters in one line. OMS agent is configured to separate logs by new line character. 

Is it possible that agent is stuck because of that long log enty?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
