### ISSUE TITLE
SyslogMessage is cut off at the beginning

### ISSUE THREAD

**Issue by dguertin** [microsoft/OMS-Agent-for-Linux#1030]
We're sending audit logs from a file server to a Linux server running OMSagent, which in turn sends the logs to Azure Log Analytics. (The file server is an appliance that we cannot install OMSagent directly on.) The syslog file on the Linux server shows what looks to be correct JSON inside the curly braces. Here's a sample sanitized entry:

`2019-08-29T13:20:51.048380-04:00 nef-1 nasuni.54146673-587a-47d2-9af9-a[800] {"to_gid": null, "event_type": "AUDIT_WRITE", "sequence": 152518, "pid": 20564, "groupname": "DOMAIN\\domain users", "result": 54, "uid": xxxxxx, "is_dir": false, "size": null, "timestamp": 1567099251.0379713, "proto": "AUDIT_PROTO_CIFS", "ipaddr": "xxx.xxx.xx.xxx", "ts": null, "to": null, "gid": xxxxxx, "filesize": null, "to_uid": null, "sid": "S-1-5-21-1983215674-46037090-646806464-xxxxxx", "tid": 20564, "username": "DOMAIN\\xxxxx", "path_timestamp": 0.0, "datasync": null, "volume": "54146673-587a-47d2-9af9-a0349cfe3861_4", "offset": 0, "path": "/path/to/file.doc", "newpath": null, "shared_link_key": null, "resource": "xxxxxxxxx", "name": null, "length": 54, "flags": null, "mode": null}`

The logs are read into Log Analytics, but the JSON inside the curly braces has the first element ("to_gid") missing, rendering the SyslogMessage into a long string instead of readable JSON.

>TimeGenerated [UTC] | 2019-08-29T17:20:51.053Z
 Computer | nef-1
 EventTime [UTC] | 2019-08-29T17:20:51Z
 Facility | local0
 HostName | nef-1
 SeverityLevel | info
 SyslogMessage | null, "event_type": "AUDIT_WRITE", "sequence": 152518, "pid": 20564, "groupname": "DOMAIN\\domain users", "result": 54, "uid": xxxxxx, "is_dir": false, "size": null, "timestamp": 1567099251.0379713, "proto": "AUDIT_PROTO_CIFS", "ipaddr": "xxx.xxx.xx.xxx", "ts": null, "to": null, "gid": xxxxxx, \<snip\>

Is there a way to fix this?

Dave

**Comment by migel0** [comment]
Same behavior
`Sep 23 10:23:56 host0001 php [23-Sep-2020 10:23:51] WARNING: [pool olimpica] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 19 idle, and 43 total children
 `
become to SyslogMessage: 
`10:23:51] WARNING: [pool olimpica] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 19 idle, and 43 total children`

Would be  REGEX ?

REGEX = /^(?<EventTime>\S+)\s{0,4}(?<HostName>\S+)\s{0,4}(?<ProcessName>\S+)\:\s{0,4}(?<SyslogMessage>.*)$/
