### ISSUE TITLE
Not provided as rpm or deb file - or not clearly documented as such.

### ISSUE THREAD

**Issue by mikemcowie** [microsoft/OMS-Agent-for-Linux#1032]
The installation instructions and scripts involve wgetting a shell script from github, and that shell script then proceeds to pull more material from github.

This doesn't give a lot of confidence that the sources couldn't be tampered with, and as a system administrator I'd expect to be able to use my system's standard software package manager (rpm and dpkg) to install it, an installation script contained entirely within the rpm or deb package to configure it, and a systemd unit (or legacy init script) to run it. I'm aware that the github account is going to be well controlled, but leaving it to just the github project's security measures is not a good defense-in-depth approach to securing this software.

Additionally, to give me confidence that a) I can update the agent and b) The software hasn't been tampered with, I'd expect the software to be provided by appropriate repositories, and be signed by appropriate GPG keys (as per other microsoft software such as powershell and dotnet which have done this well).

It should be easy to provide the appropriate installation directions in-line within the azure portal, little harder than the current directions.

I would appreciate this being improved as the functionality offered by the log analytics workspace for both azure and non-azure VMs is really excellent and the solution seems to be simpler and maybe cheaper to implement than a variety of alternatives.

**Comment by cyberjacob** [comment]
Can't agree with this enough, basic security practice includes not running random shell scripts from the internet. It's even worse to see this on a product that's intended to be security focused (Azure Sentinel), and if anything should be blocking it's own installer!

**Comment by dperusich** [comment]
Package distribution via an automated build environment like the SUSE's Open Build Service would be one avenue for this. It would also simply the process of adding other distributions. Just a thought.

**Comment by mikemcowie** [comment]
@dperusich agreed, but step 1 needs to simply be to talk to whomever operates https://packages.microsoft.com/ , discuss what they're doing to build, verify and sign their packages, and then follow whatever those guidelines are to get the OMS agent added.

**Comment by JeffMelton** [comment]
I'm surprised this issue is not only still open but has no response from the maintainers. I'm looking at deploying in an enterprise environment — curlbashing a wrapper (that curlbashes another script) from GitHub is a nonstarter.
