### ISSUE TITLE
OMS installed by script fails to be recognized in Azure.

### ISSUE THREAD

**Issue by bryohe** [microsoft/OMS-Agent-for-Linux#1041]
Using the onboard_agent.sh script provided I tested on several different OS, RHEL7.7, OEL7.3 OEL7.7, CentOS7.6, SuSE15, Ubuntu16.04 and Ubuntu18.04, the script runs successfully but OMSAgent never gets integrated into WALinuxAgent and never correctly reports the status in either the Portal Extensions pane or the az vm extension list commands in Azure CLI. It seems that the agent processes run and restart after reboot. Directories and logs are not created in the usual places such as /var/lib/waagent/<extension> or /var/log/azure/<extension>. and /var/log/waagent.log never records any action regarding the OMS agent. Once the agent is correctly installed by using CLI, the --purge option does not successfully remove the agent.

**Comment by hestolz** [comment]
This is working as expected. If you wish for guest agent / azure portal etc to be made "aware" of this VM (in respect to the presence of OMS on that machine) you should be using the [extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/oms-linux). 

The [extension](https://github.com/Azure/azure-linux-extensions/tree/master/OmsAgent) is a small wrapper around the shell bundle released here on this repo; it makes the agent manageble by waagent, will show up as an extension in the VM blade, etc. You can see the details for how to install the agent as an extension in the first link above.
