### ISSUE TITLE
Unknown output plugin 'out.oms.changetracking.file'

### ISSUE THREAD

**Issue by norzechowicz** [microsoft/OMS-Agent-for-Linux#1051]
So the omsagent is crashing on brand new machine with following error: 

```console
2019-10-07 22:00:38 +0000 [error]: config error file="/etc/opt/microsoft/omsagent/{workspace_id}/conf/omsagent.conf" error="Unknown output plugin 'out.oms.changetracking.file'. Run 'gem search -rd fluent-plugin' to find plugins"
```

OmsAgentForLinux extension version is `1.10`, it was installed through az cli. I additionally enabled Inventory, Change Tracking and Update Management through Azure Portal. 
There are no errors in the portal. 

Is there any way to install this missing plugin manually?

**Comment by DimitrovMiro** [comment]
Hi Microsoft,
same issue here, RHEL 6.9 OMS agent version 1.11.15 , in /var/opt/microsoft/omsagent/<workspace id>/log/omsagent.log - [error]: config error file="/etc/opt/microsoft/omsagent/workspace_id/conf/omsagent.conf" error="Unknown output plugin 'out.oms.changetracking.file'. Run 'gem search -rd fluent-plugin' to find plugins"
Additional heartbeat stops working 5-10 minutes after deployment of the machine and then after that there is no heartbeat at all
Also Linux Diagnostic Extension version 3.0.123 getting provisioned but seems silently it is not enabled. On the portal you see this message: Problem(s) detected in generated mdsd configuration. Can't enable, although this install/enable operation is reported as successful so the VM can complete successful startup. Linux Diagnostic Extension will exit. Config validation message: /bin/sh: /usr/local/lad/bin/mdsd: No such file or directory
@norzechowicz is your machine having heartbeat constantly or also stops working? Do you also use the Linux Diagnostic Extension?
Any help will be appreciated

**Comment by norzechowicz** [comment]
Hey @DimitrovMiro I managed to bypass this using clean log analytics workspace without change tracking solution enabled. 
About your heartbeat question, basically because of this bug in configuration, omsagent never started so it could not also send any heartbeats.

**Comment by hestolz** [comment]
Root cause is that this arose from a DSC module release. DSC modules are a way that various agent plugins can be deployed independent of the bundle/extension release cycle. Changetracking stored their file in this repo but it was not included in the installer, so when it was removed from OMS common DSC module (part of a release cleanup effort) even when the solution was enabled the file could not be found and agent wouldn't start. 

Fixes:
#1053 
[\#628](https://github.com/microsoft/PowerShell-DSC-for-Linux/pull/628)
