### ISSUE TITLE
Installer shell script and links in download section broken (points to no longer available release)

### ISSUE THREAD

**Issue by ffloimair** [microsoft/OMS-Agent-for-Linux#1062]
When running the installer shell script https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
I get an error 404 File Not Found.

We use this script to always get the latest released version.

The reason is simple: The script points to https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.12.1-0/omsagent-1.12.1-0.universal.x64.sh however the latest release is 1.12.2-0 so it should point to https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.12.2-0/omsagent-1.12.2-0.universal.x64.sh

Also the link on the release page is mixed up (1.12.2-0 script is in 1.12.1-0 folder): https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.12.1-0/omsagent-1.12.2-0.universal.x64.sh

**Comment by alainvanhoof** [comment]
So this no longer works: https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-linux-computer

**Comment by alainvanhoof** [comment]
Pull Request: https://github.com/microsoft/OMS-Agent-for-Linux/pull/1061 should fix this?

**Comment by ffloimair** [comment]
Exactly. The referenced PR addresses this. Hopefully this will get merged soon.

**Comment by BrandoDedman** [comment]
Downloading the root files works fine, but get a 404 when attempting to use the purge operation:

wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/i
nstaller/scripts/onboard_agent.sh
--2019-10-18 07:48:48--  https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2994 (2.9K) [text/plain]
Saving to: “onboard_agent.sh”

100%[==============================================================================>] 2,994       --.-K/s   in 0s

2019-10-18 07:48:48 (87.6 MB/s) - “onboard_agent.sh” saved [2994/2994]

sh onboard_agent.sh --purge
--2019-10-18 07:49:00--  https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.12.1-0/omsagent-1.12.1-0.universal.x64.sh
Resolving github.com... 192.30.253.113
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-10-18 07:49:00 ERROR 404: Not Found.

This is preventing a clean purge and re-install of the software

**Comment by hestolz** [comment]
The fix been approved and merged; our apologies for this issue.
