### ISSUE TITLE
NoMethodError fast_utc_to_iso8601_format when parsing ASA CEF

### ISSUE THREAD

**Issue by brandubh** [microsoft/OMS-Agent-for-Linux#1063]
With the latest release of the OMS agent we get the follwing error (logged as warn) when parsing Cisco ASA CEF events, we reverted to the previous version where we don't get the issue.

error_class=NoMethodError error="undefined method 'fast_utc_to_iso8601_format' for OMS::Common:Class"

**Comment by hestolz** [comment]
@brandubh can you describe the exact scenario (what versions were broken / used to fix, was this a bundle install or extension install, did you purge and then reinstall or simply --upgrade)? Thank you.

@abenbachir for awareness

**Comment by BaldrIronborn** [comment]
Hi 
I have tha same error in omsagent.log

2019-10-25 15:51:19 +0300 [warn]: dump an error event: error_class=NoMethodError error="undefined method `fast_utc_to_iso8601_format' for OMS::Common:Class" tag="oms.security.local6.warn" time=1572007879 record={"host"=>"ASA5525X-XXX", "ident"=>"%ASA-4-106103", "message"=>" access-list #ACSACL#-IP-VPN_XX-5d19a2eb denied tcp for user 'Xxxxxxx.XX' Outside1/111.11.111.11(11111) -> Inside1/11.11.11.1(1111) hit-cnt 1 first hit [0xf958d04b, 0x0]"}

**Comment by BaldrIronborn** [comment]
> @brandubh can you describe the exact scenario (what versions were broken / used to fix, was this a bundle install or extension install, did you purge and then reinstall or simply --upgrade)? Thank you.
> 
> @abenbachir for awareness


used --upgrade
agent version - omsagent-1.12.7-0

**Comment by hestolz** [comment]
@BaldrIronborn can you provide
`$ ls -la /opt/microsoft/omsconfig/modules/nxOMSPlugin/DSCResources/MSFT_nxOMSPluginResource/Plugins/Common/plugin/`
`$ ls -la /opt/microsoft/omsagent/plugin`

**Comment by hestolz** [comment]
Fixed in #1068
