### ISSUE TITLE
RHEL Kernel crash

### ISSUE THREAD

**Issue by psubhakar** [microsoft/OMS-Agent-for-Linux#1074]
This version caused lot of production servers crash

kernel: BUG: Bad page state in process omicli  pfn:56b5ff
kernel: page:fffff1a015ad7fc0 count:0 mapcount:1 mapping:          (null) index:0x7fe2e0fff
kernel: page flags: 0x2fffff00080018(uptodate|dirty|swapbacked)
kernel: page dumped because: nonzero mapcount
kernel: Modules linked in: macsec tcp_diag udp_diag inet_diag unix_diag af_packet_diag netlink_diag binfmt_misc microsoft_dependency_agent(POE) bluechannel(POE) xt_owner arc4 md4 nls_utf8 cifs ccm dns_resolver ip6t_rpfilter ipt_REJECT nf_reject_ipv4 ip6t_REJECT nf_reject_ipv6 xt_conntrack ip_set nfnetlink ebtable_nat ebtable_broute bridge stp llc ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat nf_conntrack iptable_mangle iptable_security iptable_raw ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter ext4 mbcache jbd2 dm_mirror dm_region_hash dm_log mlx4_en mlx4_core devlink joydev sb_edac iosf_mbi dm_mod crc32_pclmul ghash_clmulni_intel aesni_intel lrw gf128mul
kernel: glue_helper ablk_helper cryptd hv_utils sg ptp pci_hyperv pps_core hv_balloon i2c_piix4 pcspkr nfsd nfs_acl lockd auth_rpcgss grace sunrpc ip_tables xfs libcrc32c sd_mod crc_t10dif crct10dif_generic hv_storvsc scsi_transport_fc hv_netvsc hid_hyperv scsi_tgt hyperv_keyboard ata_generic pata_acpi hyperv_fb crct10dif_pclmul crct10dif_common crc32c_intel floppy serio_raw ata_piix libata hv_vmbus
kernel: CPU: 15 PID: 43026 Comm: omicli Tainted: P           OE  ------------   3.10.0-957.21.3.el7.x86_64 #1
kernel: Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
kernel: Call Trace:
kernel: [<ffffffff92563107>] dump_stack+0x19/0x1b
kernel: [<ffffffff9255ddb3>] bad_page.part.76+0xdc/0xf9
kernel: [<ffffffff91fbf180>] free_pages_prepare+0x170/0x190
kernel: [<ffffffff91fbfbf4>] free_hot_cold_page+0x74/0x160
kernel: [<ffffffff91fc4a93>] __put_single_page+0x23/0x30
kernel: [<ffffffff91fc4ae5>] put_page+0x45/0x60
kernel: [<ffffffff9202cab7>] __split_huge_page+0x357/0x880
kernel: [<ffffffff9202d056>] split_huge_page_to_list+0x76/0xf0
kernel: [<ffffffff9202deb0>] __split_huge_page_pmd+0x1d0/0x5c0
kernel: [<ffffffff91fe789d>] unmap_page_range+0xbdd/0xc30
kernel: [<ffffffff91fc579c>] ? pagevec_lru_move_fn+0x10c/0x130
kernel: [<ffffffff91fe7971>] unmap_single_vma+0x81/0xf0
kernel: [<ffffffff91fc5fde>] ? lru_add_drain_cpu+0xfe/0x110
kernel: [<ffffffff91fe8dad>] zap_page_range+0x11d/0x190
kernel: [<ffffffff91fe3c9d>] SyS_madvise+0x49d/0xac0
kernel: [<ffffffff92575ddb>] system_call_fastpath+0x22/0x27
sh: abrt-dump-oops: Found oopses: 1
sh: abrt-dump-oops: Creating problem directories
sh: abrt-dump-oops: Not going to make dump directories world readable because PrivateReports is on
abrt-dump-oops: Reported 1 kernel oopses to Abrt

**Comment by abenbachir** [comment]
Probably related to kernel bug : https://bugs.centos.org/view.php?id=15181

**Comment by abenbachir** [comment]
Please refer to this https://github.com/microsoft/omi/issues/650
