### ISSUE TITLE
Cisco ASA Logs not parsing correctly (Timezone issue)

### ISSUE THREAD

**Issue by denisyfrolov** [microsoft/OMS-Agent-for-Linux#1078]
Some ASA are affected by the bug [CSCve24262](https://quickview.cloudapps.cisco.com/quickview/bug/CSCve24262) leads to broken format of messages. 

Example of affected messages:

> Oct 23 14:43:13 **MSK** XXXXXXXX-XXX : %ASA-0-000000: message here...

In omsagent.log:
 
> 2019-10-23 14:43:13 +0300 [warn]: pattern not match: "Oct 23 14:43:13 MSK XXXXXXXX-XXX : %ASA-0-000000: message here..."

![Original RegEx](https://user-images.githubusercontent.com/5620027/67679068-484f9b80-f999-11e9-9641-ed60a6307392.jpg)
_Original RegEx_

![Updated RegEx](https://user-images.githubusercontent.com/5620027/67679116-661d0080-f999-11e9-8818-f1c7deb77d96.jpg)
_Updated RegEx_

**Comment by denisyfrolov** [comment]
Fixed in PR #1077

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
