### ISSUE TITLE
Support for Debian 10 Buster

### ISSUE THREAD

**Issue by marcelmore** [microsoft/OMS-Agent-for-Linux#1079]
Hello,

we are using Debian 10 Buster on some machines from the partner Credativ as listed in the "Endorsed Distros" page: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros#credativ

Is there any timeline or any plans for OMS agent compatibility with this Debian release?

**Comment by magior** [comment]
Just tried on Debian 10 latest pre-release (OMS Agent for Linux GA v1.12.15-0). It is still not functional. I've found this error on logs:

"cURL failed to perform on this base url: we-agentservice-prod-1.azure-automation.net with this error message: Stream error in the HTTP/2 framing layer. Make sure cURL and SSL libraries are up to date"

On the system, we have the latest versions of curl, libcurl and openssl.

Any updates on when it will be supported?

Thanks,
Marco

**Comment by dpurnam** [comment]
Latest version doesn't seem to work with Debian 10 (Buster), although installation succeeds and service status for both the services viz. omsagent and omsid is cool!
![OMS-Agent-for-Linux](https://user-images.githubusercontent.com/7486999/69934592-62305100-14f8-11ea-99ce-2e0958f1660b.png)
![LogAnalyticsVMStatus](https://user-images.githubusercontent.com/7486999/69934599-6c524f80-14f8-11ea-8adf-a571f374fc14.png)

**Comment by stefanpetter** [comment]
This is still an issue. Are there any updates on supper for Debian 10

**Comment by ffloimair** [comment]
OMG!
Debian 10 is out for more than a year and omsagent still does not support it.
This is embarassing!

I am clearly shocked that this has not been done yet and even more shocked that this issue has not been at least acknowledged by someone from Microsoft.
I wanted to upgrade our Debian 9 VMs to 10 and this is what's getting in the way.

Please provide a valid statement on when we can expect support for it.

**Comment by rohitbansal087** [comment]
Still it is not working , i am afraid that how microsoft will compete with AWS in future.
This is very frustrating 👎

**Comment by stefanpetter** [comment]
> Still it is not working , i am afraid that how microsoft will compete with AWS in future.
> This is very frustrating 👎

It does not need to work anymore! Currently, the Azure Monitor Agent is in public preview. Together with Data Collection ruels, this will solve all our problems! Check it out here:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/azure-monitor-agent-overview

**Comment by ffloimair** [comment]
> It does not need to work anymore! Currently, the Azure Monitor Agent is in public preview. Together with Data Collection ruels, this will solve all our problems! Check it out here:
> https://docs.microsoft.com/en-us/azure/azure-monitor/platform/azure-monitor-agent-overview

Fair enough, but this should be *prominently* mentioned on the README of this project that it is being phased out.
How else would you know that this is no longer being worked on.

**Comment by stefanpetter** [comment]
> > It does not need to work anymore! Currently, the Azure Monitor Agent is in public preview. Together with Data Collection ruels, this will solve all our problems! Check it out here:
> > https://docs.microsoft.com/en-us/azure/azure-monitor/platform/azure-monitor-agent-overview
> 
> Fair enough, but this should be _prominently_ mentioned on the README of this project that it is being phased out.
> How else would you know that this is no longer being worked on.

Could not agree more 👍

**Comment by finalbeta** [comment]
I have cloud providers (SAAS = I can't run software on it) that export audit logs etc to syslog only. 
I use https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-sources-syslog to capture the logs. That requires the OMS-Agent-for-Linux. 
if the OMS-Agent-for-Linux will not be supported on Debian 10, that leaves me in an unsupported state on June 2022 when Debian 9 LTS support ends. 

So to be clear, Debian 10 will never be supported? This software is deprecated?

**Comment by maniaX1** [comment]
Hello @finalbeta, it seems that Microsoft release few days ago new possibilities how to monitor Debin 10 and other Linux editions via Data Collection Rules in Azure Monitor:
https://azure.microsoft.com/cs-cz/updates/new-azure-monitor-agent-available-on-latest-linux-distros-and-new-regions/
Hopefully this can help!

**Comment by vlad-m-r** [comment]
While new Azure Monitor Agent for Linux does indeed support Debian 10 and is intended to replace Log Analytics Agent for Linux, the new Azure Monitor Agent does not implement all uses cases of Log Analytics Agent for Linux. For example the new agent does not have any capabilities to implement Change Tracking or Update Management for Azure Automation (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#other-services) which is a major drawback for those relying on those services. Data Collections Rules in new Azure Monitor Agent for Linux only allow data shipping of syslog and performance counters (memory, cpu etc).

So until new Agent Monitor Agent adds support for missing features, Log Analytics Agent for Linux is still needed so Debian 10 support is valid.

**Comment by maniaX1** [comment]
@vlad-m-r Yep, that's correct I just tried Data Collection Rules and I am not thrilled so much. So it is still valid question to Microsoft when Debian 10 will be fully supported by Log Analytics Workspace Agent.
Who could answer such question?

**Comment by jkroepke** [comment]
Mention that Ubuntu 20.04 is supported while Debian 10 not...

**Comment by tanawat777** [comment]
need to use azure monitor with Debian 10. I want to know how we get some way for using it ?

**Comment by stefanpetter** [comment]
> need to use azure monitor with Debian 10. I want to know how we get some way for using it ?

Try the Azure Monitor Agent :) 

[https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview?tabs=PowerShellWindows](url)

**Comment by nta18705** [comment]
> Try the Azure Monitor Agent :)
> 

How is this possible with on-prem workloads when Azure Monitor has a dependency on Arc and Arc doesn't support Debian at all?

**Comment by AkechiShiro** [comment]
Where should we report when the azure monitoring agent doesn't work like such an issue : 
```
(VMExtensionHandlerNonTransientError) The handler for VM extension type 'Microsoft.Azure.Monitor.AzureMonitorLinuxAgent' has reported terminal failure for VM extension 'AzureMonitorLinuxAgent' with error message: '[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4/./shim.sh -install
[stdout]
2024/01/16 19:00:37 [Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4] Install,failed,51,Unsupported operating system: debian 12


[stderr]
/var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4/./agent.py:46: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
  import crypt
'.
    
'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'
Code: VMExtensionHandlerNonTransientError
Message: The handler for VM extension type 'Microsoft.Azure.Monitor.AzureMonitorLinuxAgent' has reported terminal failure for VM extension 'AzureMonitorLinuxAgent' with error message: '[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4/./shim.sh -install
[stdout]
2024/01/16 19:00:37 [Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4] Install,failed,51,Unsupported operating system: debian 12


[stderr]
/var/lib/waagent/Microsoft.Azure.Monitor.AzureMonitorLinuxAgent-1.29.4/./agent.py:46: DeprecationWarning: 'crypt' is deprecated and slated for removal in Python 3.13
  import crypt
'.
    
'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'
```

I believed Debian was supported by this agent ? Maybe the Python version is too high ?

**Comment by jkroepke** [comment]
> I believed Debian was supported by this agent ? Maybe the Python version is too high ?

Yeah, but only Debian GNU/Linux 8 and 9 not Debian 12.

The OMS Agent is deprecated, do not expect updates. Instead, use Azure Monitor Agent

**Comment by AkechiShiro** [comment]
Issue is, I'm talking about the Azure Monitor Agent and the error is from the Azure Monitor Agent, please make sure to read my comment properly first @jkroepke

**Comment by jkroepke** [comment]
Sorry, but if you write a comment in a repo which is for OMS Agent, I don't expect that you are talking about different agents.

**Comment by AkechiShiro** [comment]
I'm sorry as well but I expect others to read comments before writing a response, I think it's common sense as well.

I'm just mentioning that neither agents are supporting Debian in this issue.
