### ISSUE TITLE
OMSAgentforLinux status issues on Azure Portal When OMSAgent is installed manually.

### ISSUE THREAD

**Issue by alichebel** [microsoft/OMS-Agent-for-Linux#1088]
Hello,

I'm facing some status issues on Azure portal when I installed manually OMS agent for Linux version omsagent-1.12.7-0.universal.x64 on my VM.
OMS Agent has been installed successfully on my Debian Server . It starts and run successfully. Data are collected and sent to Log Analytics Workspace
However On Azure portal   if i go to  : 
1- MyVm\Settings\Extensions =>  I don't see any OMSAgentForLinux extension installed.
2- MyLogAnalyticsWorkspace\WorkspaceDataSources\VirtualMachines\MyVM =>  I got a "not connected" status instead of "connected" status.
 
Thanks in advance for your help

**Comment by tricksterisback** [comment]
This is not an Issue, basically if you are installing agent manually then  it will not show any extension for it. Extensions are facilitator to install omsagent on VMs via Azure Portal. If you want to see the machine with extension and connected in LA workspace, Please remove the manually installed agent, go to LA workspace-->Virtual Machines blade, find the VM and click on it. You will see an option to click "Connect" Once done, you would see the extension as well as the "Connected"

**Comment by alichebel** [comment]
Ok thanks for your feedback
