### ISSUE TITLE
OMSAgentForLinux 1.12.7 not showing proper version in AzureCLI/Powershell

### ISSUE THREAD

**Issue by jamhemen** [microsoft/OMS-Agent-for-Linux#1097]
I installed some machines with the 1.12.5 agent and let them upgrade to 1.12.7. I reviewed them with my automated checks, and the agent is showing up as version 1.0 in both the az cli and in powershell.

On the machine itself it is showing 1.12.7.

**Comment by pradeepreddiv-git** [comment]
Are you trying to install the agents via the portal (ie enabling extensions)? I too encountered this issue the portal was not picking up the latest version but on the VM it has the latest version. I uninstalled the extension from the portal and installed it again. try not installing it manually on the VM.

**Comment by hestolz** [comment]
this is a portal UI / ARM issue
it will only show the major version
