### ISSUE TITLE
omsagent installation error No such file or directory

### ISSUE THREAD

**Issue by adiebr** [microsoft/OMS-Agent-for-Linux#1100]
Getting the below error when installing the omsagent on a linux machine. Any ideas on how to resolve?
IOError: [Errno 2] No such file or directory: '/etc/opt/microsoft/omsagent/*workspace*/conf/omsagent.d/security_events.conf'

**Comment by BardiaGolkar** [comment]
I am getting the same error, is there any updates to this? I don't have the omsagent.d/security_events.conf directory. I have everything up until /conf/ but the folder is empty once I invoke ls to see its content.

Any suggestions?
