### ISSUE TITLE
Invalid logrotate file for LAD

### ISSUE THREAD

**Issue by taoyama** [microsoft/OMS-Agent-for-Linux#1111]
I can see error while logrotate.
`# /usr/sbin/logrotate -d /etc/logrotate.conf
...
reading config file omsagent-LAD
error: omsagent-LAD:1 lines must begin with a keyword or a filename (possibly in double quotes)
...`

It seems that the logrotate file is invalid.
`# cat /etc/logrotate.d/omsagent-LAD
/var/opt/microsoft/omsagent/LAD/log/omsagent.log {\n\trotate 10\n\tmissingok\n\tnotifempty\n\tcompress\n\tsize 100M\n\tcopytruncate\n}`

**Comment by hestolz** [comment]
@taoyama is there an ICM/CRI associated with this? Does this repro on multiple distros or just some?
@nidhanda please take a look at #1112 as you are the original author of this code

**Comment by sbonds** [comment]
I noticed this same issue and it has been reported as part of a larger Microsoft support request. I'm hesitant to post case numbers publicly, but I referenced this issue within the case.

**Comment by hestolz** [comment]
Fixed in #1128, release ETA is February.
