### ISSUE TITLE
Install Fails on Centos 8

### ISSUE THREAD

**Issue by chandlerkent** [microsoft/OMS-Agent-for-Linux#1117]
I am using a VM extension to install the OMS Agent. ARM template:

```json
{
	"name": "logAnalytics",
	"properties": {
		"publisher": "Microsoft.EnterpriseCloud.Monitoring",
		"type": "OmsAgentForLinux",
		"typeHandlerVersion": "1.11",
		"autoUpgradeMinorVersion": true,
		"settings": {
			"workspaceId": "[reference(variables('logAnalyticsId'), '2015-11-01-preview').customerId]"
		},
		"protectedSettings": {
			"workspaceKey": "[listKeys(variables('logAnalyticsId'), '2015-11-01-preview').primarySharedKey]"
		},
		"forceUpdateTag": "RerunExtension"
	}
}
```

This works fine on Centos 7, but as I try to upgrade to Centos 8 this extension is now failing.

I'm not sure the best place to find logs, but I found some logs in `/var/log/waagent.log`:

```
2019/12/19 18:02:37.584161 WARNING ExtHandler Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config'
2019/12/19 18:02:37.596901 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config' [<FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 263 in run>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 372 in handle_ext_handlers>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 384 in wait_for_handler_successful_completion>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1137 in is_ext_handling_complete>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1122 in get_ext_handling_status>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1068 in get_status_file_path>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1052 in get_largest_seq_no>], duration=0
2019/12/19 18:02:40.725533 WARNING ExtHandler Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config'
2019/12/19 18:02:40.735810 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config' [<FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 263 in run>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 372 in handle_ext_handlers>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 384 in wait_for_handler_successful_completion>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1137 in is_ext_handling_complete>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1122 in get_ext_handling_status>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1068 in get_status_file_path>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1052 in get_largest_seq_no>], duration=0
2019/12/19 18:02:43.847749 WARNING ExtHandler Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config'
2019/12/19 18:02:43.860551 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config' [<FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 263 in run>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 372 in handle_ext_handlers>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 384 in wait_for_handler_successful_completion>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1137 in is_ext_handling_complete>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1122 in get_ext_handling_status>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1068 in get_status_file_path>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1052 in get_largest_seq_no>], duration=0
2019/12/19 18:02:46.986284 WARNING ExtHandler Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config'
2019/12/19 18:02:46.996496 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config' [<FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 263 in run>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 372 in handle_ext_handlers>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 384 in wait_for_handler_successful_completion>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1137 in is_ext_handling_complete>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1122 in get_ext_handling_status>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1068 in get_status_file_path>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1052 in get_largest_seq_no>], duration=0
2019/12/19 18:02:50.120136 WARNING ExtHandler Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config'
2019/12/19 18:02:50.134520 ERROR ExtHandler Event: name=WALinuxAgent, op=ExtensionProcessing, message=Exception processing extension handlers: [Errno 2] No such file or directory: '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/config' [<FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 263 in run>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 372 in handle_ext_handlers>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 384 in wait_for_handler_successful_completion>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1137 in is_ext_handling_complete>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1122 in get_ext_handling_status>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1068 in get_status_file_path>, <FrameSummary file bin/WALinuxAgent-2.2.45-py2.7.egg/azurelinuxagent/ga/exthandlers.py, line 1052 in get_largest_seq_no>], duration=0
```

(There are hundreds of lines just like this.)

In `/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinx/`, I see `CommandExecution.log`, but this is the only line:

```
2019/12/19 17:58:41.470509 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17
```

**Comment by kwhooley** [comment]
I'm having a similar issue, but when attempting to install the omsagent, the error I receive is "Python is not configured or Python does not support ctypes on this system, installation cannot continue.
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61"

I have python2, 2.7 and now 3.6 installed, none of which is allowing me to install ctypes. I was running CentOS7 prior and upgraded because I was having issues with rsyslog. The purpose of this machine is to forward all my syslog messages to azure.

**Comment by johanburati** [comment]
You might want to refer to https://github.com/Azure/WALinuxAgent/issues/1719

**Comment by chandlerkent** [comment]
@johanburati thank you for the information. I tried installing Python 2.7 as you recommended, but I am now getting this error:

[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17/omsagent.py -install [stdout] 2020/01/21 17:53:03 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Install,failed,51,Unsupported operating system: CentOS Linux 8.0.1905 [stderr]

**Comment by kwhooley** [comment]
> You might want to refer to [Azure/WALinuxAgent#1719](https://github.com/Azure/WALinuxAgent/issues/1719)

@johanburati , thank you. I figured I needed to tell the OS to use python2 in order to satisfy the ctypes requirement, I used that same command (alternatives --set python /usr/bin/python2) and it worked perfectly.

**Comment by jasonpnnl** [comment]
I ran through a similar series of issues but with RHEL 8 and end up with the error message: 
`2020/01/22 23:29:09 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.17] Install,failed,51,Unsupported operating system: Red Hat Enterprise Linux 8.0`

The docs say that the goal is for OMS Agent to "Always support any new Azure Linux Endorsed distros/versions." RHEL 8 appears to be a supported distro/version. Is RHEL 8 support forthcoming or should it already be working?

**Comment by johanburati** [comment]
@chandlerkent, @jasonpnnl, thanks for reporting the issue, same thing with Oracle Linux 8.

I have checked the code, the supported distributions are hard coded and 8 was not part of the list.

I have reported the issue in the extensions repo (https://github.com/Azure/azure-linux-extensions/issues/992) and also submitted a fix (https://github.com/Azure/azure-linux-extensions/pull/993) so hopefully this will get fix in the next release.

**Comment by hestolz** [comment]
By design. These distributions are not yet supported by the agent. We will verify them in the future; RHEL8 is targeted for this February. Others will follow TBD.

**Comment by DaveB93** [comment]
@hestolz is there an issue we should follow for updates on this? Or is this the best one?

**Comment by Faeon4** [comment]
Also waiting, at the moment none of our production servers running RHEL 8.1. with the Azure Extension that is tied to diagnostics, analytics etc. Not sure when in Feb it will come out though. I think all we can do is wait until then @DaveB93

**Comment by fepere** [comment]
Hello, any news about this issue ?

**Comment by parsnep** [comment]
Is there any update on this issue?

**Comment by Faeon4** [comment]
I have a ticket open with Microsoft, since we are a partner, they are giving me weekly updates, there is suppose to be a release sometime towards the end of March, but that is subject to change.

**Comment by kamsalisbury** [comment]
On CentOS 8 minimal install, follow these work-a-round steps;

sudo yum install python2
sudo alternatives --set python /usr/bin/python2

*then run the install procedure.

If you prefer a more recent python, modify the same concept work-a-round steps;
sudo yum install python3
sudo alternatives --set python /usr/bin/python3

*then run the install procedure.

Of course, if you selected a different install base (instead of minimal), you may already have python installed.

**Comment by Faeon4** [comment]
Hello,

That does not work I have tried that method

--
Kind Regards,
[thumbzup]

Paul Dias
IT Operations Engineer
[M.]
+27 82 937 7669
[T.]
+27 87 550 2689<tel:+27875502689>
[S.]
paul-dias
www.thumbzup.com<https://www.thumbzup.com/>

**Comment by Faeon4** [comment]
Hello,

And then a whole bunch of other errors, like python2 errors and searching for packages that does not exist anymore in RHEL8.1 or has been renamed differently or versions etc. RedHat support says this is 3rd Party so it will need to be fixed and corrected by them.



2020/03/30 20:07:40 ERROR:Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/03/30 20:07:40 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/03/30 20:07:40 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Install,failed,51,Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/03/31 20:06:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] sequence number is 0

2020/03/31 20:06:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/config/0.settings

2020/03/31 20:06:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"publicSettings": {"workspaceId": "eb43d3f4-e267-4f37-a90c-8b67ed63555d"}, "protectedSettings": "MIICtAYJKoZIhvcNAQcDoIICpTCCAqECAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEFHpdBfnXhGPQNRwfu0Dny4wDQYJKoZIhvcNAQEBBQAEggEAET8Rs1pXvMFsVs6IYOo0kbPGPQ3StqunnP3Gm+1Xrn3bxn8r14S/f94udwOejuoG02e0GMFsG2+9G1/BAeiDr+o22YqfJD8xIwIDSHdxYW4ywBJhGt/wpVwAkJ31NZKdC0f0nYg+uz9iQJtwVAbMZVsi5xXmWqpIpkD4BclTlM91cFySgbly25Vj3JwcEg248I8Y8MglMhaxlRmJFKzcuppXO8wbEHFeFUfAakDJpIcdHIObPb/uPc6zqNGN1+Sk5TKhyRwvVRIyw2h1/okyGBscBCujQ3T1xnA0jvd0/HuKXsKCEDHmLfvC5xifgUhyPR+3slY0e6CmeXPH/qBuZTCCAS0GCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIm96YxM3PmbWAggEI6JXmony0dwe5Fu7gqx3+lH92miyCK5mB0M/+VN/8d4gEfd8QIDLKyupsjQuWYGzTa7NpMdmoBIBk++n1P/hJTHHju2zhNuvg9GsKkidLjkVzZFuec5ARAhMWyQUOhCb3qy7CgeNxBTMZg1L+8o5csiKkxTQsScru76FjJ+7CryPiO+LoFDJVQRe1pToahir4sktTnejGDKOImemHwAPLKQsij9dR1lN6OcYG4VysNdCg/8+YUrFtavYt1OksPNBGaym07mlJCnJbG1NuvgOLTTGkL6Z6daEdhNG1QWwokPlBO4aUkEheFpNLFCUFSkD2DgDO/JUKRr+0FwK6T7iBCMze+2M2XOQu", "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}

2020/03/31 20:06:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Config decoded correctly.

2020/03/31 20:06:49 ERROR:Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/03/31 20:06:49 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/03/31 20:06:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Install,failed,51,Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/04/01 06:06:32 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] sequence number is 0

2020/04/01 06:06:32 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25/config/0.settings

2020/04/01 06:06:32 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] JSON config: {"runtimeSettings": [{"handlerSettings": {"publicSettings": {"workspaceId": "e839c7ea-11d8-4337-9dbb-646c91df662f"}, "protectedSettings": "*** REDACTED ***", "protectedSettingsCertThumbprint": "*** REDACTED ***"}}]}

2020/04/01 06:06:32 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Config decoded correctly.

2020/04/01 06:06:32 ERROR:Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/04/01 06:06:32 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Unsupported operating system: Red Hat Enterprise Linux 8.1

2020/04/01 06:06:32 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.12.25] Install,failed,51,Unsupported operating system: Red Hat Enterprise Linux 8.1


--
Kind Regards,
[thumbzup]

Paul Dias
IT Operations Engineer
[M.]
+27 82 937 7669
[T.]
+27 87 550 2689<tel:+27875502689>
[S.]
paul-dias
www.thumbzup.com<https://www.thumbzup.com/>



From: Paul Dias <paul@thumbzup.com>
Date: Wednesday, 01 April 2020 at 07:13
To: microsoft/OMS-Agent-for-Linux <reply@reply.github.com>, microsoft/OMS-Agent-for-Linux <OMS-Agent-for-Linux@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [microsoft/OMS-Agent-for-Linux] Install Fails on Centos 8 (#1117)

Hello,

That does not work I have tried that method

--
Kind Regards,
[thumbzup]

Paul Dias
IT Operations Engineer
[M.]
+27 82 937 7669
[T.]
+27 87 550 2689<tel:+27875502689>
[S.]
paul-dias
www.thumbzup.com<https://www.thumbzup.com/>

**Comment by michaelschmit** [comment]
Does anyone have an update on this issue?  I just upgraded some VMs to RHEL 8 and it appears the agents are not being installed.

**Comment by Lowmach1ne** [comment]
any update ?

**Comment by AdamWyzgol** [comment]
On RHEL 8.2 it is still not working, can anyone fix that?

**Comment by fepere** [comment]
still a issue, any update or a ETA to get this fixed ? a lot of production VMs are there without a monitoring

**Comment by pankaj-pal** [comment]
> 
> 
> (Edited to reflect python2 deprecated.)
> On CentOS 8 **minimal install**, follow these work-a-round steps;
> sudo yum install python3
> sudo alternatives --set python /usr/bin/python3
> *then run the install procedure.
> 
> If you prefer a deprecated python2, modify the same concept work-a-round steps;
> sudo yum install python2
> sudo alternatives --set python /usr/bin/python2
> *then run the install procedure.

I was trying this in on CentOs 8, python3 only. I was trying alias. It worked with Altenatives...thanks.

**Comment by parsnep** [comment]
I installed version 1.13.7-0 on my centos 8 server (tested python 2 & 3).
But my server is not showing in Log Analytics.

If i try to start the service with "service_control" i get the following message:
`service_control: line 160: /etc/opt/microsoft/omsagent/workspace-id/conf/omsadmin.conf: No such file or directory`

**Comment by parsnep** [comment]
> I installed version 1.13.7-0 on my centos 8 server (tested python 2 & 3).
> But my server is not showing in Log Analytics.
> 
> If i try to start the service with "service_control" i get the following message:
> `service_control: line 160: /etc/opt/microsoft/omsagent/workspace-id/conf/omsadmin.conf: No such file or directory`
> 
> Also used --purge to clean the installations.

Any update on this issue, just tested this on RHEL 8.2.
Here is experience the same error. 

Installation method
`wget https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.13.7-0/omsagent-1.13.7-0.universal.x64.sh`
`sudo yum install python3 -y`
`sudo alternatives --set python /usr/bin/python3`
`sudo sh ./omsagent-*.universal.x64.sh --upgrade -p <OMS gateway proxy> -w <workspace> -s <key>`

**Comment by mladen-mysynergy** [comment]
MY Synergy - Internal Use

Hello,
Thank you. The problem is not with the OMS agent but the MDATP for linux.
I followed the instruction for manual deply from here: https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/linux-install-manually

The agent deploys fine and it says it is connected at first and then the error is this:
[cid:image001.jpg@01D64ED1.716368C0]
Nevertheless the last seen date updates fine and if I do the test:
curl -o ~/Downloads/eicar.com.txt https://www.eicar.org/download/eicar.com.txt

The thread shows in the console.
In addition this is the status of the MDATP on the server:
[mysynergy@crm ~]$ mdatp health
healthy                                     : true
licensed                                    : true
engine_version                              : "3.0"
app_version                                 : "101.02.55"
org_id                                      : "d7e49cad-a1d9-4560-9303-8f04424ef6de"
log_level                                   : "info"
machine_guid                                : "fb0b3342-603a-55dc-f907-122bb606aa5b"
release_ring                                : "Production"
product_expiration                          : Mar 22, 2021 at 05:04:10 AM
cloud_enabled                               : true
cloud_automatic_sample_submission_consent   : "safe"
cloud_diagnostic_enabled                    : false
real_time_protection_enabled                : true
real_time_protection_available              : true
real_time_protection_subsystem              : "fanotify"
definitions_updated                         : Jun 30, 2020 at 08:47:03 AM
definitions_updated_minutes_ago             : 159
definitions_version                         : "80957"
definitions_status                          : "up_to_date"
edr_early_preview_enabled                   : "disabled"
edr_device_tags                             : []
edr_machine_id                              : "71050e4f656fc6062a43b2c0dd36c1256d679b5b"

[mysynergy@crm ~]$ mdatp connectivity test
Testing connection with https://cdn.x.cp.wd.microsoft.com/ping ... [OK]
Testing connection with https://eu-cdn.x.cp.wd.microsoft.com/ping ... [OK]
Testing connection with https://wu-cdn.x.cp.wd.microsoft.com/ping ... [OK]
Testing connection with https://europe.x.cp.wd.microsoft.com/api/report ... [OK]
Testing connection with https://usseu1northprod.blob.core.windows.net ... [OK]
Testing connection with https://usseu1westprod.blob.core.windows.net ... [OK]
Testing connection with https://winatp-gw-cus.microsoft.com/test ... [OK]
Testing connection with https://winatp-gw-eus.microsoft.com/test ... [OK]
Testing connection with https://winatp-gw-weu.microsoft.com/test ... [OK]
Testing connection with https://winatp-gw-neu.microsoft.com/test ... [OK]
Testing connection with https://winatp-gw-ukw.microsoft.com/test ... [OK]
Testing connection with https://winatp-gw-uks.microsoft.com/test ... [OK]
Testing connection with https://eu-v20.events.data.microsoft.com/ping ... [OK]
Testing connection with https://us-v20.events.data.microsoft.com/ping ... [OK]
Testing connection with https://uk-v20.events.data.microsoft.com/ping ... [OK]
Testing connection with https://v20.events.data.microsoft.com/ping ... [OK]


Best Regards,
_____________________________________
Mladen Georgiev
CTO
MY Synergy
E-mail: Mladen.Georgiev@MYSynergy.bg<mailto:Mladen.Georgiev@MYSynergy.bg>
Mobile: +359 889 500080<tel:003598889500080>


________________________________
CONFIDENTIAL
This message and any attachments (the "Message") are confidential and intended solely for the addressee(s). If you are not the intended recipient, any use, copying or dissemination is strictly prohibited. If you are not the intended recipient, please notify the sender immediately by return and delete this original Message and any copies from your system. E-mails are susceptible to alteration. MY Synergy Ltd. and its subsidiaries and other affiliates shall not be liable if the Message is altered, changed or falsified.
This is an environmentally friendly email. Please do not print it unless it is really necessary.

**Comment by parsnep** [comment]
Hi @mladen-mysynergy ,

I don't have ATP enabled in my environment, how would this fix my problem?

**Comment by mladen-mysynergy** [comment]
> Hi @mladen-mysynergy
> 
> I don't have ATP enabled in my environment, how would this fix my problem?

Sorry I posted the post before yours by mistake.

**Comment by pcamposs** [comment]
any update ?

**Comment by johanburati** [comment]
@pcamposs 
Just tested it and it works now on Redhat 8, do you have python installed ?

**Comment by pcamposs** [comment]
Yes, now it is Working  
My Steps from Bash
sudo yum install python2
sudo alternatives --set python /usr/bin/python2
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <XXXX> -s <YYYY> -d opinsights.azure.com

Then enable insights .... after 10min the logs appear 

The agent is always in "Connecting" state but is the least of the problems now
And from the VM Blade, always appear Insight Disable, but if you go to the logs or the azure Monitor, the performance Insights it works 

![PerfCentos8](https://user-images.githubusercontent.com/49884507/86798011-5385bb80-c03e-11ea-949b-61a8de6653b9.JPG)

![Insights](https://user-images.githubusercontent.com/49884507/86797960-4668cc80-c03e-11ea-875a-31710b673819.JPG)

Thanks!!!

**Comment by johanburati** [comment]
Great! 🎉🎉🎉
If the status still does not change after a while don't hesitate to open a ticket with Azure support for them to investigate.

**Comment by parsnep** [comment]
> > I installed version 1.13.7-0 on my centos 8 server (tested python 2 & 3).
> > But my server is not showing in Log Analytics.
> > If i try to start the service with "service_control" i get the following message:
> > `service_control: line 160: /etc/opt/microsoft/omsagent/workspace-id/conf/omsadmin.conf: No such file or directory`
> > Also used --purge to clean the installations.
> 
> Any update on this issue, just tested this on RHEL 8.2.
> Here is experience the same error.
> 
> Installation method
> `wget https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.13.7-0/omsagent-1.13.7-0.universal.x64.sh`
> `sudo yum install python3 -y`
> `sudo alternatives --set python /usr/bin/python3`
> `sudo sh ./omsagent-*.universal.x64.sh --upgrade -p <OMS gateway proxy> -w <workspace> -s <key>`

Fixed this by using a http proxyadres instead of an https proxyadres. Otherwise i will get a silent ssl error in the installation, but the installation will succeed .

**Comment by johanburati** [comment]
@parsnep I think you'd better open a case with MS directly from the Azure Portal, I do not think the OMS people are actively monitoring this thread.

**Comment by Klaas-** [comment]
@johanburati that won't help until CentOS 8 is officially supported. https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#supported-distros

**Comment by johanburati** [comment]
@Klaas- Good point, well now that RHEL 8 is supported, Centos 8 should hopefully not take much longer 😏

**Comment by parsnep** [comment]
My agents work perfectly fine in centos 8 and rhel 8

**Comment by johanburati** [comment]
> My agents work perfectly fine in centos 8 and rhel 8

I guess you patched the script then, because as of v1.13.15 I can see that's Centos 8 is still not allowed in the code, it's hard coded.

**Comment by RobinBeismann** [comment]
Is there any update on the support for CentOS 8.1?

**Comment by hestolz** [comment]
OMS 1.13.27 is now released (extension and shell bundle both) which offers support for RHEL8.X, CentOS 8.X, SLES15.X, Ubuntu 20.04. The requirement for python2 and python aliasing has been eliminated, so you can now use this on a python3-only system if you choose. Note that if both python 2 and 3 are present, the agent will always default to python2. 

Also the ctypes module is still a requirement; python3 should have this by default, but if you have python2 you may need to install the `python-ctypes` package.

**Comment by RobinBeismann** [comment]
Thanks, still looks like Azure tries to install the old version through:

> 
"message": "The handler for VM extension type 'Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux' has reported terminal failure for VM extension 'OmsAgentForLinux' with error message: '[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/omsagent_shim.sh -install\n[stdout]\n2020/07/14 20:47:36 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] Install,failed,51,Unsupported operating system: CentOS Linux 8.1.1911\n\n\n[stderr]\nnux-1.13.13/keys/keyring.gpg' created\ngpg: directory '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/keys/.gnupg' created\ngpg: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/keys/.gnupg/trustdb.gpg: trustdb created\ngpg: key 20541A3DDE321294: public key \"Microsoft (Release Signing) <dscgpgkey@microsoft.com>\" imported\ngpg: can't connect to the agent: IPC connect call failed\ngpg: Total number processed: 1\ngpg:               imported: 1'.\r\n    \r\n'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/VMExtensionOMSAgentLinuxTroubleshoot'"

**Comment by hestolz** [comment]
@RobinBeismann not sure but maybe UM is using some cached version in their calls to install the extension. If you are using UM you can just preinstall the OMS extension and to be sure use the `az vm extension set ... --version 1.13.27` flag. And then enable UM.

**Comment by hecuro** [comment]
hola con todos, tengo este mensaje de error en mi backup en azure.

[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.40/omsagent_shim.sh -install [stdout] 2023/10/10 16:47:48 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.40] Install,failed,51,Unsupported operating system: Ubuntu 22.04 [stderr]

ya reiniciamos el agente de l backup, muy aparte sysadmin indica esto:  Para poder revisar a detalle el caso se necesita el binario patch de su agente q realiza el backup para poder brindar una solucion ( esa parte no entiendo)

Saludos
