### ISSUE TITLE
OMS Agent Fails requiring ctypes

### ISSUE THREAD

**Issue by kwhooley** [microsoft/OMS-Agent-for-Linux#1121]
I cannot install the omsagent, the error I receive is "Python is not configured or Python does not support ctypes on this system, installation cannot continue.
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61"

I have python2, 2.7 and now 3.6 installed, none of which is allowing me to install ctypes. I was running CentOS7 prior and upgraded because I was having issues with rsyslog. The purpose of this machine is to forward all my syslog messages to azure.

**Comment by sissy1655** [comment]
did you find a solution for this?
