### ISSUE TITLE
Right way to install OMS agent in  thousands of server ?

### ISSUE THREAD

**Issue by melvilgit** [microsoft/OMS-Agent-for-Linux#1127]
What would be the right way to install OMS agent in  thousands of server ?
I knew this can be achieved easily using Azure ARM templates with extension , unfortunately we don't uses ARM for provisioning resources.
Can we uses Config management like Puppet to do this operation ?

**Comment by hestolz** [comment]
In general, we don't encourage custom deployment methods; from support experience, they tend to be hard to maintain correctly. 

Are you using Azure VMs? If so, any particular reason for avoiding ARM? For this scenario my recommendation by far is to use the extension. It is the safest and easiest way to achieve your goal. 

If you are onprem, you may be interested in Azure Arc, which allows you to treat onprem machines like Azure resources, including installing extensions.
