### ISSUE TITLE
Solaris 64-bit Feature Request

### ISSUE THREAD

**Issue by beigewell** [microsoft/OMS-Agent-for-Linux#1132]
when is Solaris and Solaris Sparc going to be supported on this agent please? Specifically for 64-bit

**Comment by hestolz** [comment]
Sorry, we don't have any plans to support these systems. Our strategy is to follow the [Azure endorsed Linux distribution](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros#supported-distributions-and-versions) list, except when it is not technically feasible (e.g. CoreOS).
