### ISSUE TITLE
OMSAgent is in undefined state after disconnect and reconnect

### ISSUE THREAD

**Issue by hcrutz** [microsoft/OMS-Agent-for-Linux#1152]
After the last VMInsights update we had problems with missing perf data, or data not store in expected solution/table. While trying to solve this, we also disconnected and then tried to reconnect VM/omsagent. 
But the reconnection of agent to workspace failed
When you run omsadmin manually, it reports agent already onboarded and running, but it doesn't work. 
In extension log, you can find errors accessing run, cert or conf directory.
When looking into /var/opt/microsoft/omsagent, there're links to subfolders with the workspace ID in path, but no real subfolder with the workspace ID as name, so all the links are dead!
The Installation of package is skipped, cause the existing version is the expected version, and the script starts directly with configuration. It seems like it expect the workspace id folder and links already created.

**Comment by hestolz** [comment]
If you are still blocked on this issue, please open an Azure support ticket. Thanks
