### ISSUE TITLE
OMS agent not supported on SLES 15 SP1

### ISSUE THREAD

**Issue by DimitrovMiro** [microsoft/OMS-Agent-for-Linux#1159]
Hi guys,

Do we have an ETA when OMS agent will be supported on SLES 15 SP1

**Comment by DimitrovMiro** [comment]
Hi guys,

Could you please provide a feedback on this issue

**Comment by DimitrovMiro** [comment]
@hestolz could you please have a look at provide a short feedback on this issue

**Comment by msftrobiro** [comment]
Is there any update on this topic, since it still fails for SLES15SP1 without any such exclusion of support in documentation I could find.

**Comment by DimitrovMiro** [comment]
@msftrobiro still no feedback
@hestolz could please someone have a look at that issue

**Comment by DimitrovMiro** [comment]
Hello,
Do we have any feedback.

**Comment by Lukeout** [comment]
SP1 is currently not supported.

**Comment by DimitrovMiro** [comment]
thank  you @Lukeout . Do you have ETA if/when it will be supported

**Comment by modemboy** [comment]
SLES15 SP1 came out over a year ago and Azure is a SuSE partner. How is this not supported yet?

**Comment by hestolz** [comment]
@DimitrovMiro, @modemboy, @msftrobiro, SLES15 SP1+ is now supported, as of extension version 1.13.27 which is now available in all public cloud regions. The issue with install was identified and is resolved now.
