### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by johanburati** [microsoft/OMS-Agent-for-Linux#1163]
When I look at the [release](https://github.com/microsoft/OMS-Agent-for-Linux/releases) page it  says the latest release is version **1.12.15**, however on the VMs I can see version **1.12.25** is installed.

Where can find the source code for version **1.12.25** ?

**Comment by alexvy86** [comment]
@johanburati given that the last commit in `master` is from March 6th, my guess is that version 1.12.25 matches the `master` branch as of today. Hopefully we get a tagged artifact for the latest version soon, as well as official release notes.

**Comment by ssrirama-aka** [comment]
I ran into the same issue today when checking VMs. Echoing comments made by @johanburati and @alexvy86 .  Can the latest release and its artifacts get tagged?

**Comment by hestolz** [comment]
1.12.15 and 1.12.25 are identical, we transitioned to a new build system and the latter is the newer build but from the same source.
