### ISSUE TITLE
Support for Cisco FTD variant of ASA

### ISSUE THREAD

**Issue by jpmorrison** [microsoft/OMS-Agent-for-Linux#1186]
Can support for Cisco FTD be added? It uses the same log format except logs with %FTD instead of %ASA.

Should be simple to change a few regex: like security_events.conf
I'm not sure about what ./source/code/plugins/security_lib.rb is doing with SECURITY_CISCO_ASA_BLOB 

Cisco docs:
302016

Error Message %ASA-6-302016: Teardown UDP connection number for interface :real-address /real-port [(idfw_user )] to interface :real-address /real-port [(idfw_user )] duration hh :mm :ss bytes bytes [(user )] 

302016

Error Message %FTD-6-302016: Teardown UDP connection number for interface :real-address /real-port [(idfw_user )] to interface :real-address /real-port [(idfw_user )] duration hh :mm :ss bytes bytes [(user )]

**Comment by hestolz** [comment]
Feel free to open a pull request to address this.
