### ISSUE TITLE
Installing agent on linux servers

### ISSUE THREAD

**Issue by Arslannetworkhomes** [microsoft/OMS-Agent-for-Linux#1207]
Monitoring agent not being installed on my linux servers, I am running this command and connecting via putty, any information will be great.

Command I am using to install the agent.

wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w **workspace id**-s **primarykey**== -d opinsights.azure.com

**Comment by mladen-mysynergy** [comment]
Option -d opinsights.azure.com is for government cloud. If you are not connecting to government remove that option.

**Comment by hestolz** [comment]
Not enough info to debug. Please open a ticket with Azure Support if you require further assistance. Thanks!
