### ISSUE TITLE
Installing on Databricks cluster (omsadmin.conf: No such file or directory)

### ISSUE THREAD

**Issue by scotty-tarvan** [microsoft/OMS-Agent-for-Linux#1210]
I'm following instructions for setting up monitoring on Azure Databricks clusters as found here 

https://github.com/Azure/AzureDatabricksBestPractices

The installation fails on restart with error: 

```
_/opt/microsoft/omsagent/bin/service_control: line 160: /etc/opt/microsoft/omsagent/c6a62438-xxxx-4f5c-a8e6-d9ee4aaa6c45/conf/omsadmin.conf: No such file or directory
ERROR:  start_omsagent failed with result '1' on workspace c6a62438-xxxx-4f5c-a8e6-d9ee4aaa6c45.
chmod: cannot access '/opt/dsc': No such file or directory
/var/lib/dpkg/tmp.ci/preinst: 33: kill: No such process_
```

This is the startup script (have altered log id and keys to keep private):

```
sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d 
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w LA-ID -s LA-KEY          
sudo su omsagent -c 'python /opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py' 
sudo /opt/microsoft/omsagent/bin/service_control restart LA-ID

```
See attached full log file.

Any help please? 

[20200613_182648_00_configure-omsagent.sh.stderr.log](https://github.com/microsoft/OMS-Agent-for-Linux/files/4775220/20200613_182648_00_configure-omsagent.sh.stderr.log)

**Comment by jakeatmsft** [comment]
We are seeing the same issue at one of my clients.  It seems like it's cluster specific as they have other clusters using the same script that are starting up successfully.
