### ISSUE TITLE
OMS agent fails to install on RHEL 8.0

### ISSUE THREAD

**Issue by DimitrovMiro** [microsoft/OMS-Agent-for-Linux#1213]
Although the article says OMS agent is already supported on RHEL 8.0, the installation fails. Error message from azure cli. Python is installed manually
C:\Users\mdimitrov20>az vm extension set --resource-group mxxx --vm-name rhel8md --name OmsAgentForLinux --publisher Microsoft.EnterpriseCloud.Monitoring --version 1.13 --protected-settings '{"workspaceKey":"7Fg+xxxxxxxxxx=="}' --settings '{"workspaceId":"37f96841-b9e5-4fxxxxxx"}' --verbose
Deployment failed. Correlation ID: 879a4b69-5c0d-4434-8d46-33c58ba7cfab. The handler for VM extension type 'Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux' has reported terminal failure for VM extension 'OmsAgentForLinux' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/omsagent_shim.sh -install
[stdout]
2020/06/22 06:13:56

[stderr]
Python 2.7.17
nux-1.13.13/keys/keyring.gpg' created
gpg: directory '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/keys/.gnupg' created
gpg: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13/keys/.gnupg/trustdb.gpg: trustdb created
gpg: key 20541A3DDE321294: public key "Microsoft (Release Signing) <dscgpgkey@microsoft.com>" imported
gpg: can't connect to the agent: IPC connect call failed
gpg: Total number processed: 1
gpg:               imported: 1'.

'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/VMExtensionOMSAgentLinuxTroubleshoot'

Anyone, Microsoft, any idea what is causing the issue

**Comment by DimitrovMiro** [comment]
More from the extension log
2020/06/22 06:13:56 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] ShellBundle signing verification succeeded
2020/06/22 06:13:56 ERROR:Install failed with error: 'unicode' object has no attribute 'get'
2020/06/22 06:13:56 ERROR:Stacktrace: Traceback (most recent call last):
2020/06/22 06:13:56 ERROR:  File "./omsagent.py", line 296, in main
2020/06/22 06:13:56 ERROR:    exit_code, output = operations[operation]()
2020/06/22 06:13:56 ERROR:  File "./omsagent.py", line 442, in install
2020/06/22 06:13:56 ERROR:    workspaceId = public_settings.get('workspaceId')
2020/06/22 06:13:56 ERROR:AttributeError: 'unicode' object has no attribute 'get'
2020/06/22 06:13:56 ERROR:
2020/06/22 06:13:56 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] Install failed with error: 'unicode' object has no attribute 'get'
2020/06/22 06:13:56 ERROR:Stacktrace: Traceback (most recent call last):
2020/06/22 06:13:56 ERROR:  File "./omsagent.py", line 296, in main
2020/06/22 06:13:56 ERROR:    exit_code, output = operations[operation]()
2020/06/22 06:13:56 ERROR:  File "./omsagent.py", line 442, in install
2020/06/22 06:13:56 ERROR:    workspaceId = public_settings.get('workspaceId')
2020/06/22 06:13:56 ERROR:AttributeError: 'unicode' object has no attribute 'get'
2020/06/22 06:13:56 ERROR:
2020/06/22 06:13:56 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.13] Install,failed,1,Install failed with error: 'unicode' object has no attribute 'get'
2020/06/22 06:13:56 Stacktrace: Traceback (most recent call last):
2020/06/22 06:13:56   File "./omsagent.py", line 296, in main
2020/06/22 06:13:56     exit_code, output = operations[operation]()
2020/06/22 06:13:56   File "./omsagent.py", line 442, in install
2020/06/22 06:13:56     workspaceId = public_settings.get('workspaceId')
2020/06/22 06:13:56 AttributeError: 'unicode' object has no attribute 'get'

**Comment by hestolz** [comment]
@DimitrovMiro please try extension version 1.13.27 which is now available in all public cloud regions. This issue should be fixed; if not feel free to provide more details. Thanks!
