### ISSUE TITLE
Error on adding custom plugin: Unknown input plugin 

### ISSUE THREAD

**Issue by arjun-urs** [Microsoft/OMS-Agent-for-Linux#122]
Hey guys,

I am trying to add a custom plugin and I am facing this error:

`2016-06-30 20:58:47 +0000 [error]: fluent/supervisor.rb:313:rescue in main_process: config error file="/etc/opt/microsoft/omsagent/conf/omsagent.conf" error="Unknown input plugin 'in_cloudfetch'. Run 'gem search -rd fluent-plugin' to find plugins"`

The same plugin works for td-agent.

Here are the steps I followed:

Updated /etc/opt/microsoft/omsagent/conf/omsagent.conf with:
```
<source>
  type in_cloudfetch
  tag cloud
</source>
```

Created a new 'plugin' folder `/etc/opt/microsoft/omsagent/conf/plugin` and added my input plugin: `in_cloudfetch.rb`

```
require 'fluent/input'
module Fluent
  class InCloudfetch < Input
    Fluent::Plugin.register_input('in_cloudfetch', self)

    config_param :tag

    def configure(conf)
      super
      # My plugin code here
    end

    def start
      super
      # My plugin code here
    end

    def shutdown
      super
      # My plugin code here
    end
  end
end
```

Restarted OMS agent:
`sudo /opt/microsoft/omsagent/bin/service_control restart`

Let me know if I am missing anything here.

**Comment by KrisBash** [comment]
Please copy your plugin to /opt/microsoft/omsagent/plugin, restart the omsagent service, and you should see it work.

**Comment by arjun-urs** [comment]
Thanks, might as well add it in the documentation.
