### ISSUE TITLE
Alert when OMS agents are offline

### ISSUE THREAD

**Issue by Mccrawley** [microsoft/OMS-Agent-for-Linux#1226]
Hi all,

Im new to OMS and want to ask if there is a way to alert when a Virtual machine fails to report into OMS.
I just had a relatively inactive box go down and I need to be able to alert against this. 

Do you have any suggestions?

**Comment by profesor79** [comment]
hi @Mccrawley ,
you can setup those alerts in Log Analytics - see this arctle [https://docs.microsoft.com/en-us/azure/azure-monitor/learn/tutorial-response](https://docs.microsoft.com/en-us/azure/azure-monitor/learn/tutorial-response).


I am using Sentinel and a logic app that sends an alert with details.
