### ISSUE TITLE
onboard_agent.sh contains a URL still pointing to OMSAgent_v1.13.7-0 causing a 404 error

### ISSUE THREAD

**Issue by Dann1112** [microsoft/OMS-Agent-for-Linux#1235]
The command to download and install the agent that uses the "onboard_agent.sh" script uses an outdated version of the agent causing a 404 error.

`wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <YOUR WORKSPACE ID> -s <YOUR WORKSPACE PRIMARY KEY>`

The "onboard_agent.sh" script contains the following line:

`GITHUB_RELEASE_X64="https://github.com/microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.13.7-0/"`

Which is now throwing a 404 due to the release of the new Agent v1.13.9-0 instead, in:
https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.13.9-0

**Comment by ffloimair** [comment]
latest master seems to include the fix now. Just checked.

**Comment by hestolz** [comment]
#1237
