### ISSUE TITLE
Cisco ASA missing DeviceEventClassID

### ISSUE THREAD

**Issue by KeithDarragh1** [microsoft/OMS-Agent-for-Linux#1245]
Hi,

I'm new to using the OMSagent etc, but I have setup a UbuntoServer 18.04 LTS and install the agent.

I'm getting logs etc, but some of the Cisco ASA workbook won't show data, e.g. Top 5 commands executed, because the DeviceEventClassID field as no data. Unfortunately the Message field has the event id removed from it too.

Is there something I'm doing wrong?

Thanks
Keith
![AzureCase](https://user-images.githubusercontent.com/3389637/92470845-f093da80-f1ce-11ea-8ab7-5b8ee0a4bef3.PNG)

**Comment by haiderim** [comment]
This should fix your problem

https://github.com/microsoft/OMS-Agent-for-Linux/pull/1176/files

**Comment by KeithDarragh1** [comment]
Hi @haiderim 

Thank you so much. That has fixed it for me!

Keith
