### ISSUE TITLE
Unable to install OMS agent on RHEL 8.2

### ISSUE THREAD

**Issue by SathishKumarPatchaiappan** [microsoft/OMS-Agent-for-Linux#1249]
Hi, Im trying to connect log analytics agent on RHEL 8.2 Azure VM but it keeps failing with below error even though the current python version is 3.6. Any suggestions ?

[ExtensionOperationError] Non-zero exit code: 52, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.15/omsagent_shim.sh -install [stdout] 2020/09/22 05:42:39 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.15] Install,failed,52,Install failed with exit code 52 Installation failed due to missing dependencies. For details, check logs in /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log [stderr] Python 2.7.17 ctypes on this system, installation cannot continue. Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module. You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'. You can run this shell bundle with --force; in this case, we will install omsagent, but omsconfig (DSC configuration) will not be available and will need to be re-installed. Shell bundle exiting with code 61

**Comment by pentiumoverdrive** [comment]
Works fine for me. 
Did you run the following?:

sudo yum install python2 -y
sudo alternatives --set python /usr/bin/python2

**Comment by hestolz** [comment]
OMS will default to python2 if both 2 and 3 are available. This is not configurable. To eliminate this issue, as noted in the message please install the `python-ctypes` package and ensure it is available by running `python2 -c 'import ctypes'`.

**Comment by Klaas-** [comment]
@hestolz any reason to prefer python2 over python3? I would have guessed the other way around would make more sense.

**Comment by hestolz** [comment]
@Klaas- a few reasons factored in. The main one would be minimizing risk of disruption. Pre 1.13.27 all installs were using python2 for OMS and DSC subcomponent. To release and shift everyone to use python3 is higher risk than just having the change apply to users who only have python3.
