### ISSUE TITLE
Agent not Working on Centos 8 On-Prem

### ISSUE THREAD

**Issue by Mordecaine** [microsoft/OMS-Agent-for-Linux#1256]
Hello,

I installed on an Azure machine and on an on-prem machine the OMS Agent. But on the on-prem machine, the agent does not work properly.

### The Issue:
In the azure portal, the "Update agent readiness" is always on "Not configured"

### The Operating System On-Prem and in Azure:
CentOS Linux release 8.1.1911 (Core) 

### Installation
**I installed the On-Prem and Azure machine with the following installation Steps:**
`./omsagent-1.13.27-0.universal.x64.sh --install -w '*******-****-****-****-************' -s '***************************************************************=='`

### Debugging Steps:
**Check Logfiles at the on-prem machine:**
[root@msd-ic-ma01 tmp]# tail /var/opt/microsoft/omsagent/*******-****-****-****-************/log/omsagent.log -f
2020-10-13 14:39:20 +0200 [info]: OMS agent management service telemetry request success
2020-10-13 14:39:55 +0200 [info]: Sending OMS Heartbeat succeeded at 2020-10-13T12:39:55.416Z
2020-10-13 14:40:55 +0200 [info]: Sending OMS Heartbeat succeeded at 2020-10-13T12:40:55.417Z
2020-10-13 14:41:55 +0200 [info]: Sending OMS Heartbeat succeeded at 2020-10-13T12:41:55.418Z

**Use Troubleshoot program:**
`/opt/microsoft/omsagent/bin/troubleshooter`

**On-Prem:**
Running troubleshooting tool in Python 2.7.17...
```
Welcome to the OMS Agent for Linux Troubleshooter! What is your issue?

================================================================================
1: Agent is unhealthy or heartbeat data missing.
2: Agent doesn't start, can't connect to Log Analytic Services.
3: Syslog issue.
4: Agent consuming high CPU/memory.
5: Installation failures.
6: Custom logs issue.
================================================================================
A: Run through all scenarios.
L: Collect the logs for OMS Agent.
Q: Press 'Q' to quit.
================================================================================
 Please select an option: **A**
--------------------------------------------------------------------------------
The troubleshooter can be run in two different modes.
  - Silent Mode runs through with no input required
  - Interactive Mode includes extra checks that require input
 Do you want to run the troubleshooter in silent (s) or interactive (i) mode?: **s**
Running troubleshooter in silent mode...
================================================================================
CHECKING INSTALLATION...
Checking if running a supported OS version...
ERROR(S) FOUND.
================================================================================
================================================================================
ALL ERRORS/WARNINGS ENCOUNTERED:
  **ERROR FOUND: This version of CentOS Linux (8.2.2004) is not supported. Please download 6 or 7. To see all supported** Operating Systems, please go to:

   https://docs.microsoft.com/en-us/azure/azure-monitor/platform/log-analytics-agent#supported-linux-operating-systems

--------------------------------------------------------------------------------
Please review the errors found above.
================================================================================
If you still have an issue, please run the troubleshooter again and collect the
logs for OMS.
In addition, please include the following information:
  - Azure Subscription ID where the Log Analytics Workspace is located
  - Workspace ID the agent has been onboarded to
  - Workspace Name
  - Region Workspace is located
  - Pricing Tier assigned to the Workspace
  - Linux Distribution on the VM
  - Log Analytics Agent Version
```

**Use Health Check:**
`python2 /opt/microsoft/omsagent/tst/modules/log_collector/update_mgmt_health_check.py`

**On-Prem:**
```
Debug: Machine Information:   Static hostname: n/a
Transient hostname: *********
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 55b88f3335db4657a7ad9984fc88df9a
           Boot ID: 2bedc73cf0bc4eb1928d8751faec5881
    Virtualization: vmware
  Operating System: CentOS Linux 8 (Core)
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 4.18.0-193.14.2.el8_2.x86_64
      Architecture: x86-64


**Failed: Operating System version (Linux-4.18.0-193.14.2.el8_2.x86_64-x86_64-with-centos-8.2.2004-Core) is not supported. Supported versions listed here: https://docs.microsoft.com/en-us/azure/automation/automation-update-management#clients**

Passed: Microsoft Monitoring agent is installed

Debug: omsadmin.conf file contents:
	WORKSPACE_ID=*******-****-****-****-************
	AGENT_GUID=*******-****-****-****-************
	LOG_FACILITY=local0
	CERTIFICATE_UPDATE_ENDPOINT=https://*******-****-****-****-************.oms.opinsights.azure.com/ConfigurationService.Svc/RenewCertificate
	URL_TLD=opinsights.azure.com
	DSC_ENDPOINT=https://*******-****-****-****-************.agentsvc.azure-automation.net/Accounts/*******-****-****-****-************/Nodes\(AgentId='*******-****-****-****-************'\)
	OMS_ENDPOINT=https://*******-****-****-****-************.ods.opinsights.azure.com/OperationalData.svc/PostJsonDataItems
	AZURE_RESOURCE_ID=
	OMSCLOUD_ID=
	UUID=*******-****-****-****-************
	

Passed: Microsoft Monitoring agent is running
Passed: Machine registered with log analytics workspace:['*******-****-****-****-************']
Passed: Hybrid worker package is present
**Failed: Hybrid worker is not running. current_mof file:(/etc/opt/omi/conf/omsconfig/configuration/Current.mof) is missing**
Passed: Machine is connected to internet
Passed: TCP test for {*******-****-****-****-************.agentsvc.azure-automation.net} (port 443) succeeded
**Failed: Unable to get the operations (JRDS) endpoint**
Passed: TCP test for {*******-****-****-****-************.ods.opinsights.azure.com} (port 443) succeeded
Passed: TCP test for {*******-****-****-****-************.oms.opinsights.azure.com} (port 443) succeeded
Passed: TCP test for {ods.systemcenteradvisor.com} (port 443) succeeded
```

**On Azure (There the OMS Agent works):**
```
Debug: Machine Information:   Static hostname: *********
         Icon name: computer-vm
           Chassis: vm
        Machine ID: f7850a0feae14c5c86caa77502320d1d
           Boot ID: 64fea386aad44b39990fc37ab3b39d01
    Virtualization: microsoft
  Operating System: CentOS Linux 8 (Core)
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 4.18.0-147.5.1.el8_1.x86_64
      Architecture: x86-64


**Failed: Operating System version (Linux-4.18.0-147.5.1.el8_1.x86_64-x86_64-with-centos-8.1.1911-Core) is not supported. Supported versions listed here: https://docs.microsoft.com/en-us/azure/automation/automation-update-management#clients**

Passed: Microsoft Monitoring agent is installed

Debug: omsadmin.conf file contents:
	WORKSPACE_ID=*******-****-****-****-************
	AGENT_GUID=*******-****-****-****-************
	LOG_FACILITY=local0
	CERTIFICATE_UPDATE_ENDPOINT=https://*******-****-****-****-************.oms.opinsights.azure.com/ConfigurationService.Svc/RenewCertificate
	URL_TLD=opinsights.azure.com
	DSC_ENDPOINT=https://*******-****-****-****-************.agentsvc.azure-automation.net/Accounts/*******-****-****-****-************/Nodes\(AgentId='*******-****-****-****-************'\)
	OMS_ENDPOINT=https://*******-****-****-****-************.ods.opinsights.azure.com/OperationalData.svc/PostJsonDataItems
	AZURE_RESOURCE_ID=/subscriptions/*******-****-****-****-************/resourcegroups/rg-msd-ansibletower-eus/providers/microsoft.compute/virtualmachines/*********
	OMSCLOUD_ID=*******-****-****-****-************
	UUID=*******-****-****-****-************
	

Passed: Microsoft Monitoring agent is running
Passed: Machine registered with log analytics workspace:['*******-****-****-****-************']
Passed: Hybrid worker package is present
**Failed: Hybrid worker is not running. current_mof file:(/etc/opt/omi/conf/omsconfig/configuration/Current.mof) is missing**
Passed: Machine is connected to internet
Passed: TCP test for {d5a3b8b5-4da8-4430-ba84-61421d594d33.agentsvc.azure-automation.net} (port 443) succeeded
Passed: TCP test for {we-jobruntimedata-prod-su1.azure-automation.net} (port 443) succeeded
Passed: TCP test for {d5a3b8b5-4da8-4430-ba84-61421d594d33.ods.opinsights.azure.com} (port 443) succeeded
Passed: TCP test for {d5a3b8b5-4da8-4430-ba84-61421d594d33.oms.opinsights.azure.com} (port 443) succeeded
Passed: TCP test for {ods.systemcenteradvisor.com} (port 443) succeeded

```

I have no idea, why the messages occur, that there is no support for centos 8 with OMS version 1.13.27-0.
Further more I have no idea, why the status in azure is "Not configured".
Is there support for centos 8 on-prem with version OMS 1.13.27-0?

**Comment by nwerker** [comment]
I can reproduce this issue and can't figure out how to fix this!

**Comment by jtuk** [comment]
CentOS 8 isn't in the supported OS list, but it can be made to work (at least in my scenario for use with a different Azure monitoring product).  That's using an additional syslog ingestion part that trips over SELinux a little if that's enabled.

There's a difference you might not have noticed between your onprem and azure:

On prem: Debug: Machine Information:   Static hostname: **n/a**
Azure: Static hostname: *****

So perhaps the lack of a local hostname is confusing the monitoring environment?  For some uses of the OMS connector this doesn't actually matter, it's just ingesting logs from wherever, but for the update agent stuff it might need a hostname to register it.

The troubleshooting script is using the output from: hostname -f

JT

**Comment by jfran3** [comment]
@jtuk do you have any pointers for fixing the SELinux ingestion issue? I seem to be seeing a similar agent issue on CentOS 7 with SELinux enabled.

**Comment by jtuk** [comment]
@jfran3 Hi - Not sure if you ever resolved this, but out the box it doesn't (or at least didn't) work with SELinux.  I did get it working, had to build a SELinux rule/module.  Unfortunately I've long since nuked the VM in question.  If I recall it needed a nudge to get it in the same context as the syslog agent.  The whole module IMO is well avoided until they release it in forms that can be packaged and updated properly by the OS maintainers.

**Comment by jfran3** [comment]
Thanks @jtuk I got a cobbled together version of it going with a similar approach, but I've since left the project so I'm not sure if it's still working or not. I agree though, best avoided unless absolutely necessary! Cheers!

**Comment by jtuk** [comment]
Dug out the chat I had with a colleague, this was end of the path we went down:

enabled audit.
I think those ports might be BIND (Server) rather than CONNECT (Client) and in this instance the syslog is the client..  
​    grep 25226 /var/log/audit/audit.log | grep denied | tail -n 1  | audit2allow
​    https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-fixing_problems-allowing_access_audit2allow
​    /root/sepolicies
​    grep 25226 /var/log/audit/audit.log | grep denied | tail -n 1  | audit2allow a -M syslog_to_ms
​    semodule -i syslog_to_ms.pp
​    which has introduced the rule to allow: allow syslogd_t unreserved_port_t:tcp_socket name_connect;
​    think that's got it

Although hazy now, I think it was something to do with Syslog using the DNS resolver.

**Comment by jfran3** [comment]
Nice! Thanks for posting that. I know we aren't alone in this being an issue!

**Comment by Sarta92** [comment]
Hi guy,

Did you find a solution to this problem?
I tested the agent on Centos 8 and Red Hat Enterprise Linux Server 8 and I have the same issue.

Thanks

**Comment by jfran3** [comment]
It's been quite a while since  I worked with this, but going back through my notes it looks like I had to basically go through and modify the SELINUX issues by hand using audit.log and ausearch. I do have a note that OMS 1.13.27 was supposed to work with CentOS 8.x but I'm guessing it didn't fix the issue?
