### ISSUE TITLE
No nagios alerts show up on the OMS portal

### ISSUE THREAD

**Issue by KennyMacCormik** [Microsoft/OMS-Agent-for-Linux#126]
Hi all.

Failing to collect Nagios alerts with OMS agent.

I've configured omsagent.conf
```
<source>
  type tail
  path /opt/omd/sites/DomainLocal/var/nagios/nagios.log
  format none
  tag oms.nagios
</source>

<filter oms.nagios>
  type filter_nagios_log
</filter>
```
After restarting oms agent service I can see the following warning in /var/opt/microsoft/omsagent/log/omsagent.log

```
2016-07-06 08:21:23 -0400 [warn]: temporarily failed to flush the buffer. next_retry=2016-07-06 08:28:36 -0400 error_class="TypeError" error="no implicit conversion of nil into Array" plugin_id="object:3fb0864997e4"
  2016-07-06 08:21:23 -0400 [warn]: suppressed same stacktrace
```

I can see my server connected to OMS and performance data collected.

In Check_MK web portal I can see active alers, but they did not show up in the OMS portal. I've tried to create some new alerts after the OMS agent restart, but this didn't help. They were still only in the Check_MK portal, but not in the OMS portal.

I've tried to execute `su - omsagent` and then execute `cat /opt/omd/sites/DomainLocal/var/nagios/nagios.log` and I successfully recieved output. As you can see below `ls -la` shows that everyone has read permission

```
[root@Site1CheckMK nagios]# ls -la
total 152
drwxr-xr-x  3 DomainLocal DomainLocal   121 Jul  6 08:30 .
drwxr-xr-x 11 DomainLocal DomainLocal   143 Jul  6 07:13 ..
drwxr-xr-x  2 DomainLocal DomainLocal     6 Jul  6 07:13 archive
-rw-r--r--  1 DomainLocal DomainLocal  1477 Jul  6 08:30 livestatus.log
-rw-r--r--  1 DomainLocal DomainLocal 36198 Jul  6 08:30 nagios.log
-rw-r--r--  1 DomainLocal DomainLocal 34747 Jul  6 08:30 objects.cache
-rw-r--r--  1 DomainLocal DomainLocal 34747 Jul  6 08:30 objects.precache
-rw-r--r--  1 DomainLocal DomainLocal 40472 Jul  6 08:30 retention.dat
```

The only help I get from the troubleshooting guide is this

```
Probable Causes

omsagent user does not have permissions to read from Nagios log file
Nagios source and filter have not been uncommented from omsagent.conf file
```

Any help will be highly appreciated.

**Comment by agup006** [comment]
Hey @KennyMacCormik , in the omsagent.conf file would you be able to have the agent output to stdout and send the log?

This can be done by editing `/etc/opt/microsoft/omsagent/conf/omsagent.conf` and commenting out the following sections

```
#<match oms.blob.**>
# type out_oms_blob
#  log_level info
#  num_threads 5
#  buffer_chunk_limit 10m
#  buffer_type file
#  buffer_path /var/opt/microsoft/omsagent/state/out_oms_blob*.buffer
#  buffer_queue_limit 10
#  buffer_queue_full_action drop_oldest_chunk
#  flush_interval 20s
#  retry_limit 10
#  retry_wait 30s
#  max_retry_wait 9m
#</match>

#<match oms.** docker.**>
#  type out_oms
#  log_level info
#  num_threads 5

#  buffer_chunk_limit 5m
#  buffer_type file
#  buffer_path /var/opt/microsoft/omsagent/state/out_oms_common*.buffer
#  buffer_queue_limit 10
#  buffer_queue_full_action drop_oldest_chunk
#  flush_interval 20s
#  retry_limit 10
#  retry_wait 30s
#  max_retry_wait 9m
#</match>

# Catch all Nagios data and output it to stdout
<match oms.nagios>
  type stdout
</match>

```

**Comment by agup006** [comment]
Hi @KennyMacCormik, haven't heard back in a while - I am going to close this issue. Feel free to re-open if new information is available
