### ISSUE TITLE
OMSConsistencyInvoker misses first 15 minutes of logs

### ISSUE THREAD

**Issue by bleemus** [microsoft/OMS-Agent-for-Linux#1262]
The [cron job](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/omsadmin.sh#L670) for OMSConsistencyInvoker is created for the to fire at 15 minutes, which leads to missing logs for the first 15 minutes of the VM/VMSS life time.

Workaround: Manually run /opt/omi/bin/OMSConsistencyInvoker in setup script.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
