### ISSUE TITLE
1.13.27 Agent not working under Debian 10.6

### ISSUE THREAD

**Issue by Gill-Bates** [microsoft/OMS-Agent-for-Linux#1264]
**Unsupported operating system: debian 10.6**

`
[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.27/omsagent_shim.sh -install [stdout] 2020/11/12 16:08:40 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.27] Install,failed,51,Unsupported operating system: debian 10.6 [stderr] Python 2.7.16 nux-1.13.27/keys/keyring.gpg' created gpg: directory '/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.27/keys/.gnupg' created gpg: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.27/keys/.gnupg/trustdb.gpg: trustdb created gpg: key 20541A3DDE321294: public key "Microsoft (Release Signing) <dscgpgkey@microsoft.com>" imported gpg: can't connect to the agent: IPC connect call failed gpg: Total number processed: 1 gpg: imported: 1`

**Comment by hestolz** [comment]
This is expected and by design, Debian 10 is not supported at this time due to OMI subcomponent not being supported for this distro.
