### ISSUE TITLE
omsconfig.log gives Unauthorized HTTP error (401)

### ISSUE THREAD

**Issue by KostLinux** [microsoft/OMS-Agent-for-Linux#1272]
Hey!
OMSConfig.log file gives:
```
DSC Engine Error : 
	 Error Message Failed to register with a pull server at url: https://8b9da0f5-03be-419c-b81b-d8c727d5f905.agentsvc.azure-automation.net/Accounts/8b9da0f5-03be-419c-b81b-d8c727d5f905/Nodes(AgentId='4a346199-e351-465c-a800-2a019245d1b8')/SendReport. It responded with error code: 401 for a module. 
	Error Code : 1 
2020/11/23 12:24:01: ERROR: null(0): EventId=1 Priority=ERROR Job E2190CD0-1A24-4854-8489-7EA9218075ED : 
DSC Engine Error : 
	 Error Message Failed to report to all reporting servers.  Last server failed with HTTP response code: 401. 
	Error Code : 1 

```
I thought, the problem was in key and workspaceID, but they were right.
Every time i refresh azure portal, omsconfig give same error.
Can u help me?

**Comment by KostLinux** [comment]
ok i needed to reinstall agent
next problem is
 ```

2020-11-30 11:27:54 +0200 [error]: Unable to read file /etc/opt/microsoft/omsagent/workspace-id/conf/omsagent.d/omi_mapping.json
```

**Comment by lalbers** [comment]
I can confirm this problem. I installed the agent with following command. 
```
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
sh onboard_agent.sh -w ${workspace_id} -s ${workspace_key} -p ${http_proxy_url} -d opinsights.azure.com
```
The `omsagent` seems to be healthy and sending its heartbeat. Anyway omsconfig doesn't work, no matter how many times i tried to reinstall. 

_/var/opt/microsoft/omsconfig/omsconfig.log_
```
DSC Engine Error : 
	 Error Message Failed to register with a pull server at url: https://xxx.agentsvc.azure-automation.net/Accounts/xxx/Nodes(AgentId='xxx)/SendReport. It responded with error code: 401 for a module. 
	Error Code : 1 
2021/02/10 11:05:02: ERROR: null(0): EventId=1 Priority=ERROR Job 91B1CD32-35BF-4898-9CEF-0D07945B1106 : 
DSC Engine Error : 
	 Error Message Failed to report to all reporting servers.  Last server failed with HTTP response code: 401. 
```

The corresponding linux vm has no public ip and it's only way out in the internet is through a http/https proxy. Unfortunately the logs do not help much with error handling. I'm not even sure if the proxy is to blame.

OS: Ubuntu 18.04.5 LTS

**Comment by lalbers** [comment]
Update with public ip and direct internet conneciton, it works fine:
```
successfully read /etc/rsyslog.d/95-omsagent.conf.
2021/02/11 09:54:02: INFO: Scripts/nxOMSSyslog.pyc(481):
Succesfully read /etc/opt/microsoft/omsagent/xxxx/conf/omsagent.d/syslog.conf for syslog "port" field.
2021/02/11 09:54:02: INFO: Scripts/nxOMSSyslog.pyc(481):
Succesfully read /etc/opt/microsoft/omsagent/xxx/conf/omsagent.d/syslog.conf for syslog "protocol_type" field.
```

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
