### ISSUE TITLE
Debian 10 support

### ISSUE THREAD

**Issue by valireality** [microsoft/OMS-Agent-for-Linux#1289]
Hi,
Debian 11 is work in progress, but OMS is still not supported for Debian 10.
What's the plan on this field?

Thank you.

**Comment by johanburati** [comment]
Just for your info there is already an issue about this: [Support for Debian 10 Buster #1079](https://github.com/microsoft/OMS-Agent-for-Linux/issues/1079)

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
