### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Poil** [microsoft/OMS-Agent-for-Linux#1304]
Hi,

So omsagent can run some script via sudo by example `/opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh`

But omsagent is owner of the script and can edit it `-rwxr-xr-x 1 omsagent root 287 Nov  9 23:23 /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh`

So why don't give sudo all, will be easier ...

Best regards,

**Comment by pentiumoverdrive** [comment]
Did you bother checking whats inside the script at all?

How would it run "service rsyslog restart" without sudo or even copying the files?

**Comment by Poil** [comment]
We never never never allow an user to run a script where he has write right on it. Why these scripts are owned by omsagent, here is the mistake.

**Comment by lalbers** [comment]
I would agree with @Poil. 
These sudoer rules are configured in _/etc/sudoers.d/omsagent_ during installation. With write access to whitelisted file it's possible for the `omsagent` to run any commands as root. Definitely not a good practice! 
A possible solution has already been suggested by Poli. +1

**Comment by achevalet** [comment]
Any update here? It looks like a critical vuln ...

**Comment by Poil** [comment]
Answer from the Azure Support ... :-1: 

```
Further investigating your concern, I found that so far this is not supported. 
 
Support for hardening/security features i.r.t sudoers, etc might be review in future semesters.
 
I will also advise to post your concern in this link, I believe is a great feedback as well.
https://feedback.azure.com/forums/267889-azure-monitor-log-analytics/filters/new?category_id=88096
``

I create this https://feedback.azure.com/forums/267889-azure-monitor-log-analytics/suggestions/43208223-oms-agent-take-into-account-security-issue

**Comment by Poil** [comment]
@hestolz bump

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
