### ISSUE TITLE
OMS Agent should have a 'statis' command like we have in Windows, to see how the agent is doing

### ISSUE THREAD

**Issue by 1RedOne** [microsoft/OMS-Agent-for-Linux#1309]
On a Windows machine, I can go to the control panel, and choose 'MMA Agent' and see all sorts of information about the OMS Agent, like when it last communicated, the errors, etc.

Is there this capacity for the Linux OMS Agent?  If so, it would be cool if it were listed at the end of the install script, and in the documentation.

Thanks!

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
