### ISSUE TITLE
v1.13.35-0 Not calling correct python

### ISSUE THREAD

**Issue by Fairchild110** [microsoft/OMS-Agent-for-Linux#1318]
Hello all! 

When I attempted to install script, I would run into failure to find ctypes module. 

In your What's New:
Simplified Python experience
Support for machines with Python 2, Python 3, or both
No requirement for aliasing of Python 2 or 3 to the python command

Yet, I was only able to work around this issue on Ubuntu by installing python 2 and alising the command. 

`Configure log rotate for workspace 2c0ec877-cd74-46d2-9974-f7b3d6b6dde4...
Processing triggers for systemd (246.6-1ubuntu1) ...
Applying Syslog conf hotfix...
----- Upgrading package: omsconfig (omsconfig-1.1.1-930.x64) -----
Selecting previously unselected package omsconfig.
(Reading database ... 135751 files and directories currently installed.)
Preparing to unpack .../omsconfig-1.1.1-930.x64.deb ...
Using python2
Checking for ctypes python module...
Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of python that comes with the ctypes module.
Please remove the omi package and try again after installing the ctypes module or upgrading Python.  You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'
dpkg: error processing archive 110/omsconfig-1.1.1-930.x64.deb (--install):
 new omsconfig package pre-installation script subprocess returned error exit status 1
Pausing briefly for systemctl synchronization ...
Errors were encountered while processing:
 110/omsconfig-1.1.1-930.x64.deb
omsconfig-1.1.1-930.x64 package failed to upgrade and exited with status 1
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:`

Then I ran 

`sudo update-alternatives --install /usr/bin/python /usr/bin/python2 1`

Then the wget command from my log analytics workspace worked fine. 

wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w

**Comment by Fairchild110** [comment]
I can't get the wget command to work to install in RHEL 8 either because RHEL doesn't allow the aliasing of python anymore.

**Comment by martingem** [comment]
I have the same issue as @Fairchild110 .

I'm still in a support ticket with Microsoft and they told me to run
`sudo apt-get install -y python-ctypes`

For me it's Ubuntu 20.04.

**But it should be part of the installation to install said dependencies.** 
Why?
If it's a requirement of the installation of the software, dependencies should be installed with said software.

FYI we use https://github.com/actions/virtual-environments as base (which is the same that Microsoft uses for Azure DevOps Agents). I do not believe making a ticket in that repo makes any sense when it's this repo that handles the installation of the extension.

**Comment by skalenji** [comment]
Having the same issue with vmss using Ubuntu 20.04 image. When I try to enable insights for the vmss it adds an extension for installing the oms agen `OmsAgentForLinux` which fails. When I dig into the logs I see that it uses python2 and exits with the same error: 
```
Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of python that comes with the ctypes module.
```

**Comment by bartwitkowski** [comment]
Hi, @Fairchild110 what Ubuntu version do you use?
In my last experience the OMSExtension version 1.13.35 works perfectly on Ubuntu 18.04 but not on 20.04. I'm using [GitHub Actions Virtual Environments](https://github.com/actions/virtual-environments/) images.

**Comment by egg-r** [comment]
I am also having the same issue while using Ubuntu 20.04 Azure DevOps VMSS images mentioned previously.  I ran into the issue while trying to setup VMInsights on the VMSS to review VM memory pressure.  I ran into this issue yesterday, 4/23/2021, using extension version 1.13.35.

**Comment by tdgray** [comment]
Having the same issue on Ubuntu 20.04 DevOps VMSS images. Their mercurial installer installs python 2.7 which doesn't include ctypes, and since python2 is prioritized over python3 by the OMS installer the extension installation fails unless you manually install ctypes. If you install using python3 it works just fine. In my mind the installer should not be preferring a python version that has been end of life for over a year and should prioritize python3 if it exists.
