### ISSUE TITLE
OMSAgent RPM Verify fails due to ownership being changed after installation

### ISSUE THREAD

**Issue by siffland** [microsoft/OMS-Agent-for-Linux#1344]
After installing the omsagent RPM on RHEL, 7 or 8,  there is a post script that changes the ownership to 

omsagent:root

The issue lies in the rpm verify, the manifest for the RPM has the files being owned by root:root so when DoD STIGs (This is actually a category 1 finding) are run against the server, with the following command: 

`for i in $(rpm -Va | egrep -i '^\.[M|U|G|.]{8}' | cut -d " " -f 4,5);do for j in $(rpm -qf $i);do rpm -ql $j --dump | cut -d " " -f 1,5,6,7 | grep $i;done;done`

Over 170 files installed by the rpm fail the verify.  There should be no output form the command and on a fresh installation of RHEL there is not until the omsagent is installed.  The big issue with this is it becomes difficult for the sysadmin to tell if the RPM installed has been tampered with (such as a supply chain hack).  

The proper fix should be to install the files with the proper ownership on the system and not have a hackish post script alter the ownership after installation.  This will fix the issue and allow admins to better verify the integrity and security of their systems.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
