### ISSUE TITLE
 Error response from daemon: pull access denied for microsoft/oms

### ISSUE THREAD

**Issue by Grodriggues** [microsoft/OMS-Agent-for-Linux#1356]
When I try to run the following command: 
`wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <YOUR WORKSPACE ID> -s <YOUR WORKSPACE PRIMARY KEY> -d opinsights.azure.us
`

I get the following output:
`Error response from daemon: pull access denied for microsoft/oms, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

 Why is that?

**Comment by nick4fake** [comment]
mcr.microsoft.com/azuremonitor/containerinsights/ciprod:microsoft-oms-latest

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
