### ISSUE TITLE
OMIGOD Critical Vuln in OMI- Onboard Agent script and Latest release bundle scripts need to be updated

### ISSUE THREAD

**Issue by Cyb3rWard0g** [microsoft/OMS-Agent-for-Linux#1360]
OMI latest release is `version 1.6.8-1` (Security Fix - https://www.wiz.io/blog/omigod-critical-vulnerabilities-in-omi-azure)

https://github.com/microsoft/omi/releases/tag/v1.6.8-1

OMS Agent for Linux latest release (OMSAgent_v1.13.39-0) bundle script (omsagent-1.13.39-0.universal.x64.sh ) points to  `OMI version 1.6.8.0`

https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.13.39-0

![image](https://user-images.githubusercontent.com/9653181/133464470-1bc36b5b-08eb-4048-b487-b5f932d3bf24.png)

Also, the OMS Agent for Linux Latest `onboard` installer script in the main repo points to an even older version of OMS Agent for Linux `OMSAgent_v1.13.35-0`

![image](https://user-images.githubusercontent.com/9653181/133464951-e3fd04db-26ca-424c-8b7f-c699e51b0fba.png)

https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/onboard_agent.sh#L9

That bundle installer script points to an event older version of OMI `v1.6.4-0`

![image](https://user-images.githubusercontent.com/9653181/133465933-dd8857dc-e057-47f4-aa03-49c2496b52e4.png)

https://github.com/microsoft/omi/releases/tag/v1.6.4-0

The reason why I mention the OMS Agent for Linux onboard script is because that's what is mentioned in the Microsoft docs to use as a wrapper script:

`wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <YOUR WORKSPACE ID> -s <YOUR WORKSPACE PRIMARY KEY>`

https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agent-linux#install-the-agent-using-wrapper-script

**Comment by Cyb3rWard0g** [comment]
There is a PR to at least bump the OMS Agent for Linux onboard script and README to version 1.13.39.0

https://github.com/microsoft/OMS-Agent-for-Linux/pull/1358

**Comment by hestolz** [comment]
The team is aware of the vulnerability in the OMI dependency, we are currently generating a release using the fixed OMI version and will publish the release once verified.

**Comment by Cyb3rWard0g** [comment]
Thank you @hestolz ! 🙏🏾

**Comment by Cyb3rWard0g** [comment]
https://github.com/microsoft/OMS-Agent-for-Linux/pull/1361

**Comment by errcode1202** [comment]
Hi,

As part of our deployment process we use the [OMS Agent for Linux onboard script
](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agent-linux#install-the-agent-using-wrapper-script)

Yesterday, prior to #1358 being merged I noted that the script was installing `1.6.4.0` of the OMI. With #1358 now in place Ive retested the script i.e:

`wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w "${OMS_WORKSPACE_ID}" -s "${OMS_PRIMARY_KEY}" -d opinsights.azure.com
`

however I now see that version `1.6.8.0` of the OMI is installed as part of this

![image](https://user-images.githubusercontent.com/409063/133526373-dcdcce17-ca0f-4af8-9be4-c76638842603.png)

Correct me if Im wrong, but shouldnt `1.6.8.1` be installed now as a result of #1361

**Comment by Cyb3rWard0g** [comment]
Hello @errcode1202 , as I mentioned before in my initial message, earlier the bundle script which is downloaded by the onboard script was still pointing to `1.6.4.0`. 

![image](https://user-images.githubusercontent.com/9653181/133538780-3cb47e8b-62dc-407d-99c8-e7d76c71acc8.png)

This PR https://github.com/microsoft/OMS-Agent-for-Linux/pull/1358 changed the path of the bundle script to `omsagent-1.13.39-0.universal.x64.sh`. However, that bundle script is now pointing to the `1.6.8.0` OMI version. 

This PR https://github.com/microsoft/OMS-Agent-for-Linux/pull/1362 should fix it :)

**Comment by errcode1202** [comment]
Hi @Cyb3rWard0g thanks for the update. #1362 looks like what I'm after 👍🏽. Once merged I'll re-test.

**Comment by hestolz** [comment]
Hello, the release 1.13.40 incorporating OMI 1.6.8-1 is [released](https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.13.40-0).

**Comment by Klaas-** [comment]
References https://github.com/Azure/azure-linux-extensions/issues/1419 , is that now also fixed with the new version?

**Comment by errcode1202** [comment]
Nice OMS agent now installing OMI `1.6.8.1` 

![image](https://user-images.githubusercontent.com/409063/133575189-f78afe10-c411-4113-94a8-ba50bd496e86.png)

**Comment by Poil** [comment]
The VM Extension still install 1.13.39 !

**Comment by Cyb3rWard0g** [comment]
Helo @Poil , that should be in this other other repo. https://github.com/Azure/azure-linux-extensions/issues/1425. I will close this one since from an OMS Agent for Linux release script, it is fixed. Now, the extension feature needs to be updated.
