### ISSUE TITLE
Support for AlmaLinux

### ISSUE THREAD

**Issue by johanburati** [microsoft/OMS-Agent-for-Linux#1363]
I've seen some big annoncement that [AlmaLinux was now available on Azure Marketplace](https://twitter.com/AlmaLinux/status/1427649332946288653).
However it looks like this distro is still not supported by the **OmsAgentForLinux** extension:
```
2021/09/16 00:55:54 ERROR:Unsupported operating system: AlmaLinux 8.4
2021/09/16 00:55:54 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.39] Unsupported operating system: AlmaLinux 8.4
2021/09/16 00:56:01 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.13.39] Install,failed,51,Unsupported operating system: AlmaLinux 8.4
```
**AlmaLinux** is supposed to be a drop in remplacement for **CentOS**, so it would be nice if you could add it to the supported distro list.

**Comment by NicolasKarnick** [comment]
@johanburati where are the logs from? Cant find it on our machine. 
If Azure supports AlmaLinux, there has to be a support für OMS-Agent-for-Linux.

**Comment by dse002** [comment]
Same here, log is from /var/log/waagent.log

**Comment by johanburati** [comment]
> @johanburati where are the logs from? Cant find it on our machine. If Azure supports AlmaLinux, there has to be a support für OMS-Agent-for-Linux, too.

`/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log`

**Comment by dse002** [comment]
@NicolasKarnick @johanburati Any news on this?

**Comment by tiagoabelha** [comment]
Yes, any news on this would be appreciated

**Comment by athiede-vendavo** [comment]
Opened this: https://github.com/microsoft/OMS-Agent-for-Linux/issues/1363
I believe that'll make it installable. Tried to hack my way around it on an Alma Linux system and it was able to install with these changes. Still didn't report metrics.

**Comment by NarineM** [comment]
Alma 8 support enabled in omsagent version 1.14.16.
