### ISSUE TITLE
container solution pack - preview - OMSContainers@microsoft.com is "Internal Only"

### ISSUE THREAD

**Issue by jgreat** [Microsoft/OMS-Agent-for-Linux#138]
Following documentation from here:
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Docker-Instructions.md

I'd like to sign up for the container solution pack preview.  When I try and email OMSContainers@microsoft.com it bounces.

![image](https://cloud.githubusercontent.com/assets/5324639/17119146/d48c1886-5289-11e6-8102-8ae14b174e1c.png)

**Comment by agup006** [comment]
Hi @jgreat , thanks for reporting this issue
