### ISSUE TITLE
omi upgrade script failing in debian OS

### ISSUE THREAD

**Issue by dcvtruong** [microsoft/OMS-Agent-for-Linux#1381]
```
./omi_update.sh 
OpenSSL 1.1.1 11 Sep 2018
isSSL11=0
isSSL10=1
https://github.com/microsoft/omi/releases/download/v1.6.8-1/omi-1.6.8-1.ssl_110.ulinux.x64.deb
-rwxrwxrwx 1 root root 1861004 Sep  8 04:56 /tmp/omi-1.6.8-1.ssl_110.ulinux.x64.deb
sudo
dpkg: error: archive '/tmp/' is not a regular file
dpkg: error: cannot access archive '/tmp/omi-1.6.8-1.ssl_110.ulinux.x64.deb/opt/omi/bin/omiserver': Not a directory
```

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
