### ISSUE TITLE
OMIcheck.ps1 fails with Databricks provisioned

### ISSUE THREAD

**Issue by rscottwatson** [microsoft/OMS-Agent-for-Linux#1383]
FYI.  When you have a databaricks provisioned the OMIcheck.ps1 script fails. 

The client 'x' with object id 'xx' has permission to perform action 'Microsoft.Compute/virtualMachines/runCommand/action' on scope
     | '/subscriptions/xx/resourceGroups/DATABRICKS-RG/providers/Microsoft.Compute/virtualMachines/xx';
     | however, the access is denied because of the deny assignment with name 'System deny assignment created by Azure Databricks
     | /

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
