### ISSUE TITLE
[BUG] logrotate error

### ISSUE THREAD

**Issue by johanburati** [microsoft/OMS-Agent-for-Linux#1386]
I have deployed a new RHEL VM connected to an OMS workplace, **logrotate** returns an error because of duplicate entries, in the **logrotate** config associated with **OmsAgentForLinux**  extension and the one associated with **WALinuxAgent**.

## Error
```
reading config file waagent-extn.logrotate
error: waagent-extn.logrotate:1 duplicate log entry for /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log
error: found error in file waagent-extn.logrotate, skipping
```
## Distro  
```
Red Hat Enterprise Linux release 8.4 (Ootpa)
```
## WALinuxAgent Version
```
WALinuxAgent-2.2.49.2 running on redhat 8.4
Python: 3.6.8
Goal state agent: 2.5.0.1
```

## OmsAgentForLinux Version
```
Version: 1.13.40
```

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
