### ISSUE TITLE
Unable to start omsagent service

### ISSUE THREAD

**Issue by ghost** [microsoft/OMS-Agent-for-Linux#1394]
am I the only person in the world who keeps getting this error after an update in Ubuntu, where some component of the omsagent (scx in this case) gets updated and the service has to restart?
fluent/supervisor.rb:373:rescue in main_process: config error file="/etc/opt/microsoft/omsagent/conf/omsagent.conf" error="Unknown filter plugin 'filter_auditd_dsc_log'. Run 'gem search -rd fluent-plugin' to find plugins"

**Comment by RafaelRuales** [comment]
@davidkiser I have found that to get around the issue, I either have to comment out the section that references DSC in the file, or rename the file entirely and restart the service, and it will work.
