### ISSUE TITLE
OMS Possibly Reverts OMI package back from 1.6.8.1 to 1.6.4 on Azure VM

### ISSUE THREAD

**Issue by amrsharaf** [microsoft/OMS-Agent-for-Linux#1396]
I've updated the OMI (Open Management Infrastructure) package on my azure VM from 1.6.4 to 1.6.8.1 to mitigate the reported security vulnerability with:

`sudo apt-get install omi`

However, few days after the install I notice that the OMI version gets reverted back to 1.6.4, I'm not sure why that happens and how to debug this issue, any idea what could be going on? 

I've been directed by the [OMI team](https://github.com/microsoft/omi/issues/711) to open a ticket here since this could be related to OMS.

Thanks!

**Comment by amrsharaf** [comment]
Any updates on this issue? Thanks for looking into this.

**Comment by ookhoi** [comment]
Same here:
```
Packages Altered:
    Updated    omi-1.6.4-0.x86_64 installed
    Obsoleted  omi-1.6.4-0.x86_64 installed
    Obsoleting omi-1.6.8-1.x86_64 @packages-microsoft-com-prod
```

**Comment by Klaas-** [comment]
This was addressed in https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.14.9-0 which also seems to include a lot of other security related issues

**Comment by NarineM** [comment]
Should not longer be an issue since newer versions of oms agent come with latest omi (containing security fixes)
