### ISSUE TITLE
Buffer Path for Omsagent

### ISSUE THREAD

**Issue by hemang-shah** [microsoft/OMS-Agent-for-Linux#1399]
Hi, 
I wasn't able to find this information anywhere, so wanted to post here.  What is the official stance on buffer setting for the agent?
In case where this is being used as a syslog collector, and when Internet is down, from what I understand, the current configuration will only cache data for 30 minutes.  
1) Can the path where the buffer or cache files are located can be changed?
2) Can the buffer size of data being cached be changed? If so, where do we change it.  

I understand that the omsagent.conf can be edited.  Is this supported?

I'm assuming, if we do change it, we have to disable auto update from Azure Portal? Or will this be overwritten?

Thanks

**Comment by duckie37** [comment]
I am looking for the answer to this as well.
