### ISSUE TITLE
Attempt in QueryAll to get element 46 of event list returned null

### ISSUE THREAD

**Issue by pdiniz13** [Microsoft/OMS-Agent-for-Linux#140]
All docker logs are coming in with this error under the log search.The installation worked fine, and I am able to see the service running, and docker is able to connect to it. But there seems to be something wrong with getting the logs over to azure. All other logs are working fine, this seems to be the only issue.

**Comment by agup006** [comment]
Hi pdiniz13, are you still seeing this error in Log Search? Are you able to send me a quick screenshot? My email is anugup @ microsoft dot com
