### ISSUE TITLE
`apt-update` in OMSAptUpdates.sh conflicts with cloud-init on Ubuntu 20.04

### ISSUE THREAD

**Issue by KiruyaMomochi** [microsoft/OMS-Agent-for-Linux#1405]
When we try to start a VM with image `microsoft-dsvm:ubuntu-hpc:2004:latest` on [Azure CycleCloud](https://docs.microsoft.com/en-us/azure/cyclecloud/), it fails randomly with error message
```log
('apt-configure', ProcessExecutionError("Unexpected error while running command.
Command: ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold',  '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'update']
Exit code: 100
Reason: -
Stdout: -
Stderr: -"))
```

After taken some time to investigate, we found cloud-init does `apt update` as `/opt/microsoft/omsconfig/Scripts/OMSAptUpdates.sh` is running, so cloud-init can't get apt lock and then fails.

The problem may relate to omsagent's systemd unit.

## Minimum Cloud-init file

The problem can be reproduced by provision a VM with this cloud-init config, using image `microsoft-dsvm:ubuntu-hpc:2004:latest`.

```yaml
#cloud-config
apt:
  disable_suites:
    - $RELEASE-proposed
  preserve_sources_list: true
package_update: true
package_upgrade: false
```

### Cloud-Init error log

```log
2021-11-13 21:39:29,953 - util.py[WARNING]: 
Running module apt-configure (<module 'cloudinit.config.cc_apt_configure'
from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) failed
```

### `pstree` of omsagent's apt command

```log
systemd,1
  `-omsagent,2497 /opt/microsoft/omsagent/bin/omsagent -d/var/opt/microsoft/omsagent/d4d54914-66ea-43fc-9170-c8
      `-sh,2720 -c...
          `-sh,2724 -c...
              `-python2,2729 /opt/microsoft/omsconfig/Scripts/PerformInventory.py --InMOF...
                  `-dsc_host,2909 /opt/dsc/output PerformInventoryOOB...
                      `-python2,3160 /opt/microsoft/omsconfig/Scripts/client.py 9
                          `-sh,3242 -c sudo /opt/microsoft/omsconfig/Scripts/OMSAptUpdates.sh
                              `-sudo,3243 /opt/microsoft/omsconfig/Scripts/OMSAptUpdates.sh
                                  `-OMSAptUpdates.s,3244 /opt/microsoft/omsconfig/Scripts/OMSAptUpdates.sh
                                      `-apt-get,3246 -q update
```

**Comment by murez** [comment]
one solution is implying the `apt-get` in `/usr/local/sbin`, by the following script to wait it for the lock.
``` bash
#!/bin/bash

i=0
tput sc
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    tput rc
    echo -en "\r[$j] Waiting for other software managers to finish..." 
    sleep 0.5
    ((i=i+1))
done 

/usr/bin/apt-get "$@"
```
But this is some kind of hack just don't use it.
reference:[code](https://askubuntu.com/questions/132059/how-to-make-a-package-manager-wait-if-another-instance-of-apt-is-running)

**Comment by KiruyaMomochi** [comment]
### Update

For a temporary solution, add following content to `bootcmd` part of `cloud-config`:
```yaml
  - |
    mkdir -p /etc/systemd/system/omsagent-.service.d/
    cat <<EOF > /etc/systemd/system/omsagent-.service.d/fix-cloud-init.conf
    [Unit]
    After=cloud-config.service
    EOF
    systemctl daemon-reload
```

This created a drop-in file to delay `omsagent` after `cloud-config` has finished, and reload systemd daemon.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
