### ISSUE TITLE
SCOM 2019 Agent Installation failed on RHEL7

### ISSUE THREAD

**Issue by yasirvohra** [microsoft/OMS-Agent-for-Linux#1410]
Trying to Installing SCOM 2019 Agent Installation failed on RHEL7 but Its not creating omid.service, However, I have installed same agent on another four RHEL7  server and it was successful. 

**Process Description:**
scx-1.6.8-1.rhel.7.x64.sh  --> RHEL 7 Agent Installation File

So, normally while Installing agent it runs and create omid.service.

In my case for this server Agent is installed with error but service unit "omid.service" not created and giving error while installing "ERROR: omi-logrotate selinux policy module versions could not be installed" . If service unit not created it will discover in SCOM 2019 but will not perform monitoring. 

Service unit "omid.service"created on RHEL 7 server --> nothing to do with SCOM.

See below snapshot.
![Capture](https://user-images.githubusercontent.com/93000192/143611952-9991665f-db2e-4d76-83e6-a776512efdb5.PNG)

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
