### ISSUE TITLE
Parse CEF logging and configure an additional mapping field within message

### ISSUE THREAD

**Issue by krabelize** [microsoft/OMS-Agent-for-Linux#1428]
Hi all,

Please correct me if this is not the right place to open an issue. Thanks for creating this great oms-agent by the way!

I have successfully configured and installed the oms-agent and the Microsoft CEF python log forward script on a Ubuntu 20.04 x64 VM to forward Fortinet Analyzer firewall logging to Sentinel. I receive the CEF logging in Sentinel. Most fields are mapped correctly. However, not all fields within the CEF `message` field are mapped, such as `ad.srccountry` variable. This field is now in the AdditionalExtensions variable along with other data.

Within CEF -> message -> AdditionalExtensions there is the `ad.srccountry` variable. I want the "ad.srccountry" variable mapped to `cs1` (DeviceCustomString1) in Sentinel. I got this idea from [a list of all supported CEF message mapping field.](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/cef-name-mapping.md)

However, I cannot figure out how to configure this additional parse within the message field.

My configuration:

```
vi /etc/opt/microsoft/omsagent/<tenantID>/conf/omsagent.d/security_events.conf 

<source>
  type syslog
  port 25226
  bind 127.0.0.1
  protocol_type tcp
  tag oms.security
  format /(?<time>(?:\w+ +){2,3}(?:\d+:){2}\d+|\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.[\w\-\:\+]{3,12}):?\s*(?:(?<host>[^: ]+) ?:?)?\s*(?<ident>.*CEF.+?(?=0\|)|%ASA[0-9\-]{8,10})\s*:?(?<message>0\|.*|.*)/
  <parse>
     message_format auto
  </parse>
</source>

<filter oms.security.**>
  type filter_syslog_security
</filter>
```

Works (raw message and primary CEF filter): https://regex101.com/r/rdf4iP/1

```
vi /etc/opt/microsoft/omsagent/<tenantID>/conf/omsagent.d/syslog.conf

<source>
  @type syslog
  port 25224
  bind 127.0.0.1
  protocol_type tcp
  tag oms.syslog
</source>

<filter oms.syslog.**>
  @type parser
  key_name message
  format /.*ad.srccountry=(?<cs1>.*?)\s.*$/
</filter>
 ```

Raw message and secondary `ad.srccountry` filter: https://regex101.com/r/v6iZHs/1

`systemctl restart omsagent-<TenantID>.service && systemctl restart syslog`
 
But the `DeviceCustomString1` ([cs1](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/cef-name-mapping.md)) field in `CommonSecurityLog` stays empty in Sentinel. Any tips or tricks how I can get this to work?

**Comment by jordanmills** [comment]
I think that only processes non-CEF syslog messages.  If you want to affect CEF message parsing, you'd do it in security_events.conf in the same directory.

Note that syslog messages are ingested by the agent at 127.0.0.1:25224 UDP but CEF messages are ingested at 127.0.0.1:25226 TCP.  The source section defines those, so you'd want the file that matches the settings for where those kinds of messages are sent.
