### ISSUE TITLE
Ubuntu 21.10 unsupported operating system

### ISSUE THREAD

**Issue by aavdberg** [microsoft/OMS-Agent-for-Linux#1441]
When trying to link a Ubuntu 21.10 vm in Azure to LAW with OMSAgent getting the following error:

type
Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux
Version
1.14.9
Status
Transitioning
Status level
Info
Status message
[ExtensionOperationError] Non-zero exit code: 51, /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/omsagent_shim.sh -install [stdout] 2022/03/22 09:17:49 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9] Install,failed,51,Unsupported operating system: ubuntu 21.10 [stderr] t_code is not 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:309: SyntaxWarning: "is" with a literal. Did you mean "=="? if exit_code is 1 and operation == 'Install': /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:314: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 127 and operation == 'Install': /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:325: SyntaxWarning: "is not" with a literal. Did you mean "!="? elif exit_code is not 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:649: SyntaxWarning: "is" with a literal. Did you mean "=="? if exit_code is 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1002: SyntaxWarning: "is not" with a literal. Did you mean "!="? if exit_code is not 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1164: SyntaxWarning: "is" with a literal. Did you mean "=="? if cert_exit_code is 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1199: SyntaxWarning: "is" with a literal. Did you mean "=="? if exit_code is 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1203: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 1: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1220: SyntaxWarning: "is" with a literal. Did you mean "=="? if exit_code is 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1224: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 1: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1275: SyntaxWarning: "is not" with a literal. Did you mean "!="? if exit_code is not 0: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1279: SyntaxWarning: "is" with a literal. Did you mean "=="? if exit_code is 17: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1300: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 19: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1313: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 33: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1320: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 5: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1327: SyntaxWarning: "is" with a literal. Did you mean "=="? elif exit_code is 8: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.9/./omsagent.py:1335: SyntaxWarning: "is not" with a litera
Handler status
Not Ready
Handler status level
Info
Automatic upgrade status
Not supported

**Comment by NarineM** [comment]
Same issue as https://github.com/microsoft/OMS-Agent-for-Linux/issues/1451
