### ISSUE TITLE
Disabling collection of VMProcess

### ISSUE THREAD

**Issue by JayDoubleu** [microsoft/OMS-Agent-for-Linux#1449]
Is there a configuration setting which would allow to disable collection logs that end up in VMProcess table of log analytics ?
Or specifically, I want to disable the collection of "CommandLine" field.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
