### ISSUE TITLE
McAfee OMS agent path updated /opt/isec/* - /opt/McAfee/*

### ISSUE THREAD

**Issue by vmonge** [microsoft/OMS-Agent-for-Linux#1456]
Hello, team

Recently McAfee announced a directory path change from opt/isec/* to opt/McAfee/* 
which has been updated in public Doc yet sending machines to Unhealthy/NotCOmpliant section.

This is now impacting several CXs, When will this change be reflected to the oms agent for Linux machines?  Thanks! 

DOCs: 
https://docs.microsoft.com/en-us/azure/defender-for-cloud/endpoint-protection-recommendations-technical#mcafee-endpoint-security-for-linux-threat-prevention
https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/source/code/plugins/collectmcafeeinfo.rb

**Comment by NarineM** [comment]
Please try version 1.14.16 instead that contains McAfee path related fix: https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.14.16-0
VM extension version 1.14.16.
