### ISSUE TITLE
Support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by pt0x** [microsoft/OMS-Agent-for-Linux#1458]
Hello Team,

Currently there is no support for Ubuntu 22.04 LTS. 
I want to raise this issue so we can track the status better. 

Please be advised that Canonical already has a Azure Marketplace Image for Ubuntu 22.04 LTS available, and when logging in through SSH they actively promote release upgrades from earlier versions through the MOTD.

![image](https://user-images.githubusercontent.com/64869301/168581666-a346d35b-8ddd-44a2-ade1-0e42fcf58b0c.png)

Thanks for all the hard work, keep it up!

**Comment by pdefreitas** [comment]
Ubuntu 22.04 LTS has the same behavior as described in #1451

**Comment by jkatzmandu** [comment]
I just started playing with 22.04 LTS. My installer complains with the following:

$ sudo sh onboard_agent.sh -w <workspace> -s <key>
[ ... downloads OK ... ]

Extracting OMS agent install bundle...
----- Upgrading package omi to version (omi-1.6.9-1.ulinux.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 3.0.2
Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

OMS agent shell bundle exiting with status code 55


I'll have to spin up a new VM with 20.x but this is what I'm running into. I tried to manually install the oms.deb file and it gave a similar error. There is no OpenSSL 1.x package for Ubuntu 22.x that I can find.

**Comment by voiprodrigo** [comment]
facing this issue as well, subscribing.

**Comment by DavidGarrana** [comment]
Ubuntu 22.04.1 release, which marks the "de facto" stable release of Jammy, is scheduled for August 11th. ([https://wiki.ubuntu.com/Releases]). From this date on, do-release-upgrade utility will upgrade any existing 20.04 systems to 22.04, which in turn will break every OMS Agent functionality on Ubuntu, because the installer doesn't know 22.04, and because it requires OpenSSL 1.1.  There is a reason the default OpenSSL release on 22.04 is 3.x; there are known vulnerabilities on 1.1 for ages now, even Microsoft Defender for Cloud warns about it.
<img width="1006" alt="Captura de Tela 2022-08-09 às 15 27 43" src="https://user-images.githubusercontent.com/110932073/183734736-e1abaf88-d944-4988-bc38-ffffb8f8673d.png">
I think some priority on this issue is due, specially when enterprise customers will be opening tickets about it. For the record, both Log Analytics and Microsoft Sentinel (SIEM) depends on it to work properly!

**Comment by voiprodrigo** [comment]
Meanwhile I've noticed that the OMS agent is in a deprecation path and will be retired on august 2024. The current recommendation from MS is to migrate to the Azure Monitor Agent, which I'm starting to explore. This may mean that support for newer Linux distribution versions may stop altogether.

**Comment by DavidGarrana** [comment]
> Meanwhile I've noticed that the OMS agent is in a deprecation path and will be retired on august 2024. The current recommendation from MS is to migrate to the Azure Monitor Agent, which I'm starting to explore. This may mean that support for newer Linux distribution versions in the OMS / Log Analytics Agent may stop altogether.

Just tripped on it myself, after posting the comment. For those in need, here is the link to install the AMA Extension: [https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=ARMAgentPowerShell%2CPowerShellWindows%2CPowerShellWindowsArc%2CCLIWindows%2CCLIWindowsArc](url)

**Comment by watsonb** [comment]
It is now September 8th 2022.  Any updates on this?  There is already a point release, Ubuntu 22.04.1, which is when most seriously consider using the newer version (myself included), but we really want this functionality before we start rolling out new or upgrading existing servers.

**Comment by AndrewSav** [comment]
@watsonb from the previous comment I concluded that since it's on a deprecation path, most likely there won't be an update

**Comment by voiprodrigo** [comment]
There better be an update, considering that the AMA agent is currently
incapable of collecting log files correctly (in Linux at least).

**Comment by szeestraten** [comment]
> There better be an update, considering that the AMA agent is currently incapable of collecting log files correctly (in Linux at least).

Is there an open issue or known issue note somewhere that confirms this?

**Comment by voiprodrigo** [comment]
I don’t know about that. My remark is purely based on me trialing the AMA
agent on different flavors of Linux VM’s in Azure, and finding a big
blocker: the Computer column is not created in a custom log table, so
there’s no column identifying which VM the log came from. Not even
_ResourceId. Support replicated and confirmed this.

Mind that the log file collection feature is still in preview. That said, I
was also told that the computer name will eventually be “appended” to the
RawData value, and when that happens you will need to use a KQL transform
to extract it. That was disappointing :\

**Comment by mbsnl** [comment]
AMA still can't be used everywhere. When using "Auto provisioning for Microsoft Defender for Cloud", the Log Analytics Agent is the only way forward for Enterprises.

**Comment by lodener** [comment]
Also ran into the issue of OMS not installing on Ubuntu 22.04 LTS. When contacting Microsoft about it, they stated there were no plans to port the OMS agent to Ubuntu 22.04 LTS and pointed us to AMA.

When asked about the GA of several services that are currently only in public preview for AMA, no ETA could be given. Disappointing.

**Comment by voiprodrigo** [comment]
Very disappointing indeed. Pushing customers to a solution without feature
parity and still with functionality blockers is not the way to support
clients.

**Comment by PCNZ** [comment]
They were aiming for feature parity by March 2022. Obviously missed that.
https://learn.microsoft.com/en-us/answers/questions/521200/feature-parity-roadmap-for-azure-monitor-agent.html
Last update I saw, they are now aiming for the end of this calendar year.
https://learn.microsoft.com/en-us/shows/ask-the-expert/ask-the-expert-azure-monitor-agent-migration#time=09m00s

**Comment by kkbruce** [comment]
Now, leave a record:

System
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
Log
```
2022-10-04 03:45:25 (4.84 MB/s) - ‘omsagent-1.14.19-0.universal.x64.sh’ saved [161368671/161368671]

Extracting OMS agent install bundle...
----- Upgrading package omi to version (omi-1.6.9-1.ulinux.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 3.0.2
Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

OMS agent shell bundle exiting with status code 55
```

**Comment by mblaschke-daimlertruck** [comment]
Any updates here? any timeline?

**Comment by PCNZ** [comment]
> They were aiming for feature parity by March 2022. Obviously missed that. https://learn.microsoft.com/en-us/answers/questions/521200/feature-parity-roadmap-for-azure-monitor-agent.html Last update I saw, they are now aiming for the end of this calendar year. https://learn.microsoft.com/en-us/shows/ask-the-expert/ask-the-expert-azure-monitor-agent-migration#time=09m00s

AMA supports Ubuntu 22.04 (since around October 2022) so that may remove one of the blockers to moving away from OMS.
https://learn.microsoft.com/en-us/azure/azure-arc/servers/prerequisites#supported-operating-systems

**Comment by Viajaz** [comment]
It's my understanding that AMA support for on-premises Linux servers is limited to those with Azure Arc, it would be easier to just migrate over to Telegraf with it's `azure_monitor` input plugin instead although it's not fully available yet; a disappointing migration path.

**Comment by anthonysomerset** [comment]
so according to https://github.com/microsoft/omi/issues/715 - there is now an OpenSSL 3 supported version of OMI

and an updated DEB in the MS repo - https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/o/omi/

quick download and dpkg  and it appears this issue now moves on....
```
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: ----- Upgrading package: scx (scx-1.6.8-1.universal.x64) -----
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Error: This system does not have a supported version of OpenSSL installed.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: This system's OpenSSL version: 3.0.2
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: OMS Troubleshooter is installed.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: You can run the Troubleshooter with the following command:
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: 
```
looks like there is an updated deb for that also

https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/s/scx/

with that also updated the error is now:

```
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Checking host architecture ...
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Extracting...
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: ----- Upgrading package: omi (omi-1.6.8-1.ulinux.x64) -----
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Skipping package since existing version >= version available
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Trying to stop omi with systemctl
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: omi is stopped.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Trying to start omi with systemctl
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: omi is started.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: ----- Upgrading package: omsagent (omsagent-1.14.9-0.universal.x64) -----
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Error: This system does not have a supported version of OpenSSL installed.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: This system's OpenSSL version: 3.0.2
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: OMS Troubleshooter is installed.
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: You can run the Troubleshooter with the following command:
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: 
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns:   $ sudo /opt/microsoft/omsagent/bin/troubleshooter
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: 
Notice: /Stage[main]/Azurelaagent::Install_linux/Exec[OMSAgent installation]/returns: Shell bundle exiting with code 55
```

**Comment by NYKoop** [comment]
I see from your output that it is still trying to install omi 1.6.8. 1.7.0 is the version that now supports openssl 3.0. See https://github.com/Microsoft/omi/releases. I was able to install omi 1.7.0 on a RHEL 9 box fine with the MS package at https://packages.microsoft.com/rhel/9/prod/Packages/o/omi-1.7.0-0.ssl_300.ulinux.x64.rpm. In looking at the deb URL above - https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/o/omi/ - it appears that omi 1.7.0 is also there. The next question is, when will omi 1.7.0 be packaged with OMS-Agent-for-Linux?

**Comment by anthonysomerset** [comment]
yes the installer was still attempting to install the older version but skipping due to presence of newer version manually installed. basically all the dependant programs are updated and no longer a blocker, the new error is about the omsagent itself not supporting OpenSSL3

**Comment by sofbkeller** [comment]
The supposed transition for AMA doesn't make sense with all the holes it is leaving in the existing OMS agent functionality. 

We use Update Automation; Update Management Center is the V2 release but it's still in "Preview" so not using it on our prod systems. With OMI not supporting 22.04 the suggestion is to install AMA but AMA only supports Update Management V2 which is a PREVIEW project. 
What the heck!

**Comment by danielgohlke** [comment]
same on Debian12

──╼ #bash omsagent-1.16.0-0.universal.x64.sh --install -w  xxxxx -s "xxxxxxx"
Extracting OMS agent install bundle...
----- Installing package: omi (omi-1.7.1-0.ulinux.s.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 3.0.9
Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

OMS agent shell bundle exiting with status code 55
The Log Analytics agent is on a deprecation path and won't be supported after August 31, 2024. If you use the Log Analytics agent to ingest data to Azure Monitor, make sure to migrate to the new Azure Monitor agent (https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration) prior to that date.

**Comment by jochenvw** [comment]
+1

**Comment by PCNZ** [comment]
Curious why AMA can't be used instead of OMS.
Is there something specific OMS is needed for over AMA?

Assume everyone has seen this, there is now less than 12 months before OMS is officially retired.
https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/

**Comment by mbsnl** [comment]
Aparently Microsoft is still working on AMA Autoprovisioning. There was something in Preview for AMA Autoprovisioning with a Policy, but that has been (or will next month) be deprectated. Aparently some new AMA Autoprovisioning (for SQL only?) will be availabile in December 2023.
So, all of this is still extremely bad planning and bad marketing by Microsoft (and to be honest, that was more or less expected).
So it was a good call last year to open this issue and start asking for OMS Support for newer Linux distributions.
But also there, I did not expect Microsoft to fix this (see the above chaos).

Today, AMA is not on-par with OMS/MMA. 
So, why spend effort? Things for AMA are in in Preview of were in Preview still being deprecated. OMS will probably be extended looking at all of this misery, waiting for that announcement.

**Comment by DavidGarrana** [comment]
We're talking for over an year here about the most used linux distribution, **accounting for over 1/3 of market linux share**, with **several customers using it in production environments**.

It's been almost **18 MONTHS** since it's latest LTS version is released, and nonetheless, we can't use OMS (and shouldn't, because OpenSSL 1 is notoriously unsafe and **will trigger warnings on Azure Defender for Cloud** to add insult to injury) and even though we can use AMA, no Guest Level Diagnostics because, you know, it doesn't support 22.04.

How are we supposed to recommend Azure Defender and/or Sentinel to our customers with this glaring gap on the very data they rely upon to actually do what they're supposed to?

It's not SysOps nitpicking or bleeding edge adoption stubborness we're talking here. It's a serious, major flaw on both product strategy and value to customers.

Can we please get **ANY** kind of official position regarding this? We really don't want to admit to customers they're better of with Datadog or New Relic if they plan on keep using Ubuntu.

**Comment by sofbkeller** [comment]
Thats my issue with it as well. 
Add to it being the underpinning of Services in place like Azure Update Management where there is no official migration path off the platform as the new _PREVIEW_ replacement has no roadmap or communication around it. The new one doesn't need OMS but its Preview so there is no Production support on it. Using the existing Update Management requires OMS so your basically just left on a dying product with no way to manage newer VMs.

**Comment by anthonysomerset** [comment]
So my big remaining use case here as i have been on the OMS to AMA migration journey is actually ironically - Azure Stack Hub

We cannot install the Arc Agent there (because it looks like azure, breaths like azure, and rejects the install like azure) or get a standalone version of AMA that can point to azure public cloud - so i am stuck with OMS until a suitable replacement that can support this scenario is available

I'm now going to start escalating this from my MSFT account management team because after 18 months of a stable LTS Ubuntu release and still 1 year more of supposed support this is kind of ridiculous now

**Comment by JeffreyWolford** [comment]
Anthony, I am the Product Manager for the AMA agent.  I agree the implementation on Azure Stack Hub has been bumpy. I am working with that team over the next few months to resolve this issue.

**Comment by gzerphey** [comment]
Bumping this for a timeline.  This is the latest version of Ubuntu and as of Oct 24 there is still no resolution as I can tell.

**Comment by mbsnl** [comment]
> Bumping this for a timeline. This is the latest version of Ubuntu and as of Oct 24 there is still no resolution as I can tell.

@gzerphey I still see PRs into main for the "VM Extension Repo" (show Ubuntu 22 as of 2 weeks ago) or the "OMS Agent Build Repo" (Even yesterday. Aparently the OMS-Build-Repo is needed for testing/publishing). So I have high hopes that someone is actually working on a release.

**Comment by PCNZ** [comment]
> AMA Autoprovisioning

AMA provisioning via a DCR associated with an Azure Policy is a valid method - these policies should do the job for that. The policies don't seem to be in preview anymore?
https://learn.microsoft.com/en-us/azure/azure-arc/servers/policy-reference
[Configure Linux Arc Machines to be associated with a Data Collection Rule or a Data Collection Endpoint](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fd5c37ce1-5f52-4523-b949-f19bf945b73a)
[Configure Linux Machines to be associated with a Data Collection Rule or a Data Collection Endpoint](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F2ea82cdd-f2e8-4500-af75-67a2e084ca74)

The main issue I'm seeing is with Microsoft Sentinel integrations which only work with OMS.
Also many native services do still show AMA support as being in preview, like Defender for Cloud so I do see the issue there.

**Comment by BerendvW** [comment]
> We're talking for over an year here about the most used linux distribution, **accounting for over 1/3 of market linux share**, with **several customers using it in production environments**.
> 
> It's been almost **18 MONTHS** since it's latest LTS version is released, and nonetheless, we can't use OMS (and shouldn't, because OpenSSL 1 is notoriously unsafe and **will trigger warnings on Azure Defender for Cloud** to add insult to injury) and even though we can use AMA, no Guest Level Diagnostics because, you know, it doesn't support 22.04.
> 
> How are we supposed to recommend Azure Defender and/or Sentinel to our customers with this glaring gap on the very data they rely upon to actually do what they're supposed to?
> 
> It's not SysOps nitpicking or bleeding edge adoption stubborness we're talking here. It's a serious, major flaw on both product strategy and value to customers.
> 
> Can we please get **ANY** kind of official position regarding this? We really don't want to admit to customers they're better of with Datadog or New Relic if they plan on keep using Ubuntu.

It does work on a linux vmss with ubtuntu 22.04, weirdly enough

**Comment by mbsnl** [comment]
I think we have Ubuntu 22 (and more) Release now:
https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.17.1

And there is even a patch:
https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.17.2-0

Maybe the extensions in Azure still need to be updated so it's not automatically installed/updated yet.
I did not test it yet.

**Comment by anthonysomerset** [comment]
manual install/upgrade now works for me

**Comment by DavidGarrana** [comment]
> Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.

While at it maybe you could a lend us a hand over [here](https://github.com/Azure/azure-linux-extensions/issues/1935) so it becomes close to reality faster?
