### ISSUE TITLE
Memory Leak in 1.14.11 and 1.14.12

### ISSUE THREAD

**Issue by Klaas-** [microsoft/OMS-Agent-for-Linux#1461]
It seems there is a memory leak in the latest two version cause by scx 1.6.9-1, according to MS support there is an upgrade available on packages.microsoft.com that fixes it (scx 1.6.9-2).

**Comment by NarineM** [comment]
Yes, omiagent memory leak is fixed in this version of omsagent: https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.14.13-0

**Comment by NarineM** [comment]
If you are installing omsagent through VM extension, then it is fixed in VM extension version 1.14.13.
