### ISSUE TITLE
Out of memory caused by omiagent

### ISSUE THREAD

**Issue by bonahbruce** [microsoft/OMS-Agent-for-Linux#1469]
hello, we were using omsagentforlinux version of 1.14.13, on Centos 7.9.
we had an OOM issue, and it was because of scx, version 1.6.9-1.
so, we had to uninstall hundreds of VM that was collecting syslog via log analytics workspace

and I can see this issue could be reduced by upgrading scx version to 1.6.9-2.
and my question is,

1. I tested myself that at this moment, if I install omsagentforlinux 1.14.13, scx version is installed that version is 1.6.9-2
- is this version safe? I mean, not occur OOM error anymore?

2. I have seen that Microsoft.EnterpriseCloud.Monitoring is not supported to automatic upgrade. 
- is azure planning to get this extensions possible to have a automatic upgrade?

I am looking forward to the answers.

thanks
best regards,
bonah koo

**Comment by Klaas-** [comment]
1) changelog says it's fixed :)
2) Do not expect MS to change anything with OMS unless it's a critical issue, OMS is deprecated and will be replaced by the azure monitor log agent https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview

**Comment by NarineM** [comment]
@bonahbruce yes, version  omsagent version 1.14.13 has the fix for omiagent memory leak. Newer versions of omsagent are always contain all the fixes that were available in older versions , so it is safe to upgrade.
