### ISSUE TITLE
Install,failed,51,Unsupported operating system: AlmaLinux 8.5

### ISSUE THREAD

**Issue by tiwarishrijan** [microsoft/OMS-Agent-for-Linux#1471]
Unable to install OMS AGent on linux for AlmaLinux 8.5 getting below error

2022/06/10 10:52:11 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.13] Install,failed,51,Unsupported operating system: AlmaLinux 8.5

**Comment by NarineM** [comment]
@tiwarishrijan try version 1.14.16 instead: https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.14.16-0
