### ISSUE TITLE
OpenSSL 3.0.x support - error after upgrading to Feroda 36

### ISSUE THREAD

**Issue by eda2000** [microsoft/OMS-Agent-for-Linux#1484]
As in Fedora 35, there was still OpenSSL 1.1.1 oms agent was working well. After upgrade it stop working. After analysis we found that OpenSSL 1.1.1 was replace by OpenSSL 3.0.5

Upgrade to most recent version of OMSAgent also does not works.

Is it possible to expend the support to OpenSSL 3.0.x, please?

_[proxy]$ sudo sh ./omsagent-1.14.16-0.universal.x64.sh --upgrade
Extracting OMS agent install bundle...
----- Upgrading package omi to version (omi-1.6.9-1.ulinux.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 3.0.5
Supported versions: 1.0.1 onward (1.0.0 was deprecated), 1.1.*
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

OMS agent shell bundle exiting with status code 55_

**Comment by eda2000** [comment]
Mentioned also in different disto's #1458

**Comment by eda2000** [comment]
We use this server to collect data and send them to Azure Sentinel, whats why such a sub-component of oms agent are critical for us.

**Comment by bjornwahman** [comment]
Plus one for openssl 3.0 support.

**Comment by wayne-jfl** [comment]
We are now getting the same issue in Ubuntu 22.04 with OpenSSL 3.x

**Comment by ajinkyadg** [comment]
Plus one for this issue on Ubuntu 20.0.4
