### ISSUE TITLE
issues found in OMIcheck 

### ISSUE THREAD

**Issue by Lickkylee** [microsoft/OMS-Agent-for-Linux#1485]
1. Parellel setting on subscriptions will casue notfound issue. 
https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/tools/OMIcheck/OMIcheck.ps1
Line 566: $subs | ForEach-Object -ThrottleLimit $ThrottlingLimit -Parallel {
Issue: if i use the default ThrottlingLimit 16 to run the script, it will report error not found during execution. That's because there is a command Set-AzContext -Subscription $sub.Id in UpdateVMs and UpdateVMss functions, it will change the sub during execution and cause the VM in another sub not found. 
.Get-AzVM:
Line |
   2 |  …       $VM = Get-AzVM -Name $_.Name -ResourceGroupName $_.ResourceGrou …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Resource group 'TEST' could not be found.
ErrorCode: ResourceGroupNotFound
ErrorMessage: Resource group 'TEST' could not be found.
ErrorTarget:
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 1d73ea1b-c5ab-4bd2-ba89-6e14111b331b
Get-AzVM:
Line |
   2 |  …       $VM = Get-AzVM -Name $_.Name -ResourceGroupName $_.ResourceGrou …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Resource group 'WILLDELETESA-MIGRATED' could not be found.
ErrorCode: ResourceGroupNotFound
ErrorMessage: Resource group 'WILLDELETESA-MIGRATED' could not be found.
ErrorTarget:
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 142e44e5-97f8-461f-9ce4-74f5abe50ef8

2. the script will return failed on centOS VMs. 
https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/tools/OMIcheck/omi_check.sh
which dpkg > /dev/null && dpkg -l | grep -E 'omi|omsagent|lad'
This line will return exit code 1 and the runcommand will treat the script execution result as failed. 

[root@common-cen80 ~]# which dpkg > /dev/null && dpkg -l | grep -E 'omi|omsagent|lad'
/usr/bin/which: no dpkg in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/kube)
[root@common-cen80 ~]# echo $?
1
[root@common-cen80 ~]# uname -a
Linux common-cen80 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Tue Sep 24 11:32:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@common-cen80 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
