### ISSUE TITLE
open SSL version is not picked up 

### ISSUE THREAD

**Issue by usmankhanisb** [microsoft/OMS-Agent-for-Linux#1487]
I have openSSL version 1.1.1.1q installed and I can see that from terminal. 

When I run the wget installation command for this OMS copied form Azure (with key and everything ) I get the the error that open SSL verison is not installed. 
It says : This system does not have a supported version of openSSL installed. 

Why it is not picking up the right version. where is the PATh to edit and how to fix it?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
