### ISSUE TITLE
assistance on running [https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/tools/OMIcheck]

### ISSUE THREAD

**Issue by VibhorKa** [microsoft/OMS-Agent-for-Linux#1496]
We need your assistance on running [https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/tools/OMIcheck](https://urldefense.com/v3/__https:/github.com/microsoft/OMS-Agent-for-Linux/tree/master/tools/OMIcheck__;!!DMYgIb-w!xIap7pZ74yLPy7KoFJG3KPQL4xX3-TxDs5POGuZ3tQBgW0tY8-uR-zPwh3-odALlonmEigP01CmBkxhRxvFaSz_o3HWl$)
We are getting error and .
As per Microsoft :
This script is from Github, so you would need to reach out to them on the retry logic for this particular script.
the error message is stating that there is a conflict because the Invoke-AzVMRunCommand was not able to complete a process before another process was asked from it.
Invoke-AzVMRunCommand:
Line |
13 | … $check = Invoke-AzVMRunCommand -ResourceGroupName $VM.ResourceGrou …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Run command extension execution is in progress. Please wait for completion before invoking a run command.
ErrorCode: Conflict
ErrorMessage: Run command extension execution is in progress. Please wait for completion before invoking a run command.
ErrorTarget:
StatusCode: 409
ReasonPhrase: Conflict
OperationID : a5f4c2e8-1d16-4495-9d0f-d568b337ea5e
For the VM to be able to receive the command, the "Windows Azure Guest Agent" service must be up and running. If Invoke-AzVMRunCommand is issue when the service is not running on the VM it will take the command 90 minutes to timeout and fail.
It takes around a minute after the service is started for Azure to recognize the service is available. It takes a little over 10 minutes after disabling "Windows Azure Guest Agent" service before it changes the status to Unavailable.
"Windows Azure Guest Agent " only handles one task at a time so you might get a 409 error ("Run command extension execution is in progress. Please wait for completion before invoking a run command")
Would you be please able to assist us here ?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
