### ISSUE TITLE
unable to open '/opt/microsoft/omsagent/LICENSE.dpkg-new': Permission denied:

### ISSUE THREAD

**Issue by eftech13** [microsoft/OMS-Agent-for-Linux#1499]
We're trying to install the Log Analytic Agent on Azure, Linux, Ubuntu 20 LTS.
We're using storageaccount on SMB. 

But when we see from extension from VM, the status is Transitioning, with error : Timeout (900)
![image](https://user-images.githubusercontent.com/106220538/189800905-15756511-742d-4080-b19b-b721d0de8ffd.png)

If we see the details error then we can see message : "
/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19/omsagent_shim.sh -install [stdout] 2022/09/13 01:14:35 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19] Running command "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19/packages/omsagent-1.14.19-0.universal.x64.sh --upgrade " [stderr] xit_code is 1 and operation == 'Install': ./omsagent.py:319: SyntaxWarning: "is" with a literal.

Then we checked on the log : 
:/var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/extension.log, 
It's stopped on this part : 
2022/09/13 01:14:35 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19] ShellBundle signing verification succeeded
2022/09/13 01:14:35 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19] Falling back to /etc/os-release distribution parsing
2022/09/13 01:14:35 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19] Running command "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.19/packages/omsagent-1.14.19-0.universal.x64.sh --upgrade "

It is stuck there.

We try to upgrade mannualy using command : sh ./omsagent-*.universal.x64.sh --upgrade
we encounter this error : "dpkg: error processing archive 110/omsagent-1.14.19-0.universal.x64.deb (--install):
 unable to open '/opt/microsoft/omsagent/LICENSE.dpkg-new': Permission denied:

![image](https://user-images.githubusercontent.com/106220538/189801062-c8e22abb-f374-4c71-addb-f32cd9370a78.png)

We already try using root user.

Then, we 're trying to reinstall the agent, by running the purge_omsagent.sh, and it's success.
Then we try to install the agent using  :  omsagent-*.universal.x64.sh --install

But the same error raised again : 
![image](https://user-images.githubusercontent.com/106220538/189801195-d355d620-25c3-4e70-8a9d-7c889aee6f1a.png)

Trying to run the troubleshoot, the message is only OMS config isn't installed correctly.

![image](https://user-images.githubusercontent.com/106220538/189801228-e14612f0-e962-493a-8e8a-90ab6a571d87.png)

And we have trying using root user.

If we are doing installation manually using script then we can not see the OMSAgentForLinux on Extension on VM on the Azure Portal.

So we're trying to do purge again, then try to connect manually from Log Analytic Workspace , after more than 1 hour, we can see that the OMSAgentForLinux is installed, but got error Timeout, as in the first explanation above.
![image](https://user-images.githubusercontent.com/106220538/189801345-b6240985-abed-49a9-b7b6-2d7e4b3f8990.png)
![image](https://user-images.githubusercontent.com/106220538/189801386-0408ef03-2ffc-46da-a274-498e91d55ff9.png)

and the status from analytx work space : 
![image](https://user-images.githubusercontent.com/106220538/189801451-3db02eb6-a1ae-4d78-a537-81319d6f3b28.png)

Not sure what is going on, and we have 2 VM system, both of them having same configuration (Ubuntu 20 LTS, using SMB).

Please kindly help for any advice

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
