### ISSUE TITLE
Error on Arc-enabled AWS VM

### ISSUE THREAD

**Issue by philipstreet** [microsoft/OMS-Agent-for-Linux#1509]
I have the OMS Agent installed on an AWS VM that has recently failed. VM details are;

Instance type: t3.small
OS: Ubuntu 18.04.6 LTS

The error details are;

Extension type: Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux
Version: 1.14.19
Status: Failed
Error message:
Extension returned non-zero exit code for Enable: 33.  Extension Message: Enable failed with exit code 33 Azure Resource ID updated.
-e info	Reusing previous agent GUID x-x-x-x-x
-e info	Agent GUID is x-x-x-x-x
-e info	Onboarding success
Configure syslog...
Configuring rsyslog for OMS logging
Restarting service: rsyslog
Configure heartbeat monitoring agent...
Configure log rotate for workspace x-x-x-x-x...
-e info	Retrying configuring omsconfig by calling '/opt/microsoft/omsconfig/Scripts/python3/OMS_MetaConfigHelper.py' with 'sudo'
-e error	Configuring omsconfig and generating metaconfig failed with error code 1. For more details check logs in /var/opt/microsoft/omsconfig/omsconfig.log

I can't see any errors in the omsconfig.log.

Any thoughts/suggestions?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
