### ISSUE TITLE
OmsAgentForLinux-1.14.23 Debian 11 support?

### ISSUE THREAD

**Issue by BartDecker** [microsoft/OMS-Agent-for-Linux#1515]
I deployed several Debian 11 VM's in azure and they all fail to get the extension deployed. The status stays on "unavailable" and the connection in the LA Workspace keeps on trying to connect result in an error as well in the end. 

Now the question is if Debian 11 is supported? When I read the MS documentation it should be supported right?

 "imageReference": {
                "publisher": "debian",
                "offer": "debian-11",
                "sku": "11-gen2",
                "version": "latest",
                "exactVersion": "0.20221219.1234"

`2023/01/04 07:51:19 ImportGPGkey.sh: 16: gpg: not found
2023/01/04 07:51:19 ERROR:Install failed with error: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19 ERROR:Stacktrace: Traceback (most recent call last):
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 301, in main
2023/01/04 07:51:19 ERROR:    verifyShellBundleSigningAndChecksum()
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 208, in verifyShellBundleSigningAndChecksum
2023/01/04 07:51:19 ERROR:    raise Exception("Unable to find the Extension keyring file at " + keyringFilePath)
2023/01/04 07:51:19 ERROR:Exception: Unable to find the Extension keyring file at /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/keys/keyring.gpg
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 ERROR:During handling of the above exception, another exception occurred:
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 ERROR:Traceback (most recent call last):
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 304, in main
2023/01/04 07:51:19 ERROR:    errmsg = "ShellBundle signing verification failed with '%s'" % ex.message
2023/01/04 07:51:19 ERROR:AttributeError: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23] Install failed with error: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19 ERROR:Stacktrace: Traceback (most recent call last):
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 301, in main
2023/01/04 07:51:19 ERROR:    verifyShellBundleSigningAndChecksum()
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 208, in verifyShellBundleSigningAndChecksum
2023/01/04 07:51:19 ERROR:    raise Exception("Unable to find the Extension keyring file at " + keyringFilePath)
2023/01/04 07:51:19 ERROR:Exception: Unable to find the Extension keyring file at /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/keys/keyring.gpg
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 ERROR:During handling of the above exception, another exception occurred:
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 ERROR:Traceback (most recent call last):
2023/01/04 07:51:19 ERROR:  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 304, in main
2023/01/04 07:51:19 ERROR:    errmsg = "ShellBundle signing verification failed with '%s'" % ex.message
2023/01/04 07:51:19 ERROR:AttributeError: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19 ERROR:
2023/01/04 07:51:19 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23] Install,failed,1,Install failed with error: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19 Stacktrace: Traceback (most recent call last):
2023/01/04 07:51:19   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 301, in main
2023/01/04 07:51:19     verifyShellBundleSigningAndChecksum()
2023/01/04 07:51:19   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 208, in verifyShellBundleSigningAndChecksum
2023/01/04 07:51:19     raise Exception("Unable to find the Extension keyring file at " + keyringFilePath)
2023/01/04 07:51:19 Exception: Unable to find the Extension keyring file at /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/keys/keyring.gpg
2023/01/04 07:51:19 
2023/01/04 07:51:19 During handling of the above exception, another exception occurred:
2023/01/04 07:51:19 
2023/01/04 07:51:19 Traceback (most recent call last):
2023/01/04 07:51:19   File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.14.23/./omsagent.py", line 304, in main
2023/01/04 07:51:19     errmsg = "ShellBundle signing verification failed with '%s'" % ex.message
2023/01/04 07:51:19 AttributeError: 'Exception' object has no attribute 'message'
2023/01/04 07:51:19`

**Comment by BartDecker** [comment]
Ok, figured out that it is unsupported.

**Comment by BartDecker** [comment]
No not forked it. Will be going for the new monitoring agent instead of trying to get an unsupported agent working.

**Comment by AkechiShiro** [comment]
@BartDecker that makes sense, you're right, you're talking about the AMA Agent : https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration ?

**Comment by BartDecker** [comment]
> @BartDecker that makes sense, you're right, you're talking about the AMA Agent : https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration ?

yes
