### ISSUE TITLE
Helper.py will throw a variable exception if run on an unsupported OS

### ISSUE THREAD

**Issue by best-geek** [microsoft/OMS-Agent-for-Linux#1519]
# Issue
[OMS-Agent-for-Linux](https://github.com/microsoft/OMS-Agent-for-Linux)/[source](https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/source)/[code](https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/source/code)/[troubleshooter](https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/source/code/troubleshooter)/[modules](https://github.com/microsoft/OMS-Agent-for-Linux/tree/master/source/code/troubleshooter/modules)/helpers.py has an issue when being run on an unsupported os. 

The try and except block in the below function can cause issues  if `vm_dist` does not get populated by the previous function call. This will result in the user receiving a reference exception and the troubleshooter does not continue to run.  
```
def get_os_version():
    # get vm info
    try:
        (vm_dist, vm_ver, vm_id) = linux_distribution()
    except:
        try:
            (vm_dist, vm_ver, vm_id) = dist()
        except:
            pass  # continue on to os_release check
```

# Fix
This is easily fixed by supplying a tuple of None types which then means subsequent code identifies it's an unsupported OS
```
def get_os_version():
    # get vm info
    try:
        (vm_dist, vm_ver, vm_id) = linux_distribution()
    except:
        try:
            (vm_dist, vm_ver, vm_id) = dist()
        except:
            (vm_dist, vm_ver, vm_id) = (None, None, None)
            pass  # continue on to os_release check
```

# Steps to reproduce
Install the OMS Agent from Sentinel on a Debian 11 machine and try to run `/opt/microsoft/omsagent/bin/troubleshooter`

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
