### ISSUE TITLE
selinux omsconfig rule does not take effact.

### ISSUE THREAD

**Issue by xiaodonghan-ms** [microsoft/OMS-Agent-for-Linux#1520]
The omsconfig service understand it's logs will be saved outside of /var/log folder (/var/opt/microsoft/omsconfig) like omsagent, it tried to setup the selinux configration for omsconfig like omsagent. 
However, for some reason the omsconfig rules did not take effect.

![image](https://user-images.githubusercontent.com/91401916/217151617-84409883-09d4-4182-b0d5-ecfa34c09af2.png)

![image](https://user-images.githubusercontent.com/91401916/217151638-51003fab-3f83-4bac-996c-e6e59aaf1f8b.png)

**Comment by Klaas-** [comment]
@antonhan-ms https://github.com/microsoft/OMS-Agent-for-Linux/issues/781

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
