### ISSUE TITLE
Cisco ASA Logs not parsing correctly

### ISSUE THREAD

**Issue by benedictschmieder** [microsoft/OMS-Agent-for-Linux#1521]
Hello,
like the title says, Cisco ASA logs won't parse correctly. I have a suspicion that it has something to do with dashes in the access list name, but I cannot confirm that.
Here is an example:
Syslog message sent by Cisco ASA:
`%ASA-3-106100: access-list outside-paip_access_in denied tcp outside-paip/94.102.61.38(50802) -> pub-dmz1/45.150.124.119(5020) hit-cnt 1 first hit [0xf98ea545, 0x00000000]`

![image](https://user-images.githubusercontent.com/95091844/217241431-6d58cc64-2b50-49c4-a7c3-522cccb84ad5.png)
This is the entry in the CommonSecurityLog table. As you can see, all those fields that are normally populated (e.g. DeviceAction, DestinationIP, DestinationPort, SourceIP, SourcePort, etc.) aren't filled out.

Additionally we get an error in the OMS-Agent log (/var/opt/microsoft/omsagent/4eb8f1b1-b851-4212-8aed-23415723b9ca/log/omsagent.log):
`2022-12-20 13:59:45 +0100 [warn]: pattern not match: "Dec 20 14:00:01 10.2.238.1 : message repeated 2 times: [ %ASA-3-106100: access-list EMY-Green_access_out denied udp inside/172.17.191.169(50618) -> EMY-Green/172.31.4.6(514) hit-cnt 1 first hit [0xed13c5a0, 0x00000000]]"`
(This is for an older entry, not the one shown in the screenshot)

This is a serious issue. In the last 7 days, over 88% of the logs, coming from the Cisco ASA weren't parsed correctly.

I'm happy to help, please ask any questions you have which might help resolving this issue.
Kind regards

EDIT: The config file for Cisco ASA mentioned [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Security-Events-Preview-Configuration.md) is correctly set up in the OMS-Agent.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
