### ISSUE TITLE
Troubleshooter connectivity test

### ISSUE THREAD

**Issue by sodds-eq** [microsoft/OMS-Agent-for-Linux#1522]
```
WARNING FOUND: Machine is not connected to the internet: openssl command failed. Please run the command below for more information on the failure:

  $ echo | openssl s_client -connect docs.microsoft.com:443 -brief

```

That is not the statement and check that should be implemented. I don't see any reasons why the OMSAgent should have access to docs.microsoft.com/internet in general at all. The connectivity test should only be concerned with the actual endpoints it needs to function. If it actually needs access to the docs.microsoft.com site that sounds like a design issue that should be reworked.

So giving a WARNING about the machine is not connected to the internet is misleading in my opinion.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
