### ISSUE TITLE
"Ensure lockout for failed password attempts is configured." and "Ensure password reuse is limited." don't recognize how authselect does them

### ISSUE THREAD

**Issue by josephcsible** [microsoft/OMS-Agent-for-Linux#1565]
https://github.com/microsoft/OMS-Agent-for-Linux/blob/4573f0b2f00d01556e28f9931a6f938349470281/source/code/plugins/oms_audits.xml#L218-L227
https://github.com/microsoft/OMS-Agent-for-Linux/blob/4573f0b2f00d01556e28f9931a6f938349470281/source/code/plugins/oms_audits.xml#L1348-L1357
RHEL and derivatives use authselect to manage PAM configuration. With authselect, the commands `authselect enable-feature with-faillock` and `authselect enable-feature with-pwhistory` implement the above two audits. The problem is that those rules look for the configuration options `deny`, `unlock_time`, and `remember` in the `/etc/pam.d/password-auth` and `/etc/pam.d/system-auth` files, but when you're using authselect, you're not supposed to edit those files manually, and are supposed to put those settings in `/etc/security/faillock.conf` and `/etc/security/pwhistory.conf` instead. In addition, authselect calls pam_pwhistory with `requisite` as the control value, but our rule only matches `required`.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
