### ISSUE TITLE
Please support Docker 1.12 asap

### ISSUE THREAD

**Issue by daninthewoods** [Microsoft/OMS-Agent-for-Linux#165]
ContainerLogs seems to work fine, but the Container tile isn't leaving the 'Performing Assessment' stage when using 1.12.  Confession: I have not tested earlier docker versions, so I'm assuming this is the issue.

**Comment by agup006** [comment]
Support is in the works @daninthewoods, @keikhara can provide more details

**Comment by keikhara** [comment]
Hi @daninthewoods, we are looking to support Docker 1.12 version this month. We will keep you posted.

**Comment by daninthewoods** [comment]
Great timing, we'll keep an eye out for the update.

**Comment by keikhara** [comment]
it's supported.

**Comment by daninthewoods** [comment]
Nice job.  We'll best testing it next week.
