### ISSUE TITLE
SELinux prevents omsagent logrotate settings after install on RHEL

### ISSUE THREAD

**Issue by mw007** [Microsoft/OMS-Agent-for-Linux#172]
After installing omsagent on RHEL 7.2, log rotation is prevented by Red Hat's SELinux targeted policy. The error encountered is:

`error: stat of /var/opt/microsoft/omsagent/log/omsagent.log failed: Permission denied`

SELinux logs the following in /var/log/audit/audit.log:

```
type=AVC msg=audit(1471331366.853:3801338): avc:  denied  { getattr } for  pid=2181 comm="logrotate" path="/var/opt/microsoft/omsagent/log/omsagent.log" dev="sda2" ino=35118430 scontext=system_u:system_r:logrotate_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_t:s0 tclass=file
        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.
```

This issue is fixed manually with the following commands (run as root):

```
semanage fcontext -a -t logrotate_exec_t '/var/opt/microsoft/omsagent/log/omsagent.log'
restorecon -v '/var/opt/microsoft/omsagent/log/omsagent.log'
```

However, this is a manual modification that would need to be performed on each virtual machine. I think this should be done automatically via the install script.

**Comment by dan4duk** [comment]
Surprised to find this is still not included in the install script 6 years on, thank you for the resolution. (CentOS8)
