### ISSUE TITLE
Systemd configuration should use drop-in units

### ISSUE THREAD

**Issue by colemickens** [Microsoft/OMS-Agent-for-Linux#189]
You should use drop-in units to reconfigure docker rather than editting the system package's `docker.service`. The Docker docs documents this process pretty clearly.

**Comment by agup006** [comment]
@keikhara for Docker improvement

**Comment by keikhara** [comment]
Thanks Let me look into this.

**Comment by keikhara** [comment]
We change the method in the latest version 1.2.0-148 of the OMS Linux Agent. No longer you need these settings.
