### ISSUE TITLE
Cisco ASA logs are not correctly parsed

### ISSUE THREAD

**Issue by brandubh** [Microsoft/OMS-Agent-for-Linux#201]
The host name is captured from the time part of the message, basically the format regexp is incorrect.
I cannot create a pull so if you're interested this is the format that is working in my environment:
/^(?<time>[^ ]*\s*[^ ]* [^ ]* [^ ]*) (?<host>[^ ]*) : (?<ident>[a-zA-Z0-9_%\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$/

**Comment by mgladi** [comment]
Hi brandubh,
Can you please provide a few examples of messages where the host name was captured incorrectly?
Also, If you can, please specify the OS and syslog daemon in which you encountered the issue.

Thanks!

**Comment by brandubh** [comment]
Hi Michael,
I'm currently using Ubuntu and sending syslog entries directly to the OMS agent (but it doesn't make any difference transiting from rsyslog), immo it's not an OS related issue, maybe a Cisco iOS version issue that anyway should be managed by the solution. 
This is a sample log entry written by the ASA with deviceId enabled (more info https://nocentdocent.wordpress.com/2016/09/14/msoms-collecting-cisco-asa-events-the-right-way):
Sep 14 2016 09:33:47 ASA-Progel-RE : %ASA-4-106023: Deny icmp src outside:132.245.29.98 dst inside:172.30.100.101 (type 0, code 0) by access-group "outside" [0x0, 0x0]

And this is an entry with deviceId disabled
Sep 14 2016 10:07:20: %ASA-4-106023: Deny udp src inside:172.30.20.45/58602 dst outside:13.95.227.217/3389 by access-group "inside" [0x0, 0x0]

Cisco ASA 5515, version 9.5(2)6

Daniele

**Comment by mgladi** [comment]
Hi Daniele,

A fix for was merged into the master:  #233 
I'm going to close the issue now.
Feel free to reopen it if you see any more parsing errors.

Thanks a lot for reporting this.
