### ISSUE TITLE
Better Kubernetes support

### ISSUE THREAD

**Issue by edevil** [Microsoft/OMS-Agent-for-Linux#235]
I'm trying to integrate the OMS agent in my Kubernetes cluster but there are certain things that could be improved. I'm using CoreOS, so I had to run the OMS agent in a privileged container as described in https://hub.docker.com/r/microsoft/oms/. The fact that I have to configure the Docker daemon to use the fluentd log driver instead of the json driver prevents certain commands like "docker logs" or "kubectl logs" from functioning properly.

Can't the agent tail the json log files present in /var/log/containers/*.log ?

Also, in the case of fluentd, there is a [plugin](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter) that queries the Kubernetes API to inject additional metadata in the log lines. Does the OMS agent somehow make use of fluentd underneath? Can we use this plugin?

**Comment by edevil** [comment]
I managed to find the fluentd installation inside the OMS Agent, however I could not install the plugin due to an old version of Ruby:
```
ERROR:  Error installing fluent-plugin-kubernetes_metadata_filter:
	activesupport requires Ruby version >= 2.2.2.
```
Can I upgrade the Ruby version?

**Comment by agup006** [comment]
Hi @edevil, We are looking to upgrade the version [2.2.2+] of Ruby in the OMS Agent for Linux in the next couple of months. 

Today you can change the git module in the OMS Agent for Linux source to reference to Ruby v2.2.2+. 

Thanks,
Anurag

**Comment by edevil** [comment]
Are there any build instructions for the OMS agent?

**Comment by jeffaco** [comment]
@edevil, See the [superproject](https://github.com/Microsoft/Build-OMS-Agent-for-Linux), it has detailed build instructions for the OMS agent.

**Comment by edevil** [comment]
@jeffaco The instructions mention that if I don't have access to the "OMS TestConfig" repo I should only run the first git clone. However, even there I get denied access to another repository:

```
$git clone --recursive git@github.com:Microsoft/Build-OMS-Agent-for-Linux.git bld-omsagent
Cloning into 'bld-omsagent'...
...
Checking connectivity... done.
Submodule 'auoms' (git@github.com:Microsoft/OMS-Auditd-Plugin.git) registered for path 'auoms'
Submodule 'dsc' (git@github.com:Microsoft/PowerShell-DSC-for-Linux.git) registered for path 'dsc'
Submodule 'omi' (git@github.com:Microsoft/omi.git) registered for path 'omi'
Submodule 'omsagent' (git@github.com:Microsoft/OMS-Agent-for-Linux.git) registered for path 'omsagent'
Submodule 'opsmgr' (git@github.com:Microsoft/SCXcore.git) registered for path 'opsmgr'
Submodule 'opsmgr-kits' (git@github.com:Microsoft/SCXcore-osskits.git) registered for path 'opsmgr-kits'
Submodule 'pal' (git@github.com:Microsoft/pal.git) registered for path 'pal'
Cloning into '/Users/andre/work/vc/bld-omsagent/auoms'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Microsoft/OMS-Auditd-Plugin.git' into submodule path '/Users/andre/work/vc/bld-omsagent/auoms' failed
```

**Comment by jeffaco** [comment]
@edevil Sorry, this change was made recently, and I was unaware of it.

I'm not sure what OMS-Auditd-Plugin is, and why it's private.

@robbiezhang Can you give guidance here please?

**Comment by keikhara** [comment]
Hi @edevil, 

this method has changed. You no longer need to set the --log-driver anymore. 
Please check our latest version. You will see the instruction has changed.

**Comment by edevil** [comment]
@keikhara Ok, that's good to know. What about the upgraded ruby version? I would like to be able to use the fluent-plugin-kubernetes_metadata_filter plugin in order to augment the log lines with Kubernetes specific information. However, it requires ruby >= 2.2.2.

**Comment by keikhara** [comment]
Hi @edevil, 

for the ruby version,  my colleague, @robbiezhang can provide more guidance. 
We are looking to support Kubernetes in future in addition to the Mesosphere DC/OS we have just supported. 

regards, 

Keiko

**Comment by OguzPastirmaci** [comment]
@edevil, for monitoring the containers in the cluster, you can deploy the OMS agent running as a container to Kubernetes using this DaemonSet:

https://gist.github.com/OguzPastirmaci/bba85a47c7c5fb71dc6e6f2acdd13249

**Comment by edevil** [comment]
@OguzPastirmaci Yes, that is what I'm planning to do. But I still need to be able to use the fluentd plugin that retrieves additional data from the Kubernetes API.

**Comment by keikhara** [comment]
@edevil @OguzPastirmaci 

I will consider this an enhancement which we will be working on. 
regards, 

Keiko

**Comment by edevil** [comment]
I've noticed that there's a commit 210ccc2 from October 2016 that upgrades the Ruby version of the OMS agent, however I've just tried the ruby version on the latest Microsoft/OMS docker image and it's still 2.2.0:
```
root@631c05c91553:/opt# ./microsoft/omsagent/ruby/bin/ruby -v
ruby 2.2.0p0 (2014-12-25) [x86_64-linux]
```
When will this commit reach a release?

**Comment by lagalbra** [comment]
@edevil We're looking to release a version this month that contains the update to Ruby 2.3.3, originating from commit https://github.com/Microsoft/OMS-Agent-for-Linux/commit/210ccc2247b463439ddb196a60e3acc095e8052b

**Comment by lagalbra** [comment]
@keikhara can speak more to better Kubernetes support.

As for using Ruby 2.3.3, the [latest agent release](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) does include Ruby 2.3.3.

**Comment by keikhara** [comment]
@edevil kubernetes support is there as of 2weeks ago. We are capturing k8s events.

**Comment by edevil** [comment]
@keikhara Which tag should I be using of these? https://hub.docker.com/r/microsoft/oms/tags/

Is there any additional configuration that I have to provide to the agent?

Thanks!

**Comment by edevil** [comment]
ping @keikhara 

is there some documentation about what the agent is actually capturing? I don't see this additional information on the OMS portal. On another note, how does the OMS agent know it is running on a Kubernetes cluster? Does it assume from the computer name? https://github.com/Microsoft/Docker-Provider/blob/c79a123b4f579176bc7ff000a2a69752a49e4679/source/code/providers/Container_HostInventory_Class_Provider.cpp#L145 I have tried this but still no additional info on OMS.

**Comment by keikhara** [comment]
+Sambit and Joby

**Comment by edevil** [comment]
Anyone?

**Comment by jpoon** [comment]
I haven't tried this myself, but I noticed there's a helm chart to install the OMS daemonset (https://kubeapps.com/charts/stable/msoms). @edevil, did you already try this? You can see from the [volume mounts](https://github.com/kubernetes/charts/blob/master/stable/msoms/templates/omsagent-daemonset.yaml#L52) that it's grabbing data from the docker socket and `/var/log`.

**Comment by edevil** [comment]
I haven’t tried the helm chart, but the daemonset already mounts those dirs.
