### ISSUE TITLE
Badly parsed fields when ports in Image URL's

### ISSUE THREAD

**Issue by daninthewoods** [Microsoft/OMS-Agent-for-Linux#244]
Using latest Ignite version of OMS Linux Agent with Docker 1.12.1, when image URL's contain port numbers it seems to be badly parsed into fields with incorrect values

When URL would be: registry.somehost.com:18443/zzz/xxx-yyyyyy-services:12.6.0

But is parsed into the following fields
Repository:registry.somehost.com:18443
Image:zzz/xxx-yyyyyy-services:12.6.0
ImageTag:18443/zzz/xxx-yyyyyy-services:12.6.0

Expect
Repository:registry.somehost.com:18443
Image:zzz/xxx-yyyyyy-services
ImageTag:12.6.0

**Comment by keikhara** [comment]
Hello, can you provide which version of docker, OS type and version. Thanks.

**Comment by daninthewoods** [comment]
Fixed in latest version, thanks.
