### ISSUE TITLE
Container Memory charts should show Container Name, not ID

### ISSUE THREAD

**Issue by daninthewoods** [Microsoft/OMS-Agent-for-Linux#277]
The Container Memory Usage tile uses this search
`Type=Perf ObjectName=Container CounterName="Memory Usage MB" | Measure Avg(CounterValue) as AvgUsedMemory by InstanceName interval 30minute`

However, this provides a list of container ID's.  Can this be changed (or help me define a custom search) that will provide the same data, but labelled by the Name of the container (ie. ContainerInventory.Name)?  In Swarm 1.12 this is particularly useful.

**Comment by keikhara** [comment]
Please update your OMS Linux Agent to the latest version. This is fixed in latest version of the agent.
