### ISSUE TITLE
Newest version, omsagent-1.2.0-148, of the oms agent seem to crash continuously and fills upp the disk with core dumps under the following path, /var/opt/omi/run/. 

### ISSUE THREAD

**Issue by mictsi** [Microsoft/OMS-Agent-for-Linux#286]
Installed the newest version, omsagent-1.2.0-148, of the oms agent seem to crash continuously and fills upp the disk with core dumps under the following path, /var/opt/omi/run/.
The issue seems to be with the omi provided in that package and verified that it crashes on ubuntu 16.04.1 and centos 7.2. Previous versions of the agent worked without issues.

Running on the vm's is
Docker 1.12.3
Omsagent 1.2.0-148 (omi 1.1.0)

We get the following errors on ubuntu/centos machines

[root@myhost run]# journalctl -f | grep omiag
Nov 23 14:40:22 myhost kernel: omiagent[57281]: segfault at 10 ip 00007f12d7b92869 sp 00007fffdab230e0 error 4 in libcontainer.so[7f12d7b33000+77000]
Nov 23 14:40:59 myhost kernel: omiagent[57322]: segfault at 10 ip 00007f03bc34f869 sp 00007ffd14f432a0 error 4 in libcontainer.so[7f03bc2f0000+77000]
Nov 23 14:41:36 myhost kernel: omiagent[57399]: segfault at 10 ip 00007fe3fedf4869 sp 00007ffc5f19ede0 error 4 in libcontainer.so[7fe3fed95000+77000]
Nov 23 14:42:13 myhost kernel: omiagent[57427]: segfault at 10 ip 00007f3d70af4869 sp 00007ffcf7b88350 error 4 in libcontainer.so[7f3d70a95000+77000]

A collegue ran a gdb trace and i've attached it to the issue
[gdb.txt](https://github.com/Microsoft/OMS-Agent-for-Linux/files/611360/gdb.txt)

Posted this on the omi repo, but because this is a critical issue i posted it here also

**Comment by agup006** [comment]
Thanks mctsi,

If the docker provider is not installed do you still run into this issue?

Anurag

**Comment by mictsi** [comment]
Hi Anurag,

opened an issue with the azure oms group after talking to MS rep. 
The issue seems to be in docker cimprovider and they (Raghu Shanta) are developing a fix. 

Michael

**Comment by keikhara** [comment]
Hi Michael, 

that is my team that is working for this fix. 

Keiko

**Comment by raghushantha** [comment]
@mictsi has the updated bundle with the fix now.

Sharing the instructions for the updated bundle so that others can use this if they see a similar segfault

```
#Uninstall existing package (Centos) - Use Apt-Get or dpkg on Ubuntu:
sudo yum -y remove docker-cimprov.x86_64
 
#Download and install updated bundle
cd /tmp
sudo curl -O https://raghus.blob.core.windows.net/dockercimprovider/docker-cimprov-1.0.0-16.universal.x86_64.sh
sudo chmod u+x docker-cimprov-1.0.0-16.universal.x86_64.sh
sudo /tmp/docker-cimprov-1.0.0-16.universal.x86_64.sh --install
```

**Comment by keikhara** [comment]
Will close this per Michael's comment. See below: 

Ok, thanks Raghu
I just validated the cimprovider and it works fine. 
Thanks for the quick help Raghu, Jose and Keiko.                                  
I am off to vacation now, happy holidays and again thanks for the help.

/Michael
