### ISSUE TITLE
segment fault in docker container.

### ISSUE THREAD

**Issue by youngbupark** [Microsoft/OMS-Agent-for-Linux#300]
We're using DCOS as a container OS, but every node in the docker cluster shows the below segment fault errors in the log. any idea?

[37649.866296] omiagent[13741]: segfault at 10 ip 00007f645fbbc869 sp 00007fff3cbfaad0 error 4 in libcontainer.so[7f645fb5d000+77000]

[37681.862753] omiagent[13962]: segfault at 10 ip 00007f083abf6869 sp 00007ffccbd94220 error 4 in libcontainer.so[7f083ab97000+77000]

**Comment by raghushantha** [comment]
@youngbupark I have made a few reliability fixes lately to the Docker-Provider. Please try by updating the package.

```
#Uninstall existing package:
sudo yum -y remove docker-cimprov.x86_64
 
#Download and install updated bundle
cd /tmp
sudo curl -O https://raghus.blob.core.windows.net/dockercimprovider/docker-cimprov-1.0.0-16.universal.x86_64.sh
sudo chmod u+x docker-cimprov-1.0.0-16.universal.x86_64.sh
sudo /tmp/docker-cimprov-1.0.0-16.universal.x86_64.sh --install
```

**Comment by youngbupark** [comment]
@raghushantha thanks. I'm applying this to all OMS containers. We will take a look more.

**Comment by keikhara** [comment]
@youngbupark  
Have you tried the private which Raghu has provided? Is this the results from installing it? 
What docker version are you using?

**Comment by keikhara** [comment]
Duplicate with #369 Will close this.
