### ISSUE TITLE
Installer: Detection of architecture error prone

### ISSUE THREAD

**Issue by arvedarved** [Microsoft/OMS-Agent-for-Linux#313]
The get_arch() function currently uses uname for detecting if it is running 64bit. 

This does not detect if a 32bit userland is used with a 64bit kernel. Better solution: use `getconf LONG_BIG` which returns either 64 or 32.

**Comment by sugr4** [comment]
Closing this issue as this has been resolved in the latest agent release: omsagent-1.3.1-15
