### ISSUE TITLE
Multiple workspaces: version 1.3.0 download?

### ISSUE THREAD

**Issue by bfcamara** [Microsoft/OMS-Agent-for-Linux#348]
From where can I download the version mentioned in the Full Documentation (1.3.0)? The `master` branch mentions a version 1.3.0 in the docs but if I run the command copied from OMS Portal

```sh
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <worspace ID> -s <workspace Key> -d opinsights.azure.com
```
It downloads version 1.2.0-148, which doesn't support multiple workspaces.

If I try the command to list all the workspaces as mentioned in docs to 

```sh
sudo sh /opt/microsoft/omsagent/bin/omsadmin.sh -l
```
I got the error "Illegal option"

```sh
Illegal option -l

Maintenance tool for OMS:
Onboarding:
omsadmin.sh -w <workspace id> -s <shared key> [-d <top level domain>]

Heartbeat:
omsadmin.sh -b

Renew certificates:
omsadmin.sh -r

Define proxy settings ('-u' will prompt for password):
omsadmin.sh [-u user] -p host[:port]

Enable collectd:
omsadmin.sh -c

Azure resource ID:
omsadmin.sh -a <Azure resource ID>

```

**Comment by arvedarved** [comment]
Latest version offered in Azure is 1.3.12 

If you click on Connect in Log Analytics, the following is installed:

https://zrdfepirv2am5prdstr14a.blob.core.windows.net/8b23413e0ce64aa89889a295b6122112/Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.12.0

This github repo seems to be a bit out of date.....

**Comment by bfcamara** [comment]
Thank you. Yes, the repo seems out of date.
