### ISSUE TITLE
Documentation:  Add information to remove apache, mysql rpms

### ISSUE THREAD

**Issue by ChrisHeitkamp** [Microsoft/OMS-Agent-for-Linux#37]
Symptom:
According to documentation "Uninstalling the OMS Agent for Linux" the following must be run:
sudo rpm -e omi
This fails if provider rpms are installed:
error: Failed dependencies:
        omi >= 1.0.8-3 is needed by (installed) apache-cimprov-1.0.1-1.x86_64
        omi >= 1.0.8-3 is needed by (installed) mysql-cimprov-1.0.1-1.x86_64

Request to update documentation.

**Comment by jeffaco** [comment]
@agup006 Looks like our documentation needs to be updated.

Yeah, this is incorrect from our documentation. We have some uninstall scripts, but it looks like we didn't create one for omsagent itself, just for the opsmgr agent.

Given this, there are two ways to remove the OMS agent:

1. Via the shell bundle: Run the shell bundle (that you used to install oms) with the `--remove` qualifier or, if you never intend to run again on that system, run the shell bundle with the `--purge` qualifier to also remove workspace IDs and configuration scripts. If you want to see what options are available with the shell bundle, invoke it with the `--help` qualifier.

2. By hand (this is the equivalent of the --remove qualifier):
```
sudo rpm --erase omsconfig
sudo rpm --erase omsagent
sudo /opt/microsoft/scx/bin/uninstall
```

If we've answered your questions/concerns, please go ahead and close this issue. If you have further questions or concerns, ask away.

**Comment by agup006** [comment]
This has been added with the following commit https://github.com/Microsoft/OMS-Agent-for-Linux/commit/457f94413dc38310b71347224d440f7f1ebfbb44
