### ISSUE TITLE
Custom Log ingestion issue with noperm files

### ISSUE THREAD

**Issue by brandubh** [Microsoft/OMS-Agent-for-Linux#375]
Actually this is a bug you inherit from fluentd [#936](https://github.com/fluent/fluentd/issues/936)
When a custom log files is specified omsagent user doesn't have access to, the following log entry is recorded every second by the in_tail plugin:

> 2017-02-15 11:56:10 +0100 [error]: Permission denied @ rb_sysopen - /var/log/nginx/error.log
>   2017-02-15 11:56:10 +0100 [error]: suppressed same stacktrace

This fills the disk in a similar way of issue [#366](https://github.com/Microsoft/OMS-Agent-for-Linux/issues/366)

My 2c: either you fix the fluentd in_tail plugin, you write your own for custom log ingestion plugin, the DSC process checks for proper rights and fails if they're not there.

Daniele

**Comment by lagalbra** [comment]
@brandubh We have our own [sudo_tail plugin](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/source/code/plugins/in_sudo_tail.rb) to fix this.

Another way to handle it is to give the omsagent user permissions on that file, described at the bottom of our [MySQL logs doc](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-MySQL-Instructions.md).

**Comment by brandubh** [comment]
Hi lagalbra, as you can imagine is not so easy and bullet proof to change permissions across ten or hundreds of systems especially when logs are created by a software you con't have control on and thus can change permissions at any time. The sudo_tail plugin seems the correct answer to me and since you already have it, just set your own custom log ingestion configuration to use that instead of the standard in_tail. Does this make sense? I truly believe it is a minor mod for your DSC engine.

**Comment by lagalbra** [comment]
@brandubh I'm sorry, I misunderstood what exactly you meant by custom logs earlier in the thread. Custom Logs are in Private Preview in the OMS Portal at the moment, so they are not fully supported yet.

Additionally, allowing the use of the sudo_tail plugin also requires some modification of the sudoers file that the OMSAgent sets up. Because of this, it is a major security risk to allow the DSC engine to allow the reading of (dynamically) any restricted-access file.

Unfortunately, if you wish to collect this data, you will have to create your own plugin or alter the permissions on the files manually.

**Comment by brandubh** [comment]
Hi lagalbra, I respectfully disagree, I cannot see a security risk in configuring a log to be collected (once I'm the admin of the workspace), instead I see a serious disruption allowing me to configure something that is going to kill my linux boxes. But in the end it's your call.

**Comment by lagalbra** [comment]
We are currently making a DSC resource to replace the current custom log support to use our sudo_tail plugin instead of FluentD's in_tail plugin. This thread will be updated once that work is complete.

@sugr4

**Comment by lagalbra** [comment]
@brandubh Our sudo_tail plugin is now used in our CustomLog collection; you can verify this by reading the contents of this file: /etc/opt/microsoft/omsagent/<workspace-ID>/conf/omsagent.d/customlog.conf and checking that the line `type sudo_tail` is present.
