### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by ckotsidimos** [Microsoft/OMS-Agent-for-Linux#388]
I cannot download the sh files! My Workstation keeps reconnecting when using wget and also the site is not responding

Links not working: https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent-201610-v1.2.0-148/omsagent-1.2.0-148.universal.x64.sh

https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent-201610-v1.2.0-148/omsagent-1.2.0-148.universal.x86.sh

**Comment by sasukeh** [comment]
This links are working well now for me.
I could download sh file.
I think that would be happened by github website. 

Could you try again now?

**Comment by ckotsidimos** [comment]
Hi juts tried and it is OK! Sorry, time difference
