### ISSUE TITLE
Default source for syslog-ng

### ISSUE THREAD

**Issue by webbdog28** [Microsoft/OMS-Agent-for-Linux#404]
The default configuration for the omsagent using syslog-ng looks like this:

```
#OMS_facility = all
filter f_warning_oms { level(warning); };
destination warning_oms { tcp("127.0.0.1" port(25224)); };
log { source(src); filter(f_warning_oms); destination(warning_oms); };
```

However, the default syslog-ng config (syslog-ng.conf) has the source configured like this:
```
########################
# Sources
########################
# This is the default behavior of sysklogd package
# Logs may come from unix stream, but not from another machine.
#
source s_src {
       system();
       internal();
};
```
This means that in order to use the omsagent on machines with syslog-ng, we have to change either "s_src" to "src" or we have to change the default rules that the agent injects to use "s_src". Since "s_src" is the out of the box configuration for syslog-ng, can we change the omsagent to use that?

**Comment by NarineM** [comment]
This is officially not supported:  https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#sysklog-is-not-supported

**Comment by webbdog28** [comment]
This is not for sysklog. That snippet is copied directly from the syslong-ng.conf file, attached.

[syslog-ng.conf.txt](https://github.com/Microsoft/OMS-Agent-for-Linux/files/832161/syslog-ng.conf.txt)

**Comment by NarineM** [comment]
For syslog-ng , we are looking into it to add the support for the conf.

**Comment by NarineM** [comment]
Thanks for bringing this up.

**Comment by jschluchter** [comment]
@NarineM I think this could easily be added to a PR as it seems this is a bug and @webbdog28 has the exact fix stated above.

**Comment by NarineM** [comment]
@jschluchter ,
Hi Joey, thanks for the referenced. @webbdog28 can certainly send a PR request on this repo if he has the fix ready. Unfortunetly, I can not see this code to provide feedback, but I am happy to review it when the PR is ready.

**Comment by webbdog28** [comment]
I don't know if I have the right skills to submit a pull request but it seems like the fix would be in the configure_syslog.sh file on lines 129-132:

```
        local source=`grep '^source .*src' ${SYSLOG_NG_DEST} | cut -d ' ' -f2`
        if [ -z "${source}" ]; then
            source=src
        fi
```
I think changing "source=src" to "source=s_src" should be sufficient to work with default syslog_ng configurations.

**Comment by webbdog28** [comment]
Hi @NarineM, do you happen to have a timeline on when this issue will be fixed?

**Comment by NarineM** [comment]
With the next release. I can message you as soon as the fix is in master branch in case you need to try it out before official release comes out.

**Comment by webbdog28** [comment]
That would be fantastic. Thanks!

**Comment by NarineM** [comment]
@webbdog28 
@jschluchter 
This issue has been fixed by the following PR: https://github.com/Microsoft/PowerShell-DSC-for-Linux/pull/261

**Comment by webbdog28** [comment]
Awesome. Thanks!
