### ISSUE TITLE
Docker detection fails with new docker version scheme

### ISSUE THREAD

**Issue by fjollberg** [Microsoft/OMS-Agent-for-Linux#406]
$ docker --version
Docker version 17.03.0-ce, build 60ccb22

Installation of OMSAgent says:

"Checking if Docker is installed...
  The installed version of Docker is not supported. Version 1.8 or greater is required. Docker agent will not be installed."

See:
https://blog.docker.com/2017/03/docker-enterprise-edition/

**Comment by keikhara** [comment]
@fjollberg  

Hi Fredrik, let us get back to you on this. 

regards, 

Keiko

**Comment by fjollberg** [comment]
I'll give it a try.

**Comment by fjollberg** [comment]
Installs properly it seems, waiting for data.

**Comment by fjollberg** [comment]
Honestly don't quite get how all these pieces in omsagent fits together. Installation seems fine, it obviously talks to docker. However I don't see it actually doing anything.

Have tried to reconfigure to get logs to omsagent.log and see LINUX_PERF_BLOB entries but nothing about docker. 

It's pulling the configuration when I try GetDscConfiguration.py and PerformRequiredConfigurationChecks.py also catching other changes I make in OMS but I don't see anything about container solution in the result. Don't know if I should.

$ sudo bash docker-cimprov-1.0.0-19.universal.x86_64.sh --upgrade --force
Extracting...
Updating container agent ...
----- Updating package: docker-cimprov (docker-cimprov-1.0.0-19.universal.x86_64) -----
(Reading database ... 101976 files and directories currently installed.)
Preparing to unpack docker-cimprov-1.0.0-19.universal.x86_64.deb ...
Unpacking docker-cimprov (1.0.0.19) over (1.0.0.19) ...
Setting up docker-cimprov (1.0.0.19) ...
instance of Container_DaemonEvent
{
    [Key] InstanceID=824873a2-23b3-4d18-840d-884275111048
    ElementName=kthse/logspout-oms@sha256:1f09ec42877ce753ba9bc9643deb7148789304b781b84512d5b106893a28d8ae
    Computer=kth-integral-ref-1
    TimeOfCommand=1489705215
    Command=create
    Id=1e00ba179d0593013c02c531f0bd2d29460d7fe0b762f11d5abea2cacc570b54
    ContainerName=logspout.xnjqzn8ky79qrtvpd61jazegn.n71dufre1yc0wklctxu4mzsv2
}
...

**Comment by keikhara** [comment]
@fjollberg  We will be coming up with a patch version. Will keep you posted. Sorry for the wait.

**Comment by keikhara** [comment]
@fjollberg 

please try the following patch release. 
https://keiko.blob.core.windows.net/container/omsagent-1.3.2-15.universal.x64.sh  

thanks,

Keiko

**Comment by fjollberg** [comment]
So far, installed nicely, detects docker.

Still had problems actually getting any ContainerLog data into OMS. Eventually purged all workspaces with /opt/microsoft/omsagent/bin/omsadmin.sh -X and used omsadmin.sh to onboard again, after that the container solution started working.

**Comment by keikhara** [comment]
will close this case. We have released this now. https://github.com/Microsoft/OMS-Agent-for-Linux/releases
