### ISSUE TITLE
OMS likely doesn't restart it's service if it cores

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/OMS-Agent-for-Linux#426]
@lagalbra 

I'm not certain if you want bug reports here or elsewhere. If elsewhere, let me know for the future.

MDSD just raised an issue against [OMI](https://github.com/Microsoft/omi) service control, both with [upstart](https://github.com/Microsoft/omi/issues/267) and [systemctl](https://github.com/Microsoft/omi/issues/268). These are two separate issues.

The OMI team has decided to address these in the next release, v1.3. But given that I wrote the service control scripts for OMS, I think it's highly likely that OMS suffers from these same problems.

You should take a look at your service control scripts and be sure they properly handle restarting the agent if there is a core dump.

**Comment by lagalbra** [comment]
@jeffaco This is a fine place to report bugs.

@sugr4 Could you let me know if you can work on this?

**Comment by NarineM** [comment]
OMS agent already handles the scenarios where fluent is crashing, it will automatically launch a new instance of fluentd process.
