### ISSUE TITLE
Agent reports incorrect amount of Free Disk Space

### ISSUE THREAD

**Issue by yoanisgil** [Microsoft/OMS-Agent-for-Linux#430]
Hi,

We're considering using  OMS Agent for Linux to monitor our containers running on top of a K8s cluster and we've noticed that there is a significant discrepancy between the amount of reported free space and the actual free space. See images for below. 

Also note the the percentage of used space is correct.

Maybe I'm missing something obvious, which is why I'm just posting here.

OMI Agent version
```
root@omsagent-mmwn4:/opt# /opt/omi/bin/omiagent --version
/opt/omi/bin/omiagent: OMI-1.2.0-13 - Wed Mar 29 16:26:22 PDT 2017
```

OMI Server version
```
root@omsagent-mmwn4:/opt# /opt/omi/bin/omiserver -v
/opt/omi/bin/omiserver: OMI-1.2.0-13 - Wed Mar 29 16:26:22 PDT 2017
```

Actual Free Space
=============
![capture d ecran 2017-04-03 a 16 45 27](https://cloud.githubusercontent.com/assets/918271/24631359/f122d622-188d-11e7-90f1-a68c7ed0971e.png)

Reported Free Space
================
![capture d ecran 2017-04-03 a 16 45 06](https://cloud.githubusercontent.com/assets/918271/24631324/da4d47c0-188d-11e7-9414-57d67416cd44.png)

**Comment by lagalbra** [comment]
The OMSAgent uses OMI to obtain performance measurements from the machine, so I would recommend filing this as an issue on [the OMI repository here](https://github.com/Microsoft/omi/issues).

**Comment by yoanisgil** [comment]
Will do. Should we keep this open?

**Comment by lagalbra** [comment]
No, the OMI team will assign it back if need be.

**Comment by jeffaco** [comment]
This is actually against the wrong repository. OMI is a general framework, the actual provider that is providing this data is [SCXcore](https://github.com/Microsoft/SCXcore). That's where you'd need to open an issue. I closed the issue against the OMI repository, sorry.

That said, I think this may be a misunderstanding. Your reported free space from OMS is against the `_Total` instance, which is the total amount of free space on the entire system. Actual free space (that you circled) was against a specific disk, just /dev/sda1 (ignoring /dev/sdb1 and other disks that may be in your list).

[SCXcore](https://github.com/Microsoft/SCXcore) will return information on both specific instances and `_Total`, that reflects all file systems combined. I'm not sure if OMS shows individual instances, @lagalbra can comment on that.

**Comment by lagalbra** [comment]
Yes, OMS shows individual instances. It looks like the screenshot @yoanisgil included above has already been filtered with `_Total` as the `InstanceName`.

**Comment by yoanisgil** [comment]
That's totally correct. I'm now using this query:

`Type=Perf (CounterName="Free Megabytes") (InstanceName="/") | Measure Max(CounterValue) as FreeDiskSpace by Computer interval 30minute` 

which allows me to get available space on the root partition, after which I was able to successfully create an alert rule using that query.

Sorry about the confusion. 

Just wondering where I could have found this sort information and hence avoid bothering you guys?

Anyhow thanks for the excellent support! You responded damn quick and the information was accurate :).

Good work!

**Comment by lagalbra** [comment]
Configuration of performance counters is documented [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-linux-performance-counter-collection-from-the-oms-portal). Information is also available on Microsoft Docs [here](https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-linux-agents).
