### ISSUE TITLE
rsyslog/syslog-ng detection logic issue in configure_syslog.sh on SLES 11

### ISSUE THREAD

**Issue by hosungsmsft** [Microsoft/OMS-Agent-for-Linux#431]
On SUSE Linux Enterprise Server 11 (created on Azure), there seem to be both /etc/rsyslog.conf and /etc/syslog-ng/syslog-ng.conf, so configure_syslog.sh opts for rsyslog, but there's only syslog-ng, no rsyslog on the distro. Not sure if this is the Azure image specific, or SLES 11 in general, but it looks like the rsyslog/syslog-ng detection logic in configure_syslog.sh is not very reliable and needs to be fixed. Is this scenario not tested on your final tests, by the way?

```
ladtest-suse11:/opt/microsoft/omsagent/bin # cat /etc/issue

Welcome to SUSE Linux Enterprise Server 11 SP4  (x86_64) - Kernel \r (\l).


ladtest-suse11:/opt/microsoft/omsagent/bin # ls -l /etc/rsyslog.conf
-rw------- 1 root root 4084 Oct  6  2014 /etc/rsyslog.conf
ladtest-suse11:/opt/microsoft/omsagent/bin # ls -l /etc/syslog-ng/syslog-ng.conf 
-rw-r--r-- 1 root root 6962 Nov  6  2015 /etc/syslog-ng/syslog-ng.conf
ladtest-suse11:/opt/microsoft/omsagent/bin # sh configure_syslog.sh configure LAD 25224
Configuring rsyslog for OMS logging
Restarting service: rsyslog
service: no such service rsyslog
ladtest-suse11:/opt/microsoft/omsagent/bin # 
```

**Comment by hosungsmsft** [comment]
Sorry, it might be related to our previous logic on LAD. I'll investigate this further and reactivate if necessary. Closing this for now.

**Comment by root-locus** [comment]
I run into the same issue with Ubuntu. It uses `rsyslog` by default. I switched to `syslog-ng` by removing the package (not purging it). It leads that the conf directory stayed untouched, while daemon wasn't run. 
I think, it is better to add additional check for the running daemon in https://github.com/microsoft/OMS-Agent-for-Linux/blob/807e8e7583824013f48ffdc976d006183fd5752b/installer/scripts/configure_syslog.sh#L162 with `pidof syslog-ng` and `pidof rsyslogd`?
