### ISSUE TITLE
Security Baseline Assessment: failed rules list never updated

### ISSUE THREAD

**Issue by aiolfic** [Microsoft/OMS-Agent-for-Linux#448]
I am testing the "Security and Audit" solution using a Centos 6.3 VM. The initial list of failed rules is never updated even when the issue is resolved. 

Example: 
1) received a list of failed rules that includes CCE-4325-7  "SSH must be configured and managed to meet best practices. - '/etc/ssh/sshd_config Protocol = 2' ".
2) removed issue by manually fixing the Protocol entry in /etc/ssh/sshd_config
3) after 48h the failed rule is still present in the list

A manual run of the plugin returns a correct status.
/opt/microsoft/omsagent/plugin/omsbaseline -d  /etc/opt/microsoft/omsagent/conf/omsagent.d -a 106.1
{
    "baseline_id": "OMS.Linux.1",
    "base_orig_id": "1",
    "setting_count": 78,
    "scan_time": "2017-04-19T10:43:11.583127064+02:00",
    "results": [
        {
            "msid": "106.1",
            "result": "PASS",
            "error_text": "",
            "cceid": "CCE-4325-7",
            "severity": "Critical",
            "description": "SSH must be configured and managed to meet best practices. - '/etc/ssh/sshd_config Protocol = 2'",
            "ruleId": "35868e8c-97eb-4981-ab79-99b25101cc86"
        }
    ]
}

No errors reported in logs files.

**Comment by lagalbra** [comment]
@markwgit @mgladi Please take a look.

**Comment by markwgit** [comment]
Hi,
I need more information for investigation.

1. Could you please run following query on OMS Portal Search for the period before and after fix, export the results and send me?
Query: "Type=SecurityBaseline CceId=CCE-4325-7 Computer=<relevant Centos 6.3 VM name>"

2. Please send me screenshot of "Security Baseline Assessment" dashboard.

3. Do you have additional machines with the same problem? Did you fixed all machines? 

Thanks
Mark

**Comment by aiolfic** [comment]
1) Here is what I did:
	1.1 changed /etc/ssh/sshd_config back to unfixed rule i.e. "# Protocol = 2"
	1.2 restarted omsagent
	1.3 changed config file to fix the rule i.e. "Protocol = 2"
	1.4 restarted omsagent
SearchResults.csv contains 3 rows: scan at 1.4, scan at 1.3, last night scan.
The txt file (moreinfo.txt) contains more info: part of omsagent.log after the last scan and the output of the plugin when run using command line. The plugin seems to be able to check the rules without problems but we are not able see the related updates in the dashboard.
2)  Security Baseline Assessment Dashboard: png attached. Three rules marked in yellow not yet fixed.
3)  No additional Linux VM included in our test case. 

Pls let me know if you need more info.
Thanks.
C.

Da: Mark Waitser [mailto:notifications@github.com] 
Inviato: lunedì 24 aprile 2017 13:54
A: Microsoft/OMS-Agent-for-Linux <OMS-Agent-for-Linux@noreply.github.com>
Cc: aiolfic <camillo.aiolfi@newits.it>; Author <author@noreply.github.com>
Oggetto: Re: [Microsoft/OMS-Agent-for-Linux] Security Baseline Assessment: failed rules list never updated (#448)

Hi,
I need more information for investigation.
1. Could you please run following query on OMS Portal Search for the period before and after fix, export the results and send me?
Query: "Type=SecurityBaseline CceId=CCE-4325-7 Computer=<relevant Centos 6.3 VM name>"
2. Please send me screenshot of "Security Baseline Assessment" dashboard.
3. Do you have additional machines with the same problem? Did you fixed all machines?
Thanks
Mark
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Part of the agent log after the last run
------------------------------------------

  <source>
    type exec
    tag oms.security_baseline
    command sleep 60 && /opt/microsoft/omsagent/plugin/omsbaseline -d  /etc/opt/microsoft/omsagent/conf/omsagent.d/
    format json
  </source>
  <source>
    type exec
    tag oms.security_baseline
    command sleep 60 && /opt/microsoft/omsagent/plugin/omsbaseline -d /etc/opt/microsoft/omsagent/conf/omsagent.d/
    format json
    run_interval 24h
  </source>
  <filter oms.security_baseline>
    type filter_security_baseline
    log_level info
  </filter>
                                               ....
2017-04-24 15:55:01 +0200 [info]: Security Baseline Summary: {"DataType"=>"SECURITY_BASELINE_SUMMARY_BLOB", "IPName"=>"Security", "DataItems"=>[{"Computer"=>"newits", "TotalAssessedRules"=>56, "CriticalFailedRules"=>12, "WarningFailedRules"=>1, "InformationalFailedRules"=>0, "PercentageOfPassedRules"=>77, "AssessmentId"=>"7ee91eb4-0729-4c6a-9396-5e64c7a57662", "OSName"=>"Linux", "BaselineType"=>"Linux"}]}
                                               





--------------------------------------------------
No fix --> "#Protocol = 2" in /etc/ssh/sshd_config 

/opt/microsoft/omsagent/plugin/omsbaseline -d /etc/opt/microsoft/omsagent/conf/omsagent.d/ -a 106.1
{
    "baseline_id": "OMS.Linux.1",
    "base_orig_id": "1",
    "setting_count": 78,
    "scan_time": "2017-04-24T15:46:51.684842503+02:00",
    "results": [
        {
            "msid": "106.1",
            "result": "FAIL",
            "error_text": "File /etc/ssh/sshd_config should contain one or more lines matching ['^[\\s\\t]*Protocol\\s+2$']",
            "cceid": "CCE-4325-7",
            "severity": "Critical",
            "description": "SSH must be configured and managed to meet best practices. - '/etc/ssh/sshd_config Protocol = 2'",
            "ruleId": "35868e8c-97eb-4981-ab79-99b25101cc86"
        }
    ]
}

-----------------------------------------------
Fixed:  "Protocol = 2" in /etc/ssh/sshd_config

/opt/microsoft/omsagent/plugin/omsbaseline -d /etc/opt/microsoft/omsagent/conf/omsagent.d/ -a 106.1
{
    "baseline_id": "OMS.Linux.1",
    "base_orig_id": "1",
    "setting_count": 78,
    "scan_time": "2017-04-24T15:52:15.580359011+02:00",
    "results": [
        {
            "msid": "106.1",
            "result": "PASS",
            "error_text": "",
            "cceid": "CCE-4325-7",
            "severity": "Critical",
            "description": "SSH must be configured and managed to meet best practices. - '/etc/ssh/sshd_config Protocol = 2'",
            "ruleId": "35868e8c-97eb-4981-ab79-99b25101cc86"
        }
    ]
}

**Comment by markwgit** [comment]
Hi,

I cannot see attached files. 
Please add attached files via github portal.

Please run following query on OMS Portal Search for the period before and after fix, export the results and attached .
Query: "Type=SecurityBaseline CceId=CCE-4325-7 Computer=<relevant Centos 6.3 VM name>"

Thanks
Mark

**Comment by aiolfic** [comment]
Sorry, files added to my last message.
C.

**Comment by markwgit** [comment]
Hi,

Let scheduler online conversation.
Please contact me by markwai@microsoft.com

Thanks

**Comment by markwgit** [comment]
The problem was found: On some Linux distribution the file "/etc/ssh/sshd_config" has only 600 (-rw-------) access permissions.
Fix: Change permission of "/etc/ssh/sshd_config" to 644 (-rw-r--r-- ) by following command: sudo chmod 644 /etc/ssh/sshd_config.

**Comment by aiolfic** [comment]
Tested. It works.
Thanks.
