### ISSUE TITLE
omsagent --install -w <workdpace id> -s <shared key> don't include container.conf by default

### ISSUE THREAD

**Issue by guesslin** [Microsoft/OMS-Agent-for-Linux#462]
I first install and onboarding omsagent by fellowing step:
```
curl -L -O https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent-201704-v1.3.3-15/omsagent-1.3.3-15.universal.x64.sh
chmod +x omsagent-1.3.3-15.universal.x64.sh
sudo ./omsagent-1.3.3-15.universal.x64.sh --install -w <WorkspaceID> -s <Shared Key>
```

but the `container.conf` does show up in `/etc/opt/microsoft/omsagent/<workspace id>/conf/omsagent.d/`.

But if I try fellowing step:
```
curl -L -O https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent-201704-v1.3.3-15/omsagent-1.3.3-15.universal.x64.sh
chmod +x omsagent-1.3.3-15.universal.x64.sh
sudo ./omsagent-1.3.3-15.universal.x64.sh --install 
sudo /opt/microsoft/omsagent/bin/omsadmin.sh -w <WorkspaceID> -s <Shared Key>
```

then `container.conf` file will show up in `/etc/opt/microsoft/omsagent/<workspace id>/conf/omsagent.d/`

**Comment by lagalbra** [comment]
@guesslin Because of our installation process involving Docker, the second process is the current workaround for this situation.

@samisms @keikhara Can you confirm the suggested workaround for this? Is there an estimated timeline for resolving this?

**Comment by keikhara** [comment]
@guesslin Yes there is a workaround for this. Please go here. 
https://github.com/Microsoft/OMS-docker/blob/master/ReleaseNote.md 

Go to the bottom of the documentation.

**Comment by keikhara** [comment]
@guesslin we will be fixing this soon. We will keep you noted.

**Comment by NarineM** [comment]
Hi , can you move docker related issue (if this issue has not already been addressed) to docker provider GitHub repo ? thanks.
