### ISSUE TITLE
Virtual Machine run out of disk space alert

### ISSUE THREAD

**Issue by riyazlafir** [Microsoft/OMS-Agent-for-Linux#464]
Hi , 
I'm new to OMS .  want to make Alert notification before getting  run out of disk space . I have linux virtual machine in azure .  need to monitor disk usage and and make alert if given threshold exceed using OMS . 

Do I need to install agent in my linux machine ?

thanks in advanced.

**Comment by lagalbra** [comment]
Yes, to allow OMS to monitor performance counters like disk space, you will need to install the OMSAgent on your Linux machine. See [here](https://github.com/Microsoft/OMS-Agent-for-Linux/tree/master#quick-install-guide) for our quick install steps, and [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#steps-to-install-the-oms-agent-for-linux) for more detailed installation steps.

**Comment by riyazlafir** [comment]
Thank you @lagalbra for your valuable reply.  followed above steps and I got this out put                                                 
`Checking host architecture ...
Checking for ctypes python module ...
Extracting...
Updating OMS agent ...
----- Checking package: omsagent (omsagent-1.3.4-15.universal.x64) -----
Skipping package since existing version >= version available
Checking for ctypes python module ...
----- Checking package: omsconfig (omsconfig-1.1.1-438.x64) -----
Skipping package since existing version >= version available
Extracting...
Updating cross-platform agent ...
----- Upgrading package: omi (omi-1.2.0-35.ulinux.x64) -----
Skipping package since existing version >= version available
----- Upgrading package: scx (scx-1.6.3-212.universal.x64) -----
Skipping package since existing version >= version available
----- Updating bundled packages -----
Checking if Apache is installed ...
  Apache not found, will not install
Checking if MySQL is installed ...
  MySQL not found, will not install
----- No base kits to update -----
----- Updating bundled packages -----
Checking if Docker is installed...
  Docker not found. Docker agent will not be installed.
Shell bundle exiting with code 0 `      how can I make disk out of space alert . I have searched all over the internet but I didn't received proper document for this .  If you can please let me know any document related to disk space alert with OMS.

thanks .

**Comment by keikhara** [comment]
Hi @riyazlafir, 

Can you please confirm whether your linux agent is on-boarded to OMS workspace? 
please type the following command 

/opt/microsoft/omsagent/bin/omsadmin.sh -l 
If you are successfully on-boarded, you will see the output Sucess. 

Next, here's a doc on Alerting. Once you have on-boarded and you see data on OMS, please go to log search pane. You can pass a search query in the log search pane to filter data on what you want to be alerted, Once you have that query and see the results, on the top lefthand side, you will see the Alert Icon. Press that and you will go to the Alert page. See more information on the doc below. 
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-alerts 

thanks,

Keiko

**Comment by riyazlafir** [comment]
Hi Keiko , 
 thanks for the reply . I got this out put `Status: Onboarded(OMSAgent Running)`  when I run above commmand . and I wrote log search query `* Type=Perf (ObjectName="Logical Disk") (CounterName="% Used Space")`  but actually I need to make alert when this "% Used Space"  value exceed the 85% of disk space. 

thanks.

**Comment by keikhara** [comment]
For the query, you can also do the following:
https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-search-reference

Go to the field faucets section.
You can do the field<=value.

You can specify disk space which is beyond 85% to notify you.

Regards,

Keiko

**Comment by riyazlafir** [comment]
Thank you @keikhara  and @lagalbra .
