### ISSUE TITLE
The OMS installation script fails when /tmp is mounted noexec

### ISSUE THREAD

**Issue by jeffearl** [Microsoft/OMS-Agent-for-Linux#476]
The installation script attempts to run Python script from a temporary file (created with mktemp) to validate the ctypes library. If /tmp is mounted noexec for security hardening, the installer fails with exit code 61.

**Comment by lagalbra** [comment]
@jeffearl Can you provide the OMSAgent shell bundle version you are using to install? Our [latest agent release ](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent-201705-v1.3.4-127)(version 1.3.4-127) should resolve this issue.

**Comment by jeffearl** [comment]
Thanks!  I'm just using the one supplied by the Azure portal when selecting the option to connect a VM to OMS. It's not the latest version-the script is "omsagent-1.3.4-15.universal.x64.sh". Looking at the code for 1.3.4-127, though, it appears to have the same issue. I'll test it shortly and let you know my findings.

**Comment by jeffearl** [comment]
The latest version indeed fixes the issue.  Duhhhh--now I see the ctypes check #2.  Any Idea when -127 will be used by the Azure portal? Many thanks.

**Comment by lagalbra** [comment]
@jeffearl 1.3.4-127 will be released in the Azure portal sometime this week or next. We are syncing this action with releasing the new agent version through the OmsAgentForLinux Azure VM Extension.

**Comment by jeffearl** [comment]
I may have spoken too soon. The ctype library discovery has been fixed in the main installer script of 1.3.4-127. However, the issues it appears again in a later phase of the installation when configuring the OMS agent service:

> Configuring rsyslog for OMS logging
Restarting service: rsyslog
Configuring OMS agent service ...
-bash: /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py: No such file or directory
info    Configured omsconfig
System appears to have SELinux installed, attempting to install selinux policy module for logrotate
  Trying /usr/share/selinux/packages/omsagent-logrotate/omsagent-logrotate.pp ...
Checking for ctypes python module...Error: Python does not support ctypes on this system.  Please install the ctypes module for Python or upgrade to a newer version of             python that comes with the ctypes module.
Please remove the omi package and try again after installing the ctypes module or upgrading Python.  You can check if the ctypes module is installed by starting python             and running the command: 'import ctypes'
error: %pre(omsconfig-1.1.1-534.x86_64) scriptlet failed, exit status 1
error: omsconfig-1.1.1-534.x86_64: install failed

>
I think the rpm package called "omsconfig-1.1.1-534.x64.rpm" containing code that fails the ctypes discovery. If I remount /tmp with the exec option, I can successfully install this rpm package--otherwise it fails.

**Comment by lagalbra** [comment]
We are currently working on resolving this; I'll update this thread when a fix (apart from remounting /tmp) is available.

**Comment by lagalbra** [comment]
@jeffearl Our release 1.3.5-127 should resolve this. Please install and let us know if it still fails.
https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent-201705-v1.3.5-127

**Comment by NarineM** [comment]
@jeffearl 
This issue has been fixed in master branch and the fix has been released in version# 1.3.5-127. Closing as resolved.

**Comment by jeffearl** [comment]
Thanks all. I've confirmed that release 1.3.5-127 indeed fixes the issue.

**Comment by lagalbra** [comment]
Thank you for raising this issue to our attention. I'm glad to verify that the solution fixed your issue!
