### ISSUE TITLE
Docker container log stops collecting

### ISSUE THREAD

**Issue by kevinlisota** [Microsoft/OMS-Agent-for-Linux#495]
I have two VM's and 4 docker containers being monitored by OMS.

When I start a container, it sends containerlog data to OMS for about a day and then randomly stops sending it.

The containers are still running fine and the VM hosts continue to report their stats to OMS.

How can I troubleshoot/fix this issue?

**Comment by lagalbra** [comment]
Please open this issue on the OMS Docker GitHub page: https://github.com/Microsoft/OMS-docker/issues
