### ISSUE TITLE
omiagent keep consuming high memory

### ISSUE THREAD

**Issue by guesslin** [Microsoft/OMS-Agent-for-Linux#498]
<img width="1050" alt="screen shot 2017-06-15 at 11 24 27 am" src="https://user-images.githubusercontent.com/69355/27164124-500770b2-51be-11e7-91a4-059dc1f58fe1.png">

OMS Agent version: omsagent-1.3.3-15.universal.x64
OS: 4.4.0-28-generic
Cloud Env: Azure ACS

We setup the omsagent by running `sudo ./omsagent-1.3.3-15.universal.x64.sh --install -w <WorkspaceID> -s <Shared Key>` 29 days ago. But since last 24 hours, we got a memory alert for one agent in our cluster.

**Comment by lagalbra** [comment]
@guesslin 
To debug the problem, run these steps:
1. Turn on logging in omi by editing /etc/opt/omi/config/omiserver.conf and set LOGLEVEL=DEBUG
2. Restart OMI service: `sudo /opt/omi/bin/service_control restart`
3. Send relevant information from the log files in /var/opt/omi/logs. There is one for each agent, and one for the server.
4. Also send errors from /var/opt/microsoft/scx/log/omsagent/scx.log and /var/opt/microsoft/omsagent/log/omsagent.log and /var/opt/microsoft/omsconfig/omsconfig.log

Mitigation step you can try:
- Upgrade to the latest version of the OMSAgent (1.3.5-127): `wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <WorkspaceID> -s <Shared Key>`

**Comment by sbadakhc** [comment]
Hi, we are seeing this with the latest version. Attempting to stop the agent results in a restart when I try use service_control and systemctl. Is there a way I can prevent the agent from restarting?

**Comment by lagalbra** [comment]
If you are trying to stop the `omiagent`, direct your questions about service control behavior to the [OMI repo](https://github.com/Microsoft/omi). If you are trying to stop the `omsagent` service running, the easiest way is to use `sudo sh /opt/microsoft/omsagent/bin/service_control disable`

**Comment by sbadakhc** [comment]
Thanks.

**Comment by NarineM** [comment]
@guesslin 
Can you provide some details about which solutions are enabled in your workspace? Similar issue was fixed in latest version of omsagent 1.4.0-45, you can try upgrading your agent to that version and see if you still see high CPU or not? If you still see this issue occurring in latest build for your environemnent, please attach omsconfig.log, omsagent.log.

**Comment by sylr** [comment]
![omsagent-ram](https://user-images.githubusercontent.com/153052/30695954-4b705a82-9eda-11e7-9406-3591fc424fe5.PNG)

I have the same issue with 1.4.1.45 :

```
cloudinframaster@k8s-master-62103606-0:~$ dpkg -l | grep omsagent
rc  omsagent                           1.4.1.45                                   amd64        Microsoft Operations Management Suite for UNIX/Linux agent
```

This is very unpleasant.

**Comment by lagalbra** [comment]
As Narine previously stated, if you are seeing this issue, please provide these logs:

- /var/opt/microsoft/omsagent/log/omsagent.log
- /var/opt/microsoft/omsconfig/omsconfig.log
- All files under /var/opt/omi/log/

**Comment by nphmuller** [comment]
Also having this issue. The process used about 350MB, which made the kernel kill our elasticsearch process.
Would love to provide logs, but is there any place where I can privately send them, because of confidential data? Thanks.

**Comment by lagalbra** [comment]
If you don't wish to share your logs in this forum, please email them to omslinuxteam@microsoft.com and reference this GitHub issue.

**Comment by DeV1L** [comment]
Have the same problem on all Linux servers where I installed the agent.
```
$ uname -r
3.10.0-693.2.2.el7.x86_64
$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
$ rpm -qa | grep omsagent
omsagent-1.4.1-45.x86_64
```
![Memory](https://i.stack.imgur.com/GD0vc.jpg)

I've sent the logs to omslinuxteam@microsoft.com

**Comment by DeV1L** [comment]
Your message to omslinuxteam@microsoft.com couldn't be delivered.
--
The group omslinuxteam   only accepts messages from people in its organization or on its allowed   senders list, and your email address isn't on the list.

**Comment by lagalbra** [comment]
Interesting, I was not aware of that shortcoming. I've corrected my comment, and suggest you send the logs to lagalbra@microsoft.com, narinem@microsoft.com, and keikhara@microsoft.com.

**Comment by AaronFriel** [comment]
I would really like to see some major changes to the Linux OMI agent that installs by default on Azure. I've taken to disabling the agent service entirely because on my server with multiple containers, a webserver, an entire Gitlab omnibus, and so on, this is what is using the most CPU time:

![image](https://user-images.githubusercontent.com/788800/31778795-25f08974-b4b7-11e7-853d-00742e954814.png)

Over uptime of 10.5 hours, about 1/4 of the time one core was spent doing... what?

**Comment by rocketraman** [comment]
Also had this problem today:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
50313 root      20   0 4830200 3.650g   1700 R  85.4 53.7   1553:35 omiagent
```

**Comment by goranjovanovic25** [comment]
Also had this problem today on one of the Service Fabric Linux nodes:

![screen shot 2017-11-30 at 3 18 11 pm](https://user-images.githubusercontent.com/25062428/33463778-3696edc8-d5f4-11e7-9ba0-2e4db18c7ab3.png)

**Comment by rocketraman** [comment]
Had this issue again today. Sent logs to email addresses above.

@goranjovanovic25 looks like your problem is high CPU usage, not high memory usage. If you search, you will find other GitHub issues with omiagent + high CPU.

**Comment by NarineM** [comment]
There is a new release coming up on January 22 that has new OMI 1.4.1 which has memory leak related bug fixes. Can you try the new version once it is available to see if it resolves it? 
Note that omiagent process related issues need to be created on omi provider repo on GitHub in the future.

**Comment by rocketraman** [comment]
Installing this version manually as per the instructions here solved the problem for me: https://github.com/Microsoft/Docker-Provider/issues/32#issuecomment-360368516

**Comment by rocketraman** [comment]
See my comment here: https://github.com/Microsoft/Docker-Provider/issues/32#issuecomment-368206146 -- looks like Azure just destabilized my systems again by installing a new version of OMI agent, which is still using a broken version of docker-cimprov 1.0.0.27, even though I had manually installed the fixed newer version 1.0.0.30.

@lagalbra @NarineM @keikhara come on guys, two questions: 1) why is this taking so long to get the updated docker-cimprov from @samisms integrated and shipped, and 2) why would the install script downgrade the version on people's systems?

**Comment by NarineM** [comment]
@rocketraman , hi , there is a separate docker repo for reporting docker related bugs, this repro is only tacking omsagent related issues. Please follow up on the docker provider GitHub page instead. thanks,

**Comment by NarineM** [comment]
Closing this issue. CPU or memory leaks coming from omiagent process need to be reported on powershell DSC or docker/container GitHub repositories depending on which component is causing the issue.

**Comment by rocketraman** [comment]
@NarineM The issue was already reported there and fixed, but the fix is not included in the latest version that was just deployed (see https://github.com/Microsoft/Docker-Provider/issues/32#issuecomment-368206146).

**Comment by NarineM** [comment]
Yes, all docker related issues need to be filed on docker GitHub repo. Sorry, but this repo is not tracking or looking into docker related issues. thanks.
