### ISSUE TITLE
Upgrade extension to use GA version of the agent

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Microsoft/OMS-Agent-for-Linux#503]
The extension installs public preview bits (1.1.0-217).  Can the extension be upgraded to deploy one of the recent GA releases?

**Comment by lagalbra** [comment]
@SenthuranSivananthan Please use [our Docs.Microsoft.com page](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-oms) as a guide to installing the OmsAgentForLinux Azure VM Extension. This is the latest documentation, which states that the latest version of the extension is 1.3. This will install OMSAgent package version 1.3.5-127.

The Azure VM Extension documentation in this repository will be updated to reflect the most recent version.

**Comment by SenthuranSivananthan** [comment]
Thanks @lagalbra for the quick turnaround.  Switching TypeHandlerVersion to 1.3 did the trick.

On docs.microsoft.com, should the instruction for CLI refer to 1.3 instead of 1.0?
  Please see:  https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-oms#azure-cli-deployment

**Comment by lagalbra** [comment]
Yes, that version should be 1.3; that documentation will be updated. Thank you for pointing that out!
