### ISSUE TITLE
Installed latest OMS version, not showing connected in Azure Portal

### ISSUE THREAD

**Issue by clintonm9** [Microsoft/OMS-Agent-for-Linux#52]
When using the Azure Portal to connect a VM to OMS it says connecting and installs version 1.0.0.3. (click OMS Workspace, Click Virtual machines, click on VM, then click connect). After this the Log Analytics management shows 1 connected VM.

When I manually use the shell script and installed version 1.1.0-28 it works, but says No connected under OMS Connections.

Any ideas? Thanks

**Comment by JustLoy77** [comment]
Are u using a dial up, broadband, or DSL? Is the other network device on the network using wifi, hify or cable connection. If cable what category are they. I suggest using an 2.0 USB flash drive w/ a hify connections

clintonm9 <notifications@github.com> wrote:



When using the Azure Portal to connect a VM to OMS it says connecting and installs version 1.0.0.3. (click OMS Workspace, Click Virtual machines, click on VM, then click connect). After this the Log Analytics management shows 1 connected VM.

When I manually use the shell script and installed version 1.1.0-28 it works, but says No connected under OMS Connections.

Any ideas? Thanks

-

**Comment by agup006** [comment]
Hi @clintonm9, we have known issues with the OMS Agent for Linux installing on top of a Azure Linux IaaS VM with the "Add Connection" option, we are prepping a new release that should go out shortly to fix that. 

For the manual onboarding is the file omsadmin.conf present in the `/etc/opt/microsoft/omsagent/conf/` directory?

**Comment by clintonm9** [comment]
@agup006 the manual onboarding works for me, but the VMs are not showing up in the Azure portal as Connected VMs.

Looking at MOI I do see 12 servers connected. Looking at Azure I only see 1 and the rest say not connected. It's not a big deal, just didn't know if there was a way for them to show connected.

**Comment by jeffaco** [comment]
I'm assuming the new version will resolve your issue, so I'll close this issue out. If you have further problems in this area, please feel free to re-open this issue with more information.

**Comment by arvedarved** [comment]
same here. omsagent-1.2.0-148; onboardings works. Data shows up in Log Analytics, but Virtual machine is reported as "Not connected" in Azure Portal

**Comment by cricketfan5** [comment]
@jeffaco Hi, I am trying to install the omsagent as a kubernetes daemonset on COREOS host by passing the WSID and key. I see the agent is onboarded successfully but when I see in the portal it is showing as WORKSPACE NAME as unknow. Can you please help me in figuring the issue ?. Thanks

**Comment by jeffaco** [comment]
Neither @agup006 or myself are involved with OMS anymore. @NarineM can you help?

**Comment by agup006** [comment]
+ @keikhara

**Comment by cricketfan5** [comment]
Thanks for the response.  @jeffaco @agup006
