### ISSUE TITLE
High CPU usage by omiserver

### ISSUE THREAD

**Issue by johanburati** [Microsoft/OMS-Agent-for-Linux#536]
Hi,

We had a problem with a VM where the cx notice high CPU usage by the omiserver process,
the cx remediate the situation by rebooting his VM.

Looking at the omiserver.log below there a lot of error message at that exact time related to getpwnam,
can you tell me what is the cause of the error, what is the impact and  if there is anything that can be done to prevent it from occurring again ? 

Also the cx is using omiserver v1.2, should he upgrade to 1.3 ?

```
$ /opt/omi/bin/omiserver --version
/opt/omi/bin/omiserver: OMI-1.2.0-35 - Thu Mar  2 17:03:20 PST 2017
```

Thanks,
Johan

Full log: [omiserver.log](https://gist.githubusercontent.com/johanburati/d23a99f8b7bc9938b1ba81d008a6cfcf/raw/f218aa20c348b7357c56dce5d760cd3b93bf54eb/omiserver.log)
```
WARNING: null(0): EventId=30072 Priority=WARNING getpwnam_r filed, errno 24
WARNING: null(0): EventId=30071 Priority=WARNING get user [root] uid/gid
```

**Comment by lagalbra** [comment]
Can you please send all logs from `/var/opt/omi/log/`? There will be one for each agent using omiserver, and one for the server.
Send also this log: `/var/opt/microsoft/scx/log/omsagent/scx.log`
The cause of the error is unknown without these logs. Many providers utilize the omiserver.
Do you have Docker on this particular VM?

**Comment by johanburati** [comment]
Hi @lagalbra, in the /var/opt/omi/log/ there is only two files, [omiserver.log](https://gist.githubusercontent.com/johanburati/d23a99f8b7bc9938b1ba81d008a6cfcf/raw/f218aa20c348b7357c56dce5d760cd3b93bf54eb/omiserver.log) and the other one `omiagent.root.root.log` is empty.

As for the [scx.log](https://gist.githubusercontent.com/johanburati/6cebcd22568ef37c54c1920d561450ea/raw/76acf4ecd49fb9272d1146cdd4dd410a1134c9cc/scx.log), I found it in `/var/opt/microsoft/scx/log/scx.log`, there is no `omsagent` directory.

Docker is not running on this VM, please let me know your findings.

**Comment by lagalbra** [comment]
Given that the Docker provider is not present, I suspect a DSC provider may be at fault. Please [file this issue on the DSC repo](https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues); include the logs that you linked here and any OMS solutions you are using.
On the DSC repo issue you open, it may be worth noting that there are [many instances of code in DSC calling getpwnam](https://github.com/Microsoft/PowerShell-DSC-for-Linux/search?utf8=%E2%9C%93&q=getpwnam&type=).

**Comment by niltonvasques** [comment]
Same problem here: 

![image](https://user-images.githubusercontent.com/2291529/29438485-74518434-838d-11e7-94fa-7a96de4975dd.png)

**Comment by m-ghaoui** [comment]
Turns out that omiserver has been running the cpu of our virtual Linux machine for several weeks now!

![image](https://user-images.githubusercontent.com/481297/31220014-688c2a20-a9bf-11e7-8b95-bc554b06ef86.png)

We're not happy about this because it's incurring unnecessary costs!

**Comment by m-ghaoui** [comment]
This is not funny, Microsoft!

![image](https://user-images.githubusercontent.com/481297/31220449-c66978d6-a9c0-11e7-9f20-c535dca02a20.png)

**Comment by lagalbra** [comment]
@m-ghaoui Please use the issue in the DSC repo: https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues/301

**Comment by oncloudtraining** [comment]
Can we monitor omni agent from VM insight ?
