### ISSUE TITLE
Memory growing if OMSConsistencyInvoker cron job is stuck

### ISSUE THREAD

**Issue by primegonzola** [Microsoft/OMS-Agent-for-Linux#543]
Hi,

At times we see the cron job being stuck executing runs  /bin/sh -c /opt/omi/bin/OMSConsistencyInvoker >/dev/null 2>&1

The process never dies and starts piling up. Is this a known issue? How can we debug why the cron job is hanging?

The workaround is doing a service omid restart but we would like to know more what could be causing this and if this is a known issue.

Thanks

**Comment by lagalbra** [comment]
See issue https://github.com/Microsoft/OMS-Agent-for-Linux/issues/511
