### ISSUE TITLE
OMS agent is removing existing DSC providers from /opt/omi/lib during omi upgrade.

### ISSUE THREAD

**Issue by BerheAbrha** [Microsoft/OMS-Agent-for-Linux#549]
Existing DSC installed from (https://github.com/Microsoft/PowerShell-DSC-for-Linux/releases/tag/v1.1.1-70)  stopped working after installing latest OMS extension . 
** NOTE **  This does not happen if the upgrade is from later version of DSC.

Steps to repro:-
 1.  Deploy Azure VM using a template.
  2.  Install DSC from feb release
 * Starting Open Group OMI Server:                                                                                                                                                                                                    [ OK ]
 root@berhaU:/home/berheU# dpkg -s dsc
 Package: dsc
 Status: install ok installed
 Priority: optional
 Section: utils
 Installed-Size: 8870
 Maintainer: Microsoft
 Architecture: amd64
 Source: dsc
 Version: 1.1.1.70
 Provides: dsc
 Depends: omi (>= 1.0.8-3)
 Description: Windows Powershell Desired State Configuration for Linux
 Windows Powershell Desired State Configuration for Linux
 root@berhaU:/home/berheU# dpkg -s omi
 Package: omi
 Status: install ok installed
 Priority: optional
 Section: utils
 Installed-Size: 14111
 Maintainer: The Open Group
 Architecture: amd64
 Source: omi
 Version: 1.0.8.6
 Provides: omi
 Depends: libc6 (>= 2.3.6), libpam-runtime (>= 0.79-3)
 Conffiles:
 /etc/opt/omi/conf/omiserver.conf c919d89cd81a35e2d8a7fc8db663d1ea
 Description: Open Management Infrastructure
 omi server
 
1.  Now update the existing template  to add OMS agent for Linux  and re-deploy
 
 This will upgrade the OMI version as follow
 
 root@berhaU:/opt/omi/lib# dpkg -s omi
 Package: omi
 Status: install ok installed
 Priority: optional
 Architecture: amd64
 Source: omi
 Version: 1.2.0.35
 Provides: omi
 Depends: libc6 (>= 2.3.6), libpam-runtime (>= 0.79-3)
 Conffiles:
 /etc/opt/omi/conf/omiserver.conf a90be1a82e34914d9ab3e3e005463752
 Description: Open Management Infrastructure
 omi server
  1.  It will also remove some of the DSC Linux resources form Opt/omi/lib ( Same as the reported issue).
 

> root@berhaU:/opt/omi/lib# ls
> libcrypto.so.1.0.0
> libcurl.so.3
> libcurl.so.4
> libdsccore.so
> libmicxx.so
> libmi.so
> libMSFT_nxAvailableUpdatesResource.so
> libMSFT_nxFileInventoryResource.so
> libMSFT_nxGroupResource.so
> libMSFT_nxOMSAuditdPluginResource.so
> libMSFT_nxOMSAutomationWorkerResource.so
> libMSFT_nxOMSCustomLogResource.so
> libMSFT_nxOMSGenerateInventoryMofResource.so
> libMSFT_nxOMSKeyMgmtResource.so
> libMSFT_nxOMSPerfCounterResource.so
> libMSFT_nxOMSPluginResource.so
> libMSFT_nxOMSSudoCustomLogResource.so
> libMSFT_nxOMSSyslogResource.so
> libMSFT_nxPackageResource.so
> libMSFT_nxServiceResource.so
> libMSFT_nxUserResource.so
> libomiclient.so
> libomiidentify.so
> libomsconfig.so
> libSCXCoreProviderModule.so
> libssl.so.1.0.0

**Comment by lagalbra** [comment]
Email thread is still ongoing for this issue.

**Comment by Indhukrishna** [comment]
Opened an issue on https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues/312
