### ISSUE TITLE
How to exclude this agent from new azure virtual machines

### ISSUE THREAD

**Issue by darinhoward** [Microsoft/OMS-Agent-for-Linux#553]
How do I setup a Linux VM (Ubuntu) without having this agent installed?

**Comment by lagalbra** [comment]
There are several ways that our agent can get installed on a new Azure VM.
1. Through Azure Security Center: Disable Azure Security Center data collection for the subscription in which you will create new VMs: see "How do I disable data collection?" on this page: https://docs.microsoft.com/en-us/azure/security-center/security-center-faq
2. Manually; but by your question, I'm assuming you did not choose to install either the OmsAgentForLinux Azure VM extension or the OMSAgent through our shell bundle.

**Comment by NarineM** [comment]
@darinhoward 
Please see Azure Security latest migration related article: https://docs.microsoft.com/en-us/azure/security-center/security-center-platform-migration

There is a link to support team you can forward your question. This repro is not monitored by ASC team.
