### ISSUE TITLE
OMS Agent pushes custom log entries from random positions after restart

### ISSUE THREAD

**Issue by koksan83** [microsoft/OMS-Agent-for-Linux#555]
Issue description:  

OMS Agent appears to start pushing custom logs from the top or random positions after VM restart or OMS Agent restart.  
Issue is made worse when timestamps in log files are in local time and we are forced to use newline as the delimiter instead.

Steps to reproduce the issue:  
1. Configure a custom log using newline as delimiter
2. Wait for log entries to appear in OMS Portal
3. Restart VM or restart OMS Agent via `/opt/microsoft/omsagent/bin/service_control restart`
4. Observe entries in OMS Portal

What's the expected result?  

OMS Agent starts pushing from after the last "pushed" line.

What's the actual result?  

OMS Agent starts pushing from the top or random position of the log file.
Observed when alerts were fired off for log entries with timestamps from months ago but with recent times for the "TimeGenerated" field. Spike in usage can also be observed in OMS Portal.

Additional details / screenshot:  

dpkg -s omsagent
Package: omsagent
Version: 1.3.5.127

dpkg -s omsconfig
Package: omsconfig
Version: 1.1.1.535

**Comment by lagalbra** [comment]
@koksan83 How frequently does the log you are trying to follow using Custom Logs get new lines pushed to it?

**Comment by lagalbra** [comment]
Merely restarting the omsagent should not cause old lines to be send to our backend. Can you turn on debug logging for the in <match oms.blob.**> section of the /etc/opt/microsoft/omsagent/<workspace id>/conf/omsagent.conf file and restart the omsagent to reproduce this? If so, send the output after the restart in /var/opt/microsoft/omsagent/<workspace id>/log/omsagent.log. You will see data being sent to the BLOB when a new line is added to the file, but not if the file is remaining the same.

We are currently working on a change to improve handling high-frequency logs (more than 1/minute may qualify). At the moment, you may see repeated logs if they are getting sent in high volumes.

**Comment by koksan83** [comment]
@lagalbra Output from omsagent.log:
2017-08-21 06:18:38 +0000 [info]: listening syslog socket on 127.0.0.1:25224 with udp
2017-08-21 06:18:38 +0000 [info]: Following tail of /***/***.log
2017-08-21 06:19:19 +0000 [debug]: Success getting the BLOB information in 0.033s
2017-08-21 06:19:19 +0000 [debug]: Success sending 2384443 bytes of data to BLOB 0.181s
2017-08-21 06:20:39 +0000 [debug]: Success getting the BLOB information in 0.275s
2017-08-21 06:20:39 +0000 [debug]: Success sending 308 bytes of data to BLOB 0.083s

Line count of the log file returns ~1000 lines while Log Search returns 40k results.
I set this up on a separate demo environment so the log frequency is also a lot lower.

**Comment by lagalbra** [comment]
How many lines were appended to the log file around 2017-08-21 06:20:39?

Please note: the Custom Log collection is in Public Preview and is still being worked on.

**Comment by koksan83** [comment]
Based on the size, we're looking at 1-2 lines. Not sure if its helpful but we're talking about nginx access logs here.

No worries I understand Custom Log is still in Public Preview. Its just unfortunate for us because Log Analytics + Custom Logs and the surrounding functionality is exactly what we're looking for right now.

**Comment by NarineM** [comment]
this is a bug with custom log sending duplicate entries when omsagent service is restarted and will be addressed in the future.

**Comment by hestolz** [comment]
Fixed in [1.8.1-256](https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.8.1.256) and above.
