### ISSUE TITLE
Fluent timeout error through proxy

### ISSUE THREAD

**Issue by mikemowgli** [Microsoft/OMS-Agent-for-Linux#558]
OMS agent (version 1.4.0-45) is installed on Ubuntu 17.04. 
The installation and onboarding succeeded. But OMS agent cannot communicate with OMS portal.

Please find enclosed the logs of

- [omsagent installation and onborading](https://github.com/Microsoft/OMS-Agent-for-Linux/files/1249315/omsagent-install.txt)
- [omsagent.log (with the timeout error)](https://github.com/Microsoft/OMS-Agent-for-Linux/files/1249314/omsagent.txt)
- [omsconfig commands](https://github.com/Microsoft/OMS-Agent-for-Linux/files/1249310/omsconfig.txt)

I, of course, purged and reinstalled the agent several times, and I quadruple-checked the proxy settings.
Plus, I can verify the agent should be able to connect to OMS portal with telnet and proxychains:
> mb@lt-mb3 ~ $ sudo netstat -antp | grep ruby
tcp        0      0 0.0.0.0:25324           0.0.0.0:*               LISTEN      13668/ruby          
tcp        0      1 10.0.2.15:35140         52.174.249.250:443      SYN_SENT    13668/ruby          
mb@lt-mb3 ~ $ proxychains telnet 52.174.249.250 443
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-response|: lt-mb3 does not exist
Trying 52.174.249.250...
[...]
|D-chain|-<>-192.168.253.12:8080-<><>-52.174.249.250:443-<><>-OK
Connected to 52.174.249.250.
Escape character is '^]'.
^]

What else can I check, guys?

**Comment by NarineM** [comment]
Can you check your proxy and see if outbound destination going to Azure OMS is blocked by your proxy?

**Comment by NarineM** [comment]
Please see this section for proxy setup: https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-agent-linux#Troubleshooting

**Comment by lagalbra** [comment]
Please also make sure you copy the proxy configuration as referenced [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-the-agent-for-use-with-an-http-proxy-server):
```
sudo cp /etc/opt/microsoft/omsagent/proxy.conf /etc/opt/microsoft/omsagent/conf/proxy.conf
sudo chown omsagent:omiusers /etc/opt/microsoft/omsagent/proxy.conf /etc/opt/microsoft/omsagent/conf/proxy.conf
sudo chmod 600 /etc/opt/microsoft/omsagent/proxy.conf /etc/opt/microsoft/omsagent/conf/proxy.conf
sudo /opt/microsoft/omsagent/bin/service_control restart
```

**Comment by mikemowgli** [comment]
@lagalbra thank you, the issue was the permissions on the proxy.conf file.
This is solved.
