### ISSUE TITLE
No apache nor docker logs

### ISSUE THREAD

**Issue by mikemowgli** [Microsoft/OMS-Agent-for-Linux#560]
Hi there,
I installed omsagent on Ubuntu 17.04.
The agent is properly installed and onboarded (through proxy). It sends perf & syslog properly to OMS.
However, I cannot see any docker nor apache logs in OMS.
Apache and Docker were installed before omsagent installation.
omsagent installation noticed apache & docker presence. omsagent installation log enclosed here:
[omsagent-install.txt](https://github.com/Microsoft/OMS-Agent-for-Linux/files/1251318/omsagent-install.txt)

Apache plugin was then manually configured as referenced [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Apache-HTTP-Server-Logs-Collection.md) and [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#enabling-apache-http-server-performance-counters)
I also checked that omsagent linux user was able to tail apache logs:
> mb@lt-mb3 ~ $ sudo -u omsagent tail -n1 /var/log/apache2/access.log
127.0.0.1 - - [25/Aug/2017:10:26:01 +0200] "GET / HTTP/1.0" 200 11175 "-" "ApacheBench/2.3"

The omsagent log after agent restart does not show errors, but no Apache blob is ever sent:
> 2017-08-25 10:26:46 +0200 [info]: listening syslog socket on 127.0.0.1:25224 with udp
2017-08-25 10:26:46 +0200 [info]: Following tail of /var/log/apache2/error.log
2017-08-25 10:26:46 +0200 [info]: Following tail of /var/log/apache2/access.log
2017-08-25 10:27:06 +0200 [debug]: Success sending LINUX_PERF_BLOB.LOGMANAGEMENT x 15 in 0.24s

And Type=ApacheAccess_CL returns nothing in OMS portal.

About Docker plugin, [this doc](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Docker-Instructions.md) was followed. But OMS portal shows 0 container running, although:
> mb@lt-mb3 ~ $ docker ps -q
38aadcfd92b6

Any idea what else I may check?

thanks

**Comment by lagalbra** [comment]
The OMSAgent is not yet supported on Ubuntu 17. See our list of supported distros [here](https://github.com/Microsoft/OMS-Agent-for-Linux/tree/master#supported-linux-operating-systems).

**Comment by mikemowgli** [comment]
@lagalbra , 
about Apache: seems like restarting the host fixed the issue
about Docker, I installed omsagent on a ubuntu 16.04 host and am now able to monitor containers. So the docker issue was indeed related to OS support.
thank you
Closing issue.
