### ISSUE TITLE
Support Ubuntu 17

### ISSUE THREAD

**Issue by kulttuuri** [Microsoft/OMS-Agent-for-Linux#561]
Hi,

Is it on the pipeline to add support for Ubuntu version 17? Ubuntu 17 has been released quite a long time ago, so this would be ideal to have working.

**Comment by lagalbra** [comment]
There are several distros which we do not currently support, but they are on our backlog to test and ensure support for, including Ubuntu 17.

**Comment by kulttuuri** [comment]
Thank you for the information @lagalbra ! :)

**Comment by NarineM** [comment]
I was able to install the agent on Ubuntu 17. It is not on supported list yet, but it would be very helpful if you list the issues you are seeing in your environment with Ubuntu 17 install.

**Comment by NarineM** [comment]
Ubuntu 17 never made to LTS build . Although agent can be installed on Ubuntu 17 we are not going to officially support this desktop version.
