### ISSUE TITLE
python <defunct> process building up

### ISSUE THREAD

**Issue by mbanks850** [Microsoft/OMS-Agent-for-Linux#570]
I am running omsagent 1.4.0-45 and I am noticing a build up of python <defunct> process.

Z    47193 21645 python \<defunct>
Z    47193 21648 python \<defunct>
Z    47193 21651 python \<defunct>
Z    47193 21654 python \<defunct>
Z    47193 21660 python \<defunct>
Z    47193 21680 python \<defunct>

[root@localhost ~]# ps aux | grep 47193
omsagent 47193  4.4  0.1 688316 25816 ?        Sl   08:52   9:15 /opt/omi/bin/omiagent 10 13 --destdir / --providerdir /opt/omi/lib --loglevel WARNING

If I kill the omsagent process , the zombie processes disappear.

The system is RHEL 7.3
this is the python rpm installed
python-2.7.5-48.el7.x86_64

**Comment by lagalbra** [comment]
@mbanks850 Please file this issue in the DSC repo: https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues

When you file the issue, please list what solutions are enabled on the workspace that this OMSAgent is sending data to.
