### ISSUE TITLE
OMS agent incompatible with openssl in Ubuntu 16.04 LTS after upgrade openSSL to 1.1

### ISSUE THREAD

**Issue by vascofolgado** [Microsoft/OMS-Agent-for-Linux#572]
Done this:

apt update 
apt upgrade

After a reboot the oms agent stop working.
Try to install the new version but no success (openssl upgraded to 1.1.0f):

root@XXXXXXXXXX:/tmp/oms# sh omsagent-1.4.1-45.universal.x64.sh --install -w xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -s xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Checking host architecture ...
Extracting...
Installing OMS agent ...
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 1.1.0f
Supported versions: 0.9.8*, 1.0.*
Shell bundle exiting with code 60
root@XXXXXXXXXXXX:/tmp/oms#

**Comment by NarineM** [comment]
@vascofolgado 
This is a known limitation and supporting open SSL is targeted to be available in October release of omsagent.

**Comment by ryannix123** [comment]
Any word on when this fix will be released? 

----- Checking package: omsagent (omsagent-1.4.1-45.universal.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 1.1.0f
Supported versions: 0.9.8*, 1.0.*
Shell bundle exiting with code 60

**Comment by brazabr** [comment]
I could use the information also. I have a bunch of VMs that I cannot monitor anymore.

**Comment by lavmeiker** [comment]
We're also after this. Any updates?

**Comment by VexedSyd** [comment]
any update on this?
it is almost the end of November, I'm trying to install Microsoft.Azure.Diagnostics.LinuxDiagnostic v3.0.109 and I'm getting the same error:

Failed to set up mdsd dependencies: omsagent setup failed 5 times. Last exit code=1, Output=setup_omsagent_for_lad(): omsagent universal installer shell execution failed. Output: Checking host architecture ... Extracting... Updating OMS agent ... ----- Checking package: omsagent (omsagent-1.4.0-45.universal.x64) ----- Error: This system does not have a supported version of OpenSSL installed. This system's OpenSSL version: 1.1.0f Supported versions: 0.9.8*, 1.0.* Shell bundle exiting with code 60

**Comment by NarineM** [comment]
Yes, Debian 9 and ssl 1.1 are not yet supported. I will add the link to installer in this thread as soon as it is released.

**Comment by VexedSyd** [comment]
@NarineM Thanks for your prompt response. Looking forward to using the new version. Do you have a rough ETA for the new release?

**Comment by mrx88** [comment]
We're also after this. Any ETA?

**Comment by ffloimair** [comment]
I desperately need this!
The odd thing is that you can additionally install libssl1.0.2 in Debian 9 - which would be compatible - but the installer only detects the highest installed version (which obviously is 1.1.0f).
A quick fix would probably be to only adapt the version check in the installer to check if there are additional (compatible) versions of libssl installed instead of just the highest version.

**Comment by tfanhaUK** [comment]
Any news on this release ? we have over 100+ desktops/vms that we cannot monitor anymore ?!

**Comment by NarineM** [comment]
We are working on this. I can update this thread when this support is released. thanks.

**Comment by pappavic** [comment]
@NarineM can you tell us which OS versions are supported? We have a marketplace image based on Ubuntu 16.04 LTS but if required we can change it to another supported OS for now.

**Comment by ryannix123** [comment]
I'm still seeing this on Ubuntu 16.04
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 1.1.0g
Supported versions: 0.9.8*, 1.0.*
Shell bundle exiting with code 60

**Comment by NarineM** [comment]
yes, open ssl 1.1 is not yet supported. We are working on releasing a new version of omsagent that will support open ssl 1.1.

**Comment by esbenbach** [comment]
Come on already - it can be that low priority to support a security related library

**Comment by oviliz** [comment]
Same here with Ubuntu 14.04 LTS...
> Checking host architecture ...
> Extracting...
> Updating OMS agent ...
> ----- Checking package: omsagent (omsagent-1.4.4-210.universal.x64) -----
> Error: This system does not have a supported version of OpenSSL installed.
> This system's OpenSSL version: 1.1.0g
> Supported versions: 0.9.8*, 1.0.*
> Shell bundle exiting with code 60
In my case 1.1.0g-2.1+ubuntu14.04.1+deb.sury.org+1 comes from the Ondřej PHP repo https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/13716628

**Comment by NarineM** [comment]
We are right now working on release a new version that supports open ssl 1.1 . Stay tuned..

**Comment by esbenbach** [comment]
For anyone who cant wait, it seems that most basic features works if you compile your own openssl and install it in a separate directory path.

**Comment by yobyot** [comment]
Six months since first reported and counting...

**Comment by peterschen** [comment]
There is a new release available which fixes this. This is explicitly not for production and meant for Docker environments but it might alleviate immediate problems.

**Comment by NarineM** [comment]
It is being released right now. And should be available this week for on-prem customers and next week for Azure customers.

**Comment by NarineM** [comment]
Published on GitHub: https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.6.0-42
