### ISSUE TITLE
Issues with Docker Redploys

### ISSUE THREAD

**Issue by kevi5702** [Microsoft/OMS-Agent-for-Linux#579]
Really hoping someone can point me in the right direction here, every time we redeploy our docker instances our SCX logs at (/var/opt/microsoft/scx/log/scx.log) beging to fill very rapidly with the following messages:

2017-09-29T15:02:39,523Z Error      [scx.core.common.pal.system.disk.statisticallogicaldiskinstance:############] statvfs() failed for /var/lib/docker/overlay/######################/merged; errno = 2

Systemctl restart omsagent##### seems to take care of this, but we were expecting the agent to be aware when a container went away and to stop trying to stat the directory it used to be mounted to.

So far we have tried removing and reinstalling the OMS bundle. But curious if there is something else we are doing wrong here?

**Comment by lagalbra** [comment]
I have raised this issue on the OMS-Docker repo; they own Docker issues: https://github.com/Microsoft/OMS-docker/issues/76
