### ISSUE TITLE
DSC service unable to connect through proxy when proxy.conf entry contains newline

### ISSUE THREAD

**Issue by thiezn** [Microsoft/OMS-Agent-for-Linux#588]
When adding a proxy entry ending with a newline character to /etc/opt/microsoft/omsagent/conf/proxy.conf the DSC engine fails to connect to the reporting servers:

```
# tail -f /var/opt/microsoft/omsconfig/omsconfig.log
2017/10/10 11:35:31: ERROR: null(0): EventId=1 Priority=ERROR Job E2A48E3D-6AE6-4923-9F04-FFD8F168F438 :
DSC Engine Error :
         Error Message Failed to report to all reporting servers.  Last server failed with HTTP response code: 0.
        Error Code : 1
```

When the proxy entry doesn't contain a newline the engine successfully connects:

```
# tail -f /var/opt/microsoft/omsconfig/omsconfig.log
2017/09/05 21:40:01: WARNING: null(0): EventId=2 Priority=WARNING Job AA396351-A956-4E15-B1EE-575E53EA651D :
Displaying messages from built-in DSC resources:
         WMI channel 1
         ResourceID:
         Message : []:                            [] Consistency check completed.
```

I suspect the function parse_proxy_config(proxy_conf_str) in /OMS-Agent-for-Linux/source/code/plugins/oms_configuration.rb is not taking the potential newline into account but my ruby/regex-fu isn't up to speed to submit a proper pull request.

Application teams within our organisation frequently run into this issue when deploying machines, so it would be helpful if the newline would be accepted as a valid entry.

**Comment by lagalbra** [comment]
This issue should be handled by the DSC team. As such, I have re-opened this issue on their repo: https://github.com/Microsoft/PowerShell-DSC-for-Linux/issues/334
