### ISSUE TITLE
Unable to see Linux VM connected to OMS

### ISSUE THREAD

**Issue by deepushri** [Microsoft/OMS-Agent-for-Linux#602]
Hi,
I have followed the steps as per the GitHub documentation. I could see that the shell bundle returned a code 0 ( which means that agent installation was a success). But when I log into the OMS portal to check the connected devices, I see the number of connected devices as 0.
Is there a time that I have to wait to see my device connected in the OMS portal?? If so , how much time is expected??
I am trying to forward custom logs to the log analytics but as I don't see my device connected in the first place, I don't see my logs as well in the log search.
 
Details about my environment:-
1) OS - Centos 7.1 (Azure VM)
2) OMS Agent version :- omsagent-1.4.2-124.x86_64

Please do let me know if anything else is required from my end.

**Comment by NarineM** [comment]
Hi, was this issue resolved? can you attach omsagent.log and omsconfig.log if it is still repo ing in your environment?

**Comment by shpimpal** [comment]
A later version is available. Please try installing that and see if the issue resolves.

**Comment by shpimpal** [comment]
Closing it for now, please re-open if issue occurs.
