### ISSUE TITLE
Log collector tool link is broken

### ISSUE THREAD

**Issue by temores** [Microsoft/OMS-Agent-for-Linux#606]
On Line 33

Link reference to
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/tools/LogCollector/OMS_Linux_Agent_and_Container_Log_Collector.docx
gives 404

**Comment by arjun-urs** [comment]
@temores On Line 33 of which source? Can you share the link please?

**Comment by NarineM** [comment]
Can you check if is has been resolved for you environment or you are still seeing broken link?
