### ISSUE TITLE
[Feature Request] Process list

### ISSUE THREAD

**Issue by HDYA** [microsoft/OMS-Agent-for-Linux#608]
Was is possible for OMS Agent to ship VM process list regularly?

**Comment by NarineM** [comment]
hi, I am not sure if I understand what the ask is. can you describe your scenario ?

**Comment by HDYA** [comment]
Hi @NarineM Sorry I mean, if it is possible, that you will add a new kind of telemetry that regularly reports back what processes are running on monitored instances.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
