### ISSUE TITLE
OMS agent is not sending data

### ISSUE THREAD

**Issue by jjindrich** [Microsoft/OMS-Agent-for-Linux#612]
Hi, I have problem that agent is not sending data info OMS workspace. I checked log and seems to be working. I found that is sending hearbeat correctly. But not Perf data.
I found this error in /var/opt/microsoft/omsconfig/omsconfig.log
2017/12/04 10:16:07: ERROR: Scripts/nxService.pyc(306):
CalledProcessError.  Error Code is 1
2017/12/04 10:16:07: ERROR: Scripts/nxService.pyc(311):
CalledProcessError.  Command string was initctl list
2017/12/04 10:16:07: ERROR: Scripts/nxService.pyc(316):
CalledProcessError.  Command result was

Ubuntu 16.04.3 LTS

**Comment by jjindrich** [comment]
Probably not working with OMI 1.4. which is required by dotnet core (https://www.microsoft.com/net/learn/get-started/linuxubuntu) - adding sourcelist repo with new OMI

**Comment by NarineM** [comment]
There is a known issue with omsagent older than 1.4.3-174 if customer has upgraded only OMI to 1.4.1. No perf data will be sent to OMS. This is fixed in version #174 of omsagent.
