### ISSUE TITLE
Update Nagios parser to include service name in service alerts

### ISSUE THREAD

**Issue by bshaw** [microsoft/OMS-Agent-for-Linux#613]
The Nagios parser does not include the name of the service when a SERVICE ALERT event is taken from the log.

Using the sample from the included test, [test/code/plugins/nagios_log_parser_test.rb, line 69](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/b7a227b6e1b2357826247f36ef1f48a7da61ff79/test/code/plugins/nagios_log_parser_test.rb#L69):
```
[1436810490] SERVICE ALERT: nagios-2;Current Users;CRITICAL;SOFT;1;CHECK_NRPE: Error - Could not complete SSL handshake.`
```

The second field (Current Users) is being overlooked.

This information is necessary to display meaningful data in Log Analytics or an OMS dashboard. Ideally, we should be able to surface the data in a manner that eliminates the need to go to the Nagios console for everything.

The parser should work such that the expected_record at  [test/code/plugins/nagios_log_parser_test.rb, line 61](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/b7a227b6e1b2357826247f36ef1f48a7da61ff79/test/code/plugins/nagios_log_parser_test.rb#L60) should have an additional field (ServiceName), like below:
```
expected_record = {
	"Timestamp"=>"2015-07-13T18:01:30+00:00",
	"AlertName"=>"SERVICE ALERT",
	"HostName"=>"nagios-2",
	"ServiceName"=>"Current Users",
	"State"=>"CRITICAL",
	"StateType"=>"SOFT",
	"AlertPriority"=>1,
	"AlertDescription"=>"CHECK_NRPE: Error - Could not complete SSL handshake."
}
```

**Comment by NarineM** [comment]
we will look into adding ServiceName property to Nagios alerts. I will update this thread as soon as it is available. thanks for bringing this up.

**Comment by hestolz** [comment]
Closing, [custom logs](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-sources-custom-logs) is our current supported path for collecting from Nagios/Zabbix.
