### ISSUE TITLE
OMS agent does not work on Debian 9 Stretch

### ISSUE THREAD

**Issue by mrx88** [Microsoft/OMS-Agent-for-Linux#617]
Example:
 wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w <id> -s <secret> -d opinsights.azure.com
...
2017-12-21 08:58:21 (11.8 MB/s) - ‘omsagent-1.4.2-124.universal.x64.sh’ saved [100769185/100769185]

Checking host architecture ...
Extracting...
Updating OMS agent ...
----- Checking package: omsagent (omsagent-1.4.2-124.universal.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 1.1.0f
Supported versions: 0.9.8*, 1.0.*
Shell bundle exiting with code 60

OS:

Distributor ID: Debian
Description:    Debian GNU/Linux 9.3 (stretch)
Release:        9.3
Codename:       stretch

Is it possible to add newer openssl support? Thanks.

**Comment by VexedSyd** [comment]
@mrx88 I'm having the same issue, and I raised it here more than a month ago. It is a known issue and I'm waiting for Debian Stretch and OpenSSL 1.1 to get supported.

[https://github.com/Microsoft/OMS-Agent-for-Linux/issues/572#issuecomment-345581881](url)

**Comment by NarineM** [comment]
We are working on supporting Debian 9. We will update the thread when the release is available.

**Comment by NarineM** [comment]
New release version #42 has Debian 9 support: https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.6.0-42
