### ISSUE TITLE
omsagent PerformRequiredConfigurationChecks fails to create configuration directory

### ISSUE THREAD

**Issue by thiezn** [Microsoft/OMS-Agent-for-Linux#625]
Hello,

We are deploying cloudfoundry hardened linux stem cells to Microsoft Azure but having difficulty getting OMI to register itself. Because of this Microsoft Security Center is unable to scan for security updates, etc.

The output of 'PerformRequiredConfigurationChecks.py' seems to indicate this is a permissioning issue somewhere but I haven't been able to find a reference to the configuration directory the output points to. Is there some way to determine where the agent is trying to write?

```
sudo -u omsagent /opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py
instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=The creation of the configuration directory failed. Verify the directory permissions and try again.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
}

/opt/omi/bin/omicli: result: MI_RESULT_FAILED
/opt/omi/bin/omicli: result: The creation of the configuration directory failed. Verify the directory permissions and try again.
```

The actual command run by the python script is
```
/opt/omi/bin/omicli iv root/oms { MSFT_DSCLocalConfigurationManager } PerformRequiredConfigurationChecks { Flags 1 }
```

Note: Initially raised this question in OMI repo (https://github.com/Microsoft/omi/issues/477) but got referred back to omsagent:

**Comment by NarineM** [comment]
Hi, please move this issue to powershell DSC for Linux GitHub repr instead. this page is for tracking omsagent related issues only. thanks.

**Comment by MrCNeale** [comment]
This is closed in error.  It's an issue with the linux OMS agent, it has nothing to do with Powershell or DSC.
The OP is running the steps listed in the OMS troubleshooting guide!

**Comment by wenboyang214** [comment]
@MrCNeale Yes I also think it's a OMS agent related issue. This error is produced by following the OMS official [documents](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/agent-linux-troubleshoot#issue-you-are-not-seeing-any-custom-log-data).
