### ISSUE TITLE
walinuxagent 2.2.20 handler is keeping download the omsagent 1.4.58.7 but failed to disable older omsagent extension 1.4.56.5

### ISSUE THREAD

**Issue by sundaxi** [Microsoft/OMS-Agent-for-Linux#630]
Error message logs repeat in waagent.log looks like below.

From guest os perspective, I could see lots of traffic was generated by waagent handler and from the waagent logs, I could see the handler is trying download/install the omsagentforlinux 1.4.58.7 but failed to disable omsagentforlinux 1.4.58.5. The operation kept failed repeatly and the omsagentfor linux extension states as "Transitioning"

2018/01/06 23:07:46.731983 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
2018/01/06 23:07:46.743489 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
2018/01/06 23:07:51.094812 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
2018/01/06 23:07:51.107818 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:07:51.121596 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
2018/01/06 23:07:51.142064 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
2018/01/06 23:07:51.159026 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable extension [omsagent.py -disable]
2018/01/06 23:07:51 OmsAgentForLinux started to handle.
2018/01/06 23:07:51 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] cwd is /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5
2018/01/06 23:07:51 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Change log file to /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/1.4.56.5/extension.log
2018/01/06 23:07:52.174867 ERROR Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=[ExtensionError] Non-zero exit code: 1, omsagent.py -disable, duration=0
2018/01/06 23:07:52.191380 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:07:52.291125 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7
2018/01/06 23:07:55.373756 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
2018/01/06 23:07:55.384748 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
2018/01/06 23:08:00.278801 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
2018/01/06 23:08:00.291616 WARNING Too many files under: /var/lib/waagent/events, removing oldest
2018/01/06 23:08:00.299439 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
2018/01/06 23:08:00.313816 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
2018/01/06 23:08:00.328295 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable extension [omsagent.py -disable]

**Comment by sundaxi** [comment]
The extension.log is huge but repeat the same errror below
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] sequence number is 0
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5/config/0.settings
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettingsCertThumbprint": "8CB4E2939C96FC93D39D0D5439FFC60D1B9E9C95", "protectedSettings": "MIICtAYJKoZIhvcNAQcDoIICpTCCAqECAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEGTUuftXZt6mShaVoEYrS28wDQYJKoZIhvcNAQEBBQAEggEAjv9AZBZCVoSkpt4ahZzd4nfdcqGV15zB7AtTLF1e2uOFo2ImHxn7fCZJkPSBYI4Ye7pOUqQ2XFo6JhsJ2I6xrft/Vyh1uVWWSGWipXobtSUyn+CXT9Rkc3QGgOqVjFZ5t8KtPqBlinP2CxhxvIlRaCGS0zfKwOkW+OKsufvWJBQAqrBN9vsbqt4MuxDXS+jqdCXBOs6GltF+gEaRfExS9eEJok0rM0O+4ooaXNvODMWDvsMKaTDv1JSjcSW1Tjf4op+ceMa7lf7bDsHHxLr6MlAdrrr1GvJ9V4ORmlcRYl+w4woEBpMbK/+YZ7z32YfivBanvEfzImmjLoEh5xPlajCCAS0GCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIdNZV89ZkqYGAggEIoRFh2xIP48ZJKRVCWx729ODi7+t4YdGgS+YvsJP5sESrYY0FO6mP44oIoqCHdy07+LTmU8Lj5reVvF/C5peTJt2cU9mk0L7kIhVOJQFv//eNa58bCcMFGicStS+uJsnVyCNrxeBLWe2R3VDFfVGKGTXIW53zAPto5h0ufBnU34yYw7amWHjiMLVbrbbVK3palUaV4uGtdnRir+PxatCX5w0jZuXu7gMrq84sqCK33KmLIUyFi6cO/HJyMFw6AOUjer4YN/7QiumO7KK9MnUVGwDCh/vWik+eCq2A5w2gAlpnQdOJx39Fqp9idWNDSK/FG38gdZWCL2afO4vNIYhVRmFQP1CzesLY", "publicSettings": {"workspaceId": "ad9244f1-e9c7-431f-813d-5ba9e98d81fe", "azureResourceId": "/subscriptions/fe4c153a-e4be-4922-b139-a3edd6062474/resourcegroups/prestashop/providers/microsoft.compute/virtualmachines/nineeleven", "stopOnMultipleConnections": true}}}]}
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Config decoded correctly.
2018/01/25 14:19:33 ERROR:CalledProcessError. Error Code is 1
2018/01/25 14:19:33 ERROR:CalledProcessError. Command string was /opt/microsoft/omsagent/bin/service_control disable
2018/01/25 14:19:33 ERROR:CalledProcessError. Command result was invoke-rc.d: unknown initscript, /etc/init.d/omsagent- not found.
2018/01/25 14:19:33 ERROR:ERROR: disable_omsagent_service failed with result '100' on workspace ad9244f1-e9c7-431f-813d-5ba9e98d81fe.
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Output of command "/opt/microsoft/omsagent/bin/service_control disable":
2018/01/25 14:19:33 invoke-rc.d: unknown initscript, /etc/init.d/omsagent- not found.
2018/01/25 14:19:33 ERROR: disable_omsagent_service failed with result '100' on workspace ad9244f1-e9c7-431f-813d-5ba9e98d81fe.
2018/01/25 14:19:33 ERROR:Disable failed with exit code 1
2018/01/25 14:19:33 ERROR:[Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable failed with exit code 1
2018/01/25 14:19:33 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] Disable,failed,1,Disable failed with exit code 1
2018/01/25 14:19:43 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] sequence number is 0
2018/01/25 14:19:43 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5] setting file path is/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.56.5/config/0.settings

**Comment by NarineM** [comment]
hi, please file waagent issues on https://github.com/Azure/WALinuxAgent/issues GitHub repo. thanks.

**Comment by sundaxi** [comment]
Interesting, waagent team requested to open an issue to OMS team and OMS team requested me to open issue to waagent team. 
Check https://github.com/Azure/WALinuxAgent/issues/1019

So, where can I get the answer??

**Comment by NarineM** [comment]
You can try uninstalling OMS Linux extension and re-installing it. My initial impression was that your previous install was successful and upgrade did not work based on provided logs in this ticket when looks like it failed to be installed in the first place.

**Comment by NarineM** [comment]
Remove the OmsAgentForLinux extension from the VM:  https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/remove-azurermvmextension?view=azurermps-5.1.1&viewFallbackFrom=azurermps-4.4.0
•	Wait until Uninstall operation completes (operation details can be seen in /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/<version>/extension.log ) 

Download OMSAgent shell bundle from GitHub :  https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_GA_v1.4.4-210

On the downloaded bundle, run: 

•	sudo omsagent-*.sh --purge 

Re-install the OmsAgentForLinux extension on the VM https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-oms

**Comment by sundaxi** [comment]
Thanks @NarineM 
Uninstall and install could work. But the main issue is due to waagent could not disable the old oms version. I am not sure who maintain the disable script. 
If we uninstall the omsagent and reinstall it, this could skip the procedure of disable older version of omsagent

**Comment by NarineM** [comment]
install/uninstall/enable/disable routines are owned by waagent. I do not have any information on why install was failing in your environment, but if was installed successfully but upgrade of new version did not happen it would be an issue with waagent I believe. Let us try the mitigation steps for now to see if your machine is recovered.

**Comment by sundaxi** [comment]
@NarineM I have more than 5 customers met with such kind of issue and I suggested them to do the same thing, uninstall and re-install could migrate the issue. I didn't see other extension meet such kind of issue before. But anyway, if you can confirm the the disable routines are owned by waagent. I will try to search some help from waagent team as well.

**Comment by NarineM** [comment]
There are two issues going on here, one is oms extension fails to perform service disable because agent was uninstalled from the box, the second issue is with waagent getting into the loop where if would keep calling disable () when extension disable fails for a long time instead of failing fast,
I can only see the last portion in these logs when waagent was in a strange state. Do you know if the previous installation was successful or not or whether the agent was manually uninstalled on the box using the bundle *.sh directly instead of uninstalling using extension? 
This GitHub repo is for monitoring agent related issues and I provided mitigation steps to make agent recover you need to try. For everything else please follow up on waagent GitHub page.

**Comment by NarineM** [comment]
re installing waagent should mitigate the issue. Here are the steps how to re-install waagent: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/update-agent

If you see this issue in the future , please file an issue at WaLinuxAgent repo.
