### ISSUE TITLE
[1.4.59] Logs in /var/opt/microsoft/omsconfig are not rotated in (at least) Ubuntu 14.04 LTS & 16.04 LTS

### ISSUE THREAD

**Issue by gpenin** [Microsoft/OMS-Agent-for-Linux#631]
In Ubuntu 14.04 LTS & 16.04 LTS, logrotate ignores /etc/logrotate.d/omsconfig (symlink to /opt/microsoft/omsconfig/etc/logrotate.conf) because the file is not owned by root : 

[root@server ~]# logrotate -d /etc/logrotate.conf
reading config file /etc/logrotate.conf
including /etc/logrotate.d
...
Ignoring omsconfig because the file owner is wrong (should be root).
...

As a consequence, logs in /var/opt/microsoft/omsconfig are growing indefinitely.

**Comment by franbarberan** [comment]
Hi,

How install omsagent in ubuntu 14.04 o 16.04 ?
when i tryed install, ubuntu return this error
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 1.1.0g
Supported versions: 0.9.8*, 1.0.*
Shell bundle exiting with code 60

of course my version is 
root@testazure14:/var/tmp# openssl version
OpenSSL 1.1.0g  2 Nov 2017
 i think that downgrade the openssl is dangerous

Thanks for all

FRANK

**Comment by NarineM** [comment]
Should be fixed in this release: https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.6.0-42
