### ISSUE TITLE
mdsd running at 100% CPU usage after agent update

### ISSUE THREAD

**Issue by EricTendian** [Microsoft/OMS-Agent-for-Linux#632]
*Was told to post this here. Following up from [this Azure forum thread](https://social.msdn.microsoft.com/Forums/azure/en-US/5ab85f9b-0bfc-482f-8331-bbd7d994e1c2/high-cpu-usage-by-mdsd-command-in-azure-linux-vm?forum=WAVirtualMachinesforWindows) and [this GitHub issue](https://github.com/Microsoft/omi/issues/425)...*

At 06:15 GMT the OmsAgentForLinux extension updated on my VMs. In addition to a faulty cron job causing lots of emails (see other issue), the CPU for some of the VMs which received the update (not all of them) went to 100% about 10 seconds before because of the mdsd process (mdsd-lde service).

All my VMs are using Ubuntu 16.04. I believe the ones affected by the CPU issue had the Microsoft.OSTCExtensions.LinuxDiagnostic extension, but that was not updated during the other extension update.

Here's what it looked like from a system resources perspective:

![screenshot from 2018-01-25 16-40-24](https://user-images.githubusercontent.com/498525/35416371-87e5daa6-01ee-11e8-9d79-052740908d3f.png)

And a snippet of syslogs:

```
Jan 25 06:15:30 {redacted} python3[1180]: 2018/01/25 06:15:30.341189 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Target handler state: enabled
Jan 25 06:15:30 {redacted} python3[1180]: 2018/01/25 06:15:30.349937 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] [Enable] current handler state is: notinstalled
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.874452 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Download, message=Download succeeded, duration=0
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.890790 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:35 {redacted} python3[1180]: 2018/01/25 06:15:35.902593 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Initialize extension directory
Jan 25 06:15:36 {redacted} python3[1180]: 2018/01/25 06:15:36.038708 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update settings file: 0.settings
Jan 25 06:15:36 {redacted} python3[1180]: 2018/01/25 06:15:36.054356 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Disable extension [omsagent.py -disable]
Jan 25 06:15:36 {redacted} systemd[1]: Stopping Operations Management Suite agent...
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Main process exited, code=killed, status=9/KILL
Jan 25 06:15:36 {redacted} systemd[1]: Stopped Operations Management Suite agent.
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Unit entered failed state.
Jan 25 06:15:36 {redacted} systemd[1]: omsagent-{redacted}.service: Failed with result 'signal'.
Jan 25 06:15:36 {redacted} systemd[1]: Reloading.
Jan 25 06:15:36 {redacted} systemd[1]: Starting Daily apt upgrade and clean activities...
Jan 25 06:15:36 {redacted} systemd[1]: Started ACPI event daemon.
Jan 25 06:15:36 {redacted} systemd[1]: Reloading.
Jan 25 06:15:36 {redacted} systemd[1]: Started ACPI event daemon.
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.072793 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Disable, message=Launch command succeeded: omsagent.py -disable, duration=0
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.096212 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.107894 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Copy status files from old plugin to new
Jan 25 06:15:37 {redacted} python3[1180]: 2018/01/25 06:15:37.121501 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Update extension [omsagent.py -update]
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.140972 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Update, message=Launch command succeeded: omsagent.py -update, duration=0
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.157980 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:38 {redacted} python3[1180]: 2018/01/25 06:15:38.169870 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Uninstall extension [omsagent.py -uninstall]
Jan 25 06:15:38 {redacted} systemd[1]: Stopping OMI CIM Server...
Jan 25 06:15:38 {redacted} omiserver[430]: /opt/omi/bin/omiserver: stopped server
Jan 25 06:15:38 {redacted} systemd[1]: Stopped OMI CIM Server.
Jan 25 06:15:38 {redacted} systemd[1]: Starting OMI CIM Server...
Jan 25 06:15:38 {redacted} systemd[1]: omid.service: PID file /var/opt/omi/run/omiserver.pid not readable (yet?) after start: No such file or directory
Jan 25 06:15:38 {redacted} systemd[1]: Started OMI CIM Server.
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.186971 INFO Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=UnInstall, message=Launch command succeeded: omsagent.py -uninstall, duration=0
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.201603 WARNING Too many files under: /var/lib/waagent/events, removing oldest
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.212578 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Remove extension handler directory: /var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7
Jan 25 06:15:39 {redacted} python3[1180]: 2018/01/25 06:15:39.248443 INFO [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.4.58.7] Install extension [omsagent.py -install]
```

I have since tried to uninstall the extension from the Azure portal, but it seems that after a couple minutes the extension gets reinstalled on the machine. I don't have a need for the extension and would ideally like to remove it, since I have experienced multiple resource usage issues from it in the past.

**Comment by mszaczhang** [comment]
We have same problem in RedHat RHEL 7.3 and Ubuntu 16.04.  A lot customer see this issue recently.

**Comment by rhyssmith** [comment]
Same here on RHEL 7 VMs. Load average on a server that is usually <1, <1, <1 is currently 9.09, 9.27, 8.76.

**Comment by msternik** [comment]
Same here on ubuntu 16.04. Please advise how to solve it.

**Comment by maurert** [comment]
Same problem here running Ubuntu 16.04.2 LTS. 

 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  1963 root      20   0  965900  29776  11480 S 99.7  0.8   1937:37 mdsd

![image](https://user-images.githubusercontent.com/4974327/35443805-a0ea5f36-02ac-11e8-9b1d-75d70d82bd19.png)

**Comment by matheus-santoro** [comment]
Same using Centos 7.3 Any solution? 

Should we consider downgrading the version?

**Comment by matheus-santoro** [comment]
Same using Centos 7.3. Any solution for this?

Downgrading the version on multiple servers should not be an option to solve this.

**Comment by bprime** [comment]
Same issue here, Ubuntu 16.04.

**Comment by mstrhh** [comment]
I had all quite some issues with this Azure software suite: hanging waagent with 100% CPU, cron error mails in 1 minute intervals, log files full of omsagent messages, 

This is not acceptable on Red Hat, in production, on Azure. Fixes urgently needed.

**Comment by sbadakhc** [comment]
Hi,

Same issue here as well on RHEL 7.4. Please fix ASAP as these are productions servers!

**Comment by WGdata** [comment]
We are also having issues on both RHEL 7.4 and Ubuntu 16.04 production machines.

**Comment by noamo48** [comment]
Same issue with Cent OS 7.2. I tried upgrading the Linux Azure Diagnostics agent to version 3.0 but it had no effect on the CPU usage - it's still way too high.

**Comment by tony-nilan** [comment]
we are running several machines as per below and having >80% cpu usage by mdsd:

Operating System: Ubuntu 16.04.2 LTS
Kernel: Linux 4.4.0-83-generic
Architecture: x86-64

**Comment by bprime** [comment]
About 10 minutes ago our CPU usage finally returned to normal levels, so they may have pushed out the fix.

**Comment by mstrhh** [comment]
many problem confirmations here, but no solutions or suggestions? 

Maybe the omi case   #425 is fixed first, but my trace is showing a deadlock I think, right? 

And this happend 2 months ago,  without a pushed faulty version.

**Comment by pnmcosta** [comment]
Had the same issue, upgraded everything, including kernel to ` 4.13.0-1007-azure #9-Ubuntu` and am no longer having the issue, so far...

`waagent --version` reports:

WALinuxAgent-2.2.17 running on ubuntu 16.04
Python: 3.5.2
Goal state agent: 2.2.20

Please note I do not use Python on this machine, but I did notice it updated during the `apt-get upgrade` so beware of any dependencies.

**Comment by Xiao4** [comment]
any solution to fix this?

**Comment by pnmcosta** [comment]
hi @Xiao4 since the update to `4.13.0-1007-azure #9-Ubuntu` I've not had the issue.

**Comment by riskgod** [comment]
I met the same problem, as I kill the mdsd, it looks fine

**Comment by ChrisMcKee** [comment]
Any chance of msft at the very least putting a leash on this so, worst case scenario, this thing breaks it can't wipe out the entire processor.

https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html
https://unix.stackexchange.com/a/223282/3792

**Comment by NarineM** [comment]
Hi, please file LAD extension related issues on Linux diagnostic agent GitHub repo. You can look at reported issues here: https://github.com/Azure/azure-linux-extensions/issues

**Comment by Kris-Law** [comment]
I know it's an old thread, but still seems relevant. 

It appears the issue may be related to disk tier. My understanding is that standard HDD is not supported waagent / WaLinuxAgent, but Premium SSD is and seems to do fine. 

In once instance, even Premium SSD load was high, but a performance tier increase from p4 to p6 resolved the issue
