### ISSUE TITLE
[1.4.59] Cron job (ktstrip) generates unwanted output

### ISSUE THREAD

**Issue by gpenin** [Microsoft/OMS-Agent-for-Linux#634]
When /etc/krb5.keytab does not exists, the ktstrip cron job generates output that can lead, with some configurations, to then sending of one email per minute.

Is it possible to add standard/error output redirection (>/dev/null 2>&1 for example) to the cron job ?

**Comment by silverl** [comment]
If the keytab doesn't exist, the cron is unable to complete its work anyway. The better workaround is likely to simply comment out the line entirely until Microsoft fixes this.

**Comment by NarineM** [comment]
This is an issue with omi and needs to be filed on omi GitHub repo here: https://github.com/Microsoft/omi
Similar issue has been fixed in omi version 1.4.2. Please try latest version and see if it resolves your case, if not please file a new issue on omi.
