### ISSUE TITLE
"omiagent" segfault libnss_dns

### ISSUE THREAD

**Issue by srice01** [Microsoft/OMS-Agent-for-Linux#635]
On our RM provisioned VMs in Azure we noticed that the root partition is filling up with large numbers of "core.###" files in the /var/opt/omi/run directory.

Further investigation shows segmentation faults (in /var/log/messages) as follows:
```
Jan 30 10:17:17 ML001 kernel: omiagent[2054]: segfault at 7f6b7e181e00 ip 00007f6b7e181e00 sp 00007f6b78846d50 error 14
Jan 30 10:32:12 ML001 kernel: omiagent[3298]: segfault at 7fa8356f4e00 ip 00007fa8356f4e00 sp 00007fa82fdb9d50 error 14
Jan 30 11:02:19 ML001 kernel: omiagent[5873]: segfault at 7fbd84d3de00 ip 00007fbd84d3de00 sp 00007fbd7ede0d50 error 14 in libnss_dns-2.17.so[7fbd84ec5000+5000]
Jan 30 11:17:19 ML001 kernel: omiagent[13175]: segfault at 7fbac740ae00 ip 00007fbac740ae00 sp 00007fbac54bcd50 error 14 in libnss_dns-2.17.so[7fbac7592000+5000]
Jan 30 11:32:21 ML001 kernel: omiagent[20049]: segfault at 7f79230dfe00 ip 00007f79230dfe00 sp 00007f791d7a4d50 error 14
Jan 30 12:02:14 ML001 kernel: omiagent[46782]: segfault at 7f9fa8939e00 ip 00007f9fa8939e00 sp 00007f9fa296dd50 error 14 in libnss_dns-2.17.so[7f9fa8ac1000+5000]
```
Environment information:

- OMS Agent: 1.4.3-174 (latest)
- OMI 1.4.1
- Operating System: CentOS Release 7.4.1708 (fully patched, that is, "yum update" shows no updates pending)

**Comment by NarineM** [comment]
Can you move this issue to OMI GitHub repo? There are two similar issues that SCX and DSC providers are working on with OMI right now. This repository is monitoring oms agent specific issues. thanks,

**Comment by srice01** [comment]
Done. https://github.com/Microsoft/omi/issues/491
