### ISSUE TITLE
can i install OMS agent on a Kubernetes node on GCP

### ISSUE THREAD

**Issue by sundeepk1** [microsoft/OMS-Agent-for-Linux#637]
Hi ,

Is it possible to install the agent on a  k8 worker/master nodes on GCP and then use Azure OMS to monitor the GCP - Google Kubernetes engine etc . 

Regards,
Sundeep Kumar

**Comment by shpimpal** [comment]
Hi,
Please go through this link to see if it suitable for your requirement - https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-containers.
Thanks.
