### ISSUE TITLE
No information about rpm packages available updates sends to Log Analytics/OMS portal 

### ISSUE THREAD

**Issue by alexk2000** [microsoft/OMS-Agent-for-Linux#640]
We just started using OMS portal for on-premise Linux servers and added several RHEL 5/6/7 to OMS. We see perf, syslog, inventory data in Log Analytics/OMS portal, we successfully tested sending custom json data to Log Analytics, all looks good. Only one problem is no information sending to Log Analytics about available package updates, thus in OMS portal view 'System Update Assessments' all Linux servers up to date. All servers have developer subscription from RedHat,  yum check-update shows that updates are available. There is nothing interesting regarding this in the log files:
/var/opt/microsoft/omsagent/log/omsagent.log
/var/opt/microsoft/omsconfig/omsconfig.log
/var/opt/microsoft/omsconfig/omsconfigdetailed.log

It looks like update management configuration missing. Maybe it works only on Azure Linux virtual machines ? 

omi-1.4.1-0.x86_64
omsagent-1.4.3-174.x86_64
auoms-1.0.0-2.x86_64
omsconfig-1.1.1-649.x86_64

**Comment by tkomlichenko** [comment]
Hi,
we also have similar issue. (https://github.com/Microsoft/OMS-Agent-for-Linux/issues/641).
Almost all our VMS are green in "Workspace->Virtual Machines", but "Not-assessed" in "Update management (Preview)".
Could you share, please, if your VMS are showed as different from "Not assessed"?
BR

**Comment by cricketfan5** [comment]
@alex-frankel @tkomlichenko I am new azure, and I installed the oms agent on azure vms, But i don't see tick that shows it is being monitored in portal. Is this a expected behaviour. Thanks
