### ISSUE TITLE
Allow disabling of repositories when checking for updates

### ISSUE THREAD

**Issue by davemulford** [microsoft/OMS-Agent-for-Linux#645]
In RHEL, the OMS Agent performs a `yum check-update` in the `/opt/microsoft/omsconfig/Scripts/OMSYumUpdates.sh` script. If I have a large repository enabled, this can completely fill the OS disk.

My proposal is to allow the disabling of specific repositories so the disk is not full. This would cause `yum check-update` to be executed like this:

    yum check-update --disablerepo=<repo-name> --disablerepo=<...>

Environment:
- Microsoft Azure virtual machine associated with OMS
- Red Hat Enterprise Linux

**Comment by johnsontnc** [comment]
I'm curious, why would check-update fill up your disk? Or why would you enable a large repo? I would think more than just OMS might call check-update.

**Comment by davemulford** [comment]
The repo is internal to our organization, and a check-update fills the OS disk because of how large the yum cache files are under /var/cache/yum.

**Comment by NarineM** [comment]
@Atchub  @shuliums can you take a look?

**Comment by Klaas-** [comment]
@davemulford I would suggest to do it the other way around, disable the repo by default and only enable it when you really need it (but you won't be able to use it anyways if you can't download the needed yum metadata)

**Comment by davemulford** [comment]
@Klaas- that makes sense. I agree with your idea here.  I'll go ahead and close this out.
