### ISSUE TITLE
RedHat Linux 5.11, runbook not running through hybrid worker, custom log configuration on OMS portal not applied on the host

### ISSUE THREAD

**Issue by alexk2000** [microsoft/OMS-Agent-for-Linux#646]
Short issue description: RedHat Linux 5.11, runbook not running through hybrid worker, custom log configuration on OMS portal not applied on the host. 

Use case:
On-premise RedHat Linux 5.11  host is in own hybrid worker group. Python runbook is started on the hosts' hybrid worker group and write data to custom log. 
Custom log is defined in OMS portal -> Settings -> Data -> Custom logs. 

Expected behaviour: python script collects some data and write to custom log on the host. 
Data from the log transferred to Log Analytics and available under custom log type.
This solution works fine on another test host with RedHat Linux 7.4

Problem description:
1. When starting python runbook on hosts's hybrid worker group it's queued, then suspended and not started on the host.
2. Even if run python script locally on the host, data from log not transferred to log Log Analytics. 
Deep investigation showed that custom log configuration is missing /etc/opt/microsoft/omsagent/conf/omsagent.d/customlog.conf (should be created by omsconfig using custom log configuration from OMS portal)  

Action performed:
1. Trying to find solution in official documentation:
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md
https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md
2. Log analyzing  
3. Server reboots, reinstalling OMS agent (removed by sh ./omsagent-*.universal.x64.sh --purge, installed by wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh ...) 

Details about the issue.

OS: RedHat 5.11, SELinux disabled, ESXi vm

Packages version:
omsconfig-1.1.1-649
scx-1.6.3-474
auoms-1.0.0-2
apache-cimprov-1.0.1-9
omsagent-1.4.3-174
omi-1.4.1-0

Installation method:
wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w ... -s ... -d opinsights.azure.com

Automation hybrid worker registration (host is in its own hybrid worker group, the same as hostname): 

python /opt/microsoft/omsconfig/modules/nxOMSAutomationWorker/DSCResources/MSFT_nxOMSAutomationWorkerResource/automationworker/scripts/onboarding.py --register -k ... -w ... -g test5-2 -e ...
python /opt/microsoft/omsconfig/modules/nxOMSAutomationWorker/DSCResources/MSFT_nxOMSAutomationWorkerResource/automationworker/scripts/require_runbook_signature.py --false ...

ls -al /etc/opt/microsoft/omsagent/conf/omsagent.d

drwxr-xr-x 2 omsagent omiusers  4096 Фев 16 16:02 .
drwxr-xr-x 3 omsagent omiusers  4096 Фев 16 16:02 ..
-rw-r--r-- 1 omsagent omiusers   459 Фев 16 16:02 heartbeat.conf
-rw-r--r-- 1 omsagent omiusers   885 Фев 16 16:02 monitor.conf
-rw-r--r-- 1 omsagent omiusers 14231 Дек 20 03:14 omi_mapping.json
-rw-r--r-- 1 omsagent omiusers   962 Фев 16 16:02 operation.conf
-rw-r--r-- 1 omsagent omiusers   156 Фев 16 16:02 syslog.conf

The hosts sends to Log Analytics 3 types of records: Heartbeat, Operation, Usage

Log Analytics, Type: Heartbeat

SourceSystem: OpsManager
TimeGenerated: 2018-02-17T11:22:53.847Z
Computer: test5-2
Type: Heartbeat
ComputerEnvironment:Non-Azure
OSType: Linux
OSName: Red Hat Enterprise Linux
Category: Direct Agent
OSMajorVersion: 5
OSMinorVersion: 11
Version: 1.4.3-174
Solutions: "security", "updates", "antiMalware", "changeTracking", "sqlAssessment", "azureAutomation", "networkMonitoring", "serviceMap"

Log Analytics, Type: Operation 

SourceSystem: OpsManager
TimeGenerated: 2018-02-17T12:03:23.897Z
Computer: test5-2
Type:Operation
OperationStatus: Warning
Detail: Two successive configuration applications from OMS Settings failed – please report issue to github.com/Microsoft/PowerShell-DSC-for-Linux/issues
OperationCategory: OMS Agent for Linux issue
Solution: Log Management

-- /var/opt/microsoft/omsagent/log/omsagent.log

2018-02-17 13:43:08 +0200 [info]: DSC AgentService Heartbeat success
2018-02-17 13:47:53 +0200 [info]: Sending OMS Heartbeat succeeded at 2018-02-17T11:47:53.858Z
2018-02-17 13:52:53 +0200 [info]: Sending OMS Heartbeat succeeded at 2018-02-17T11:52:53.860Z
2018-02-17 13:57:53 +0200 [info]: Sending OMS Heartbeat succeeded at 2018-02-17T11:57:53.862Z

-- /var/opt/microsoft/omsconfig/omsconfig.log

2018/02/17 14:30:39: WARNING: null(0): EventId=2 Priority=WARNING Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
Displaying messages from built-in DSC resources:
         WMI channel 1
         ResourceID:
         Message : [test5-2]:                            [] Starting consistency engine.
2018/02/17 14:30:39: WARNING: null(0): EventId=2 Priority=WARNING Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
Displaying messages from built-in DSC resources:
         WMI channel 1
         ResourceID:
         Message : [test5-2]:                            [] A pending configuration exists. DSC will process a set request on the pending configuration.
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 5. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [nxOMSPluginResource]nodepluginconf and SourceInfo is C:\temp\MicrosoftOperationsManagementLinuxConfiguration.ps1::50::1::nxOMSPluginResource. ErrorMessage is The specified class does not exist..
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 5. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [nxOMSGenerateInventoryMofResource]nodegenerateinventoryconf1 and SourceInfo is null. ErrorMessage is The specified class does not exist..
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 5. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [MSFT_nxOMSAutomationWorkerResource]AutoRegister01 and SourceInfo is null. ErrorMessage is The specified class does not exist..
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 5. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [MSFT_nxOMSAuditdPluginResource]AuditdPlugin and SourceInfo is null. ErrorMessage is The specified class does not exist..
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 5. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [nxOMSSudoCustomLogResource]nodecustomlogconf and SourceInfo is C:\temp\MicrosoftOperationsManagementLinuxConfiguration.ps1::30::1::nxOMSSudoCustomLogResource. ErrorMessage is The specified class does not exist..
2018/02/17 14:30:39: ERROR: null(0): EventId=1 Priority=ERROR Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
DSC Engine Error :
         Error Message Failed to apply the configuration.  These resources produced errors: [nxOMSPluginResource]nodepluginconf, [nxOMSGenerateInventoryMofResource]nodegenerateinventoryconf1, [MSFT_nxOMSAutomationWorkerResource]AutoRegister01, [MSFT_nxOMSAuditdPluginResource]AuditdPlugin, [nxOMSSudoCustomLogResource]nodecustomlogconf. Detailed error information can be found in the log file.
        Error Code : 5
2018/02/17 14:30:39: WARNING: null(0): EventId=2 Priority=WARNING Job C480EBC3-9F94-4914-8027-0280FFFFFFFF :
Displaying messages from built-in DSC resources:
         WMI channel 1
         ResourceID:
         Message : [test5-2]:                            [] Consistency check completed.
2018/02/17 14:30:50: WARNING: null(0): EventId=2 Priority=WARNING Job C480EBC3-9F94-4914-8027-0280FFFFFFFF : PerformRequiredConfigurationChecks DSC operation completed in 49.5192 seconds.

-- /var/opt/microsoft/omsconfig/omsconfigdetailed.log

2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Displaying messages from the engine:
         WMI channel 1 
         ResourceID: [nxOMSPluginResource]nodepluginconf
         Message : [test5-2]: LCM:  [ Start  Resource ]  [[nxOMSPluginResource]nodepluginconf]
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Getting a registration instance for MSFT_nxOMSPluginResource
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Moving the resource [nxOMSPluginResource]nodepluginconf of class MSFT_nxOMSPluginResource to desired state.
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF : 
Method Exec_WMIv2Provider started with parameters 
         Class name: MSFT_nxOMSPluginResource 
         Resource ID: [nxOMSPluginResource]nodepluginconf
         Flags: 134217984 
         Execution Mode: 192
         DSC resource Namespace: null
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Executing operations for WMIv2 DSC resource MSFT_nxOMSPluginResource with resource name [nxOMSPluginResource]nodepluginconf
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF : 
Invoking session and getting result for namespace root/oms, classname MSFT_nxOMSPluginResource for method TestTargetResource
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF : 
Displaying messages from the engine:
         WMI channel 1 
         ResourceID: [nxOMSPluginResource]nodepluginconf
         Message : [test5-2]: LCM:  [ Start  Test     ]  [[nxOMSPluginResource]nodepluginconf]
2018/02/17 14:33:24: ERROR: null(0): EventId=1 Priority=ERROR Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
DSC Engine Error : 
         Error Message Failed to apply the configuration.  These resources produced errors: [nxOMSPluginResource]nodepluginconf. Detailed error information can be found in the log file. 
        Error Code : 5 
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Displaying messages from the engine:
         WMI channel 1 
         ResourceID:  
         Message : [test5-2]: LCM:  [ *FAILED*Test     ]     Completed processing test operation. The operation failed.
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF : 
Method CallTestConfiguration ended successfully
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Setting Metaconfiguration instance. 
2018/02/17 14:33:24: INFO: null(0): EventId=3 Priority=INFO Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF :
Copying configuration file from MetaConfig.mof to MetaConfig.backup.mof.
2018/02/17 14:33:24: WARNING: null(0): EventId=2 Priority=WARNING Job AAE9F5A8-978A-4E3D-8027-0280FFFFFFFF : TestConfiguration DSC operation completed in 0.6155 seconds.

**Comment by shpimpal** [comment]
@amal-khalaf , can you help here?

**Comment by TheMP** [comment]
Having the same issue, did you manage to solve it?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
