### ISSUE TITLE
OMS agent new e-mail message every minute

### ISSUE THREAD

**Issue by asubmani** [Microsoft/OMS-Agent-for-Linux#648]
Using the latest version of the agent. 1.4.3-174 .

The server is running RHEL 6.9, and recieving logs from one ESXi 6.5 host. We can see the data in VMWare solution in OMS, but see the below message getting queued up in cron. The job is spooling a new message every minute.
`crontab -l
#* * * * * [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab`

**Copy of e-mail**
`Message 7021:
From root@inltiv-hamtest.contoso.com  Wed Feb 21 06:41:01 2018
Return-Path: <root@inltiv-hamtest.contoso.com>
X-Original-To: root
Delivered-To: root@inltiv-hamtest.contoso.com
From: root@inltiv-hamtest.contoso.com (Cron Daemon)
To: root@inltiv-hamtest.contoso.com
Subject: Cron <root@inltiv-hamtest> [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Date: Wed, 21 Feb 2018 06:41:01 -0700 (MST)
Status: R

src kt = /etc/krb5.keytab
File   /etc/krb5.keytab  does not exist
`

**Comment by NarineM** [comment]
Hi, this is an OMI bug and has been fixed in omi version 1.4.1.-2. .Please file omi bugs on OMI repo here: https://github.com/Microsoft/omi
This repo is tracking omsagent related issues. thanks.
