### ISSUE TITLE
option to disable environment variable logging

### ISSUE THREAD

**Issue by akramwaseem** [Microsoft/OMS-Agent-for-Linux#649]
When I run a container on a VM using docker , I can see the environment variable which has all of secrets or passwords. because of this we have to modify the filter_container.rb file to stop collecting the env variable.
Can you consider option to disable the env variable collection ?

**Comment by NarineM** [comment]
Please file a new issue on container docker provider GitHub repo. sorry, but this page is only monitoring oms agent related issues. thanks.
