### ISSUE TITLE
x64 checksums for 1.4.4 not matching

### ISSUE THREAD

**Issue by Cutriss** [Microsoft/OMS-Agent-for-Linux#659]
Trying to install this for the first time, the checksums aren't matching for the x64 version (both MD5 and SHA256). The x86 version matches correctly. I tried downloading with both wget and Firefox.
![checksums](https://user-images.githubusercontent.com/638297/37263336-90930d20-259f-11e8-995e-dbd447766934.png)

**Comment by akramwaseem** [comment]
Have the same issue here too.

**Comment by akramwaseem** [comment]
Seems like issue is fixed.

**Comment by shpimpal** [comment]
This was fixed, closing it.
