### ISSUE TITLE
Application Insight resource is showing connected to the OMS workspace which is already been deleted 2 month ago.

### ISSUE THREAD

**Issue by sid326** [Microsoft/OMS-Agent-for-Linux#660]
I have connected my application insights resource to the log Analytics OMS workspace using
log-analytics-app-insights-connector. After testing I have deleted the OMS workspace But when I again tried to connect that application insight resource to another OMS workspace its showing that it is already connected to some other workspace( Previous workspace which was deleted 2 months back). Why it is showing that it is already connected to the workspace when that workspace is deleted?? Can anyone please help with this. 

![image](https://user-images.githubusercontent.com/11275940/37328176-2f046af6-26bf-11e8-8b8a-456a3d20f82e.png)

**Comment by pixelicous** [comment]
Still an issue, over here as well! This should be considered a bug!!

**Comment by shpimpal** [comment]
Hi, can you please file the issue on Application Insights repo here - https://github.com/Microsoft/ApplicationInsights-Home . Thanks!

**Comment by pixelicous** [comment]
@shpimpal done, although this is not the only place where people shout out on this problem.. its been for a long time.. should be handled.

We overcame our problem with restoring original OMS..

**Comment by shpimpal** [comment]
Glad to know you could work around the problem. But this is the repo for OMS **agent** hence outside its the scope :). Closing this, thank you.

**Comment by pixelicous** [comment]
@shpimpal im not the original requster anyways :)
