### ISSUE TITLE
Very high memory consumption (>10GB)

### ISSUE THREAD

**Issue by mblaschke** [microsoft/OMS-Agent-for-Linux#665]
I'm experiencing on a regular base a very high memory consumption which **kills every service on the VM** because the OMSagent takes often more then 10 or 20 GB of memory.

This happens since at least some weeks. These screenshots are from two different nodes on the nearly exact time some hours before:

![image](https://user-images.githubusercontent.com/7583579/37564581-32f9216e-2a99-11e8-8aac-582afef0bff1.png)

![image](https://user-images.githubusercontent.com/7583579/37564588-49ceeed2-2a99-11e8-9e0f-1a4b33966297.png)

For a workaround please adjust the OOM score of the omsagent so the OMS agent is killed and not the services.

**Comment by okke-formsma** [comment]
We are running into the same issue occasionally. Our services are repeatedly killed until the OOM killer decides to kill OMSagent. Unfortunately by this time the server is usually crippled.

**Comment by mblaschke** [comment]
@okke-formsma 
Using Docker/Kubernetes?
Try to update the docker connector:

```
wget -O/root/docker-cimprov-1.0.0-31.universal.x86_64.sh https://github.com/Microsoft/Docker-Provider/releases/download/1.0.0-31/docker-cimprov-1.0.0-31.universal.x86_64.sh
sh /root/docker-cimprov-1.0.0-31.universal.x86_64.sh --purge
sh /root/docker-cimprov-1.0.0-31.universal.x86_64.sh --upgrade
rm -f /root/docker-cimprov-1.0.0-31.universal.x86_64.sh
```

But still omsagent should prevent this by setting a oms kill score. It's bad if the monitoring is not avialable but it's worse if our services are dying because of bug in a monitoring tool.

**Comment by okke-formsma** [comment]
@mblaschke thanks for the suggestion, I'm currently monitoring if the memory use stays stable on this newer version.

**Comment by KresoDenis** [comment]
Unfortunetly in our case --purge --upgrade didnt help. Only completely removing with --remove did solve it with kubernetes cluster.

**Comment by palmerabollo** [comment]
We're facing the same issue. OmsAgent is using more than 90% of the memory (>13GiB in our case). The only solution we have found is uninstalling the agent. It must have some kind of bug or memory leak.

**Comment by vishiy** [comment]
Can u please share  the omsagent version that has this issue ?

**Comment by mblaschke** [comment]
The one which is getting installed automatically when a Azure VM is created.

As workaround I'm killing the OMSagent regularly to avoid the common issues  (eg. high memory consumption, causing deadlocks in Docker daemon).

**Comment by vishiy** [comment]
@Microsoft/omsagent-devs

**Comment by johnkemnetz** [comment]
@mblaschke what version of the OMS agent are you running?

**Comment by mblaschke** [comment]
omsagent 1.6.0.42

At least this very high memory consumption seems to be fixed but we still see that omsagent is still increasing it's memory usage over runtime.

**Comment by KresoDenis** [comment]
I have put memory limits on omsagent via cgroup. But everytime before it hits limits and get OOM killed it makes kube containers go doown withunready status.

i tried upgrading docker-cimprov...etc. But it doesnt help.

If i dont use 
http://www.microsoft.com/oms
at all

Is it safe to completely uninstall OMSAgent with
```
 wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
 sudo sh onboard_agent.sh --purge
```
Is OMS required for anything critical besides OMS panel.

**Comment by temelj** [comment]
bump.

I am curious if there are any updates regarding this issue and/or why it may be happening in the first place?

![image](https://user-images.githubusercontent.com/8325278/46645157-efaf3400-cbc6-11e8-97dc-67f4b9270bd0.png)

**Comment by vishiy** [comment]
@temelj - do you know how many logs are generated across all containers in each node? we are working on optimizing memory for stdout/stderr container log collection which will go out in 2-3 weeks.

**Comment by temelj** [comment]
@vishiy  - we're hoping to update our cluster and re-check the behaviour.
Currently we're on 1.10.6 with an available upgrade to 1.11.3

I'm unfamiliar with the handling of logs on the cluster. Would you be able to point me in the right direction to investigate how logs are being handled on the cluster and to extract enough information to be able to answer your question.

**Comment by zerothabhishek** [comment]
We too are facing memory issues with omsagent on our VMs. Right now it is taking 253Mb RSS.
The VM has been quite unstable ever since we started using it (by enabling Security centre).

**Comment by mrnonz** [comment]
I still have this problem.

**Comment by agalisteo** [comment]
Same problem with AKS 1.11.3

**Comment by joby-thomas** [comment]
@agalisteo: How much memory usage are you seeing, the current agent has 300 MB limit for the DaemonSet POD, it cannot go beyond that. Could you please share a screenshot?

**Comment by vishiy** [comment]
@agalisteo - are you just oing with % used memory? We limit ourselves to 300 MB. We want to be running medium to little hot from time to time but stay with-in 300MB. Is that what you are seeing ?

**Comment by vishiy** [comment]
@agalisteo - Can you please tell us what you are seeing now ?

**Comment by agalisteo** [comment]
Solved upgrading to 1.11.5

**Comment by chadccollins** [comment]
I believe we are also seeing this issue on a cluster running 1.11.8.

**Comment by Boriszn** [comment]
Hey all. 

We have this issue on `1.13.5` on AKS cluster. (on the image below) 
Can some please suggest the solution ? 
Thanks a a lot in advance. 

![image](https://user-images.githubusercontent.com/12999498/60578790-21ce7a80-9d82-11e9-83a3-6584878e8332.png)

**Comment by vishiy** [comment]
@boriszn - the percentages you are seeing in the trend are with respect to the agent limits (300M) 77% is based in the container limit (not the node capacity)

**Comment by igor9silva** [comment]
It does seem to be an issue (in AKS, at least) that is still happening.

I was facing lots of memory pressure issues on one cluster only, which is very similar to others we have. The only differece was the `omsagent`. 

Uninstalling it (`az aks disable-addons -a monitoring -n cluster-name -g resource-group`) did the job. 

For Microsoft folks: It's very frustrating to face big issues like that and find out that there is people reporting it for more the 2 years now.

The ironic part is that I was only able to trace down the "guilty" using Azure Monitoring. And it was itself...

**Comment by vishiy** [comment]
is your cluster over commited? There are limits (150mc cpu, 600mi memory) for the agent, so it cannot take more than that.

**Comment by igor9silva** [comment]
@vishiy 
I wasn't being able to scale (to 1) a small statefulset (nor with 2Gi RAM as required, nor with 500Mi, nor with no requirements at all).

I had literally turned every deployment and statefulset down and yet not possible. The only one I've let running was traefik ingress controller. 

All I got was that:
![image](https://user-images.githubusercontent.com/3062866/88317352-87740880-ccef-11ea-828f-73728f957bf1.png)

I had downscaled to 1 node for debbuging (as this is a development environment), but same happened with 2 and 3 nodes - all said to have no mem available.

On the monitoring page (through Azure Portal), I had `omsagent` RAM usage ranging between 16 and 40% on all nodes as well.
![image](https://user-images.githubusercontent.com/3062866/88317877-47f9ec00-ccf0-11ea-8d22-26d287d4613c.png)

This cluster VM size is `Standard_B2s` (4 GiB RAM). K8s version was 1.14.8 (1.15.12 now - upgrade was done after the `omsagent` uninstalling and proper health checks - most likely not related).

**Comment by vishiy** [comment]
@igor9silva - Those % are based on the container limits when specified.

**Comment by igor9silva** [comment]
There were not limits explicitly defined for my pods. I'm not sure of the expected behaviour. What I've found is that:
![image](https://user-images.githubusercontent.com/3062866/88319112-1a15a700-ccf2-11ea-9fdf-df79d58a7875.png)
(https://docs.microsoft.com/en-us/azure/aks/developer-best-practices-resource-management)

On that same page there was no other pod using > 7%.

**Comment by vishiy** [comment]
Please set requests & limits. the % you see in the ux is w.r.t to limits if specified. If limits are not specified, it is w.r.t to nodes capacity. so 7% of node capacity will be more than say 20% of limits.

**Comment by pyron83** [comment]
I just experimented this issue on a Debian 10 kvm guest: omsagent randomly consumed all the ram and swap on the VM, and oom_reaper started killing processes trying to free memory, in fact stopping every service running on the machine.

**Comment by MarcelT-NL** [comment]
Same thing is happening to our AKS cluster (1.19.3). 

OMSagent will consume a LOT of memory, and then all pods are evicted by OOMkiller due to disk constraints. I would love to lose some logs in favor of keeping production running. Is there any way to cap OMS?

**Comment by vishiy** [comment]
@MarcelT-NL  - Can you explain what you mean by 'cap' ? These containers should have limits so that it they wont take over the cluster.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
