### ISSUE TITLE
Azure OMS Agent Install Fails on Clear Linux

### ISSUE THREAD

**Issue by kamsalisbury** [Microsoft/OMS-Agent-for-Linux#679]
The OMS AGent Linux install as directed from the OMS Log Analytics Advanced Settings blade;

wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh && sh onboard_agent.sh -w long-workspace-guid -s super-long-oms-workspace-key -d opinsights.azure.com

The downloaded OMS agent installer script tests for an RPM or DPKG installer but does not error trap and inform the console the script cannot continue on non-RPM/DPKG distributions (Clear Linux OS).

Connecting to github-production-release-asset-2e65be.s3.amazonaws.com|52.216.131.107|:443... connected. 
HTTP request sent, awaiting response... 200 OK 
Length: 114996853 (110M) [application/octet-stream] 
Saving to: âomsagent-1.4.4-210.universal.x64.shâ

omsagent-1.4.4-210. 100%[===================>] 109.67M 8.08MB/s in 14s

2018-03-23 23:00:23 (8.08 MB/s) - âomsagent-1.4.4-210.universal.x64.shâ saved [114996853/114996853]

Checking host architecture ... 
Extracting... 
Updating OMS agent ... 
----- Checking package: omsagent (omsagent-1.4.4-210.universal.x64) ----- 
----- Checking package: omsconfig (omsconfig-1.1.1-681.x64) ----- 
Extracting... 
Updating cross-platform agent ... 
----- Upgrading package: omi (omi-1.4.2-1.ulinux.x64) ----- 
./bundles/scx-1.6.3-527.universal.x64.sh: line 303: rpm: command not found 
----- Upgrading package: scx (scx-1.6.3-527.universal.x64) ----- 
./bundles/scx-1.6.3-527.universal.x64.sh: line 303: rpm: command not found 
----- Removing package: scx ----- 
./bundles/scx-1.6.3-527.universal.x64.sh: line 269: rpm: command not found 
----- Removing package: omi ----- 
./bundles/scx-1.6.3-527.universal.x64.sh: line 269: rpm: command not found 
----- Installing package: omi (omi-1.4.2-1.ulinux.x64) ----- 
./bundles/scx-1.6.3-527.universal.x64.sh: line 249: rpm: command not found 
Upgrade failed.

I recommend adding error trapping to the installer script to inform that only RPM or DPKG platforms are supported *or* add support for non-RPM/DPKG platforms.

**Comment by shpimpal** [comment]
Hi, thanks for reporting this. Right now only dpkg and rpm based systems are supported. But will add the error trapping for non dpkg/rpm systems.

**Comment by shpimpal** [comment]
Hi, this has been fixed in #710.
Thanks!
