### ISSUE TITLE
Unable to see syslog data in log analytics after installing the OMS through extension

### ISSUE THREAD

**Issue by akramwaseem** [Microsoft/OMS-Agent-for-Linux#683]
I was trying to install the OMS through the arm template using the extension mechanisam provided by Microsoft, Seems like it was able to install the OMS but I cannot see the syslog data at all.
I can only see heartbeat and perf data .
Below msg is what I get in log analytics.

OperationStatus | Warning
-- | --
  | Detail | Two successive configuration applications from OMS Settings failed – please report issue to github.com/Microsoft/PowerShell-DSC-for-Linux/issues
  | OperationCategory | OMS Agent for Linux issue
  | Solution | Log Management

I am using ubuntu 14.04.5 Machine and it is a VMSS machine .

**Comment by NarineM** [comment]
First , you need to enable syslog data collections in your workspace, save workspace changes, then the VMs that are connected to that workspace will start sending syslog. Syslog is not collected by default.

**Comment by akramwaseem** [comment]
Issue is  still the same. Even after configuring in the log analytics workspace. it doesn't get resolved.

**Comment by akramwaseem** [comment]
This is being resolved offline. Closing this for now.
