### ISSUE TITLE
SysLogMessage not complete

### ISSUE THREAD

**Issue by tomaaa** [Microsoft/OMS-Agent-for-Linux#684]
Hello,
my firewall is logging data with syslog on hardrive with rsyslog. Everything is working fine. However, when I use Azure Log Analytics, the SyslogMessage column is not complete, unfortunatly, the beginning of the string is missing even though they are complete in my flat file.

I don't find any working solution for this.

Example:
From my flat file:
Apr  4 16:19:51 myserver MyProcessName ﻿ 11.11.111.123 - - [04/Apr/2018:16:19:51 -0400] "GET https://abc.com/notifications HTTP/1.1" 200 74

From Azure Logs Analytics
16:19:51 -0400] "GET https://abc.com/notifications HTTP/1.1" 200 74 

Thanks

**Comment by shpimpal** [comment]
Hi, have you changed any configuration related to syslog or its format/filtering?

**Comment by tomaaa** [comment]
Hi, 
I tried but didn't work and I don't understand how filtering works.

**Comment by NarineM** [comment]
For devices that do not generate syslog messages that are compliant with fluentd default syslog filter, you can use this guide to setup custom syslog filters: https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#install-the-oms-agent-for-linux

"...........
Customizing syslog log format using FluentD's format regular expression parameter if syslog data shows up truncated in OMS portal

OMS agent syslog configuration /etc/opt/microsoft/omsagent/<your_wid>/conf/omsagent.d/syslog.conf is using FluentD's default syslog log format. If your device is generating non-standard syslog formats you can add custom filters to syslog.conf through fluentd 'format' parameter as regexp as documented here.

You can use rubular tool that can help to easily write regular expressions like shown in this example.
"

**Comment by shpimpal** [comment]
Hello @tomaaa , was your issue resolved? Closing it for now, please re-open if issue exists. Thanks!

**Comment by PhantoManresa** [comment]
Hi, I am having this very same issue. The message is truncated at the first colon. I looked the filters but there is nothing beyond the default. I even tried adding a "msg:" to the beginning of the message in a new filter before the oms filter takes place, with the purpose of having a dummy text before the first colon, but it is added after the message was truncated. 
If I save the message in a local file, then the message is complete.

The example provided at the beginning by @tomaaa fully reflects my problem.

Any help is appreciated. Thanks
