### ISSUE TITLE
OMS receiving only heartbeat from connector

### ISSUE THREAD

**Issue by txdotnetdev** [Microsoft/OMS-Agent-for-Linux#685]
I've gone through the troubleshooting guide. I've purged and re-onboarded the connector on my Azure Linux VM and all I ever seem to get from it is the heartbeat. I'm running Ubuntu 16.04. I've set up the data tab in OMS to report Linux Performance Indicators and Custom Logs and Syslogs. I have yet to receive any of those.  When I look through the logs, I see no indication that a configuration is downloaded from OMS at any point. If I attempt to run any of the python scripts for the DSC, they fail with the following message:

root@deaiotrunaboutnode1:~# sudo su omsagent -c '/opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py'
instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=A general error occurred, not covered by a more specific error code.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
}

/opt/omi/bin/omicli: result: MI_RESULT_FAILED
/opt/omi/bin/omicli: result: A general error occurred, not covered by a more specific error code.

Nothing particularly helpful there.  There is no omsconfig.log file, so I can't get any information from there. Checking the OMI client log provides me with the following, but I'm using the latest cURL package:

2018/04/06 18:45:01 [106935,106935] WARNING: null(0): EventId=30042 Priority=WARNING cannot open shared library: {/opt/omi/lib/libomsconfig.so}: /opt/omi/lib/libcurl.so.3: symbol curl_multi_fdset, version CURL_OPENSSL_3 not defined in file libcurl.so.4 with link time reference
2018/04/06 18:45:01 [106935,106935] WARNING: null(0): EventId=30041 Priority=WARNING cannot open shared library: {omsconfig}: omsconfig: cannot open shared object file: No such file or directory
2018/04/06 18:45:01 [106935,106935] WARNING: null(0): EventId=30065 Priority=WARNING failed to open provider library: omsconfig
2018/04/06 18:45:01 [106935,106935] ERROR: null(0): EventId=20001 Priority=ERROR Agent _RequestCallback: ProvMgr_NewRequest failed with result 1 !

The only other thing that struck me as potentially odd is this message during onboarding:

Generating certificate with hostname="deaiotrunaboutnode1", domainname="qe3so2gr                                                                                                                                                             4c4exexz4czj5ap2ha.jx.internal.cloudapp.net"
Error generating SSL certificate.  Use scxsslconfig to generate a new certificat                                                                                                                                                             e, specifying host and domain names if necessary.  The error was: 'Unable to add                                                                                                                                                              the domain name to the subject.'
Hostname or domain likely not RFC compliant, trying fallback: "localhost.local"
Generating certificate with hostname="localhost", domainname="local"

Any ideas for me to try? Do I need to assign a DNS name to my server? I haven't seen any documentation as to that respect.

**Comment by txdotnetdev** [comment]
I went and ran an ls -l on my /opt/omi/lib directory to see if that provides any useful information and this is the output of that:

root@deaiotrunaboutnode1:/opt/omi/lib# ls -l
total 8560
lrwxrwxrwx 1 root     root          40 Apr  6 18:56 libcrypto.so.1.0.0 -> /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
lrwxrwxrwx 1 root     root          40 Apr  6 17:05 libcurl.so.3 -> /usr/lib/x86_64-linux-gnu/libcurlpp.so.0
lrwxrwxrwx 1 root     root          40 Apr  6 17:05 libcurl.so.4 -> /usr/lib/x86_64-linux-gnu/libcurlpp.so.0
-rwxr-xr-x 1 root     root      168472 Feb  1 23:30 libmicxx.so
-rwxr-xr-x 1 root     root      726600 Feb  1 23:30 libmi.so
-rw-r--r-- 1 omsagent omiusers 1029995 Apr  6 17:05 libMSFT_nxAvailableUpdatesResource.so
-rw-r--r-- 1 omsagent omiusers 1044603 Apr  6 17:05 libMSFT_nxFileInventoryResource.so
-rw-r--r-- 1 omsagent omiusers 1027820 Apr  6 17:05 libMSFT_nxGroupResource.so
-rw-r--r-- 1 omsagent omiusers  443606 Apr  6 17:05 libMSFT_nxOMSKeyMgmtResource.so
-rw-r--r-- 1 omsagent omiusers  447616 Apr  6 17:05 libMSFT_nxOMSPerfCounterResource.so
-rw-r--r-- 1 omsagent omiusers  444264 Apr  6 17:05 libMSFT_nxOMSSyslogResource.so
-rw-r--r-- 1 omsagent omiusers 1035896 Apr  6 17:05 libMSFT_nxPackageResource.so
-rw-r--r-- 1 omsagent omiusers 1030879 Apr  6 17:05 libMSFT_nxServiceResource.so
-rw-r--r-- 1 omsagent omiusers 1029863 Apr  6 17:05 libMSFT_nxUserResource.so
-rwxr-xr-x 1 root     root      246312 Feb  1 23:30 libomiclient.so
-rwxr-xr-x 1 root     root       53280 Feb  1 23:30 libomiidentify.so
lrwxrwxrwx 1 root     root          44 Apr  6 17:05 libomsconfig.so -> /opt/microsoft/omsconfig/lib/libomsconfig.so
lrwxrwxrwx 1 root     root          50 Feb  7 03:25 libSCXCoreProviderModule.so -> /opt/microsoft/scx/lib/libSCXCoreProviderModule.so
lrwxrwxrwx 1 root     root          37 Apr  6 18:56 libssl.so.1.0.0 -> /lib/x86_64-linux-gnu/libssl.so.1.0.0
drwxr-xr-x 5 root     root        4096 Apr  6 17:05 Scripts

**Comment by txdotnetdev** [comment]
This is the output of the ps aux command you posted:

root@deaiotrunaboutnode0:~# ps aux | grep omi
root       9380  0.0  0.0  12944   924 pts/0    S+   14:27   0:00 grep --color=auto omi
root      58851  0.0  0.0  20768  2616 ?        S    Apr09   0:13 /opt/omi/bin/omiserver -d
omi       58852  0.0  0.0  20760  1856 ?        S    Apr09   0:11 /opt/omi/bin/omiengine -d --logfilefd 3 --socketpair 9
root      58929  0.0  0.0 173136  9136 ?        Sl   Apr09   2:32 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING
omsagent  59105  0.0  0.0  29564  4320 ?        S    Apr09   0:09 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING

Both of the python commands result in:

instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=A general error occurred, not covered by a more specific error code.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
}

/opt/omi/bin/omicli: result: MI_RESULT_FAILED
/opt/omi/bin/omicli: result: A general error occurred, not covered by a more specific error code.

**Comment by txdotnetdev** [comment]
One item of note is that I have two servers that are otherwise identical. On my other server, I pointed the symlinks for libcurl to their appropriate SOs in /bin/local instead of the libcurlpp it was pointing to and the python scripts would then succeed, but I still got no change in my main issue. I'll admit my Linux is very weak, so I don't know if that means anything at all.

**Comment by txdotnetdev** [comment]
For reference, this is the output of the python scripts from the other VM:

root@deaiotrunaboutnode1:/opt/omi/lib# sudo su omsagent -c '/opt/microsoft/omsconfig/Scripts/GetDscLocalConfigurationManager.py'
instance of GetMetaConfiguration
{
    ReturnValue=0
    MetaConfiguration=    instance of MSFT_DSCMetaConfiguration
    {
        ConfigurationModeFrequencyMins=30
        RebootNodeIfNeeded=false
        ConfigurationMode=ApplyAndMonitor
        Credential=NULL
        RefreshMode=PUSH
        CertificateID=NULL
        ConfigurationID=NULL
        DownloadManagerName=NULL
        DownloadManagerCustomData=NULL
        RefreshFrequencyMins=1
        AllowModuleOverwrite=false
        LocalConfigurationManagerState=Busy
        ConfigurationDownloadManagers=NULL
        ResourceModuleManagers=NULL
        ReportManagers=NULL
        PartialConfigurations=NULL
        ActionAfterReboot=NULL
        DebugMode=NULL
        LCMVersion=NULL
        LCMCompatibleVersions=NULL
        LCMState=NULL
        LCMStateDetail=NULL
        StatusRetentionTimeInDays=NULL
        AgentId=c0954c5f-92a9-4e0f-bc52-afcb9c07a4d4
        EnableSignatureValidation=NULL
        DisableModuleSignatureValidation=NULL
    }
}


root@deaiotrunaboutnode1:/opt/omi/lib# sudo su omsagent -c '/opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py'
instance of PerformRequiredConfigurationChecks
{
    ReturnValue=0
}

**Comment by NarineM** [comment]
Sorry, this repo is not monitoring DSC (omsconfig) related issues. Please file an issue on https://github.com/Microsoft/PowerShell-DSC-for-Linux instead.

**Comment by arlliu** [comment]
I have the same issue, still open there. any help? thanks
