### ISSUE TITLE
Inconsistent heartbeat interval

### ISSUE THREAD

**Issue by JanVanMeirvenne** [microsoft/OMS-Agent-for-Linux#687]
[omsagent.log](https://github.com/Microsoft/OMS-Agent-for-Linux/files/1888888/omsagent.log)

One of my customers has a Docker Swarm setup with the OMS monitoring solution on top of it. For some nodes with the (latest) Linux agent installed, we notice varying intervals of heartbeats not being sent. This results in false positives. I already tried to set the heartbeat interval to 1 minute per [this](https://cloudadministrator.wordpress.com/2018/02/23/configure-oms-linux-agent-heartbeat-interval/) blogpost. I see the value changing in the log-file, but the process still stalls often.

Is this related to an environmental issue (I see connection errors), or a possible conflict on the side of the agent setup?

Thanks in advance for your opinion!

Regards,
Jan

**Comment by hestolz** [comment]
Realizing this is a very old issue, its hard to make a definite conclusion. Connection errors could be a cause, as could the container solution—I have seen cases in the past where container inventory etc. interferes with heartbeat function. If you still have the issue with the latest agent versions you should open a support ticket.
