### ISSUE TITLE
How to find the current running OMS agent on a Linux Machine?

### ISSUE THREAD

**Issue by akramwaseem** [Microsoft/OMS-Agent-for-Linux#688]
Hi,
I am trying to find the current version of OMS agent running on a linux machine .Not sure how to find it .

**Comment by zidormi** [comment]
apt list --installed | grep omsagent

Should return this:
apt list --installed | grep omsagent
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
omsagent/now 1.4.4.210 amd64 [installed,local]

**Comment by akramwaseem** [comment]
yep, it worked. Thanks
