### ISSUE TITLE
OMS-Agent-for-Linux not work on openSUSE Leap 42.3

### ISSUE THREAD

**Issue by sakanamax** [microsoft/OMS-Agent-for-Linux#690]
There is openSUSE Leap 42.3 linux in Azure.
I could success install omsagent in openSUSE Leap 42.3 but in OMS it show there is no connect with openSUSE Leap 42.3.
openSUSE Leap 42.3 is like SLES 12.
Please consider support openSUSE Leap linux

**Comment by NarineM** [comment]
Can you provide the console output from the bundle installer?

**Comment by sakanamax** [comment]
Hi, Thanks for the reply

The console output is here

========================
100%[===================================================================>] 114,996,853 64.5MB/s   in 1.7s   

2018-04-27 04:09:24 (64.5 MB/s) - ‘omsagent-1.4.4-210.universal.x64.sh’ saved [114996853/114996853]

Checking host architecture ...
Extracting...
Updating OMS agent ...
----- Checking package: omsagent (omsagent-1.4.4-210.universal.x64) -----
----- Checking package: omsconfig (omsconfig-1.1.1-681.x64) -----
Extracting...
Updating cross-platform agent ...
----- Upgrading package: omi (omi-1.4.2-1.ulinux.x64) -----
Creating omiusers group ...
Creating omi group ...
Creating omi service account ...
Generating a 2048 bit RSA private key
.....................................................................................................+++
.....................................................................+++
writing new private key to '/etc/opt/omi/ssl/omikey.pem'
-----
2018-04-27 04:09:34 : Crontab not configured to update omi keytab automatically. Skip unconfigure
2018-04-27 04:09:34 : Crontab configured to update omi keytab automatically
Configuring OMI service ...
Created symlink from /etc/systemd/system/multi-user.target.wants/omid.service to /usr/lib/systemd/system/omid.service.
----- Upgrading package: scx (scx-1.6.3-527.universal.x64) -----
Generating certificate with hostname="test01", domainname="x0vsndny2n1e3f2pyg5nchrboh.bx.internal.cloudapp.net"
----- Updating bundled packages -----
Checking if Apache is installed ...
  Apache not found, will not install
Checking if MySQL is installed ...
  MySQL not found, will not install
Preparing...                          ################################# [100%]
Creating omsagent group ...
Creating omsagent service account ...
Creating nxautomation group ...
Creating nxautomation service account ...
Updating / installing...
   1:omsagent-1.4.4-210               ################################# [ 50%]
info	Setting process limit for the omsagent user in /etc/security/limits.conf to 75...
info	Reading onboarding params from: /etc/omsagent-onboard.conf
Workspace 13f5c68d-55e0-40f1-b9e4-5ae4e4df449c already onboarded and agent is running.
Symbolic links have not been created; re-onboarding to create them
info	Generating certificate ...
info	Agent GUID is 2e2a8cb1-6e6e-4d20-963f-11ac8ec2b004
info	Onboarding success
Configure syslog...
No supported syslog daemon found. Syslog messages will not be processed.
Configure heartbeat monitoring agent...
Configure log rotate for workspace 13f5c68d-55e0-40f1-b9e4-5ae4e4df449c...
INFO:  Configuring OMS agent service 13f5c68d-55e0-40f1-b9e4-5ae4e4df449c ...
-bash: /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py: No such file or directory
error	MetaConfig generation script not available at /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py
Configure log rotate for workspace 13f5c68d-55e0-40f1-b9e4-5ae4e4df449c...
Checking for ctypes python module...
   2:omsconfig-1.1.1-681              ################################# [100%]
Extracting to /opt/microsoft/omsconfig/modules
Installing resource MSFT_nxUserResource
Installing resource MSFT_nxServiceResource
Installing resource MSFT_nxAvailableUpdatesResource
Installing resource MSFT_nxPackageResource
Installing resource MSFT_nxGroupResource
Extracting to /opt/microsoft/omsconfig/modules
Installing resource MSFT_nxOMSPerfCounterResource
Extracting to /opt/microsoft/omsconfig/modules
Installing resource MSFT_nxOMSSyslogResource
Extracting to /opt/microsoft/omsconfig/modules
Installing resource MSFT_nxOMSKeyMgmtResource
Extracting to /opt/microsoft/omsconfig/modules
Installing resource MSFT_nxFileInventoryResource
gpg: directory `/etc/opt/omi/conf/omsconfig/.gnupg' created
gpg: new configuration file `/etc/opt/omi/conf/omsconfig/.gnupg/gpg.conf' created
gpg: WARNING: options in `/etc/opt/omi/conf/omsconfig/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/etc/opt/omi/conf/omsconfig/.gnupg/secring.gpg' created
gpg: keyring `/etc/opt/omi/conf/omsconfig/keymgmtring.gpg' created
gpg: /etc/opt/omi/conf/omsconfig/.gnupg/trustdb.gpg: trustdb created
gpg: key 44BC4178: public key "Microsoft (Release Signing) <msgpgkey@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: keyring `/etc/opt/omi/conf/omsconfig/keyring.gpg' created
gpg: key DE321294: public key "Microsoft (Release Signing) <dscgpgkey@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Successfully configured omsconfig.
----- Updating bundled packages -----
Checking if Docker is installed...
  Docker is not listening on /var/run/docker.sock. Docker agent will not be installed.
Checking if required dependencies for auoms are installed...
Extracting...
Updating auoms ...
----- Updating package: auoms (auoms-1.0.0-2.universal.x64) -----
Restarting auditd
Shell bundle exiting with code 0
================================================================

Shell bundle exiting with code 0

I check OMS in Azure, but still show this VM( in Azure ) is not connect

**Comment by shpimpal** [comment]
Hi, can you please get the log files as well ? 
Please run the log collector tool as described here - https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md#im-unable-to-connect-through-my-proxy-to-oms

**Comment by Petkuchev** [comment]
Hi, whenever you install the agent manually, its status will not be reflected in the portal. To verify that it is still running, check Log Analytics for  received data:

Heartbeat
| where Computer == "vmname"

Check if the service is running:
 systemctl status omsagent.service

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
