### ISSUE TITLE
Feed logs to event hubs

### ISSUE THREAD

**Issue by parsoFish** [microsoft/OMS-Agent-for-Linux#692]
As the OMS agent for linux cannot be configured to report to more than one Log Analytics workspace but this may be desired behaviour what would be the feasability of modifying the log collector to instead feed to an aggregator such as event hubs. Not only would this allow for mutliple OMS workspaces to subscribe to the event hub but other applications also could.

**Comment by ArtemProc** [comment]
Hello, you can check fluentd plugin for Azure EventHub
https://github.com/htgc/fluent-plugin-azureeventhubs 

So you can setup data upload to Event Hub this way.

P. S. Basically under the hood OMS Agent uses fluentd right now to upload data if you check folders and logs + conf files you will notice that.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
