### ISSUE TITLE
No syslogs showing in log analytics

### ISSUE THREAD

**Issue by Strandedpirate** [Microsoft/OMS-Agent-for-Linux#697]
I have the OMS agent chart from https://github.com/kubernetes/charts/tree/master/stable/msoms installed in multiple k8s clusters for a while and we do receive some heartbeat and container data but the syslog's for the nodes are node being pumped in. 

I tried following this guide but the portal won't allow me to add a "facility".

https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#configuring-syslog-collection-from-the-oms-portal

![image](https://user-images.githubusercontent.com/1452996/39208721-6a246c0a-47c9-11e8-8117-4b6ce3cc23a2.png)

What do I need to do to get the logs from the k8s master and nodes to send their logs to OMS?

**Comment by shpimpal** [comment]
Hi @Strandedpirate , was this resolved ? I'm closing it, please re-open if you still have the issue.
