### ISSUE TITLE
Network Bytes/sec

### ISSUE THREAD

**Issue by rcarmo** [microsoft/OMS-Agent-for-Linux#701]
There should be a performance counter for this. Right now, the total counters, being monotonic, make it hard to plot bandwidth charts per time interval.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
