### ISSUE TITLE
What's the difference between --install and --upgrade when on-boarding the OMS agent on a linux machine.

### ISSUE THREAD

**Issue by akramwaseem** [Microsoft/OMS-Agent-for-Linux#705]
I want to know the difference between the --install and --upgrade.
I can see it in the documentation but what difference does it make when installing the OMS agent.
If I do --install -w -s, does that make the on-boarding successfull for OMS or do I need to --upgrade -w -s to onboard it.
What scenario would it be when OMS agent is installed using the OMS extension , do we need to do additional functionality  like --upgrade too ?

If you look at the below documentation, is this information still credible.
Onboarding using the command line
Run the omsadmin.sh command supplying the workspace id and key for your workspace. This command must be run as root (w/ sudo elevation):

cd /opt/microsoft/omsagent/bin
sudo ./omsadmin.sh -w <WorkspaceID> -s <Shared Key>

How does the above scenario comes into play when installing the OMS agent through the extension ?

**Comment by shpimpal** [comment]
With --install, it will onboard if you provide workspace and key. --upgrade too will do the same, it will additionally upgrade the packages over older installed ones, while --install won't upgrade if older version is installed. 
The script omsadmin is to onboard explicitly, for example when you want to onboard to another workspace. You can check more options with -h option.

**Comment by akramwaseem** [comment]
thanks for the info.
