### ISSUE TITLE
problem installing with omsagent-1.6.0-42.universal.x86.sh with openssl1.1 >> "dpkg: error: cannot access archive '110/[...]"

### ISSUE THREAD

**Issue by wowolla** [Microsoft/OMS-Agent-for-Linux#706]
I'm installing v1.6.0-42 with:
sudo sh ./omsagent-1.6.0-42.universal.x86.sh --upgrade -w <workspace id> -s <shared key>
but it reports errors after extracting:
----- Upgrading package: omi (omi-1.4.2-2.ulinux.x86) -----
dpkg: error: cannot access archive '110/omi-1.4.2-2.ulinux.x86.deb': No such file or directory
----- Upgrading package: scx (scx-1.6.3-559.universal.x86) -----
dpkg: error: cannot access archive '110/scx-1.6.3-559.universal.x86.deb': No such file or directory

I tried on different servers with the same result. With x64 architecture everything worked.

Then I tried extracting:
sudo sh ./omsagent-1.6.0-42.universal.x86.sh --extract
and I find that dir 110 doesn't exists (that dir refers to openssl 1.1). There are only 098 and 100 dirs.

Could you help me? Thanks!

**Comment by shpimpal** [comment]
Hi, there is no support for openssl-1.1.0 for oms agent on x86 systems.
