### ISSUE TITLE
omsagent log  can’t rotate on [Debian 8 x86] and [Debian 9 x64] with selinux enabled.

### ISSUE THREAD

**Issue by jaelynch** [microsoft/OMS-Agent-for-Linux#708]
### ENV

> **Server:**  SCXOM-W12-07S(10.225.197.68 )
> **Client:**  omt64-deb9-01(10.248.217.120) -- SELinux enabled
>            omt86-deb8-02(10.248.246.69) -- SELinux enabled 
> **OMS Agent Location:** \\\redmond.corp.microsoft.com\wsscfs\OMS\OMSData\builds\omsagent\develop\1.6.0-42

### Repro Steps

1. Enable SELinux

> 1) apt-get install selinux-basics selinux-policy-default auditd
> 2) selinux-activate
> 3) reboot
> 4) check-selinux-installation
> 5) setenforce 1
>     echo "enforcing=1" >> /etc/default/grub
>     vi /etc/selinux/config
>             SELINUX=enforcing

2. Install oms agent
3. Wait for omsagent log file to cross 10M or add text in omsagent logfile so that it crosses 10M.
4. Once it crosses the 10M threshold limit the omsagent log file should get rotated but we have observed that it is not getting rotated.
5. In audit log we have observed that log rotation has denied.

**Comment by sarojcare** [comment]
**Initial Investigation:**

**Comment by sarojcare** [comment]
Relevent Log From audit log:

type=AVC msg=audit(1526286901.033:4967): avc:  denied  { getattr } for  pid=17365 comm="logrotate" path="/var/opt/microsoft/scx/log/scx.log" dev="dm-0" ino=394979 scontext=system_u:system_r:logrotate_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:var_t:s0 tclass=file permissive=0
type=SYSCALL msg=audit(1526286901.033:4967): arch=40000003 syscall=196 success=no exit=-13 a0=89299a0 a1=bfa64e0c a2=8929188 a3=8929058 items=0 ppid=17364 pid=17365 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=473 comm="logrotate" exe="/usr/sbin/logrotate" subj=system_u:system_r:logrotate_t:s0-s0:c0.c1023 key=(null)
type=PROCTITLE msg=audit(1526286901.033:4967): proctitle=2F7573722F7362696E2F6C6F67726F74617465002F6574632F6C6F67726F746174652E642F7363786167656E74
type=AVC msg=audit(1526286901.033:4968): avc:  denied  { read } for  pid=17365 comm="logrotate" name="log" dev="dm-0" ino=394973 scontext=system_u:system_r:logrotate_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_t:s0 tclass=dir permissive=0
type=SYSCALL msg=audit(1526286901.033:4968): arch=40000003 syscall=5 success=no exit=-13 a0=bfa64a20 a1=98800 a2=2a a3=2004 items=0 ppid=17364 pid=17365 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=473 comm="logrotate" exe="/usr/sbin/logrotate" subj=system_u:system_r:logrotate_t:s0-s0:c0.c1023 key=(null)
type=PROCTITLE msg=audit(1526286901.033:4968): proctitle=2F7573722F7362696E2F6C6F67726F74617465002F6574632F6C6F67726F746174652E642F7363786167656E74
type=AVC msg=audit(1526286901.033:4969): avc:  denied  { getattr } for  pid=17365 comm="logrotate" path="/var/opt/microsoft/scx/log/scx.log" dev="dm-0" ino=394979 scontext=system_u:system_r:logrotate_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:var_t:s0 tclass=file permissive=0
type=SYSCALL msg=audit(1526286901.033:4969): arch=40000003 syscall=196 success=no exit=-13 a0=89299c8 a1=bfa6519c a2=0 a3=bfa6519c items=0 ppid=17364 pid=17365 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=473 comm="logrotate" exe="/usr/sbin/logrotate" subj=system_u:system_r:logrotate_t:s0-s0:c0.c1023 key=(null)

**Comment by hestolz** [comment]
Fixed #376
