### ISSUE TITLE
heartbeat diagnostic logging issue

### ISSUE THREAD

**Issue by AlexL-CC** [microsoft/OMS-Agent-for-Linux#717]
As far as I can see,  file `source/code/plugins/in_dsc_monitor.rb` in function `check_install` should check whether package omsconfig  is installed and print warning if not. In fact it does not work for ubuntu: in the `log search` at Azure portal I see "omsconfig is not installed, OMS Portal configuration will not be applied and solutions..." but the package is installed:

```
root@myVM:~# dpkg --list omsconfig
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                   Version          Architecture     Description
+++-======================-================-================-==================================================
ii  omsconfig              1.1.1.728        amd64            Operations Management Suite Agent Configuration
root@myVM:~# dpkg --list omsconfig > /dev/null 2>&1; echo $?
0
```

Also, it'd be nice to add to the error message something like "you may try to install it with `apt-get install omsconfig -y` or `yum install omsconfig -y`"

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
