### ISSUE TITLE
Container Insights through Portal creating duplicate Solutions

### ISSUE THREAD

**Issue by temelj** [microsoft/OMS-Agent-for-Linux#720]
I'm not sure if this is an issue for the Azure Portal or related to the OMS Agent.
And if it is Portal related, where could I log it? Under which project?

I've created a test K8 Cluster through the portal and enabled container monitoring.
The Log Analytics Workspace gets created - "DefaultWorkspace-GUID-EUS".

This creates a "**ContainerInsights(DefaultWorkspace-GUID-EUS)**" solution.

Just to clarify:  By default - under the OMS Workspace The Linux Server agent is connected (see Advanced Settings).

However, The summary shows no data and no Solution Resources is present.

If you then "Create a resource" - "Container Monitoring Solution" and associate it to the existing OMS Workspace, it does not associate it to the existing solution.

Instead it creates a new one called "**Containers(DefaultWorkspace-GUID-EUS)**". The new one then shows the analytics summary & the linked Solution Resource.

It his the expected behaviour or am I not associating the agent to my solution correctly?

**Comment by ArtemProc** [comment]
Hi how you have create K8S as Service or as Azure Container Services?
You added ContainerInsights AFAIK this added as part of Health (Preview) for K8S Service created as Service.
So this will add moniotring Configuration but not OMS/LA Tile

**Comment by keikhara** [comment]
@temelj ContainerInsights and Container Monitoring Solutions are 2 different product which just happens to use log analytics in the backend. When you say, you are not seeing any data, this is on the container health page?
