### ISSUE TITLE
Issue with installing OMS agent on Debian i386

### ISSUE THREAD

**Issue by ondrejvysek** [Microsoft/OMS-Agent-for-Linux#721]
When installing OMS agent on Debian v9 i386 (32bit), I'm receiving error during installation and agent is not installed. 
Debian is fresh new install, updated, OS details:
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch
here is the console output during agent installation:
2018-06-05 20:03:34 (815 KB/s) - ‘omsagent-1.6.0-42.universal.x86.sh’ saved [106529191/106529191]
Checking host architecture ...
curl was not found; attempting to install curl...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcurl3
The following NEW packages will be installed:
  curl libcurl3
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 545 kB of archives.
After this operation, 1,049 kB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security stretch/updates/main i386 libcurl3 i386 7.52.1-5+deb9u6 [315 kB]
Get:2 http://security.debian.org/debian-security stretch/updates/main i386 curl i386 7.52.1-5+deb9u6 [230 kB]
Fetched 545 kB in 1s (407 kB/s)
Selecting previously unselected package libcurl3:i386.
(Reading database ... 26652 files and directories currently installed.)
Preparing to unpack .../libcurl3_7.52.1-5+deb9u6_i386.deb ...
Unpacking libcurl3:i386 (7.52.1-5+deb9u6) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.52.1-5+deb9u6_i386.deb ...
Unpacking curl (7.52.1-5+deb9u6) ...
Setting up libcurl3:i386 (7.52.1-5+deb9u6) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up curl (7.52.1-5+deb9u6) ...
Extracting...
----- Upgrading package: omi (omi-1.4.2-2.ulinux.x86) -----
dpkg: error: cannot access archive '110/omi-1.4.2-2.ulinux.x86.deb': No such file or directory
----- Upgrading package: scx (scx-1.6.3-559.universal.x86) -----
dpkg: error: cannot access archive '110/scx-1.6.3-559.universal.x86.deb': No such file or directory
----- Removing package: scx -----
dpkg: warning: ignoring request to remove scx which isn't installed
----- Removing package: omi -----
dpkg: warning: ignoring request to remove omi which isn't installed
----- Installing package: omi (omi-1.4.2-2.ulinux.x86) -----
dpkg: error: cannot access archive '110/omi-1.4.2-2.ulinux.x86.deb': No such file or directory
omi-1.4.2-2.ulinux.x86 package failed to install and exited with status 2
Upgrade failed
Shell bundle exiting with code 19
root@atomprobe1:~# apt-get install omi
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package omi

**Comment by shpimpal** [comment]
Hi, there is no support for OMS agent with openssl 1.1.x on 32bit platforms. It works with openssl versions 0.9.8 or 1.0.x on 32bit machines.
