### ISSUE TITLE
Missing directories

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Microsoft/OMS-Agent-for-Linux#724]
When install the agent with --upgrade parameter the script fails because of missing directories:

![image](https://user-images.githubusercontent.com/33453919/41713967-16acfb24-754f-11e8-9319-13e707c17f78.png)

The script is being run as root.

**Comment by shpimpal** [comment]
Hi @nicolaibaralmueller , can you please put entire console logs here starting from where upgrade was run ? I am unable to see installation logs for omsagent package here. 
Or can you again try installing the latest shell bundle by removing first (--remove) and then run upgrade. Thanks!

**Comment by nicolaibaralmueller** [comment]
Hi @shpimpal . How do I show the entire console logs? it's pure centos console so I cannot copy & paste.

**Comment by shpimpal** [comment]
Okay, these are just warnings, agent still should onboard. Can you please check omsagent.log file and if the machine is connected to the workspace ? If no luck, then please see if re-installing helps as mentioned above.

**Comment by nicolaibaralmueller** [comment]
Result:

`Checking host architecture ...
Extracting...
----- Upgrading package: omi (omi-1.4.2-2.ulinux.x64) -----
Selecting previously unselected package omi.
(Reading database ... 31153 files and directories currently installed.)
Preparing to unpack 110/omi-1.4.2-2.ulinux.x64.deb ...
Creating omiusers group ...
Creating omi group ...
Creating omi service account ...
Unpacking omi (1.4.2.2) ...
Setting up omi (1.4.2.2) ...
Generating a 2048 bit RSA private key
....+++
............+++
writing new private key to '/etc/opt/omi/ssl/omikey.pem'
-----
2018-07-17 11:31:26 : Crontab not configured to update omi keytab automatically. Skip unconfigure
2018-07-17 11:31:26 : Crontab configured to update omi keytab automatically
Configuring OMI service ...
Created symlink /etc/systemd/system/multi-user.target.wants/omid.service → /lib/systemd/system/omid.service.
Processing triggers for systemd (232-25+deb9u3) ...
----- Upgrading package: scx (scx-1.6.3-559.universal.x64) -----
Selecting previously unselected package scx.
(Reading database ... 31202 files and directories currently installed.)
Preparing to unpack .../scx-1.6.3-559.universal.x64.deb ...
Unpacking scx (1.6.3.559) ...
Setting up scx (1.6.3.559) ...
Generating certificate with hostname="debian", domainname="localdomain"
----- Upgrading package: omsagent (omsagent-1.6.0-42.universal.x64) -----
Selecting previously unselected package omsagent.
(Reading database ... 31237 files and directories currently installed.)
Preparing to unpack .../omsagent-1.6.0-42.universal.x64.deb ...
Creating omsagent group ...
Creating omsagent service account ...
Creating nxautomation group ...
Creating nxautomation service account ...
Unpacking omsagent (1.6.0.42) ...
Setting up omsagent (1.6.0.42) ...
-e info	Reading onboarding params from: /etc/omsagent-onboard.conf
Workspace XXX already onboarded and agent is running.
Symbolic links have not been created; re-onboarding to create them
info	Generating certificate ...
-e info	Agent GUID is XXX
-e info	Onboarding success
Configure syslog...
-e info	netstat tool is not available. Default port defined in omsadmin.sh will be used.
Configuring rsyslog for OMS logging
Restarting service: rsyslog
Configure heartbeat monitoring agent...
-e info	netstat tool is not available. Default port defined in omsadmin.sh will be used.
Configure log rotate for workspace XXX...
INFO:  Configuring OMS agent service XXX ...
Created symlink /etc/systemd/system/multi-user.target.wants/omsagent-XXX.service → /lib/systemd/system/omsagent-XXX.service.
-e error	MetaConfig generation script not available at /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py
Configure log rotate for workspace XXX...
Processing triggers for systemd (232-25+deb9u3) ...
----- Upgrading package: omsconfig (omsconfig-1.1.1-728.x64) -----
Selecting previously unselected package omsconfig.
(Reading database ... 39317 files and directories currently installed.)
Preparing to unpack .../omsconfig-1.1.1-728.x64.deb ...
Checking for ctypes python module...
Unpacking omsconfig (1.1.1.728) ...
Setting up omsconfig (1.1.1.728) ...
VERBOSE from InstallModule.py: Extracting module zip file from /opt/microsoft/omsconfig/module_packages/nx_1.0.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxAvailableUpdatesResource
VERBOSE from InstallModule.py: Installing resource MSFT_nxServiceResource
VERBOSE from InstallModule.py: Installing resource MSFT_nxGroupResource
VERBOSE from InstallModule.py: Installing resource MSFT_nxUserResource
VERBOSE from InstallModule.py: Installing resource MSFT_nxPackageResource
VERBOSE from InstallModule.py: Extracting module zip file from /opt/microsoft/omsconfig/module_packages/nxOMSPerfCounter_2.2.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxOMSPerfCounterResource
VERBOSE from InstallModule.py: Extracting module zip file from /opt/microsoft/omsconfig/module_packages/nxOMSSyslog_2.2.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxOMSSyslogResource
VERBOSE from InstallModule.py: Extracting module zip file from /opt/microsoft/omsconfig/module_packages/nxOMSKeyMgmt_1.0.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxOMSKeyMgmtResource
VERBOSE from InstallModule.py: Extracting module zip file from /opt/microsoft/omsconfig/module_packages/nxFileInventory_1.1.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxFileInventoryResource
gpg: keybox '/etc/opt/omi/conf/omsconfig/keymgmtring.gpg' created
gpg: directory '/etc/opt/omi/conf/omsconfig/.gnupg' created
gpg: /etc/opt/omi/conf/omsconfig/.gnupg/trustdb.gpg: trustdb created
gpg: key C4EC49E544BC4178: public key "Microsoft (Release Signing) <msgpgkey@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: keybox '/etc/opt/omi/conf/omsconfig/keyring.gpg' created
gpg: key 20541A3DDE321294: public key "Microsoft (Release Signing) <dscgpgkey@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
VERBOSE from OMS_MetaConfigHelper.py: OMS config path being read: /etc/opt/microsoft/omsagent/9f71c41d-d67b-48f2-a0c0-720c120960b9/conf/omsadmin.conf
instance of SendConfigurationApply
{
    ReturnValue=0
}


VERBOSE from OMS_MetaConfigHelper.py: Successfully configured omsconfig.
----- Updating bundled packages -----
Checking if Apache is installed ...
  Apache found, Apache agent will be installed
Extracting...
Updating Apache agent ...
----- Updating package: apache-cimprov (apache-cimprov-1.0.1-10.universal.1.x86_64) -----
Detected Apache v2.4 ...
Selecting previously unselected package apache-cimprov.
(Reading database ... 39384 files and directories currently installed.)
Preparing to unpack .../apache-cimprov-1.0.1-10.universal.1.x86_64.deb ...
Unpacking apache-cimprov (1.0.1.10) ...
Setting up apache-cimprov (1.0.1.10) ...
Checking if Docker is installed...
  Docker not found. Docker agent will not be installed.
Checking if MySQL is installed ...
  MySQL not found, will not install
Checking if required dependencies for auoms are installed...
Extracting...
Updating auoms ...
----- Updating package: auoms (auoms-1.2.1-6.universal.x64) -----
Selecting previously unselected package auoms.
(Reading database ... 39400 files and directories currently installed.)
Preparing to unpack auoms-1.2.1-6.universal.x64.deb ...
Unpacking auoms (1.2.1.6) ...
Setting up auoms (1.2.1.6) ...
Shell bundle exiting with code 0
`

**Comment by nicolaibaralmueller** [comment]
It just showed up in update management. Thanks for the responses.
