### ISSUE TITLE
Multiple VMExtensions per handler not supported for OS type 'Linux'

### ISSUE THREAD

**Issue by TechnologyAnimal** [microsoft/OMS-Agent-for-Linux#744]
I am trying to configure the OMS agent for linux during the RHEL server provisioning process, but I am getting an error message about multiple extensions per handler.

[31m
[1m[31mError: [0m[0m[1mError applying plan:
1 error(s) occurred:
* azurerm_virtual_machine_extension.preprod_monitoring_agent: 1 error(s) occurred:
* azurerm_virtual_machine_extension.preprod_monitoring_agent: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="**Multiple VMExtensions per handler not supported for OS type 'Linux'. VMExtension 'Microsoft_Monitoring_Agent' with handler 'Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux' already added or specified in input.**"

I would have assumed this meant I cannot install multiple VM extensions from this specific handler (Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux) on the same VM, but it seems this is conflicting with the CustomScript extension(the only other extension installed)?

After the OMS agent for linux is working, I was planning on adding the DSC for linux extension.  Do you happen to know if that will be a problem as well?

**Comment by ep9123** [comment]
Any solution encountering same problem

**Comment by pawarsum** [comment]
Try with below suggestion my problem get resolved 
https://stackoverflow.com/questions/42206705/azure-extension-script-for-linux/42216716#42216716

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
