### ISSUE TITLE
OMS Syslog

### ISSUE THREAD

**Issue by rodent-x** [Microsoft/OMS-Agent-for-Linux#753]
OMS Agent 1.6.0-42

Ubuntu 16.04 sending heartbeats but Syslog does not get sent to OMS.

From /var/opt/microsoft/omsconfig/omsconfig.log I get the following errors (curl and openssl are both the latest versions) : 

DSC Engine Error :
         Error Message Failed to report to all reporting servers.  Last server failed with HTTP response code: 0.
        Error Code : 1

DSC Engine Error :
         Error Message cURL failed to perform on this base url: we-agentservice-prod-1.azure-automation.net with this error message: Failure when receiving data from the peer. Make sure cURL and SSL libraries are up to date.

**Comment by shpimpal** [comment]
Hi, could you please file this omsconfig related issue on this repo - Microsoft/PowerShell-DSC-for-Linux?
Also, please paste the contents of "/etc/rsyslog.d/95-omsagent.conf" file to see if syslog is configured properly. 
Thanks!

**Comment by shpimpal** [comment]
Closing it. Please re-open if syslog issue exists. thanks!

**Comment by rbhanot4739** [comment]
I am also facing this issue, however to me it happnes when I configure the NSG in the following manner.

Allow Access to `AzureMonitor` from any source
Block access to `Internet` from `VirtualNetwork`

If i remove the second rule it starts working so my issue is why applying the `AzureMonitor` does not work as expected.
