### ISSUE TITLE
security_events.conf and[warn]: pattern not match

### ISSUE THREAD

**Issue by niloc3C** [microsoft/OMS-Agent-for-Linux#767]
Using the security_events.conf file, out of the box the format appears to fail on matching the regex within the file with the following log from a Cisco ASAv NVA. 

format /^(?<time>(?:\w+ +){2,3}(?:\d+:){2}\d+):? ?(?:(?<host>[^: ]+) ?:?)? (?<ident>[a-zA-Z0-9_%\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?: *(?<message>.*)$/

2018-08-09 22:23:00 +0000 [warn]: pattern not match: "CiscoASAv-a %ASA-6-302016: Teardown UDP connection 296126860 for outside:1.1.1.1/53 to subnetA:2.2.2.2/65000 duration 0:00:00 bytes 182"

I took a crack at deconstructing this and failed. Help!

https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/Security-Events-Preview-Configuration.md

https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/conf/omsagent.d/security_events.conf

**Comment by niloc3C** [comment]
I found this parser, not sure if it can be used/converted.

https://github.com/daichi703n/fluent-plugin-cisco-asa-parser
https://github.com/rogeriobastos/fluent-plugin-cisco-asa-parser/blob/master/lib/fluent/plugin/parser_cisco_asa.rb

**Comment by igivl** [comment]
HI, now i have the same problem.
Did you solve the problem?

**Comment by JimmyJamCABD** [comment]
@igivl I too have the same issue.  I am using rsyslog with messages that are RFC5424 compliant and the  security_events.conf is expecting RFC3**** which is the old standard.

So, even when I create a proper string to match my header, it is not picking up the correct message attributes.  There seems to be no info out there for creating a custom blob unless you want to use the custom field "wizard" that is not as smart as it needs to be an extremely hard to replicate.

I too am a bit lost

**Comment by tarrenj** [comment]
I'm now having this issue too. Has anyone found any documentation on this outside of https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Security-Events-Preview-Configuration.md?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
