### ISSUE TITLE
No longer capturing KubeEvents

### ISSUE THREAD

**Issue by srmorin** [microsoft/OMS-Agent-for-Linux#770]
The in_kube_events.rb is no longer able to successfully query for incoming events after upgrading to 1.6.0-42.  The snippet from the plugin is shown below, we are always getting blank logs instead of valid events.  Is there some configuration we need to do to enable this?

      if KubernetesApiClient.isValidRunningNode
          if eventList.nil?
            events = JSON.parse(KubernetesApiClient.getKubeResourceInfo('events').body)
          else
            events = eventList
          end
          eventQueryState = getEventQueryState
          newEventQueryState = []
          begin
            if(!events.empty?)
              events['items'].each do |items|
                record = {}
                eventId = items['metadata']['uid'] + "/" + items['count'].to_s
                newEventQueryState.push(eventId)
                if !eventQueryState.empty? && eventQueryState.include?(eventId)
                  next
                end
                record['ObjectKind']= items['involvedObject']['kind']
                record['Namespace'] = items['involvedObject']['namespace']
                record['Name'] = items['involvedObject']['name']
                record['Reason'] = items['reason']
                record['Message'] = items['message']
                record['Type'] = items['type']
                record['TimeGenerated'] = items['metadata']['creationTimestamp']
                record['SourceComponent'] = items['source']['component']
                record['FirstSeen'] = items['firstTimestamp']
                record['LastSeen'] = items['lastTimestamp']
                record['Count'] = items['count']
                if items['source'].key?('host')
                        record['Computer'] = items['source']['host']
                else
                        record['Computer'] = (OMS::Common.get_hostname)
                end
                record['ClusterName'] = KubernetesApiClient.getClusterName
                router.emit(@tag, time, record) if record
              end
            end
            writeEventQueryState(newEventQueryState)
          rescue  => errorStr
            $log.warn line.dump, error: errorStr.to_s
            $log.debug_backtrace(errorStr.backtrace)
          end
        else
          record = {}
          record['ObjectKind']= ""
          record['Namespace'] = ""
          record['Name'] = ""
          record['Reason'] = ""
          record['Message'] = ""
          record['Type'] = ""
          record['TimeGenerated'] = ""
          record['SourceComponent'] = ""
          record['FirstSeen'] = ""
          record['LastSeen'] = ""
          record['Count'] = "0"
          record['Computer'] = ""
          record['ClusterName'] = ""
          router.emit(@tag, time, record)
        end

**Comment by arwkmd** [comment]
Did you enable RBAC authorization in Kubernetes?
