### ISSUE TITLE
Any way to disable ContainerLog ?

### ISSUE THREAD

**Issue by ins4n333** [microsoft/OMS-Agent-for-Linux#774]
Hi!
My kubernetes pods write a logs to stdout and now all this logs capturing by OMS agent.
In my case I would like to collect only diagnostic information without stdout logs. 
Is it any way to disable stdout (ContainerLog) collecting ?

**Comment by shpimpal** [comment]
@keikhara please take a look

**Comment by ins4n333** [comment]
@vishiy Hi! Yes. We use a different stack for collection pod logs. And for us its much cheaper. From the other side by security reasons we have to store logs in our corporate datacenter. I have heard that you provide some tecknology for hidding some criticatal or user log infromation. But this required approve from our security service.

**Comment by sheerun** [comment]
Same issue
