### ISSUE TITLE
Docker oms agent for swarm split lines by \n

### ISSUE THREAD

**Issue by mmpyro** [microsoft/OMS-Agent-for-Linux#776]
Explanation:
oms agent was started as swarm service for gathering logs. docker service create --name omsagent --mode global --mount type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock  --mount type=bind,source=/var/lib/docker/containers,destination=/var/lib/docker/containers -e WSID="<WORKSPACE ID>" -e KEY="<PRIMARY KEY>" -p 25225:25225 -p 25224:25224/udp --restart-condition=on-failure microsoft/oms

Actual:
Each line is logged as sepparated log message and ends with \n character.

Expected:
Multiline log should be logged as single record.

**Comment by shpimpal** [comment]
@keikhara can you please take a look?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
