### ISSUE TITLE
SLES 11 SP4 supported?

### ISSUE THREAD

**Issue by aydeisen** [Microsoft/OMS-Agent-for-Linux#778]
SLES 11 SP4 appears to meet the requirements laid out in the "Supported Distro/Version strategy" heading of the README, perhaps with the exception of `6. Only support versions that run SSL 1.x by default.`

SUSE has [a document](https://www.suse.com/documentation/suse-best-practices/singlehtml/securitymodule/securitymodule.html#sec.usingpack) regarding the security module of SLES 11 SP4 and having it use OpenSSL 1.x

Is the OpenSSL requirement in the strategy the reason why SLES 11 SP4 is no longer supported, even though SLES 11 SP4 continues to be a server OS under SUSE General Support, and is listed as an endorsed distro in the Azure document?  If so, are there additional steps required to allow the OMS agent to continue to work with SLES 11 SP4?

**Comment by abhijeetgaiha** [comment]
As per doc, the default system SSL is still 0.9.8. We would need a special build for SLES 11 that links to the special location of SSL 1.x.

**Comment by johnkemnetz** [comment]
Yes, #6 is why SLES SP4 is not supported. The default system SSL is still < 1.x, so there would have to be custom work and a special build for SLES 11 SP4. This wouldn't just be for omsagent, it would also have to be done in our dependencies (DSC, OMI) as well.

Per the supported distro/version strategy section, you can always fork the code and create a custom build that works with SLES 11 SP4.
