### ISSUE TITLE
Ubuntu Performance counters for % Disk Used reporting precission

### ISSUE THREAD

**Issue by rubroboletus** [microsoft/OMS-Agent-for-Linux#782]
Hello,

on Ubuntu 16.04 is OMS Agent reporting very different numbers about % Disk Used then system "df" utility. What is the precision / algorithm used?
![image](https://user-images.githubusercontent.com/19551186/45538641-e91bdf80-b807-11e8-972e-a642236987f5.png) is what system is reporting
![image](https://user-images.githubusercontent.com/19551186/45538682-02bd2700-b808-11e8-9638-aa63169feed5.png)
is what is logged by OMS

Robert

**Comment by shpimpal** [comment]
The metrics are collected by SCX provider. @vimish can you please take a look?

**Comment by hestolz** [comment]
Issue opened against SCX team.
