### ISSUE TITLE
Compliance finding - ODSIngestion.status is world writable upon install

### ISSUE THREAD

**Issue by falmada** [microsoft/OMS-Agent-for-Linux#784]
Whenever running the installation of omsagent and then registering it against a workspace, file "ODSIngestion.status" is reported as a world-writable file.

Scan finding:
/var/opt/microsoft/omsagent/[workspace-id]/log/ODSIngestion.status
owner: omsagent, group: omiusers, permissions: 0666

As the owner and the group are properly set, do we really need the o+w permission here?

Can this be fixed on the installer and/or the umask set whenever the process is triggered?

Thanks!

**Comment by shpimpal** [comment]
Created a backlog task to take a look at this, thanks!

**Comment by rexc** [comment]
Is there an update on this?
This sets off our vulnerability scanner too, and internal consumers of the scan reports often aren't knowledgeable enough to accurately determine if this a risk and generates a lot of unnecessary alarm.

**Comment by cookeji** [comment]
We have this issue as well

**Comment by bigtob** [comment]
Yep, same here. Is there any progress here? Can't see a need for this file to be world writeable.

**Comment by nielsvbrecht** [comment]
I'm having the same issue, this screws up my CIS compliance scan report. Next to the facts the OMSagent script installs a system account with a shell configured.

**Comment by mohit-kumar-sharma** [comment]
@shpimpal do we have any update on this?

**Comment by shpimpal** [comment]
Tagging folks who could have updates- @simathith, @abenbachir 
My apologies for delay, I haven't been working on this project for almost 2 years now :)

**Comment by mohit-kumar-sharma** [comment]
@abenbachir @simathih  can we get further updates? This issue is causing a serious problems now.

**Comment by Lukeout** [comment]
Hi folks,

Removing of world-writable files and more CIS Hardening standards will be coming in our new agent in the second half of this year. https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview

**Comment by awidner** [comment]
Hello, @Lukeout any update on the new agent? We too are having this same issue with our vulnerability scanner.
