### ISSUE TITLE
Compliance finding - Orphaned files upon install

### ISSUE THREAD

**Issue by falmada** [microsoft/OMS-Agent-for-Linux#785]
After finishing installing and registering omsagent to a workspace on RHEL, we are getting below scan finding:

Check Name: 6.1.11 Ensure no unowned files or directories exist

Actual Value: The following 5 files are orphaned::
/home/omi
owner: 5009, group: omi, permissions: 0750
/home/omi/.bash_profile
owner: 5009, group: omi, permissions: 0644
/home/omi/.kshrc
owner: 5009, group: omi, permissions: 0644
/home/omi/.bash_logout
owner: 5009, group: omi, permissions: 0644
/home/omi/.bashrc
owner: 5009, group: omi, permissions: 0644

As noted, all the files/directories are getting user ID 5009 as owner, while this should go to "omi" user ID instead, which upon creation had received UID 186 instead. Funny thing is that files/dirs get the group assignment properly, but not the user/owner.

[root@hostname~]# ls -la /home/omi
total 24
drwxr-x---.  2 5009 omi  4096 Feb 13  2018 .
drwxr-xr-x. 18 root root 4096 Dec 14  2017 ..
-rw-r--r--.  1 5009 omi    18 Sep  6  2017 .bash_logout
-rw-r--r--.  1 5009 omi   193 Sep  6  2017 .bash_profile
-rw-r--r--.  1 5009 omi   231 Sep  6  2017 .bashrc
-rw-r--r--.  1 5009 omi   172 Aug  2  2017 .kshrc
[root@hostname~]# id omi
uid=497(omi) gid=186(omi) groups=186(omi)
[root@hostname~]#

Thanks

**Comment by shpimpal** [comment]
Created a backlog task to take a look at this, thanks!

**Comment by hestolz** [comment]
Hi @falmada, [OMI](https://github.com/microsoft/omi) owners have made a change a while back to address this ([this PR](https://github.com/microsoft/omi/pull/512)); they create the omi user as a system user, so no home directory will be created and there will be no such issues with orphaned files.

This fix has been out for a few years, so we will close this issue.
