### ISSUE TITLE
Compliance finding - omsagent and nxautomation share home directory

### ISSUE THREAD

**Issue by falmada** [microsoft/OMS-Agent-for-Linux#786]
User omsagent and nxautomation both share /var/opt/microsoft/omsagent/run as home directory. This is then detected by CIS compliance rule "6.2.9 Ensure users own their home directories".

/var/opt/microsoft/omsagent/[workspace_id]/run mode: 0750 owner: omsagent (should be nxautomation)

If you check on passwd information, both have the same home, hence compliance finding cannot be fixed.

[root@hostname~]# egrep "omsagent|nxautomation" /etc/passwd
omsagent:x:499:189:OMS agent:/var/opt/microsoft/omsagent/run:/bin/bash
nxautomation:x:498:187:nxOMSAutomation:/var/opt/microsoft/omsagent/run:/bin/bash
[root@hostname~]#

Thanks!

**Comment by shpimpal** [comment]
Created a backlog task to take a look at this, thanks!

**Comment by syedzac** [comment]
Another clarification needed
  `omsagent:x:990:990:OMS agent:/var/opt/microsoft/omsagent/run:/bin/bash
nxautomation:x:989:987:nxOMSAutomation:/home/nxautomation/run:/bin/bash`

but compliance says all users should have nologin

**Comment by bsuchorowski** [comment]
> Another clarification needed
> `omsagent:x:990:990:OMS agent:/var/opt/microsoft/omsagent/run:/bin/bash nxautomation:x:989:987:nxOMSAutomation:/home/nxautomation/run:/bin/bash`
> 
> but compliance says all users should have nologin

Did you worked it around somehow?

**Comment by falmada** [comment]
@bsuchorowski, unfortunately in my case, ended up opening an exception from security team internally, as it does not seem there is much interest on fixing these.

**Comment by bsuchorowski** [comment]
Weird. In my case, I have a few VMs with OMS-agent-for-linux installed and security center stands that I have secuirty issues on these vms: "Vulnerabilities in security configuration on your machines should be remediated". Only two accounts that does not comply are omsagent and nxautomation.

**Comment by etcetc** [comment]
Do omsagent and nxautomation require a bash shell? Why would they require login?

**Comment by goniomdq** [comment]
> Do omsagent and nxautomation require a bash shell? Why would they require login?

Does anyone know (or have tested) whether these users actually require a shell?

**Comment by abenbachir** [comment]
Hi this was solved here https://github.com/microsoft/OMS-Agent-for-Linux/commit/7dfe68178ea15689046ea59f0165c77b41430f53

sudo egrep "omsagent|nxautomation" /etc/passwd
omsagent:x:998:998:OMS agent:/var/opt/microsoft/omsagent/run:/bin/bash
nxautomation:x:997:995:nxOMSAutomation:/home/nxautomation/run:/bin/bash

**Comment by marinnedea** [comment]
Maybe this can help understanding the "why" questions:

`[root@myvm ~]# ls -l /etc/sudoers.d/
total 12
-r--r-----. 1 root root  122 Mar  5  2021 90-cloud-init-users
-r--r-----. 1 root root 3702 Oct 20 12:22 omsagent
-r--r-----. 1 root root   33 Nov 11 09:25 waagent
[root@myvm ~]# head /etc/sudoers.d/omsagent
# Begin sudo configuration for omsagent
Defaults:omsagent !requiretty
Defaults:omsagent lecture = never

#update and restart syslog
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsconfig/Scripts/OMSRsyslog.post.sh
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsconfig/Scripts/OMSSysklog.post.sh
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsconfig/Scripts/OMSSyslog-ng.post.sh

#Service status
`
I only listed the head of the file, as I didn't want a wall of text.
Basically, I see a lot of shell scripts that omsagent can call... probably something similar is for nxautoamtion account.
