### ISSUE TITLE
auoms flooding messages file with Fail to read /proc/93331/cmdline

### ISSUE THREAD

**Issue by samispurs** [microsoft/OMS-Agent-for-Linux#789]
Sep 25 10:23:25 auoms: Failed to read /proc/93589/cmdline: No such file or directory
Sep 25 10:23:25  auoms: Failed to read /proc/93622/stat: No such process
Sep 25 10:23:25 auoms: Failed to read /proc/93630/stat: No such process
Sep 25 10:23:25  auoms: Failed to read /proc/93677/cmdline: No such file or directory
Sep 25 10:23:26  auoms: Failed to read /proc/93698/stat: No such process
Sep 25 10:24:20  auoms: Failed to read /proc/93860/stat: No such process
Sep 25 10:24:50  auoms: Failed to read /proc/93933/stat: No such process
Sep 25 10:26:01  auoms: Failed to read /proc/94110/stat: No such process
Sep 25 10:26:42  auoms: Failed to read /proc/94262/status: No such process

This causes rsyslog to complain about rate limits.

sh ./omsagent-1.6.1-3.universal.x64.sh --version-check
Extracting...
omsagent       1.6.1.3        1.6.1.3        No
omsconfig      1.1.1.831      1.1.1.831      No
omi            1.4.2.5        1.4.2.5.ulinux No
scx            1.6.3.659      1.6.3.659      No
apache-cimprov None           1.0.1.10       Yes
mysql-cimprov  None           1.0.1.5        Yes
docker-cimprov    None           1.0.0.32       Yes
Shell bundle exiting with code 0

Updating auoms ...
----- Updating package: auoms (auoms-1.2.1-6.universal.x64) -----
Skipping package since existing version >= version available

**Comment by adrianohf** [comment]
Some problem here...

**Comment by shpimpal** [comment]
@taglines can you please take a look?

**Comment by OwainWin** [comment]
I also have this issue with omsagent 1.7.9 on CentOS 7.5.1804

**Comment by taglines** [comment]
The latest version of OMS agent (1.8.1.256) includes auoms version 1.3.0-3. This new version of auoms includes changes that reduce/silence the noisy logging reported here.
