### ISSUE TITLE
omiagent segfault in libcontainer.so

### ISSUE THREAD

**Issue by towasz** [Microsoft/OMS-Agent-for-Linux#792]
The following segfault occurs on kubernetes minions running under CentOS in Azure based environment. It looks like the site effect of segfault is cousing  cni0 bridge entering disabled state. 

```
[Thu Sep 27 16:13:29 2018] omiagent[34149]: segfault at 30 ip 00007fc1f67d0240 sp 00007ffdaec54b60 error 4 in libcontainer.so[7fc1f6786000+87000]
[Thu Sep 27 16:13:43 2018] XFS (dm-17): Unmounting Filesystem
[Thu Sep 27 16:13:43 2018] XFS (dm-14): Unmounting Filesystem
[Thu Sep 27 16:13:57 2018] XFS (dm-9): Unmounting Filesystem
[Thu Sep 27 16:13:57 2018] XFS (dm-10): Unmounting Filesystem
[Thu Sep 27 16:13:57 2018] cni0: port 1(vethd45d82a6) entered disabled state
```
**Environment**:
```
OS: CentOS Linux release 7.5.1804 (Core)
Kernel: 3.10.0-862.11.6.el7.x86_64
docker-ce-17.03.2.ce-1.el7.centos.x86_64
Open Management Infrastructure: omi-1.4.2-5.x86_64
docker-cimprov-1.0.0-32.x86_64
```

The similar issue has been addressed in https://github.com/Microsoft/OMS-Agent-for-Linux/issues/300 . and the provided hint was to upgrade docker-cimprov. Since the issue still occurs on docker-cimprov-1.0.0-32.x86_64 looking forward for any hints on that?

**Comment by shpimpal** [comment]
closing this as new OMS agent is released. Please re-open if issue persists.
