### ISSUE TITLE
OMS fails on SLES 11.4 on openssl check

### ISSUE THREAD

**Issue by domlock** [Microsoft/OMS-Agent-for-Linux#829]
Hi Guys. I have a small issue.
The environment that I am responsible for; runs a mixture of SLES 11.4/SLES12.2 & SLES 12.3 servers. We are in the process of upgrading all the systems to 12.3.
However; there is now a requirement to integrate all the systems with MS OMS; so I am busy rolling out the agent on all servers.
On SLES 11.4; the install fails with:
----- Upgrading package: omi (omi-1.4.2-5.ulinux.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 0.9.8j-fips
Supported versions: 1.0.*, 1.1.*
Shell bundle exiting with code 55

The problem is that I have installed the required bundle; and open ssl1 is installed. But; on SLES 11; openssl is called as:
openssl version (as per scripts); and openssl1 is called explicitly as:
openssl1 version

However; I cannot  edit the install scripts to look for openssl1.

Is there any way that you can assist? 
The omsagent version is:
omsagent-1.6.1-3.universal.x64.sh

Kind regards

**Comment by shpimpal** [comment]
We do no support SLES 11 anymore - https://github.com/Microsoft/OMS-Agent-for-Linux#supported-distroversion-strategy.
However, you are free to fork the repo and make the changes and build the bundle yourself. But please note that we cannot provide support in that case should you face any issues. thanks!
