### ISSUE TITLE
OMS Agent RHEL5.11 fails at Python and OpenSSL check

### ISSUE THREAD

**Issue by AjKundnani** [Microsoft/OMS-Agent-for-Linux#831]
When attempting to install OMS agent along with configuration for RHEL 5.11, we get below error
__________________________________________
Checking host architecture ...
Error: Python is not configured or Python does not support ctypes on this system, installation cannot continue.
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61 
_______________________________________________
When we try to force past same, we get below error
________________________________________________
Python is not configured or it does not support ctypes on this system, please upgrade Python to a newer version that comes with the ctypes module and re-install omsconfig later.
Installation will continue without installing omsconfig.
Extracting...
----- Installing package: omi (omi-1.4.2-5.ulinux.x64) -----
Error: This system does not have a supported version of OpenSSL installed.
This system's OpenSSL version: 0.9.8e-fips-rhel5
Supported versions: 1.0.*, 1.1.*
Shell bundle exiting with code 55 
_________________________________________________
The server is running on RHEL 5.11 with Python 2.4 and OpenSSL 0.9

Can we modify the installer to support RHEL5.11 ?

**Comment by shpimpal** [comment]
You need python ctypes module to work with omsconfig. 
Plus the OMS agent is not supported on RHEL 5.x and openssl 0.x. See this - https://github.com/Microsoft/OMS-Agent-for-Linux#supported-distroversion-strategy

The options are that you could fork the repo, make changes and build it yourself or you can use older version of OMS agent that supported this scenario. Please note that neither of these options will be supported by us and we definitely don't recommend using older agent.
Thanks!
