### ISSUE TITLE
OMS-Agent support for FreeBSD

### ISSUE THREAD

**Issue by fbotha-stratuscloud** [microsoft/OMS-Agent-for-Linux#837]
OMS Agent support is required for FreeBSD

**Comment by ctateOCS** [comment]
Agreed. If not native support, then "linux compatible" installation instructions to work with your image would be very beneficial.

**Comment by nathank1989** [comment]
Agreed. I have several VMs that are FreeBSD for our SMB clients and are unable to utilize the tool.

Initially I get:
Error: This system does not have supported package manager
Supported Sytems: 'DPKG' & 'RPM'
Shell bundle exiting with code 66

But then I force install DPKG and confirmed it is installed, and yet it still won't install.

**Comment by hestolz** [comment]
Unfortunately FreeBSD is not part of [Azure endorsed distros](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros); as a consequence we are not committed to supporting it.
