### ISSUE TITLE
Syslog messages are truncated

### ISSUE THREAD

**Issue by jburke-idam** [microsoft/OMS-Agent-for-Linux#847]
We have omsagent configured to capture syslog messages that can contain long java stacktraces. When we view the captured messages in log analytics they're truncated at around 2000 characters long. It's not clear to me if this is a hard limit in the length of the log analytics column, or if this is a setting from omsagent, or possibly fluent that we can customize. Is there any documentation on the max length limit of SyslogMessages captured by omsagent, and how to change it?

Thanks.

**Comment by qc-gordon** [comment]
fluentd defaults to 2048 chars but it can be changed via config file
/etc/opt/microsoft/omsagent/[omsid]/conf/omsagent.d/security_events.conf

https://docs.fluentd.org/v/0.12/input/syslog

**Comment by root-locus** [comment]
I run into the same issue, but with OMS' syslog listener: `/etc/opt/microsoft/omsagent/[omsid]/conf/omsagent.d/syslog.conf`.
I think, it would be ok if it will be increased to 64K (syslog-ng [1]) or 8K (rsyslogd)


[1]: https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.19/administration-guide/log-msg-size
[2]: https://www.rsyslog.com/doc/v8-stable/configuration/global/index.html

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
