### ISSUE TITLE
OMSAgent increased 5 times billable data ingestion to Log Analytics

### ISSUE THREAD

**Issue by AntonTimiskov** [microsoft/OMS-Agent-for-Linux#848]
Azure Kubernetes Services with Enabled Log Analytics installs OMSAgent on every node and collect Node statistics, Pod statistics, Logs and so on.
Recently the ingestion of ContainerInventory was increased in 5 times.
That led to an unexpected billing raise for this unexpected additional ingestion.
I guess that it's because of increased frequency of heartbeat reported to Log Analytics.
I found a recent commit related to this: `change heartbeat frequency to 1 min`
https://github.com/Microsoft/OMS-Agent-for-Linux/commit/3c40e02aca1282c6c772088da3bdce29ae8b0653
This small change caused many bucks to be spent.

It have to be configurable: on/off for heartbeating statuses, configurable frequency in AKS.
And please don't change defaults that can affect billing in Azure.

**Comment by PashaPash** [comment]
Got 200$ bill for small 4-node cluster. Monitoring costs are now higher than VM costs.

**Comment by AntonTimiskov** [comment]
The cost mostly related to collected environment variables into ContainerInventory table.
FYI: MSFT introduced an article how to disable env collection: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-manage-agent
It works, but requires changes in configuration of all pods, and still some containers (like kube-system) have extended logged environment variables.

**Comment by PeterRockstars** [comment]
> The cost mostly related to collected environment variables into ContainerInventory table.
> FYI: MSFT introduced an article how to disable env collection: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-manage-agent
> It works, but requires changes in configuration of all pods, and still some containers (like kube-system) have extended logged environment variables.

For us the cost is only partly caused by the environment variables. By default, all stdout and stderr is logged. This caused the most ingestion in our case. This article demonstrates how to turn that off: https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-agent-config#configmap-file-settings-overview. Also in that article is how to disable the environment variable logging without having to change the configuration of all pods.

**Comment by hestolz** [comment]
Unlikely that ingestion was increased 5x as a result of heartbeat change alone. In order for that to be the case, heartbeat would have to be the sole data source being collected, which is an unlikely customer scenario. Thanks to all who pointed out the documentation for how to limit excess container-related ingestion.
