### ISSUE TITLE
oms agent and ClamAV cpu usage issue

### ISSUE THREAD

**Issue by OwainWin** [microsoft/OMS-Agent-for-Linux#856]
This issue was originally logged on the waagent GitHub issues page but after investigation has been found to be an oms agent issue and I was asked to open a new issue here, the original waagent issue is here:
    https://github.com/Azure/WALinuxAgent/issues/1403

I have an issue where some change in the waagent has a conflict with ClamAV on-access scanning and causes the waagent python process - python -u bin/WALinuxAgent-2.2.33-py2.7.egg -run-exthandlers - to gradually consume all the cpu.

This started a some point with 2.2.26 on any new VM's deployed, existing VM's running the same waagent version are fine.
 This has persisted through every new agent release up to and including 2.2.33.

I've had this open as a support call and upgrading LAD 2.39 to 3.0 has lessened the impact - it takes longer to consume all the cpu, but is still an issue. I have been advised by support to create a new issue here.
 I have been able to temporarily fix this by excluding the following directories from on-access scanning:
•/opt/microsoft/omsagent
•/opt/microsoft/omsconfig
•/opt/omi/share/omsconfig
•/var/lib/waagent
•/var/opt/microsoft/omsagent
•/var/opt/microsoft/omsconfig

As instructed I removed the /var/lib/waagent directory exclusion so this directory is being scanned and there was no issue showing that the problem is with the oms agent and not the waagent.

**Comment by morwn** [comment]
Hey @OwainWin,
Do you register to Azure Security Center? 
What is your Linux distribution name and version?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
