### ISSUE TITLE
RHEL 6 x64 install error gzip: stdin: invalid compressed data--format violated

### ISSUE THREAD

**Issue by dzboy15** [Microsoft/OMS-Agent-for-Linux#857]
Using instructions from here: https://docs.microsoft.com/en-us/system-center/scom/manage-install-crossplat-agent-cmdline?view=sc-om-1807

sh ./omsagent-1.6.0-42.rhel.6.x64.sh --install --enable-opsmgr
Checking host architecture ...
Extracting...

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Failed: could not extract the install bundle.
Shell bundle exiting with code 2

I was wondering if anyone else had come across this error?
Thanks.

**Comment by dzboy15** [comment]
Using instructions from here: https://docs.microsoft.com/en-us/system-center/scom/manage-install-crossplat-agent-cmdline?view=sc-om-1807

**Comment by helshabini** [comment]
Yeah me too. Oracle Linux 7. I suspect it might be because of the way the file is transferred (FTP). I am going to try different methods and see what happens.

**Comment by helshabini** [comment]
Confirmed. Make sure the file transfer is done as "Binary" whether FTP or SCP. It seems transferring the file as ASCII makes the file format not readable by Linux.

**Comment by dzboy15** [comment]
Thanks for the fix.
