### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by INGourav** [microsoft/OMS-Agent-for-Linux#859]
Getting below error message during installation of OMSextension of Linux VM.

Deployment failed. Correlation ID: 293f8984-0c47-4040-98a9-d4db3ca8fb17. Handler 'Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux' has reported failure for VM Extension 'OmsAgentForLinux' with terminal error code '1007' and error message: '[ExtensionError] Non-zero exit code: 22, omsagent.py -install

Using bash script to do this operations: -

az vm extension set \
--resource-group 'cloud' \
--vm-name 'rhel75-goldenimagevm' \
--name OmsAgentForLinux \
--publisher Microsoft.EnterpriseCloud.Monitoring \
--version 1.4 --protected-settings '{"workspaceKey": "XXXXXXXXXXXXXXXXXXX+XXXXXXXXXXXXX=="}' \
--settings '{"workspaceId": "XXXXX-XXX-4XXf-8XX5-dXXXXXXXXa"}'

**Comment by wenboyang214** [comment]
here is the source code of [omsagent.py](https://github.com/Azure/azure-linux-extensions/blob/master/OmsAgent/omsagent.py)
