### ISSUE TITLE
High CPU usage by omiagent

### ISSUE THREAD

**Issue by s3bast1aan** [microsoft/OMS-Agent-for-Linux#860]
Hi all,

We seem to be having some issues with the OMS Agent for Linux and 80 to 100% CPU usages on Linux Azure VM's. The issue appears to be less intrusive on a 2 vCPU system then with a 1 vCPU system.

1 vCPU system
![annotation 2018-12-28 220145](https://user-images.githubusercontent.com/42578716/50528804-ce3c5500-0af0-11e9-96ed-06bac599276c.jpg)

2 vCPU system
![annotation 2018-12-28 220221](https://user-images.githubusercontent.com/42578716/50528837-fc219980-0af0-11e9-9a86-4d816969a1eb.jpg)

The version in use is: /opt/omi/bin/omiserver: OMI-1.4.2-5

I have collected the logfiles mentioned in a couple of other topics touching the same issue.
https://github.com/Microsoft/omi/issues/458
https://github.com/Microsoft/OMS-Agent-for-Linux/issues/498
 Just don't feel comfortable attaching them here. So if need be I can send them by email.

Thanks,
Sebastiaan

**Comment by abenbachir** [comment]
Hi, please follow resolution steps in this documentation: https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md#i-see-omiagent-using-100-cpu

**Comment by s3bast1aan** [comment]
Hi,
I currently do not have production or test VM's with 1 vCPU.
As soon as we have another 1 vCPU system that is experiencing the same issues I'll gather the requested logfiles and post back here.
