### ISSUE TITLE
Issue forwarding custom logs in latest OMS agent

### ISSUE THREAD

**Issue by anandsugumaran** [microsoft/OMS-Agent-for-Linux#864]
We tried to push custom logs to oms workspace and found the below issue in OMS logs.

2019-01-16 12:04:58 +0000 [warn]: WARN /opt/myapp/custom.log does not exist. Cannot tail the file.
2019-01-16 12:04:58 +0000 [warn]: WARN /opt/myapp/myapp.log does not exist. Cannot tail the file.

While troubleshooting, we found that this is because of the latest change in 
https://github.com/Microsoft/OMS-Agent-for-Linux/commit/9271277bc947bb547a5eb8a3c891ef5611fc1488#diff-5665a3d779bb51486f4a673512bb896a

Line no 23 is where the issue is. In linux, if a file exists, then it will return 0. But as per this line, when we get 0, it will go to else block and fail the log processing. So whatever code in if block should go to else and vice versa.

**Comment by bknabel** [comment]
We ran into the same issue on one of our VMs. However our other Linux VMs continued to send logs.
I worked with the Azure support team and based on their recommendation looked at /etc/sudoers on both machines.

The difference was that our failing VM included the line "Defaults requiretty" in sudoers. I commented this line out and restarted the omsagent. It started collecting logs immediately.

I looked at the diff that you referenced above - the offending line that you referenced looks like it isn't new - it was just refactored slightly. I believe that this method for detecting the existence of the log file is valid.

I hope this helps.

**Comment by anandsugumaran** [comment]
Thanks for the details. We too had a discussion with the team and they acknowledged the issue and made a fix in this diff

https://github.com/Microsoft/PowerShell-DSC-for-Linux/pull/528/commits/40da0a50b56788fda8a0821ce33fbb00a018f6aa
