### ISSUE TITLE
Syslog port hardcoded in /etc/rsyslog.d/95-omsagent.conf, why not use Unix Domain Socket instead

### ISSUE THREAD

**Issue by abenbachir** [microsoft/OMS-Agent-for-Linux#865]
In the case of events comming from HAProxy (samething could happend with different service), we cannot edit /etc/rsyslog.d/95-omsagent.conf to enable forwarding HAProxy logs from rsyslog to omsagent, because during updates or reinstallation the file 95-omsagent.conf will reset as before.

So to solve the problem HAProxy config should stay on it own config /etc/rsyslog.d/49-haproxy.conf, but the issue here is the omsagent hardcoded port number. From testing we know that the port is not fixed because omsagent will choose different port when the default one was taken. When omsagent decide to choose a different port he reset the file 95-omsagent.conf but no other services like HAProxy can know about this.

For now as a workaround we provided customer with this [script](https://gist.github.com/abenbachir/46eb61ff0ae447ec77493da51074406e) to keep 49-haproxy.conf updated but this is not the perfect solution.

```
update_haproxy()
{
	distination=$(cat /etc/rsyslog.d/95-omsagent.conf | cut -d@ -f2 | tail -1)

	echo "
# Create an additional socket in haproxy's chroot in order to allow logging via
# /dev/log to chroot'ed HAProxy processes
$AddUnixListenSocket /var/lib/haproxy/dev/log
# Send HAProxy messages to a dedicated logfile
:programname, startswith, "haproxy" {
	/var/log/haproxy.log
	@${distination}
	stop
}
" > /etc/rsyslog.d/49-haproxy.conf
	service rsyslog stop
	service rsyslog start
}

if [ -e /etc/rsyslog.d/95-omsagent.conf ]; then
	update_haproxy
else
	echo "Error: this file /etc/rsyslog.d/95-omsagent.conf was not found, update was cancelled."
fi
```

One of the straightforward solution would be to use Unix Domain Socket with fixed path like this : 
```
<source>
  @type unix
  path /var/run/omsagent/syslog.socket
</source>
```

**Comment by abenbachir** [comment]
I just verified that fluentd doesn't provide support for Unix Domain Socket for syslog, the only existing one is "unix" which is for msgpack protocol.

**Comment by hestolz** [comment]
Moving to devops.
