### ISSUE TITLE
Does the OMS Agent for Linux Support Mult-homed?

### ISSUE THREAD

**Issue by Xergy** [microsoft/OMS-Agent-for-Linux#872]
Howdy!  Can the Linux OMS Agent now talk to more than one OMS Workspace?

**Comment by hestolz** [comment]
It is in consideration as an upcoming feature.

**Comment by hestolz** [comment]
This won't be supported ever for OMS. The [AMA](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/azure-monitor-agent-overview?tabs=CLI1%2CCLI2) which is in preview offers multihoming functionality and will eventually have a superset of OMS functionality.
