### ISSUE TITLE
OMS Agent sudo error  "command not allowed"

### ISSUE THREAD

**Issue by goidor** [microsoft/OMS-Agent-for-Linux#885]
Hello. We have received a lot of sudo errors with "**Command not allowed**". We have added this lines in the sudoers config to resolved the problem.
```
omsagent ALL=(ALL) NOPASSWD: /opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/plugin/containerlogtailfilereader.rb *

omsagent ALL=(ALL) NOPASSWD: /bin/touch /var/opt/microsoft/docker-cimprov/state/ContainerLogFile.pos.log
```
Another problem right now is: 
`sudo: pam_succeed_if(sudo:auth): requirement "uid >= 900" not met by user "omsagent"`. 

To Resolved, we have changed our config file /etc/pam.d/system-auth by this:
`auth        requisite     pam_succeed_if.so uid >= 800 quiet_success`

The user ID should not be greater than 1000?

Attach an image with the errors.
![captura de pantalla_2019-03-04_16-51-24](https://user-images.githubusercontent.com/4967223/53760757-8f38d000-3ea2-11e9-8794-6d7f1fa3673a.png)

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
