### ISSUE TITLE
Agent install on RHEL 7.6 certificate path doesn't get created/detected properly

### ISSUE THREAD

**Issue by bobfrankly** [microsoft/OMS-Agent-for-Linux#898]
- **SCOM Management Server:** at 1807 on Server 2012 R2 patched to current.
- **Target Linux Server:**   Red Hat Enterprise Linux Server release 7.6 (Maipo)   on VMware 6.5

Following the official [documentation](https://docs.microsoft.com/en-us/system-center/scom/manage-install-crossplat-agent-cmdline?view=sc-om-1807#signing-agent-certificates) 

1. Performed a install of omsagent-1.6.0-163.rhel.7.x64.sh
1. attempted to find the certificate for signing. normal linux path does not exist. /etc/opt/microsoft/scx/ssl contains only scx.pem. No host pem file.
1. attempted running /opt/microsoft/omsagent/bin/regenerate_scom_cert.sh
got the following output:

>    Regenerating SCOM certs
>   Generating certificate with hostname="servername.redacted.org"
>
>    Generation of certificate raised an exception
>    Output path "/etc/opt/microsoft/omsagent/scom/certs/" does not exist

### WORKAROUND ### 
I was able to create the missing path, and generate some certificates. I still have to sign them and test further, but this looks on the face like undesireable behavior.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
