### ISSUE TITLE
service_control is-running returns 1 on missing workspace configuration

### ISSUE THREAD

**Issue by josh-barker** [microsoft/OMS-Agent-for-Linux#908]
## Description

Hi,

I'm installing the OMS agent on an Ubuntu system and need to send the logs to a 2nd Log Analytics workspace.

I attempted running the following commands to setup the secondary log analytics workspace.

```
/opt/microsoft/omsagent/bin/omsadmin.sh -w $WORKSPACEID -s $KEY -v -m 'secondary' -U
/opt/microsoft/omsagent/bin/service_control restart $WORKSPACEID
```

However, it would say the workspace was already configured and exit.
```bash
root@vm-host-1:~$/opt/microsoft/omsagent/bin/omsadmin.sh -w $WORKSPACEID -s $KEY -v -m 'secondary' -U
Workspace xxxxxxxx already onboarded and agent is running.
```

I found that the service controller would return an `exit code 1` if the workspace was not configured, or if the service was running. See [here](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/omsadmin.sh#L462)

### Workspace is not configured
```
root@vm-host-1:~# /opt/microsoft/omsagent/bin/service_control is-running Missing-Workspace-ID
/opt/microsoft/omsagent/bin/service_control: line 159: /etc/opt/microsoft/omsagent/Missing-Workspace-ID/conf/omsadmin.conf: No such file or directory
root@vm-host-1:~# echo $?
1
```

### Workspace is configured output

```
root@vm-host-1:~# /opt/microsoft/omsagent/bin/service_control is-running xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
root@vm-host-1:~# echo $?
1
```

## Work around

To work around the issue, I can export either `TEST_WORKSPACE_ID` or `TEST_SHARED_KEY` to skip the [if statement](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/omsadmin.sh#L461), and force the configuration of the workspace.

```
export TEST_WORKSPACE_ID=DUMMY_VALUE
/opt/microsoft/omsagent/bin/omsadmin.sh -w $WORKSPACEID -s $KEY -v -m 'secondary' -U
/opt/microsoft/omsagent/bin/service_control restart $WORKSPACEID
```

## Configuration:

```bash
root@vm-host-1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
```

```
Agent Name: OmsAgentForLinux
Agent Version: 1.9
```

**Comment by wenboyang214** [comment]
maybe you need disable the previous oms service first and then start a new with your workspace id. hope below will do some help

`
root@wbubuntu:/opt/microsoft/omsagent/bin# ./service_control help
    USAGE:  ./service_control -h
    USAGE:  ./service_control help
    USAGE:  ./service_control <script command> [workspace id]
    Where script commands are any of the following:
        -h or help
        disable:         To disable the OMS service, leaving it installed.
        enable:         To enable the OMS service after being disabled.
        find-systemd-dir To establish directory of your OS's systemd, if it has one.
        is-running:         Boolean whether or not omsagent is running.  This is a 1
                         for true, and 0 for false, unlike script booleans (Legacy).
        reload:           Reload agent configuration (at this time same as restart below)
        restart:         Restart the OMS service via the service control manager
        start:           Start the OMS service via the service control manager
        stop:               Stop the OMS service via the service control manager

    Note: Bourne Shell / Dash / POSIX apparently does not see arguments in a
    source evocation.  So to get the WORKSPACE_ID to a sourced copy, unless it
    is in Bourne shell or another shell that sees 0 and , ,..., you need to
    define the variable beforehand, which this draft sees under the name:
        WORKSPACE_ID
root@wbubuntu:/opt/microsoft/omsagent/bin#
`

**Comment by hestolz** [comment]
Hi Josh, multi-homing (sending to multiple workspaces) is not supported by the Linux Log Analytics agent. It is in consideration as a possible upcoming feature.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
