### ISSUE TITLE
OMS AzSecID file missing

### ISSUE THREAD

**Issue by pejub** [microsoft/OMS-Agent-for-Linux#909]
After installing the latest OMS agent on a Centos 7.6.1810 server I get the following error when running systemctl -l status omsagent-GUID.service
/opt/microsoft/omsagent/plugin/omsbaseline[10265]: Couldn't open AzSecID file: open /etc/azsec/AzSecID: no such file or directory

Any suggestion on how to fix it?

I had the same error on an Ubuntu server ut that went away when I installed the audid package. The audit package is installed on the Contos bos.

**Comment by ewierschke** [comment]
I'm seeing this error on RHEL 7.6 as well

**Comment by ffloimair** [comment]
Happens on Debian 9 as well now.

**Comment by granwizzard** [comment]
Any Update on this?
I'm having the same issue when I'm trying to execute this command from an ansible-playbook on a centOS 7.8.
Command being executed: /opt/microsoft/omsagent/plugin/omsremediate -r disable-unnecessary-kernel-mods

The exact error is:
"disable-unnecessary-kernel-mods"], "delta": "0:00:00.010624", "end": "2020-05-30 16:44:32.379278", "msg": "non-zero return code", "rc": 1, "start": "2020-05-30 16:44:32.368654", "stderr": "2020/05/30 16:44:32 ERR: Couldn't open AzSecID file: open /etc/azsec/AzSecID: no such file or directory\nFailed to get remediations from audits file: Error validating baseline scanning audit file: Error validating file /opt/microsoft/omsagent/plugin/oms_audits.xml. Expected: 5709971aaedd6efeea836e8b44737449a2cf26447975bf68808e5eceaca1e163; Found: e5ed11579208cd6a8b9ffca8eeed08004c91e35cd33bf5310f8185e446ef522e", "stderr_lines": ["2020/05/30 16:44:32 ERR: Couldn't open AzSecID file: open /etc/azsec/AzSecID: no such file or directory", "Failed to get remediations from audits file: Error validating baseline scanning audit file: Error validating file /opt/microsoft/omsagent/plugin/oms_audits.xml. Expected: 5709971aaedd6efeea836e8b44737449a2cf26447975bf68808e5eceaca1e163; Found: e5ed11579208cd6a8b9ffca8eeed08004c91e35cd33bf5310f8185e446ef522e"

**Comment by smacritchie** [comment]
I'm seeing this on 3 of my Ubuntu 18.04.4 LTS VMs right now, but 12 others work fine

**Comment by ffloimair** [comment]
This project is soooo bad. No one even ever bothered to acknowledge this issue, let alone do something about it.
Come on Microsoft. omsagent is essential for Azure Security center. This is unacceptable!

**Comment by granwizzard** [comment]
This case is opened for more than one year, and you are trying to sell security center, Sentinel, etc where the main feature for us to be able to use all these features falls on top of the OMS agent for Linux and MMA for windows.
Some kind of feedback would be appreciated after more than a year.

**Comment by dguertin** [comment]
I'm also seeing this on CentOS 7.6. The whole /etc/azsec directory is missing. I don't know if anyone at Microsoft even reads this, but I want to add my voice to the chorus that this is still a problem.

**Comment by john-joyner** [comment]
Adding a +1 still seeing this in March 2021 on Ubuntu 18 VMs that have Azure Defender for Server coverage.

**Comment by carcioni** [comment]
Ran into this AGAIN!
So here's a work around (HACK!!) that has worked for me in the past.
It seems the build process for 'omsremediate' and possibly other parts of the OMSAgent code base, doesn't appear to update the checksum for the oms_audit.xml file (other files too??) in the omsremediate script.

When you see:
Failed to get remediations from audits file: Error validating baseline scanning audit file: Error validating file /opt/microsoft/omsagent/plugin/oms_audits.xml. Expected: 5709971aaedd6efeea836e8b44737449a2cf26447975bf68808e5eceaca1e163; Found: e5ed11579208cd6a8b9ffca8eeed08004c91e35cd33bf5310f8185e446ef522e"

Edit /opt/microsoft/omsagent/plugin/omsremediate file, and search for the first value: _5709971aaedd6efeea836e8b44737449a2cf26447975bf68808e5eceaca1e163_

Replace it with the second value: 
_e5ed11579208cd6a8b9ffca8eeed08004c91e35cd33bf5310f8185e446ef522e_

This second value is the checksum value generated from:
sha256sum /opt/microsoft/omsagent/plugin/oms_audits.xml
so in this particular case:
_e5ed11579208cd6a8b9ffca8eeed08004c91e35cd33bf5310f8185e446ef522e_

I am not sure why/how the build process does not update the  'omsremedidate' file, but this seems to solve the problem for now.

**Comment by tfmark** [comment]
On one Ubuntu 20.04 box I am able to run the remediate:
```
$ sudo /opt/microsoft/omsagent/plugin/omsremediate -r disable-unnecessary-kernel-mods
2021/09/08 12:42:52.229511 INFO: Performing baseline remediations. Detected Distro: Id=ubuntu, Version=20.04
2021/09/08 12:42:52.229587 INFO: Remediation 'disable-unnecessary-kernel-mods' has 1 actions to perform: Disable unnecessary Kernel Modules
2021/09/08 12:42:52.237361 INFO: Running script:


# (Audit6.1 - 6.6, 54, 55, 57) Disable unnecessary Kernel Modules
cat > /etc/modprobe.d/blacklist-azurebaseline.conf <<EOF
# Modules disabled per Azure baseline
install dccp /bin/true
install sctp /bin/true
install rds /bin/true
install tipc /bin/true
install cramfs /bin/true
install freevxfs /bin/true
install hfs /bin/true
install hfsplus /bin/true
install jffs2 /bin/true
install usb-storage /bin/true
EOF
chown root.root /etc/modprobe.d/blacklist-azurebaseline.conf
chmod 644 /etc/modprobe.d/blacklist-azurebaseline.conf
```
On another Ubuntu 20.04 box, I am not:
```
$ sudo /opt/microsoft/omsagent/plugin/omsremediate -r disable-unnecessary-kernel-mods
2021/09/08 12:43:09 ERR: Couldn't open AzSecID file: open /etc/azsec/AzSecID: no such file or directory
Failed to obtain distro info: unsupported distro ubuntu 20.04
```

Neither box has the /etc/azsec directory, so I'm assuming there is a check before looking for /etc/azsec to try to get the current distro.

The output of `cat /etc/lsb-release` is the same for both boxes, I'm not sure why one works and one doesnt...
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

I'll update this comment if I make any progress...

**Comment by eksklawa** [comment]
On my Redhat7 system I have similar problems, having this version:

```# rpm -q omsagent omsconfig
omsagent-1.13.35-0.x86_64
omsconfig-1.1.1-930.x86_64
 ```

I've done similar workaround proposed a few posts before.
There were still issues with many commands, e.g.

```
# /opt/microsoft/omsagent/plugin/omsremediate -r set-pass-min-days
No remediations found that meet specified constraints.
```


I noticed that the file ```/opt/microsoft/omsagent/plugin/oms_audits.xml oms_audits.xml``` is much smaller from the file offered on ```https://raw.githubusercontent.com/microsoft/OMS-Agent-for-Linux/master/source/code/plugins/oms_audits.xml```

```
# ls -al /opt/microsoft/omsagent/plugin/oms_audits.xml oms_audits.xml
-rw-r--r--. 1 root     root 121832 Sep 10 14:59 oms_audits.xml
-rw-r--r--. 1 omsagent root  65026 Feb 17  2021 /opt/microsoft/omsagent/plugin/oms_audits.xml
```


so, I copied the newer file ```oms_audits.xml``` from the github location to above directory, and after modifying it a bit:

```
# diff /opt/microsoft/omsagent/plugin/oms_audits.xml oms_audits.xml
1,4c1,5
< <data>
<   <audits
<     BaselineId="OMS.Linux.1"
<     BaseOrigId="1">
---
> <baseline BaselineId="OMS.Linux.1" BaseOrigId="1">
>   <baselines>
>     <baseline id="SSH.Linux" />
>   </baselines>
>       <audits>
2089,2090c2090
<
< </data>
---
> </baseline>
```

and modifying "sha256sum" again in the ```/opt/microsoft/omsagent/plugin/omsremediate``` it started to work:

```
# /opt/microsoft/omsagent/plugin/omsremediate -r set-pass-min-days
2021/09/13 21:19:00 INFO: Performing baseline remediations. Detected Distro: Id=redhat, Version=7
2021/09/13 21:19:00 INFO: Remediation 'set-pass-min-days' has 1 actions to perform: Set the minimum days between password changes to 7
2021/09/13 21:19:00 INFO: Changing value of 'PASS_MIN_DAYS' from '0' to '7' in '/etc/login.defs'
# find /etc -type f -mmin -1 -ls
2120437    4 -rw-r--r--   1 root     root         2025 Sep 13 21:19 /etc/login.defs
# grep PASS_MIN_DAYS /etc/login.defs
#       PASS_MIN_DAYS   Minimum number of days allowed between password changes.
PASS_MIN_DAYS   7
```

Crazy stuff it is, I am afraid this is not the right way Microsoft wanted it to be handled by, but who will guess what their idea was if this issue is not solved for so many years.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
