### ISSUE TITLE
omsagent extension status is always provisioning

### ISSUE THREAD

**Issue by wenbya** [microsoft/OMS-Agent-for-Linux#923]
**1. yesterday when I restart my vm, I can't see my vm extension (omsagent and some others).
and the log says:**
```
2019/04/15 10:53:38 [Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.9.1] Change log file to /var/log/azure/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux/1.9.1/extension.log
2019/04/15 10:53:38.772574 ERROR Event: name=Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux, op=Enable, message=(000003)Non-zero exit code: 9, omsagent.py -enable
2019/04/15 10:53:38.773386 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Expected handler state: enabled
2019/04/15 10:53:38.774155 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Decide which version to use
2019/04/15 10:53:38.788989 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Use version: 2.0.6
2019/04/15 10:53:38.792614 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Current handler state is: Enabled
2019/04/15 10:53:38.794934 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Update settings file: 6.settings
2019/04/15 10:53:38.796390 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Enable extension.
2019/04/15 10:53:38.797119 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Launch command:bin/custom-script-shim enable

```
this morning I can find my extension list but the OMSagent status show provisioning all the time 
the log says:
```
2019/04/15 20:22:40.867828 INFO Event: name=WALA, op=HeartBeat, message=
2019/04/15 20:55:27.626970 WARNING Socket IOError [Errno 111] Connection refused, args:(111, 'Connection refused')
```
**is there anyone has the same issues ? what's the root cause and how to fix ?**

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
