### ISSUE TITLE
Installation of OMSAgent failed after purging previous version

### ISSUE THREAD

**Issue by yinqchen** [microsoft/OMS-Agent-for-Linux#930]
I tried to install a different OMSAgent version after purging the previous version and get following errors.
I am not seeing this issue when I install OMSAgent on a fresh VM (no OMSAgent previously installed).

Unpacking omsagent (1.10.0.1) ...
dpkg: error processing archive 110/omsagent-1.10.0-1.universal.x64.deb (--install):
 unable to open '/opt/microsoft/omsagent/ruby/bin/rake.dpkg-new': Operation not permitted
ls: cannot access '/etc/opt/microsoft/omsagent': No such file or directory
Deleting nxautomation service account ...
Deleting omsagent service account ...
Deleting omsagent group ...
Processing triggers for systemd (237-3ubuntu10.19) ...
Processing triggers for ureadahead (0.100.0-20) ...
Errors were encountered while processing:
 110/omsagent-1.10.0-1.universal.x64.deb
omsagent-1.10.0-1.universal.x64 package failed to install and exited with status 1
Shell bundle exiting with code 17

**Comment by othmanaljundi-microsoft** [comment]
Ensure that /etc/opt/microsoft/omsagent is there :
# ls -ld /etc/opt/microsoft/omsagent

if it is not ; you can have work around by cloning this directory from old disk of the affected VM 
just try to mount the latest disk (Taken in the Azure VM backup) 
# mkdir /seconddisk
# mount /dev/…  /seconddisk
# cp -pr /seconddisk/etc/opt/microsoft/omsagent /etc/opt/microsoft/
# umount  /seconddisk

**Comment by WolterKamphuis** [comment]
For anyone experiencing the same issue, please verify that your virusscanner (if any) is disabled. I had the same issue on a VM where the client installed Sophos Anti-Virus for Linux.

I was able to install omsagent only after disabling the virusscanner.

There was no need to copy any files from a backup, just remove everything (--purge) and do a reinstall using the onboard_agent.sh script.
