### ISSUE TITLE
Zip files - /var/lib/waagent

### ISSUE THREAD

**Issue by mrevros** [microsoft/OMS-Agent-for-Linux#932]
Hi All,

I am seeing many .zip files under /var/lib/waagent folder like below. Is there any config parameter to set  deleting those files after installing?

Many thanks,

Evrs

-rw-r--r--. 1 root root  112M Oct 23  2016 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.2.75.0.zip
-rw-r--r--. 1 root root  114M Jan 28  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.12.0.zip
-rw-r--r--. 1 root root   87M May 31  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.127.5.zip
-rw-r--r--. 1 root root   87M Jun 14  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.127.7.zip
-rw-r--r--. 1 root root   87M Mar  9  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.15.1.zip
-rw-r--r--. 1 root root   87M Mar 29  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.18.2.zip
-rw-r--r--. 1 root root   92M Apr  7  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.18.4.zip
-rw-r--r--. 1 root root   92M Apr 27  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.3.18.7.zip
-rw-r--r--. 1 root root   97M Aug  4  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.45.2.zip
-rw-r--r--. 1 root root   98M Sep  8  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.45.3.zip
-rw-r--r--. 1 root root   97M Oct 27  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.55.4.zip
-rw-r--r--. 1 root root   97M Nov  7  2017 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.56.5.zip
-rw-r--r--. 1 root root   97M Jan  5  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.58.7.zip
-rw-r--r--. 1 root root  113M Jan 25  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.59.1.zip
-rw-r--r--. 1 root root  110M Mar  8  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.4.60.2.zip
-rw-r--r--. 1 root root  158M Aug 15  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.6.42.0.zip
-rw-r--r--. 1 root root  108M Aug 28  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.7.3.zip
-rw-r--r--. 1 root root  108M Sep 13  2018 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.7.9.zip
-rw-r--r--. 1 root root  108M Feb  2 21:10 Microsoft.EnterpriseCloud.Monitoring__OmsAgentForLinux__1.8.12.zip

**Comment by Foxinou35** [comment]
Hi all !
Got the same problem. Files keep on filling the hard drive. I got a /var full this morning on one of my server (not prod luckily, but could happen on prod)

Please can you tell us if we have to clean manually those zip ?

**Comment by sbonds** [comment]
So far it looks like a manual cleanup is needed. This would be a great housekeeping feature to add to the agent so it doesn't slowly fill /var.

**Comment by johanburati** [comment]
@sbonds It seems the devs added some code to clean up the zip files https://github.com/Azure/WALinuxAgent/pull/1642, but since they also changed the filename pattern of the zip files the agent will only clean-up those, as for the ones with the old pattern the devs suggested we delete them manualy.

**Comment by hestolz** [comment]
Thanks for referencing the PR, Johan. I knew they were planning a fix for this but didn't catch when it merged/released.
