### ISSUE TITLE
Unable to install MMA for CoreOS VM

### ISSUE THREAD

**Issue by anshulee** [microsoft/OMS-Agent-for-Linux#944]
We have a teamCity instance running on a CoreOS VM via the [Marketplace template](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/jetbrains.teamcity?tab=Overview) .

After enabling the MMA Extension it shows "Agent missing ID"
![image](https://user-images.githubusercontent.com/4685167/57353400-fa926d00-7185-11e9-80e1-dcb407a99434.png)

Trying to manully install agent via steps at https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-azurevm or https://docs.microsoft.com/en-us/azure/azure-monitor/learn/quick-collect-linux-computer doesn't work since there is no rpm manager in CoreOS

![image](https://user-images.githubusercontent.com/4685167/57353420-07af5c00-7186-11e9-8e68-7a3d4ca3cd8c.png)

How do we enable monitoring on this VM?

**Comment by hestolz** [comment]
Hi Anshulee, the Log Analytics agent for Linux [does not support the CoreOS distro](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/oms-linux#operating-system), my guidance would be to choose a supported distribution should you remain interested in using Log Analytics.

**Comment by pearj** [comment]
In case anyone comes here looking for CoreOS support, the above-linked ticket says that you should use the OMS container instead.

https://github.com/JetBrains/teamcity-azure-template/issues/7#issuecomment-490051441

https://docs.microsoft.com/en-us/azure/azure-monitor/insights/containers#install-and-configure-linux-container-hosts

https://hub.docker.com/r/microsoft/oms
