### ISSUE TITLE
Installation failure: AttributeError 'tuple' has no attribute 'major'

### ISSUE THREAD

**Issue by chralb-erst** [microsoft/OMS-Agent-for-Linux#945]
Deployment failed. Correlation ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX. VM has reported a failure when processing extension 'OmsAgentForLinux'. Error message: "Enable failed with error: 'tuple' object has no attribute 'major'
Stacktrace: Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.10.3/omsagent.py", line 167, in main
    exit_code, output = operations[operation]()
  File "/var/lib/waagent/Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux-1.10.3/omsagent.py", line 430, in enable
    if sys.version_info.major > 2:
AttributeError: 'tuple' object has no attribute 'major'

**Comment by DimitrovMiro** [comment]
Hi charlb-erst,
this is known issue with the newest omsagent 10.x version and older Linux images like 6.x , which have older python version. The newest oms agent needs at least python 2.7.x on the VM and the affected VMs have 2.6.x python version. MS are going to relase a hotfix for this issue in the newest omsagent, they should start pushing it to the different regions starting from this Wednesday/Thursday. For now you can revert to the older oms agent 1.9 or await the fix to come out.

Hope this helps.
Regards,
Miroslav Dimitrov

**Comment by chralb-erst** [comment]
I see. Thanks for your reply.

**Comment by DimitrovMiro** [comment]
Newer oms agent version 1.10.5 is pushed to the Central US region containing the fix for me. Only present in the Central US region so far. You can try to install the oms agent on a machine running in Central US and check if it is solved. You should see the 1.10.5 version and not 1.10.3

**Comment by hestolz** [comment]
1.10.5 is rolled out to all regions now, thank you for your patience.
