### ISSUE TITLE
Python3 not recognized on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by Jnchi** [microsoft/OMS-Agent-for-Linux#965]
```terminal
Python is not configured or it does not support ctypes on this system, please upgrade Python to a newer version that comes with the ctypes module and re-install omsconfig later.

python

Command 'python' not found, but can be installed with:

sudo apt install python3
sudo apt install python
sudo apt install python-minimal

You also have python3 installed, you can run 'python3' instead.

python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>>
```

I've also tried the following:

- Symlinking e.g., `ln -s $(which python3) /usr/local/bin/python`

- Invoking previous command with `--force`

**Comment by Jnchi** [comment]
For now, installing python2.7 fixes the issue, but keep in mind that it will be [EOL soon](https://www.python.org/dev/peps/pep-0373).

```terminal
apt install -y python
```

**Comment by j0h** [comment]
Anyone manage to get this working with python3?

**Comment by pachi-belero** [comment]
I my case, also on Ubuntu 18.04.02 in an Azure VM, even installing the python (and python-ctypes) package makes no difference. Symlinking though, as suggested by @Jnchi, makes the installation work OK:
e.g., `ln -s $(which python3) /usr/local/bin/python`

It seems like the installation script is looking for a "python" executable instead of "pyhton2" or "python3".

**Comment by mateuszdrab** [comment]
Python 2 is EOL, could this get fixed finally? 🙄

**Comment by VboxNick** [comment]
+1

**Comment by pcgeek86** [comment]
+1

**Comment by pcgeek86** [comment]
#1246

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
