### ISSUE TITLE
onboard_agent.sh not updated for latest release

### ISSUE THREAD

**Issue by Klaas-** [microsoft/OMS-Agent-for-Linux#987]
Hi,
it seems onboard_agent.sh was not updated for the latest release.
https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/onboard_agent.sh#L8-L11

Should be
GITHUB_RELEASE="https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_v1.11.0-7/"
BUNDLE_X64="omsagent-1.11.0-7.universal.x64.sh"
BUNDLE_X86="omsagent-1.11.0-7.universal.x86.sh"

I can just say again -- maybe you should look at creating a proper repository and use that in the script. Then you would not need to update it with each release. See #652 "Provide repositories for apt/yum"

Greetings
Klaas

**Comment by RalfWenzel** [comment]
we can reproduce this. How to update to 11.x ?

**Comment by RalfWenzel** [comment]
As a workaround, we 
1) uninstalled the agent
2) reinstalled using the 'az vm extension set ... --version x.y' CLI command 

as documented here:  

https://docs.microsoft.com/de-de/cli/azure/vm/extension?view=azure-cli-latest#az-vm-extension-set

**Comment by Klaas-** [comment]
I'm guessing you could also modify the onboard_agent.sh manually @RalfWenzel -- my suggestions should work fine but I haven't tested it.

**Comment by othmanaljundi-microsoft** [comment]
I think you are right; what can be done is a simple file within the repo that includes the latest version of the omsagent in which at the begining of the onboard script it will be :
wget http://....../omsagent-latest-release-x64.txt
wget http://....../omsagent-latest-release-x86.txt
then subsitute the value as 
BUNDLE_X64=`cat omsagent-latest-release-x64.txt`
BUNDLE_X86=`cat omsagent-latest-release-x86.txt`

until then ; what you can do is to edit the script and add the value needed manually 
then update both waagent and omsagent packages through yum

**Comment by Klaas-** [comment]
if you create a repository you won't need a file that points to the latest version, you'll just use yum/apt and it will use the newest version automatically @othmanaljundi-microsoft

**Comment by Klaas-** [comment]
This was fixed in 0f9fbfb096a6f3dc7cc7f5512128188739bf7eba and 91a58108f949f620ed5c3d593841269db1ce9d13 by @simathih
