### ISSUE TITLE
OMS-Agent-for-Linux Installation Failure on WSL2

### ISSUE THREAD

**Issue by MedAnd** [microsoft/OMS-Agent-for-Linux#988]
For full details see: [WSL2: OMS-Agent-for-Linux Installation Failure](https://github.com/microsoft/WSL/issues/4238)

As per comments from @therealkenc, the issue is the use of systemd (or anything that systemd usually starts, like dbus-daemon):

> Ask them how to make it run on Alpine/Gentoo/Void Linux ref #4158 (message). It will make a better formed question, and you will get a shorter and less confused answer. LZ is [#994](https://github.com/microsoft/WSL/issues/994).

**Comment by MedAnd** [comment]
Following steps as per [wsl2-hacks](https://github.com/shayne/wsl2-hacks) the installation on WSL2 progresses and now fails with:

> Checking host architecture ...
Error: Python is not configured or Python does not support ctypes on this system, installation cannot continue.
Please install the ctypes package (python-ctypes)or upgrade Python to a newer version of python that comes with the ctypes module.
You can check if the ctypes module is installed by starting python and running the command: 'import ctypes'.
You can run this shell bundle with --force; in this case, we will install omsagent,
but omsconfig (DSC configuration) will not be available and will need to be re-installed.
Shell bundle exiting with code 61

Shouldn't the onboard_agent.sh script automatically install any required packages?

**Comment by hestolz** [comment]
Considering we specifically call out the necessary dependencies [here](https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#package-requirements), this is reasonable and expected.
