### ISSUE TITLE
OMS agent on Raspberry Pi

### ISSUE THREAD

**Issue by format81** [microsoft/OMS-Agent-for-Linux#997]
Hi experts,
I'd like to run OMS agent on Raspberry Pi (Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux)
Do you have any guidance to build package?

Thanks
Antonio

**Comment by kenyelima** [comment]
me too, i also tried to run as a container, but unsuccessful

**Comment by abenbachir** [comment]
We have documentation for building steps check here: https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Development.md

**Comment by MagdaPaj** [comment]
@abenbachir Hello, I would also like to run the OMS agent on my Raspberry Pi (ARM architecture). I tried to follow the steps in your [Development.md](https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Development.md) document. 
I'm getting this error, when building docker:
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Docker build containers that you recommend are useful only for building for x86_64 architecture. How this relates to Raspberry Pi and building for ARM architecture?

I also tried to just directly build it on my Raspberry Pi after cloning Build-OMS-Agent-for-Linux repo with [building steps](https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Development.md#building-steps)

``` 
./configure
make
```

But the make fails with:
```
make: *** [Makefile:192: /home/ubuntu/Build-OMS-Agent-for-Linux/omi/Unix/output/lib/libbase.a] Error 1
```
I've checked the omi project, and it doesn't have libbase.a file.

Do you have any other up-to-date documentation about how to build the OMS agent for Raspberry Pi?
